includes/classes/class.zcPassword.php, testFramework/config/localconfig_EXAMPLE.php, zc_install/ajaxAdminSetup.php, zc_install/ajaxGetHelpText.php, zc_install/ajaxGetProgressValues.php, zc_install/ajaxLoadMainSql.php, zc_install/ajaxLoadUpdatesSql.php, zc_install/ajaxTestDBConnection.php, zc_install/ajaxTestSystemSetup.php, zc_install/ajaxValidateAdminCredentials.php, zc_install/index.php
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/253)
=> use __DIR__ for dirname(__FILE__)

admin/includes/functions/general.php
remove left over old code
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/255)
=> Remove old zen_has_product_attributes_OLD

admin/includes/languages/english.php, admin/profiles.php
Ref: http://www.zen-cart.com/showthread.php?215729-Replace-hard-coded-language-text-in-admin-profiles-php
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/261)
=> Remove hard-coded language text into language file

includes/functions/functions_email.php
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/256)
=> Add function to return customers_email_address

includes/classes/db/mysql/query_factory.php
Addendum to #263 ... to allow only valid characters: A-Z,_
=> Strip spaces on sql_mode if defined

includes/modules/pages/checkout_confirmation/header_php.php, includes/modules/pages/checkout_payment/header_php.php, includes/modules/pages/checkout_shipping/header_php.php
Fixes #267 Order comments clean up for spaces
=> Fix #267: Order comments clean up for spaces

admin/includes/classes/object_info.php
A bit of cleanup to the objectInfo class
=> A bit of cleanup to the objectInfo class

includes/functions/plugin_support.php
Let plugin version checker handle null responses
Fixes #281
=> Let plugin version checker handle null responses

zc_install/includes/classes/class.zcDatabaseInstaller.php, zc_install/includes/modules/pages/database/header_php.php
Initializes some db fields on the screen from configure.php.
=> Fixes crash on initial db update for new admin user in no SSL environment

admin/includes/functions/general.php, includes/languages/english/meta_tags.php
Adds admin page name to title for admin pages.
=> Fix issue 144 Admin Title Tags.

.travis.yml, composer.json
This will have Travis CI test against the PHP 7 nightly
=> Add PHP 7 testing to Travis

admin/specials.php
$products_id is set on line 34 and 58
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/316)
=> $products_id is set twice

includes/modules/order_total/ot_coupon.php
See http://www.zen-cart.com/showthread.php?216420-Error-in-ot_coupon-php
=> Fixes issue with mismatched signatures for calculate_deductions.

admin/salemaker_info.php
The html in this file is just plain wrong.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/319)
=> Fixing html errors

includes/modules/pages/download/header_php.php
NOTE: Line 222 is where the change is.
The rest are whitespace issues getting cleaned up.
=> Fixes octal problem with chmod introduced in #148

includes/classes/shopping_cart.php
Adds the ability to calculate total weight, price or quantity in categories with or without subcategories.
=> Ability to calculate totals in cart categories

includes/modules/payment/authorizenet.php, includes/modules/payment/authorizenet_aim.php, includes/modules/payment/authorizenet_echeck.php
Applying same changes as #275 to sibling modules
=> Continuation of #275 - int vs string for MySQL strict mode

.scrutinizer.yml
=> reinstate templates into scrutinizer path

admin/includes/classes/actions/admin/class.zcActionAdminIndex.php, admin/includes/template/templates/tplIndex.php
Fixes #189 (Dashboard Widgets errors new admin). 
This issue was reported by @Ajeh.
=> Fix #189  (Dashboard Widgets errors new admin)

admin/coupon_admin.php, admin/customers.php, admin/includes/classes/box.php, admin/includes/init_includes/init_category_path.php, includes/classes/class.zcRequest.php, includes/library/zencart/admin/DashboardWidget/src/OrderSummary.php
'selected_box' hasn't been used in years. Removing leftover fragments of it.
=> Remove deprecated 'selected_box' GET/SESSION vars from Admin

includes/classes/db/mysql/query_factory.php
Only do move/seek if we have a resultset
=> Fix QueryFactory Iterator rewind

includes/modules/sideboxes/manufacturers.php, includes/modules/sideboxes/music_genres.php, includes/modules/sideboxes/record_companies.php
ref: http://www.zen-cart.com/showthread.php?204962-Manufacters-names-in-dropdown-menus-being-html-converted and @lat9
=> Ampersands were being double-encoded in mfg pulldowns

admin/includes/functions/general.php, includes/classes/template_func.php, includes/functions/functions_general.php, includes/functions/functions_lookups.php, includes/functions/html_output.php, includes/init_includes/init_templates.php, includes/languages/english.php, includes/modules/require_languages.php
Provides for "shared" directory which is searched after your_template but before template_default.
Tested with the following files: 
includes/languages/english/html_includes/shared/define_main_page.php
includes/languages/english/shared/index.php
includes/languages/shared/english.php
includes/languages/english/shared/header.php
includes/templates/shared/common/tpl_header.php
includes/templates/shared/templates/tpl_login_default.php
- also tested with editing the first file in the admin defines pages editor.
=> Implement intermediate "shared" template tier

includes/functions/html_output.php
=> Fix broken image paths introduced by #350

includes/autoload_namespaces.php, includes/library/zencart/admin/Controllers/src/AbstractAjaxController.php, includes/library/zencart/admin/Controllers/src/AbstractController.php, includes/library/zencart/admin/Controllers/src/AjaxDashboardWidget.php, includes/library/zencart/admin/Controllers/src/Index.php, includes/library/zencart/admin/Services/src/IndexRoute.php
Rename templateVariables to tplVars for consistency
Use a service class in the Admin Index route
=> Further refactoring of admin controllers

admin/includes/modules/copy_to_confirm.php, admin/includes/modules/product_music/copy_to_confirm.php
Ref: https://www.zen-cart.com/showthread.php?216804
=> Remove redundant movenext() call

includes/library/zencart/admin/DashboardWidget/src/WidgetManager.php
=> Fixes #395 Fatal error in dashboard widget manager when creating a new user

admin/developers_tool_kit.php, admin/includes/languages/english/developers_tool_kit.php
Add regex search to DTK (searches only individual lines, not across multiple lines)
Also fixed context-highlight to show number of context lines in input box.
Also added "search all file types" to dropdown.
=> Add regex search to DTK (searches only individual lines, not across multiple lines)

admin/includes/modules/newsletters/newsletter.php, admin/includes/modules/newsletters/product_notification.php, includes/classes/order_total.php
... okay, I confess I also cleaned up some line-indenting messes too.
=> Remove obsolete global statements for $_POST, $_GET

includes/library/zencart/platform/src/listingBox/formatters/TabularProduct.php
Seems like I reversed the functions for testShowBuyNow and testShowAddProduct in the Formatter
=> PRODUCT_LIST_PRICE_BUY_NOW settings not working correctly

includes/functions/functions_lookups.php
PR #365 wasn't handling multi-lang scenarios
=> Handle multiple-language situations with single-attrib-add

includes/library/zencart/platform/src/QueryBuilder.php
Added feature to allow for custom select fields on JOIN table command
Added some extra notifiers
=> Updates to queryBuilder

includes/library/zencart/platform/src/listingBox/boxes/AbstractListingBox.php
Updated method flow, necessary to support Admin LEAD type listing boxes in the future
Added some notifiers. possibly might need some more?
=> Updates to AbstractListingBox

includes/library/zencart/platform/src/Paginator/AbstractScroller.php, includes/library/zencart/platform/src/Paginator/scrollers/Standard.php
Fixing some minor variable setting problems
=> Updates to paginator classes

includes/templates/template_default/listingboxes/tpl_listingbox_columnar.php, includes/templates/template_default/listingboxes/tpl_listingbox_productliststd.php, includes/templates/template_default/listingboxes/tpl_listingbox_tabular.php, includes/templates/template_default/templates/tpl_index_product_list.php
Failed to update the bottom of these templates to use new tplVar structures for paginator
Meant that pagination would not show at bottom of list.
Also fix hardcoded template for product list
=> Updating listingbox templates

admin/includes/modules/product/collect_info.php
Not really important, but it is still 2015
=> Not really important, but it is still 2015

admin/includes/init_includes/init_db_config_read.php
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/424)
=> Typo, movenext() should be MoveNext().

includes/init_includes/init_add_crumbs.php
This time I tried the new iterator. Hope I got it right.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/426)
=> Another movenext()

includes/init_includes/init_db_config_read.php
updated to the new iterator
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/427)
=> And Another movenext()

admin/includes/init_includes/init_db_config_read.php, includes/init_includes/init_add_crumbs.php, includes/init_includes/init_db_config_read.php
Fix some syntax errors in #426 and #427 and #424 and implement the iterator fully in these small files
=> Fix iterator syntax errors

includes/init_includes/init_customer_auth.php
This should fix issues with Customer Authorization and customer order stays review for Guest Checkout customers when CUSTOMERS_APPROVAL_AUTHORIZATION not set to 0
=> Fixes #440 customer authorization vs guest checkout order status checks

.gitignore, .travis.yml, composer.lock
The main fix is to commit a composer.lock so that composer install doesn't need
to work out it's dependancies.
=> fixing timeout problems with travis

admin/includes/modules/prod_cat_header_code.php
The function zen_reset_page() seems to be unused, and can IMHO be deleted.
=> function zen_reset_page() seems to be unused

includes/modules/pages/login/header_php.php, includes/modules/payment/paypal/tpl_ec_button.php, includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php, includes/templates/template_default/templates/tpl_login_default.php
This removes the business logic from the template, meaning no template changes to get the same result as #453
=> Addendum to PayPal intro-text-removal in #453

zc_install/sql/updates/mysql_upgrade_zencart_160.sql
Correct an error on the functions for SHOW_COUNTS_ADMIN and SHOW_CATEGORY_PRODUCTS_LINKED_STATUS
=> Correct configuration function settings

admin/includes/functions/general.php, admin/includes/init_includes/init_languages.php
=> Falls back to default (english) files if current language not available.

admin/includes/modules/copy_to_confirm.php, admin/includes/modules/product_music/copy_to_confirm.php
This change sets it to null instead of 01/01/0001
=> Copy Product to Duplicate Product sets Date Available to 01/01/0001

includes/templates/template_default/common/tpl_columnar_display.php
Small tidying of tpl_columnar_display.php to output HTML directly instead of echoed by PHP
=> Small tidying of tpl_columnar_display.php to output HTML directly

.travis.yml
http://docs.travis-ci.com/user/migrating-from-legacy
=> use the new travis infrastructure

admin/products_price_manager.php
=> Change admin products price manager to use admin tax-display mode

includes/modules/pages/checkout_shipping/header_php.php
Missing reset shipping cost
https://www.zen-cart.com/showthread.php?217864-Free-Shipping-can-unintentionally-retain-cost-gt-0-if-cart-contents-change
=> Add checkout_shipping reset cost

includes/templates/template_default/templates/tpl_shopping_cart_default.php
This is required for future targeting of form elements
=> Add missing ID to form on shopping_cart template

includes/classes/order.php, includes/classes/shopping_cart.php, includes/functions/functions_prices.php, includes/modules/attributes.php, includes/modules/order_total/ot_coupon.php, includes/modules/pages/login/header_php.php
Remove commented lines ending with brackets. Lines like this break bracket-matching in vi.  If they are genuinely needed, push the bracket to the next line so that the brackets still match.
=> Remove commented lines ending with brackets ... because vi gets confused

includes/classes/order.php, includes/modules/order_total/ot_shipping.php
Fix issue of
PHP Warning:  Illegal string offset 'id' in /public_html/dev/includes/classes/order.php
=> fix issue of: Illegal string offset 'id' in classes/order.php

includes/languages/english/modules/payment/paypalwpp.php, includes/modules/payment/paypal/paypal_curl.php, includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php
Various changes to update the API to the latest-available version, for both Express Checkout and Website Payments Pro/PayPal Payments Pro.
=> Paypal API updates to 124.0

admin/orders.php
There will be more of these in the future, but I'm submitting this PR now to clear out stale branches.
=> Add additional notifier hooks to admin orders page

zc_install/includes/languages/lngEnglish.php, zc_install/includes/systemChecks.yml
Was spelled with 3 P's in a number of places.
=> Fix spelling of "SUPPORT"

includes/library/zencart/listingBox/src/boxes/UpcomingProductsCenter.php
Fixes #508 - wrong product-type lookup on links for Upcoming Products
=> Wrong product-type lookup on links for Upcoming Products listingBox - Fixes #508

includes/library/zencart/listingBox/src/boxes/FeaturedProductsCenter.php, includes/library/zencart/listingBox/src/boxes/FeaturedProductsPage.php, includes/library/zencart/listingBox/src/boxes/NewProductsCenter.php, includes/library/zencart/listingBox/src/boxes/NewProductsPage.php, includes/library/zencart/listingBox/src/boxes/SpecialsProductsCenter.php, includes/library/zencart/listingBox/src/boxes/SpecialsProductsPage.php
Fixes #509 - Typo in listingBox tablename
=> Typo in listingBox tablename - Fixes #509

includes/templates/template_default/common/html_header.php
Ensure Internet Explorer’s Quirks Mode and Compatibility View are disabled
=> Ensure Internet Explorer’s Quirks Mode and Compatibility View are disabled

extras/curltester.php, zc_install/includes/classes/class.systemChecker.php, zc_install/includes/systemChecks.yml
Point CURL testing tools to AWS endpoint
This will help with improving performance and reachability.
=> Point CURL testing tools to AWS endpoint

includes/modules/payment/paypal/paypalwpp_admin_notification.php
I chose to just comment-out this code segment, pending relevance for future updates to the payflow code
=> Fixes #384 PayPal/Payflow Admin Metadata display issue

includes/templates/template_default/templates/tpl_account_edit_default.php
Ref: https://www.zen-cart.com/showthread.php?217924-customer-referral-snip-in-edit-account
=> Fix small styling bug for customers_referral field in tpl_account_edit

includes/classes/shopping_cart.php
Ref: https://www.zen-cart.com/showthread.php?217915-shopping_cart-get_product_id_list-function
=> Fix empty-string error in shopping_cart::get_product_id_list

admin/define_pages_editor.php, admin/layout_controller.php, admin/modules.php, admin/newsletters.php
Ref: https://www.zen-cart.com/showthread.php?217903-Layout-Controller-detects-files-with-extensions-other-than-php
=> Fixes layout_controller lookup of non-php files

admin/includes/functions/general.php, admin/includes/init_includes/init_languages.php
Fixed line-ending issue
Added comments
Renamed function
=> Fix formatting in functions-general; rename new function

includes/classes/order_total.php, testFramework/webtests/tests/loworderfeeTest.php
Also added some web tests to cover.
=> Fixes #474 loworder fee isssue

admin/includes/functions/general.php, admin/includes/languages/english/server_info.php, admin/server_info.php
=> Add some additional MySQL status indicators on system-info page

admin/includes/modules/product_music/copy_to_confirm.php
=> Fix media-copy toggle

includes/classes/db/mysql/define_queries.php, includes/modules/also_purchased_products.php
=> Randomize also-purchased results

ajax.php
Ref: https://www.zen-cart.com/showthread.php?216691-PHP-Warning-Invalid-UTF-8-sequence-in-argument-in-ajax-php-on-line-24
=> Fix UTF8 sequence error in ajax call

includes/templates/template_default/common/tpl_favicon.php
Many of the standard/expected resolutions have changed, so this updates accordingly.
=> Add a few modernizations to the tpl_favicon template

includes/modules/payment/authorizenet_aim.php
Ref: https://www.zen-cart.com/showthread.php?215694-Known-Bugs-and-fixes-with-v1-5-4&p=1276877#post1276877
=> Fix missing cc_type field introduced in v154

admin/includes/extra_configures/enable_error_logging.php, includes/extra_configures/enable_error_logging.php
Adapted from plugin version v1.1.0 at https://www.zen-cart.com/downloads.php?do=file&id=1879&name=lat9-myDEBUG-backtrace
=> Add the excellent Debug Backtrace plugin by @lat9

includes/modules/pages/popup_image_additional/header_php.php
Reporter: Tim Coen http://curesec.com/
Affected Versions: Current & unreleased (reporter tested against v154)
Vulnerability Release date: 13th September 2015
Vulnerability Type: Information Leakage
Vulnerability Severity: Low
Details
Info Leak
Description
An attacker can check if a file exists on the server, thus gaining information about installed software.
`http://localhost/zen-cart-v1.5.4-12302014/index.php?main_page=popup_image_additional&pID=26&pic=1&products_image_large_additional=../../../../../../../etc/passwd`
results in `<a href="javascript:window.close()"><img
src="../../../../../../../etc/passwd"`
`http://localhost/zen-cart-v1.5.4-12302014/index.php?main_page=popup_image_additional&pID=26&pic=1&products_image_large_additional=../../../../../../../etc/passwd2`
results in …
=> Security - Information leakage

includes/languages/english/checkout_payment.php
This will help stop people from losing their place in checkout when they click the link
=> Make T&C "link" open in new window

includes/functions/html_output.php, includes/modules/pages/checkout_confirmation/header_php.php
Add additional sanitization to comments and password fields
> Credit: Thanks to Trustwave SpiderLabs for pointing these out
=> Add additional sanitization to comments and password fields

admin/products_to_categories.php
Remove extraneous code that has no purpose and is never used
=> Remove extraneous code

admin/includes/template/templates/tplIndexStartWizard.php, includes/library/zencart/Controllers/src/admin/Index.php
Use new ajax controller href and add getZones handler
=> Fixes #455 - Setup wizard countries/zones updates

admin/attributes_controller.php, admin/banner_manager.php, admin/categories.php, admin/includes/modules/new_product_preview.php, admin/mail.php, admin/manufacturers.php, admin/media_manager.php, admin/product_types.php, includes/library/zencart/Services/src/LeadService.php
Credits to [curesec.com](http://blog.curesec.com/article/blog/Zen-Cart-154-Code-Execution-and-Information-Leak-54.html) for pointing out possible problems where these restrictions don't exist.
=> Enforce additional restrictions on uploaded files

zc_install/includes/application_top.php
=> Disable cache during zc_install via xcache.cacher INI setting

admin/includes/template/css/index.css, admin/includes/template/css/stylesheet.css
=> Style Changes for the Admin Widgets

admin/includes/template/css/index.css
=> font size / padding tweaks for Widget "edit" dialog

admin/includes/template/css/stylesheet.css
=> Fix admin td/th padding as part of #573

testFramework/webtests/tests/installerNoErrorsTest.php
Probably not the best way to fix, but selenium2 changed the way wait stuff worked and can't get it to work so far.
=> Fix timeout on installer tests

zc_install/sql/install/mysql_latin1.sql, zc_install/sql/install/mysql_utf8.sql, zc_install/sql/updates/mysql_upgrade_zencart_160.sql
=> Fixes #271 Italy address format

admin/includes/languages/english/email_extras.php, email/email_common.css, email/email_template_checkout.html, email/email_template_contact_us.html, email/email_template_coupon.html, email/email_template_default.html, email/email_template_direct_email.html, email/email_template_gv_mail.html, email/email_template_gv_queue.html, email/email_template_gv_send.html, email/email_template_low_stock.html, email/email_template_newsletters.html, email/email_template_order_status.html, email/email_template_password_forgotten.html, email/email_template_product_notification.html, email/email_template_welcome.html, includes/functions/functions_email.php, includes/languages/english/email_extras.php
Source: https://github.com/lat9/common_email_styling
=> Integrate the email-common-css-styling package by @lat9

admin/system_inspection.php
Since I was porting 1.5.x code, I completely missed doing this.
=> switch to new style loops

admin/login.php
Need to load application_top before calling strtotime() so that the timezone overrides are executed first.
=> Fix admin timezone chicken/egg problem

ajax.php
Thanks to High Tech Bridge for the security report. https://www.htbridge.com/advisory/HTB23282
=> fix for lfi

zc_install/sql/updates/mysql_upgrade_zencart_160.sql
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/673)
=> typo Gueat should be Guest

includes/modules/pages/gv_redeem/header_php.php
The closing bracket for preg_replace is in the wrong position. It should be in front of the colon.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/670)
=> Syntax error in gv_redeem/header_php.php on line 20

admin/reviews.php
The info in this query is already present in $reviews.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/650)
=> Query can be simpliefied

includes/modules/payment/paypaldp.php
Problem discovered when testing ajax-checkout
=> Fix check for order amount, to handle chicken/egg case when doing validations or ajax

includes/templates/responsive_classic/jscript/jquery.matchHeight.js, includes/templates/responsive_classic/jscript/jquery.mmenu.fixedelements.js, includes/templates/responsive_classic/jscript/jquery.mmenu.js, includes/templates/responsive_classic/jscript/jquery.mmenu.oncanvas.js
Add unminified versions of `mmenu` and `matchHeight` scripts, just for dev/debug purposes. Not actually used by the template code unless the template is altered to do so.
=> Add unminified versions of mmenu and matchHeight scripts (for dev use)

includes/modules/sideboxes/banner_box.php, includes/modules/sideboxes/banner_box2.php, includes/modules/sideboxes/banner_box_all.php, includes/templates/template_default/sideboxes/tpl_banner_box.php, includes/templates/template_default/sideboxes/tpl_banner_box2.php, includes/templates/template_default/sideboxes/tpl_banner_box_all.php
Improve the test for whether to display the banner sidebox(es), and clean up some of the code in the related files to fix indenting consistency etc.
=> Banners sidebox code tidying

admin/includes/languages/english/modules.php, admin/modules.php
Fixed long-standing problem of duplicate sort-orders wiping each other out ... in Admin->Modules screens.
=> Fix problem of duplicate sort-orders on module settings

includes/classes/categories_ul_generator.php
For php7 compatibility
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/706)
=> Change constructor for zen_categories_ul_generator to __construct()

includes/init_includes/init_canonical.php
Enhancements to init_canonical to prevent rogue parameters from getting into the canonical URL link
=> Enhancements canonical URL generator to prevent rogue parameters

includes/modules/payment/paypal/tpl_ec_button.php, includes/modules/payment/paypalwpp.php, includes/templates/classic/css/stylesheet.css, includes/templates/responsive_classic/css/stylesheet.css, includes/templates/template_default/css/stylesheet.css
Add support for PayPal InContext Checkout (updated Express Checkout features)
Ref: https://developer.paypal.com/docs/classic/express-checkout/in-context/
=> Add support for PayPal InContext Checkout (updated Express Checkout features)

includes/modules/payment/authorizenet.php, includes/modules/payment/authorizenet_aim.php
Authorize.net supports multiple currencies, but only one-currency-per-gateway-account. 
Previously there was a bug whereby transactions would be charged the same amount but pass the wrong currency code instead of converting both amount and currency correctly to the single currency supported by the account. This change now forces the storeowner to specify which currency their gateway account is configured for, and converts purchases to that amount before submission.
=> Fix authorize.net to convert currencies to gateway-supported value

includes/templates/responsive_classic/common/html_header.php, includes/templates/template_default/common/html_header.php
Ref: https://moz.com/learn/seo/hreflang-tag
Ref: https://sites.google.com/site/webmasterhelpforum/en/faq-internationalisation
Credits: @balihr
=> Add hreflang metatag to support multiple language indexing

includes/classes/db/mysql/define_queries.php
Updates #662 and replaces #686
=> Update also-purchased query for ONLY_FULL_GROUP_BY compatibility with MySQL 5.7

includes/templates/responsive_classic/common/html_header.php, includes/templates/template_default/common/html_header.php
When looking in a text editor there appears to be an extra dot after the closing php bracket
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/745)
=> Stray character ??

includes/functions/html_output.php
=> Check for #id before generating one

admin/stats_products_purchased.php
This report already uses the new report style so I thought
it should have the new iterator too so it's a good template.
=> Migrate this report to new iterator style

includes/classes/split_page_results.php, includes/languages/english.php, includes/templates/responsive_classic/common/html_header.php, includes/templates/responsive_classic/templates/tpl_account_history_default.php, includes/templates/responsive_classic/templates/tpl_featured_products_default.php, includes/templates/responsive_classic/templates/tpl_modules_product_listing.php, includes/templates/responsive_classic/templates/tpl_product_reviews_default.php, includes/templates/responsive_classic/templates/tpl_products_all_default.php, includes/templates/responsive_classic/templates/tpl_products_new_default.php, includes/templates/responsive_classic/templates/tpl_reviews_default.php, includes/templates/responsive_classic/templates/tpl_specials_default.php
The generated markup embraces class names compatible with Bootstrap 3 and Foundation For Sites 6, just to prevent the need to alter core files if using those frameworks.
=> Pagination as Unordered List

includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php, includes/templates/responsive_classic/templates/tpl_modules_products_new_listing.php, includes/templates/template_default/templates/tpl_modules_products_all_listing.php, includes/templates/template_default/templates/tpl_modules_products_featured_listing.php, includes/templates/template_default/templates/tpl_modules_products_new_listing.php
(requires `.clearBoth{clear:both}` which is already in default stylesheet)
=> Change deprecated clear="all" syntax to class="clearBoth"

admin/includes/init_includes/init_sanitize.php, includes/init_includes/init_sanitize.php
This is to tighten security against plugins which fail to properly sanitize inputs or bypass get/post
=> Add additional sanitization to the `request` array

includes/templates/responsive_classic/common/html_header.php
=> Fix misplaced bracket around mobile-detect instantiation

includes/languages/english/button_names.php, includes/languages/english/responsive_classic/button_names.php, includes/templates/template_default/templates/tpl_discount_coupon_default.php
Changed from `Send Now` to `Lookup`
=> Change the discount-coupon-lookup submit button text to "lookup"

admin/includes/init_includes/init_general_funcs.php
Fix problems with errant SSLPWSTATUSCHECK values triggered by admin `configure.php` improvements
=> Fix problems with errant SSLPWSTATUSCHECK values

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_155.sql
Thanks to @lat9 for the reminder!
=> Remove auto-increment from products_description table

includes/templates/responsive_classic/css/responsive_tablet.css, includes/templates/responsive_classic/css/stylesheet_css_buttons.css
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/791)
=> linebreak gives error in css

zc_install/sql/demo/mysql_demo.sql
In the demo data Customer Bill Smith has id 1
The reviews table has customers_id set to 0 instead of 1
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/792)
=> Bill Smith has id 1

includes/functions/functions_prices.php
This suggestion from rbarbour adds additional styling targets to prices.
=> Add spans for productBasePrice and productFreePrice

admin/includes/classes/AdminRequestSanitizer.php
=> Reworking Admin Sanitization

includes/classes/ajax/zcAjaxPayment.php, includes/classes/payment.php, includes/modules/pages/checkout_payment/jscript_main.php, includes/templates/responsive_classic/jscript/jscript_framework.php, includes/templates/template_default/jscript/jscript_framework.php
Also fix an intermittent error which would temporarily show an jscript alert
And remove references to noScriptCokkie code
=> remove need for ajax to check collectCardsOnsite status

admin/customers.php, admin/orders.php
This allows plugins to add to these menus without touching core code.
=> Add notifiers for button nav in admin orders/customers pages

includes/languages/english/modules/payment/payeezyjszc.php, includes/modules/pages/checkout_payment/jscript_payeezy.php, includes/modules/payment/payeezyjszc.php
Payeezy JS is a PCI Compliant credit card payment solution.
Works with First Data / Global Gateway e4 merchant accounts.
=> Add Payeezy JS payment module (replaces Linkpoint API)

admin/customers.php
Ref: https://www.zen-cart.com/showthread.php?219492-admin-customers-php-sortOrderHeader
=> Retain search criteria when sort customer results in admin

includes/functions/featured.php, includes/functions/salemaker.php, includes/functions/specials.php
Based on initial reading, the below was added/modified to address adding notifiers to the associated auto-actions related to specials, featured purchases, and salemaker items.
In parallel: 
1. removed the closing ?>
2. converted while (!$var->EOF) statements to foreach, and
3. added bindVars references for the date.
=> Mc12345678 issue #60

zc_install/ajaxAdminSetup.php, zc_install/includes/template/templates/admin_setup_default.php
This addresses a renaming issue created by #825.
=> More fixing of admin dir rename issue (ref #825)

includes/modules/product_listing.php, includes/modules/product_listing_alpha_sorter.php, includes/modules/responsive_classic/product_listing.php, includes/templates/responsive_classic/common/tpl_columnar_display.php, includes/templates/responsive_classic/common/tpl_tabular_display.php, includes/templates/template_default/common/tpl_columnar_display.php, includes/templates/template_default/common/tpl_tabular_display.php
Additional notifier hooks, as discussed in https://www.zen-cart.com/showthread.php?211797&p=1256923#post1256923
=> Additional notifier hooks (ref #60)

admin/includes/classes/AdminRequestSanitizer.php, admin/includes/init_includes/init_sanitize.php
=> More updates to Admin Sanitization

admin/admin_account.php, admin/admin_page_registration.php, admin/includes/index.css, admin/includes/stylesheet.css, admin/index.php, admin/index_dashboard.php, admin/profiles.php, admin/users.php
=> Updates to footer handling

admin/includes/functions/admin_access.php
Add @torvista suggestion for auto-assigning max+1 sort order
Ref: https://www.zen-cart.com/showthread.php?199251&p=1304539#post1304539
=> Add @torvista's suggestion for auto-assigning max+1 sort order

admin/includes/template/common/tplAdminHtmlHead.php, admin/includes/template/css/index.css, admin/includes/template/css/stylesheet.css
=> Affix admin nav menu to top of page; add odd/even rows on widgets

includes/.htaccess, pub/.htaccess, zc_install/.htaccess
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/862)
=> typo causes site load to fail

admin/includes/classes/message_stack.php, admin/includes/stylesheet.css
Icons weren't showing correctly, and using FontAwesome is the intended future direction, so makes sense to fix it this way.
Also adding Bootstrap styling to messageStack alerts makes for better consistency.
=> Make Admin messageStack use FontAwesome icons and bootstrap styling

admin/orders.php
This puts back the logo and date from nav area, and restores the ability to print the list of orders.
=> Restore printing capability on Admin orders page

includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php
It seems PayPal has removed the 201 spec from production and from their website reference docs.
=> Downgrade PayPal API to 124.0

docs/changed_files-v1-5-5.html, includes/languages/english/classic/header.php, zc_install/includes/classes/class.systemChecker.php, zc_install/includes/languages/lngEnglish.php
Also fixed a timeout delay in zc_install system inspection
=> Minor fixes to language files and documentation

includes/templates/template_default/templates/tpl_document_general_info_display.php, includes/templates/template_default/templates/tpl_document_product_info_display.php, includes/templates/template_default/templates/tpl_product_free_shipping_info_display.php, includes/templates/template_default/templates/tpl_product_info_display.php, includes/templates/template_default/templates/tpl_product_music_info_display.php
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/881)
=> removal of extra space in <span>

admin/includes/template/javascript/select2DriverGeoZonesDetail.php, includes/library/zencart/Controllers/src/admin/GeoZonesDetail.php, includes/library/zencart/Services/src/LeadGeoZonesDetailRoutes.php, includes/library/zencart/Services/src/LeadRoutes.php
removing duplicate code
add some language handling for select2 entities
=> Updating AutoComplete (Select2) code

admin/includes/classes/AdminRequestSanitizer.php, admin/includes/init_includes/init_sanitize.php, not_for_release/testFramework/unittests/testAdminSanitizationCase.php
Add debug logging
Update filterStrictSanitizeValues to recurse better
Add/Update Unittests
Add logging for STRICT_SANITIZE_VALUES
=> Updates to Admin Sanitization Code

admin/includes/auto_loaders/config.adminSanitize.php, admin/includes/classes/AdminRequestSanitizer.php, admin/includes/init_includes/init_sanitize.php, not_for_release/testFramework/unittests/testAdminSanitizationCase.php
add FLOAT_VALUE_REGEX for floats
adding custom sanitizer stuff
Usage instructions and customization details at http://docs.zen-cart.com/Developer_Documentation/v1.5.5/code_docs/admin_sanitization
=> Update admin sanitizer and make MULTI_DIMENSIONAL recursive

includes/modules/meta_tags.php
removes `*` in addition to `"` from meta-data.  also allows to remove any character from meta-data, by just adding that character to the array.
=> Creates array to clean meta-data

includes/modules/payment/authorizenet_aim.php
Thanks to @numinix for pointing it out
=> Fix typo in authnet test for test-mode

admin/includes/languages/english/orders.php, admin/orders.php
Move font awesome markup into code for easier language updates.
=> Move admin orders icons out of language files. Fixes #917

admin/orders.php
Strangely enough it requires a double `&&`
=> Fix whois lookup link

admin/configuration.php, admin/coupon_admin.php, admin/customers.php, admin/downloads_manager.php, admin/ezpages.php, admin/gv_mail.php, admin/gv_queue.php, admin/includes/functions/localization.php, admin/includes/modules/copy_to_confirm.php, admin/includes/modules/move_product_confirm.php, admin/includes/modules/product_music/copy_to_confirm.php, admin/includes/modules/product_music/update_product.php, admin/includes/modules/update_product.php, admin/modules.php, admin/orders.php, admin/salemaker.php, admin/specials.php, admin/sqlpatch.php, admin/store_manager.php, includes/functions/specials.php
=> Add multiple notifiers to the Admin for prod/cat/gv/sale/special/ezpage/currency/orders/etc

includes/classes/db/mysql/query_factory.php
=> Trigger E_USER_ERROR if bindVars field-type is invalid/unsupported

admin/login.php
=> Fix inconsistencies in HTML - admin

admin/includes/debug_logs_checker.php, admin/includes/functions/general.php, admin/includes/languages/english/view_log.php, admin/includes/languages/english/widgets_default.php, admin/view_log.php, includes/filenames.php, includes/library/zencart/DashboardWidget/src/Logs.php
Tests:
- missing file
- javascript in file
- tampering with logname parameter.
=> Fixes #76 Makes debug logs clickable

includes/init_includes/init_canonical.php, includes/templates/template_default/common/html_header.php, includes/templates/template_default/sideboxes/tpl_languages.php
=> Fix $language_array pointer reset clash

zc_install/sql/updates/mysql_upgrade_zencart_160.sql
Updates #976 and closes #374 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/980)
=> query updated for mutlingual stores that upgrade

includes/library/zencart/listingBox/src/boxes/LeadMediaManagerClips.php, includes/library/zencart/listingBox/src/boxes/LeadMediaManagerProducts.php
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/983)
=> Wrong define

includes/library/zencart/listingBox/src/boxes/ReportStatsProductsViewed.php
=> Fixes #982 Blank page for Admin Products Viewed

admin/includes/languages/english/widgets_default.php, includes/library/zencart/DashboardWidget/src/Logs.php
Provide a link in the widget to make it easy to clean everything out.
=> Link to Store Manager to clean out logs

admin/includes/languages/english/widgets_default.php, includes/library/zencart/DashboardWidget/src/AbstractWidget.php, includes/library/zencart/DashboardWidget/src/Logs.php, includes/library/zencart/DashboardWidget/src/WidgetManager.php, includes/library/zencart/Services/src/IndexRoute.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_160.sql
Shows the logs widget in normal color with an "all's well" icon when there are no logs, only switching to red with the warning icon if logs exist.
=> Logs color

includes/modules/pages/shopping_cart/header_php.php
Ref https://www.zen-cart.com/showthread.php?220471-Mixed-Stocks-in-shopping-cart
=> Fix alert to accommodate out-of-stock variations in shopping basket

zc_install/includes/functions/general.php
Removes https for localhost installs
=> Don't use https when building URLs if site does not support it

includes/library/zencart/Services/src/IndexRoute.php, zc_install/sql/install/mysql_latin1.sql, zc_install/sql/install/mysql_utf8.sql, zc_install/sql/updates/mysql_upgrade_zencart_160.sql
As a result of this discussion on the forum: https://www.zen-cart.com/showthread.php?220480-Countries-minor-changes-and-missing-entries&p=1313510#post1313510 , and the iso site https://www.iso.org/obp/ui/#search
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1006)
=> Some updates in country names and added missing countries

includes/library/zencart/Controllers/src/AbstractLeadController.php, includes/library/zencart/Paginator/src/Paginator.php, includes/library/zencart/listingBox/src/boxes/AbstractLeadListingBox.php, includes/library/zencart/listingBox/src/boxes/AbstractListingBox.php
It should be noted that I have only addressed those issues mentioned in  #1012 
There may be some further issues related to pagination, especially for LEAD pages that use extra row actions.
=> fixes #1012 LEAD pagination not persisted across page loads

admin/includes/languages/english/widgets_default.php, admin/includes/template/dashboardWidgets/tplWhosOnline.php, includes/library/zencart/DashboardWidget/src/WhosOnline.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_160.sql
NOTE: Depends on #1035 being merged first
=> Add whos_online dashboard widget

admin/includes/languages/english/widgets_default.php, admin/includes/template/dashboardWidgets/tplCounterHistoryGraph.php, includes/library/zencart/DashboardWidget/src/CounterHistoryGraph.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_160.sql
Graphs the last 14 days of activity
=> Add counter-history graph dashboard widget

admin/includes/template/dashboardWidgets/tplWhosOnline.php
Fixed to show counts as well as red-yellow-green traffic lights.
=> Who's Online shows indicators but not statistics

includes/modules/payment/paypaldp.php
Fixes #1024 - Unused var in PayPalDP module
Also fixes compatibility check
=> Remove unused var in module

includes/library/zencart/QueryBuilderDefinitions/src/definitions/LeadGeoZones.php, includes/library/zencart/QueryBuilderDefinitions/src/definitions/LeadGeoZonesDetail.php, includes/library/zencart/QueryBuilderDefinitions/src/definitions/LeadMediaManager.php, includes/library/zencart/QueryBuilderDefinitions/src/definitions/LeadMediaManagerClips.php, includes/library/zencart/QueryBuilderDefinitions/src/definitions/LeadMusicGenre.php, includes/library/zencart/QueryBuilderDefinitions/src/definitions/LeadRecordCompany.php, includes/library/zencart/QueryBuilderDefinitions/src/definitions/LeadTaxClasses.php, includes/library/zencart/QueryBuilderDefinitions/src/definitions/LeadUsers.php
=> Add LEAD date-added/updated relationships

admin/includes/template/partials/leadInputTypes/tplLanguageText.php, includes/library/zencart/Controllers/src/AbstractLeadController.php, includes/library/zencart/FormValidation/src/FormValidation.php, includes/library/zencart/Lead/src/AbstractBuilder.php, includes/library/zencart/QueryBuilderDefinitions/src/definitions/LeadCountries.php, includes/library/zencart/QueryBuilderDefinitions/src/definitions/LeadTaxClasses.php, includes/library/zencart/QueryBuilderDefinitions/src/definitions/LeadUsers.php, includes/library/zencart/Services/src/LeadService.php
some initial code for LEAD form validation
=> some initial code for LEAD form validation

admin/includes/template/dashboardWidgets/tplBannerStatistics.php
Without this change it issues a debug log and shows no graph.
Similar issue as was fixed in PR #1088
=> Fix banner statistics widget

admin/includes/template/templates/tplIndexStartWizard.php
=> Fix JQuery Selector in Zones Ajax call - Fixes #1101

includes/modules/pages/checkout_payment/jscript_main.php
Fix posted by  @lat9  ref https://www.zen-cart.com/showthread.php?220658
=> Fix incorrect selector in checkout_payment form-submit jQuery

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_160.sql
There are only a few with this issue and increasing their
height completely solves the problem.
=> Fixes #1104 Some widgets chopped off at bottom

admin/includes/template/dashboardWidgets/tplBannerStatistics.php, admin/includes/template/dashboardWidgets/tplCounterHistoryGraph.php, admin/includes/template/dashboardWidgets/tplSalesGraphReport.php, includes/library/zencart/DashboardWidget/src/NewCustomers.php, includes/library/zencart/DashboardWidget/src/NewOrders.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_160.sql
Repositioned default widgets.
Also resized some of the graphs to fit single-height widget locations
=> Realign widget default layouts to be more realistic for busy stores

admin/includes/template/common/tplFooter.php, admin/includes/template/layouts/default.php
=> Fixes #1060 admin index page squashed

.travis.yml
This allows testing against 7.1 etc
=> Add PHP nightly to Travis CI tests

zc_install/includes/languages/lngEnglish.php, zc_install/includes/template/templates/admin_setup_default.php
Do not rename admin folder when in DEVELOPER_MODE.
Message accordingly.
=> Read DEVELOPER_MODE from includes/localConfig.php

includes/library/zencart/Services/src/LeadLanguagesRoutes.php, includes/library/zencart/Services/src/LeadRoutes.php
=> fix changes to updateExecuteStandard previously comitted

includes/classes/shopping_cart.php, includes/functions/functions_general.php, includes/library/zencart/Paginator/src/AbstractScroller.php
These should fix small issues flagged up by code inspection
- return types
- missed array notation on param list
- indentation inconsistency
=> Fix minor code-review inconsistencies

admin/categories.php, admin/configuration.php, admin/includes/template/common/tplHtmlHead.php, admin/includes/template/common/tplHtmlHeadLegacy.php, admin/includes/template/layouts/default.php, admin/product.php
Some Notes.
I have only converted
admin/configuration.php
admin/categories.php
admin/product.php
There has been no attempt to use consistent css and as such there are still some
minor styling issues. The main thrust of the commit was to provide some bridging
for tplVars.
=> Many admin pages do not have the new look References issue #996

includes/classes/currencies.php, includes/init_includes/init_currencies.php
`isset` should have been `is_set`, but changing to `exists` for clarity
=> Fix error introduced in #1122

admin/includes/languages/english/users.php
They were missing from includes/languages/english/users.php however.
=> These messages were all used in admin/users.php

admin/includes/languages/english/extra_definitions/system_inspection.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1141)
=> Shouldn't the file extension be removed?

zc_install/includes/classes/class.zcDatabaseInstaller.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1142)
=> Minor clean up, tabs should be spaces

admin/invoice.php, admin/orders.php, admin/packingslip.php, admin/reviews.php, includes/classes/order.php
=> Retire remaining uses of zen_db_output() with zen_output_string_protected()

includes/classes/category_tree.php
Stores with large numbers of categories can error during recursion.
=> Switching to non-recursive category tree.

admin/customers.php, includes/functions/functions_customers.php
Move a bunch of processing logic into functions file instead of admin/customers.php
=> Refactor admin customers queries and code to shared functions

includes/languages/english/modules/payment/payeezyjszc.php, includes/modules/pages/checkout_payment/jscript_payeezy.php, includes/modules/payment/payeezyjszc.php
Ref https://github.com/zencart/payeezyjs/releases/tag/0.91
=> Update Payeezy module to 0.91

admin/customers.php
The default case does indeed run, for example for case 'isconfirm'.
=> Fixes #936 This ticket is wrong, so comment is incorrect

zc_install/sql/updates/mysql_upgrade_zencart_160.sql
Currently, upgrade from 1.5.5 creates multiple logs
=> Fix upgrade sql differences from v155 to v160

includes/library/zencart/DashboardWidget/src/WidgetManager.php
=> Function zen_is_superuser has no parameters

includes/modules/category_row.php
Extra "!" accidentally left in probably during copy/paste.
=> Fix extra unnecessary character

ajax.php
Include application_bottom.php so that any session-related changes made
by an AJAX handler are properly saved.
=> #1202: Save session after AJAX request

includes/functions/plugin_support.php, zc_install/includes/classes/class.systemChecker.php
=> Extend CURL timeouts to accommodate slower AWS resolution for Asia

includes/autoload_func.php, ipn_main_handler.php
Syntax changes for PHP 7.0 compatibility
=> #1222: Additional $$ changes

admin/includes/template/javascript/select2DriverGeoZonesDetail.php, admin/includes/template/javascript/select2DriverStandard.php, includes/library/zencart/Controllers/src/AbstractLeadController.php, includes/library/zencart/Controllers/src/AbstractListingController.php, includes/library/zencart/View/src/TplVarManager.php
some further refactoring of controllers re view/tplVars
=> V160 view controller (#1243)

includes/library/zencart/Controllers/src/admin/ServerInfo.php
=> Server information page formatting issue

includes/classes/currencies.php, includes/classes/order.php, includes/functions/functions_taxes.php
Using the example from the issue, bot the catalog and admin
show the price at $6.99.
=> FIXES #276 Admin tax rounding not the same as catalog

admin/includes/template/css/stylesheet.css, admin/includes/template/partials/specialMenu/tplUserDropdown.php, includes/library/zencart/AdminUser/src/AdminUser.php
Fixes #1241 - credits to @barco57
=> Fix gravatar image resolution

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_160.sql
Forgot to remove language_id from index when removing from
dashboard_widgets_groups table.
=> Removes deleted field from index

ipn_main_handler.php
create_add_products function from orders class only has 1 parameter.
=> Fixing erroneous extra parameter

includes/functions/functions_email.php
- inner loop at line 282 - use different variables than are used on line 81.
- same at line 364 vs line 81.
This is not a true bug but someone could accidentally create one by not
being aware of the reuse.
=> Function re-uses loop variables for inner and outer loop

includes/library/zencart/Controllers/src/AbstractLeadController.php, includes/library/zencart/ListingQueryAndOutput/src/definitions/AbstractDefinition.php, includes/library/zencart/ListingQueryAndOutput/src/definitions/AbstractLeadDefinition.php
The controller editExecute method was using buildResults, when really it needs it's own method.
=> Fixes #1155 (Mostly) unused return value from buildResults()

includes/library/zencart/Controllers/src/AbstractLeadController.php, includes/library/zencart/ListingQueryAndOutput/src/definitions/LeadCountries.php, includes/library/zencart/ListingQueryAndOutput/src/definitions/LeadZones.php, includes/library/zencart/Services/src/LeadService.php
Note.  There were a couple of bugs in previous code.
1. Handling of language keys was broken due to a clash in variable naming.
2. Handling of template output for add/edit fields was broken when validation failed. 
Item 2 still needs some work. At the moment I have just introduced a workaround
=> Updating some validation code

includes/modules/pages/shopping_cart/header_php.php
=> Remove stray line from long ago

includes/modules/payment/paypalwpp.php
This unreached code has been here since 1.3.9.  Let's remove.
=> Remove block of unreached code

zc_install/includes/classes/class.systemChecker.php, zc_install/includes/languages/lngEnglish.php, zc_install/includes/systemChecks.yml
i think this is correct.
Fixes #1275
=> Fixes #1275 checks ini_set function on install

includes/templates/template_default/sideboxes/tpl_search.php
Fixes an error found while researching #928
=> Fix "non well formed numeric value" in tpl_search.php

includes/classes/payment.php
=> Add missing semicolon

admin/orders.php
I've removed the unnecessary <br /> tags in the order information table in admin/orders.php
=> Removed unnecessary <br /> tags in the order information table

ajax.php
Make ajax handler respond only to ajax calls
And clean up the code so that sessions are closed properly under all execution paths.
Fixes #1296
=> Make ajax handler respond only to ajax calls

admin/includes/functions/html_output.php
=> Add deprecation alert/log for admin use of zen_href_link

includes/classes/cc_validation.php
Now recognizes: `510000-550000` and `222100-272099` as MasterCard
Thanks to @proseLA
=> Update the cc_validation to recognize the new MasterCard BIN "2" range

includes/languages/english.php, includes/library/zencart/CheckoutFlow/src/flowSteps/Shipping.php, includes/modules/pages/checkout_shipping/header_php.php
(since v1.3.9)
Ref https://www.zen-cart.com/showthread.php?220775
Thanks @lat9
=> Move inline error message text to language file

admin/includes/stylesheet.css
Ref: https://www.zen-cart.com/showthread.php?219982-admin-css-selector-language-dependent
Thanks @torvista
=> Change admin css selector for module buttons to be multi-lang friendly

zc_install/sql/updates/mysql_upgrade_zencart_155.sql
Ref: https://www.zen-cart.com/showthread.php?220696-Missing-layout_boxes-configuration-for-responsive_classic-on-upgrade
=> Include layout-boxes defaults for responsive-classic in v155 upgrade sql

includes/templates/template_default/templates/tpl_account_edit_default.php
Ref: https://www.zen-cart.com/showthread.php?221142-Fax-number-on-tpl_account_edit_default-php
=> Fix: if fax disabled in config, should also disable in account-edit tpl

includes/templates/responsive_classic/templates/tpl_checkout_payment_address_default.php, includes/templates/responsive_classic/templates/tpl_checkout_shipping_address_default.php
Ref: https://www.zen-cart.com/showthread.php?221119-Checkout-shipping-payment-addresses-Can-t-cancel-if-only-1-address
Thanks @lat9
=> Enable the "back" button on checkout address edit pages

includes/templates/template_default/common/html_header.php
Make separator dynamic; and Display for all languages (or skip if only 1 language).
Updates #727
=> Make hreflang separator dynamic and display for all languages

includes/functions/functions_email.php
=> Fix email_collect_extra_info()  formatting.

includes/modules/pages/product_info/main_template_vars.php, includes/modules/pages/shopping_cart/header_php.php
Fixes blank page on shopping cart when removing last item from basket
=> fix instantiation of model factory

admin/login.php, docs/whatsnew_1.5.5.html
... because evidently Chrome 54.0.2840.59 doesn't like javascript functions named 'animate'.
=> Fix Chrome browser incompatibility with javascript function name

ajax.php
=> Rearrange function declarations in ajax handler for compatibility

docs/changed_files-v1-5-5.html, docs/whatsnew_1.5.5.html, includes/modules/order_total/ot_coupon.php
Merge @lat9 fixes for correcting tax on `Free Shipping Off / %`
=> 20160417-lat9-Correct tax on free-shipping+off/%

docs/changed_files-v1-5-5.html, docs/whatsnew_1.5.5.html, includes/classes/shopping_cart.php
(Backported from v160)
Also removes `number_of_uploads` from URI on add-to-cart redirects.
=> Add shopping cart methods for calc in-cart details for category-lookups

admin/includes/template/common/tplMainMenu.php
Fixes #1264
replaces / closes #1325
=> Fix collapsing/expanding of main admin menu in mobile view

includes/languages/english/login.php, includes/languages/english/password_forgotten.php, includes/modules/pages/login/header_php.php, includes/modules/pages/password_forgotten/header_php.php
Closes #1295 
i'm sorry; i was not sure about the proper way to add a new config value into the database.
i have it in a new temp file in the zc_install directory.  
please tell me the best way to handle this if the PR is on its way to being accepted and i will modify accordingly.
best.
=> Add invalid email address message fixes #1295

admin/includes/init_includes/init_sanitize.php
=> Fixes 1348 add products_options_comment field to sanitizer

includes/library/zencart/DashboardWidget/src/NewOrders.php
Remove some unnecessary aliases which make the query harder to read
=> Tidy the SQL query in the NewestOrders widget

.travis.yml
(Travis doesn't currently display the installed version of MySQL in its list of installed resources.)
=> TravisCI: echo mysql version & skip admin config file (no longer used)

admin/includes/languages/english/server_info.php, admin/includes/template/templates/tplServerInfo.php, app/Controllers/admin/ServerInfo.php
Update the Tools->Server Info to include database configuration
=> Server Info:  Add database section

includes/auto_loaders/config.paypalwpp_incontext.php, includes/classes/observers/class.paypalwpp_incontext.php, includes/classes/payment.php, includes/modules/pages/checkout_confirmation/jscript_paypal_incontext.php, includes/modules/pages/checkout_payment/jscript_paypal_incontext.php, includes/modules/pages/checkout_shipping/jscript_paypal_incontext.php, includes/modules/pages/checkout_success/jscript_paypal_incontext.php, includes/modules/pages/index/jscript_paypal_incontext.php, includes/modules/pages/login/jscript_paypal_incontext.php, includes/modules/pages/shopping_cart/jscript_paypal_incontext.php, includes/modules/pages/time_out/jscript_paypal_incontext.php, includes/modules/payment/paypal/paypalwpp_incontext.php, includes/modules/payment/paypal/tpl_ec_button.php, includes/modules/payment/paypalwpp.php, includes/templates/template_default/templates/tpl_checkout_confirmation_default.php
=> Mc12345678 restore paypal incontext operation

includes/classes/shopping_cart.php
In #1163, an issue with updating the cart was identified.
The solution to that issue (#1164) prevented assigning the maximum product
to the cart on update `added:`(when trying to increase the in-cart quantity above the maximum allowed) `:`
and instead would result in the last acceptable
quantity remaining in the cart instead of going "out-of-bounds".
This corrects the issue(s) discussed in those two threads by minorly
rearranging the actionUpdateProduct code to perform the cart decrease actions `added:`with no revision of the decrease functionality (ie. no change in cart quantity resolution if add less than the minimum/unit combination)`:`
before any cart increase actions and specifically to support mixed product as
that is a situation where two or more cart products can/do depend on
each …
=> Provide maximum product on shopping cart product update.

includes/classes/db/mysql/query_factory.php
=> Add __destruct method to query-factory

app/Controllers/AbstractListingController.php, behat.yml, includes/library/zencart/ListingQueryAndOutput/src/ViewDefinitionFactory.php, includes/library/zencart/ListingQueryAndOutput/src/definitions/ReportStatsCustomers.php, includes/library/zencart/Services/src/LeadService.php, includes/modules/sideboxes/whats_new.php, includes/templates/template_default/sideboxes/tpl_categories.php, testFramework/behat/features/testFeatures/adminReports.feature, testFramework/behat/features/testFeatures/testInstaller.feature
Create a better Dependancy Injection for view definitions
Fix errors in reports caused by change to table aliases
Fix errors in catalog caused by change to table aliases
Add some more Behat tests
=> V160 major controller refactor

admin/includes/defined_paths.php
=> ENABLE_SSL_ADMIN temporary bridge for plugins

admin/includes/header_navigation.php
=> Remove double class attr in nav

admin/customers.php
Fixes bug in v1.5.5c and v1.5.5d
=> Fix error from merge of #1351 for customer-delete actions

app/Controllers/AbstractAdminController.php, app/Controllers/AbstractLeadController.php, app/Controllers/AbstractListingController.php, app/Controllers/admin/Currencies.php, app/Controllers/admin/GeoZonesDetail.php, app/Controllers/admin/Index.php, app/Controllers/admin/Languages.php, app/Controllers/admin/MediaManagerClips.php, app/Controllers/admin/MediaManagerProducts.php, app/Controllers/admin/OrdersStatus.php, app/Controllers/admin/ServerInfo.php, app/Controllers/admin/SystemInspection.php, app/Model/CountriesName.php, includes/library/zencart/ListingQueryAndOutput/src/definitions/AbstractDefinition.php, includes/library/zencart/Services/src/LeadService.php, includes/library/zencart/View/src/TplVarManager.php
The intent here is to move to use tplVarManager code over localized tplVars in classes,
and also tidy up some language related model code
=> refactoring template var stuff, and some model language code

includes/modules/attributes.php
Adds the secondary sort by option name when sorting also by option sort-order.
See [this ](https://www.zen-cart.com/showthread.php?222184-Product-attribute-sorting)Zen Cart posting for additional information.
=> Attribute option sort ordering

includes/init_includes/init_file_db_names.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1425)
=> Fix some typos in the comments

includes/templates/responsive_classic/css/responsive_tablet.css
=> Fix CSS typo on "row"

includes/init_includes/init_sanitize.php
=> Re-sanitize against XSS in v160 default template

includes/classes/class.base.php, zc_install/includes/classes/class.zcDatabaseInstaller.php
=> Refactor deprecated create_function() calls

.travis.yml, composer.json, testFramework/composer-php55.lock
And selectively downgrade only when testing older PHP versions
=> Update to latest phpunit

includes/library/aura/di/.travis.yml, includes/library/aura/di/composer.json, includes/library/aura/di/src/Container.php, includes/library/aura/di/src/Injection/InjectionFactory.php, includes/library/aura/di/src/Injection/Lazy.php, includes/library/aura/di/src/Injection/LazyArray.php, includes/library/aura/di/src/Injection/LazyCallable.php, includes/library/aura/di/src/Injection/LazyInclude.php, includes/library/aura/di/src/Injection/LazyRequire.php, includes/library/aura/di/src/Injection/LazyValue.php, includes/library/aura/di/src/ResolutionHelper.php, includes/library/aura/di/src/Resolver/Reflector.php
Aura.Di 3.2.0 plus untagged updates
=> Update Aura.Di package to 3.2.0 

includes/modules/payment/authorizenet_aim.php
One configuration setting wasn't being displayed in the edit page.
Updated comments
Also logs more detailed validation failure details
=> Fix missing AIM configuration setting

includes/classes/shopping_cart.php
=> Fix calc for attr qty prices onetime

admin/includes/extra_datafiles/dup_models.php, admin/includes/languages/english/extra_definitions/dup_models.php, includes/filenames.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1445)
=> Move box define to language file

admin/includes/languages/english/extra_definitions/system_inspection.php, includes/filenames.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1444)
=> move filename define to filenames.php

includes/classes/db/mysql/query_factory.php
Add a function to the database class that returns the number of affected rows in the previous SELECT, UPDATE, REPLACE or DELETE query.
=> Database: Add affectedRows function

includes/classes/db/mysql/query_factory.php, includes/classes/order.php
I know I've got this messed up (pulling in two changes), but I don't understand how to coerce GitHub and SourceTree to reflect that.
=> Order notifiers special taxes

includes/languages/english/checkout_guest_emailonly_account_collect_flow.php, includes/languages/english/checkout_payment_flow.php, includes/templates/template_default/templates/tpl_checkout_guest_emailonly_account_collect_default.php, includes/templates/template_default/templates/tpl_checkout_payment_default.php
=> Fix terms-conditions mismatched span

admin/customers.php, admin/includes/languages/english/customers.php
Ref https://www.zen-cart.com/showthread.php?190076-Disabling-Customers-Email
=> Allow Admin to disable all emails to certain customers

admin/includes/functions/localization.php
Feed format was changed. Now using the json source.
=> Update BOC exchange rate updater

includes/templates/responsive_classic/common/html_header.php, includes/templates/template_default/common/html_header.php
Ref: https://www.zen-cart.com/showthread.php?222554-hreflang-problem-please-help&p=1332828#post1332828
=> Remove zenid from hreflang

includes/templates/template_default/common/tpl_price_block.php
=> Fix nested block error

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_156.sql
=> Remove unused `final_price` field from customers_basket table.

admin/zcAjaxHandler.php, includes/library/zencart/AjaxDispatch/src/AjaxDispatch.php
=> Ajax handler should close session before exit

app/Controllers/AbstractListingController.php
Fixes errors when using LEAD page filtering
=> need to use tplVarManager rather than old tplVars

admin/includes/init_includes/init_header.php, admin/includes/languages/english.php, includes/modules/order_total/ot_gv.php
=> Remove SHOW_GV_QUEUE define from english.php into ot_gv settings

admin/includes/languages/english/product.php, admin/product.php
Ref https://www.zen-cart.com/showthread.php?222731
=> Fix confusing text related to copying qty discounts when cloning products

admin/includes/functions/html_output.php
By adding $parameters to the zen_draw_file_field function, it is possible to style the button with for a better look, for example with bootstrap (class="form-control")
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1495)
=> Sugestion: add $parameters to filefield

zc_install/sql/updates/mysql_upgrade_zencart_156.sql
product_options should be products_options
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1497)
=> typo in table name

admin/includes/modules/document_general/preview_info_meta_tags.php, admin/includes/modules/product/preview_info_meta_tags.php, admin/includes/modules/product_free_shipping/preview_info_meta_tags.php, admin/includes/modules/product_music/preview_info_meta_tags.php
Brackets for the row in this table were missing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1498)
=> Add missing <tr> brackets

includes/functions/functions_email.php
For reference see:
https://www.zen-cart.com/showthread.php?222776-Remnants-of-obsolete-Tell-a-Friend-feature-in-ZC-1-5-5x
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1501)
=> remove tell a friend remnants

includes/languages/english/shopping_cart.php, includes/templates/responsive_classic/templates/tpl_shopping_cart_default.php, includes/templates/template_default/templates/tpl_shopping_cart_default.php
=> Split TEXT_VISTORS_CART to create TEXT_CART_HELP for shopping_cart page

includes/dist-configure.php, zc_install/includes/catalog-configure-template.php, zc_install/includes/classes/class.systemChecker.php, zc_install/includes/classes/class.zcDatabaseInstaller.php, zc_install/includes/template/common/html_header.php
Fixes some strict type errors
Fixes typo in dist-configure - thx @mc12345678
=> Updates to zc_install

includes/modules/create_account.php
=> Support ISO-8601 style date-of-birth date (merge #1515)

admin/includes/template/common/tplHtmlHead.php
- Added protocol to links
- change moment.min.js to moment-with-locales.min.js in favor of multi lingual use
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1519)
=> CDN protocol updates to some admin js assets

admin/index_dashboard.php
=> Fix graph display when counter-history is empty

includes/modules/additional_images.php, includes/modules/main_product_image.php
These notifiers, included in IH-5, v5.0.0 and later, allow Image Handler and associated large-image viewers (like Fual Slimbox and ColorBox) to be "drop-in".
=> Image Handling: Additional notifiers

admin/includes/modules/update_product.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1532)
=> remove extra closing brackets

includes/templates/responsive_classic/jscript/jscript_framework.php, includes/templates/template_default/jscript/jscript_framework.php
... as discovered and corrected within the "One Page Checkout" plugin's distribution.
=> v156: Corrections to jscript_framework.php

admin/includes/functions/html_output.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1539)
=> removing obsolete $language variable

admin/includes/modules/product_music/update_product.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1540)
=> Corrections to #1516

admin/includes/classes/object_info.php
Also updated for PHP7.2 compatibility, plus code formatting
=> Add magic methods objectInfo class

zc_install/includes/nginx_conf/ngx_server_template.txt
1. Removes Superfluous "Internal" Location Blocks
2. Adopts Consistent Approach by Eliminating Nested Location Blocks
=> Misc Fixes to Nginx Conf Template

admin/option_name.php, admin/option_values.php, admin/options_name_manager.php, admin/options_values_manager.php
This is an update for the page layout. Giving it a more modern look.
There are no functional changes , only  things like "while" to "foreach", and removing obsolete/unused code
Related to #1511 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1546)
=> Admin layout updates for Options Manager screens

includes/modules/pages/account_newsletters/header_php.php
Incorporated notifiers into includes/modules/pages/account_newsletters/header_php.php to support the newsletter plugin and not further modifying this file.
3 Notifiers added: 
NOTIFY_HEADER_START_ACCOUNT_NEWSLETTERS
NOTIFY_HEADER_ACCOUNT_NEWSLETTER_UPDATED
NOTIFY_HEADER_END_ACCOUNT_NEWSLETTERS
=> Add Notifiers associated with account_newsletters

admin/categories.php
The place of the closing bracket prevents search parameter from being added to the path
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1562)
=> Wrong place of closing bracket - breaks category search in admin

admin/includes/stylesheet.css, admin/password_forgotten.php, includes/templates/responsive_classic/common/html_header.php, includes/templates/template_default/common/html_header.php
- Added missing protocol to the  link
- Updated the bootstrap version from 3.3.5 to 3.3.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1573)
=> V1.5.6: Add protocol to link and update bootstrap version

admin/includes/classes/AdminRequestSanitizer.php, admin/includes/init_includes/init_sanitize.php
This also added transfer of the parameterDefinition through the
processCustom function to allow the custom function to know the associated
definition.
=> Add a Simple array to sanitize operation.

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_156.sql
Allows for longer path names (or optionally URLs if plugins are doing that).
Fixes #1564
=> Lengthen fields for image paths

admin/attributes_controller.php, admin/banner_manager.php, admin/categories.php, admin/downloads_manager.php, admin/includes/functions/general.php, admin/includes/modules/product_music/update_product.php, admin/includes/modules/update_product.php, admin/manufacturers.php, admin/record_artists.php, admin/record_company.php, includes/functions/functions_general.php
Compliments #1574 
And addresses deeper issue in #1564
=> Add helper function to limit filename length for images too long for db

includes/functions/functions_prices.php
Strict reporting correction for functions_prices
=> V156 strict zen get products display price

includes/classes/order.php
These changes have been required for Edit Order's operation for a couple of years now.  It's time to "go core".
=> Change to enable order reconstruction

includes/classes/categories_ul_generator.php, includes/classes/currencies.php, includes/modules/pages/advanced_search_result/header_php.php
=> Fix some PHP strict-typing errors

admin/orders.php
Align the notifiers previously added, using the interface currently present in the v160 version of the orders.php script.
=> Align previous commit #1613 with v160

includes/modules/pages/download/header_php.php
Update the download page's processing, with some re-factoring, to enable a download to be gathered via order's email address, in support of guest checkout.
=> zc156-downloads-for-guests

admin/includes/init_includes/init_templates.php
small change.  little cleaner.
=> remove unnecessary preg_replace Fixes #1616

includes/functions/functions_customers.php
Additional functions, allowing core-code and plugins to consistently identify whether or not a customer is logged in and whether/not a guest-checkout is active.
=> v156-customer-logged-in-guest

admin/login.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1629)
=> fix typo in css name

admin/login.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1640)
=> More refactoring of admin login page

admin/ezpages.php
- remove double setting of parameters
- remove parameters that are defined twice
- minor layout update
- some bug fixes (missing closing form tag, and typo in button class)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1646)
=> Ez page updates

admin/orders.php
Pull in the notifiers that are currently present in the zc160/develop branch, but not in the v156 branch.
=> #1650-align-zc156-admin-orders-notifiers

admin/orders.php
Align the develop branch's /admin/orders.php notifiers with their v156 counterparts.
=> #1650-dev-align-admin-orders-notifiers

email/email_template_checkout.html, includes/classes/order.php, includes/languages/english/email_extras.php
Also provide notifier for additional customization.
=> Include store-defined message in all order confirmation emails

includes/classes/order_total.php
php was complaining about:
Undefined property: ot_subtotal::$credit_class in
/includes/classes/order_total.php on line 165
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1674)
=> Undefined property: ot_subtotal::$credit_class

includes/functions/functions_email.php
Don't try to pull in css file if it doesn't exist.
=> Fix errors where old sites are missing new email css file

.gitignore
Update .gitignore file with IDE file entries from 1.6.0.
=> Updating .gitignore to ignore IDE files

includes/functions/functions_email.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1686)
=> Tiny fix: wrong @param name

admin/product.php
Add a notifier to support display of additional options when copying a product.
=> Add product notifier to UI for copying attributes

includes/functions/functions_prices.php
Builds on the attributes modifications previously made so that discounts can be incorporated into the final_attributes_price function.
=> Update attribute price handling to address discounts.

includes/functions/functions_email.php
Recommendation from @lat9 in discussion of pull request #1685  here: https://github.com/zencart/zencart/pull/1685#issuecomment-390402459
=> Downgrade error to warning - should not be fatal

includes/modules/shipping_estimator.php
Looks bigger than it is because I removed the control-Ms as well.
=> Remove some unused code from shipping estimator module

admin/customers.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1705)
=> Fix typos from previous refactoring

zc_install/includes/languages/lngEnglish.php, zc_install/includes/modules/pages/completion/header_php.php, zc_install/includes/modules/pages/index/header_php.php, zc_install/includes/nginx_conf/.gitignore, zc_install/includes/nginx_conf/ngx_server_template.txt, zc_install/includes/nginx_conf/zencart_ngx_http.conf, zc_install/includes/template/templates/completion_default.php, zc_install/includes/template/templates/index_default.php
=> [v156] Port Nginx Config

docs/0.about_zen_cart.html, docs/1.readme_installation.html, docs/2.readme_how_to_upgrade.html, docs/changed_files-v1-5-0.html, docs/changed_files-v1-5-1.html, docs/changed_files-v1-5-2.html, docs/changed_files-v1-5-3.html, docs/changed_files-v1-5-4.html, docs/changed_files-v1-5-5.html, docs/changed_files-v1-5-6.html, docs/important_site_security_recommendations.html, docs/index.html, docs/whatsnew_1.5.0.html, docs/whatsnew_1.5.1.html, docs/whatsnew_1.5.2.html, docs/whatsnew_1.5.3.html, docs/whatsnew_1.5.4.html, docs/whatsnew_1.5.5.html, docs/whatsnew_1.5.6.html, docs/zen.css, includes/templates/template_default/templates/tpl_zc_install_suggested_default.php
Minor Tweaks and add missing changes in "Install Suggested" page.
Before: https://www.screencast.com/t/mEceXJGG87i
After: https://www.screencast.com/t/whmYahWLiG
Updates #1669
=> [v156] Updates to #1669 (Documentation files)

includes/modules/pages/account_edit/jscript_form_check.php, includes/modules/pages/account_password/jscript_form_check.php, includes/modules/pages/address_book_process/jscript_main.php, includes/modules/pages/checkout_payment_address/jscript_main.php, includes/modules/pages/checkout_shipping_address/jscript_main.php, includes/modules/pages/create_account/jscript_form_check.php, includes/modules/pages/login/jscript_form_check.php
=> Fix syntax error in check_state function (jscript_main files)

admin/orders.php
Removed second initialization (and a block of commented out code); changed subsequent set of variable to use concatenation instead of just assignment.
=> Fixes #1667 - $fields variable is already initialized

includes/modules/payment/paypal/paypal_curl.php
=> micropayments for pp express Fixes #1618

includes/classes/order.php
... by specifying the sort-order for the query.
=> Correct attributes' display "randomness" - Fixes #1729

includes/modules/pages/featured_products/header_php.php, includes/modules/pages/specials/header_php.php, includes/modules/pages/specials/main_template_vars.php
=> Update notifiers for featured_products/specials

zc_install/includes/languages/lngEnglish.php, zc_install/includes/modules/pages/completion/header_php.php, zc_install/includes/modules/pages/index/header_php.php, zc_install/includes/template/templates/completion_default.php, zc_install/includes/template/templates/index_default.php
This aligns the Nginx Config in Dev by bringing in edits done when back porting the config to v156. In some cases this just means indicating that the changes were introduced in v1.5.6.
=> [Dev] Align Nginx Config with v156

includes/templates/template_default/templates/tpl_modules_create_account.php
Per suggestion from @torvista.
=> Move country to the top of the Address form

admin/ezpages.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1743)
=> v156 fix incorrect variables in admin/ezpages.php

admin/attributes_controller.php, admin/includes/functions/general.php, admin/includes/header.php, admin/includes/modules/document_general/preview_info.php, admin/includes/modules/document_product/preview_info.php, admin/includes/modules/product/preview_info.php, admin/includes/modules/product_free_shipping/preview_info.php, admin/includes/modules/product_music/preview_info.php, admin/includes/modules/products_previous_next.php, admin/includes/modules/update_product.php, admin/options_name_manager.php, admin/product_types.php, admin/products_price_manager.php, includes/classes/order.php, includes/classes/shopping_cart.php, includes/functions/functions_lookups.php, includes/init_includes/init_customer_auth.php, includes/init_includes/init_gzip.php, includes/init_includes/init_header.php, includes/modules/shipping_estimator.php
Unsure of which if any of these have already been reported/fixed because
of the number of items identified.  Advise which to remove or request
to rebase which should remove any already incorporated at that time (even
if it means for me to remove merge errors).
=> v156 Eliminate some of the strict error reports

admin/includes/classes/message_stack.php, includes/languages/english/html_includes/responsive_classic/define_main_page.php, includes/modules/meta_tags.php, includes/modules/pages/page/header_php.php, includes/modules/product_listing_alpha_sorter.php, includes/modules/responsive_classic/product_listing.php, includes/templates/responsive_classic/templates/tpl_index_product_list.php
Found some more items reported when operating in strict mode as have continued to use v1.5.6 and running various tests.
=> Strict error corrections

includes/functions/plugin_support.php
=> Stop using trigger_error() during plugin version-update checking

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_156.sql
=> Change primary key on sessions table

.gitignore
Wanted to use the "dev-" pattern for ADMIN_BLOCK_WARNING_OVERRIDE but not have it checked in.
=> Adding things from 160 .gitignore

admin/customers.php, admin/includes/languages/english/customers.php
While not a fan of having html in languages stuff, makes sense here.
Also don't see the need for text when there is only one addressbook link
but have allowed for that with TEXT_INFO_ADDRESS_BOOK_COUNT_SINGLE
fixes issue #1585
=> issue #1585 cosmetic change admin customers addresses

includes/modules/pages/account_newsletters/header_php.php, includes/templates/template_default/templates/tpl_account_newsletters_default.php
=> Fixes issue #1704 Newsletter update redirect

includes/templates/template_default/templates/tpl_zc_install_suggested_default.php
This fixes the broken css link to the docs folder, as there should be no docs folder in a production environment.
Fixes #1776
=> fix broken css link

admin/category_product_listing.php
Note that the module that requires update has changed for the 1.5.6 release!
=> #1778: Correct categories+products in categories

docs/zen.css, includes/templates/template_default/templates/tpl_zc_install_suggested_default.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1786)
=> fix: remove space after colon

admin/options_values_manager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1788)
=> Fix some errors

admin/includes/classes/stats_sales_report_graph.php, admin/index_dashboard.php
=> Admin sales-report-graph corrections

admin/ajax.php, admin/includes/init_includes/init_admin_auth.php, admin/includes/javascript_loader.php, includes/filenames.php
=> Add admin-level, common AJAX support

includes/modules/attributes.php
Value was set to 'selected'.  
See https://www.zen-cart.com/showthread.php?224305-Call-to-zen_draw_radio_field-in-includes-modules-attributes-php
=> Call to zen_draw_radio_field should have boolean third parameter

admin/customers.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1808)
=> Remove stray <tr> tag

admin/includes/functions/admin_access.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1820)
=> Add missing global $messageStack

admin/includes/languages/english/product.php
Alerts what is required for metatags data to activate
Fixes #1555
=> Indicate what the Product's MetaTag Title is affected by

admin/featured.php, admin/products_price_manager.php, admin/products_to_categories.php, admin/specials.php
for Specials, Featured, Copy, Price Mgr
I think this fixes #1606
... Testing feedback welcome :)
=> Skip admin exclusion of products flagged as no-add-to-cart

admin/includes/stylesheet.css, admin/index_setup_wizard.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1822)
=> Bootstrap Styling updates to admin index_setup_wizard

admin/includes/languages/english/orders.php
I missed this file in the initial PR for the subject change.  This adds the `Updated By` column-text for the Customers->Orders detailed order display.
=> Add missing language file entry for #1346

includes/modules/attributes.php
=> Added fixes based on comments made to #1681

includes/classes/db/mysql/query_factory.php
=> Fixes #1824

includes/init_includes/init_sanitize.php
Avoids array-to-string-conversion notices
=> Add an extra layer of subarray handling to inputs

admin/includes/functions/general.php, includes/functions/functions_general.php, zc_install/includes/functions/general.php
Simplified code by using early-return syntax, and more memory efficient comparisons.
=> Refactor zen_not_null to add null check

admin/customers.php, admin/tax_rates.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1856)
=> Minor admin layout tweaks for responsive view improvement

admin/includes/stylesheet.css, admin/index.php, admin/index_dashboard.php
- Report box columns were not resizing the width on smaller screens
- Updated http protocol on links in bottom to https
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1857)
=> Updates to admin index page

admin/admin_activity.php, admin/admin_page_registration.php, admin/profiles.php, admin/users.php
Layout updates to some admin pages, that not got converted in the previous update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1855)
=> Styling updates to admin pages

admin/ezpages.php, admin/includes/languages/english/ezpages.php, includes/modules/pages/page/header_php.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_156.sql
Allow ezpage to be marked visible even if not show in header, footer or sidebox. 
Fixes #1823
=> Allow EZPage to show even if not in header,footer,sidebox

admin/orders.php
=> Admin-orders notifications "future-proofing"

admin/banner_manager.php, admin/banner_statistics.php
As this was one of the first converted pages some details were missed by me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1863)
=> Layout Tweaks for banner pages

admin/salemaker.php, admin/salemaker_info.php, admin/salemaker_popup.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1865)
=> Bootstrap updates for Salemaker pages

includes/modules/payment/paypal/tpl_ec_button.php
Fixes #230 by resetting sess var
=> Fix PayPal EC possible issue doing new purchase after checkout/cancel

includes/classes/currencies.php
Reduce duplication and make the math easier to follow
=> Refactor currencies class

admin/includes/javascript/spiffyCal/spiffyCal_v2_1.css, admin/includes/javascript/spiffyCal/spiffyCal_v2_1.js
I know this script will be removed in the future, but Zen Cart 1.5.6 will be around for some time. So I found it necessary to update the layout, so it matches the bootstrap theme better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1871)
=> Updates to Spiffy

admin/includes/modules/newsletters/newsletter.php, admin/includes/modules/newsletters/product_notification.php, admin/newsletters.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1875)
=> Layout updates to Newsletter and Notifications

admin/whos_online.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1876)
=> Layout Updates to Who's online

admin/includes/modules/product_music/update_product.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1880)
=> Change $_GET to $_POST to fix error on saving product type music

admin/products_price_manager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1873)
=> Layout updates to pricemanager

admin/sqlpatch.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1879)
=> Layout Updates for SQL patch

admin/includes/auto_loaders/config.adminNotifications.php, admin/includes/classes/AdminNotifications.php, admin/includes/modules/notificationsDisplay.php, admin/index_dashboard.php, admin/modules.php, includes/classes/ajax/zcAjaxAdminNotifications.php, includes/database_tables.php, includes/version.php, not_for_release/testFramework/unittests/phpunit.xml, not_for_release/testFramework/unittests/testsAdminNotifications/AdminNotificationsTest.php, zc_install/includes/version.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_156.sql
allow for targeted banner notifications on some pages
=> Notifications/Promos 

admin/stats_customers.php, admin/stats_customers_referrals.php, admin/stats_products_lowstock.php, admin/stats_products_purchased.php, admin/stats_products_viewed.php, admin/stats_sales_report_graphs.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1874)
=> Layout updates for reports

admin/includes/javascript/spiffyCal/spiffyCal_v2_1.js, admin/includes/languages/english/products_price_manager.php, admin/specials.php
see #1882
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1885)
=> Fix some bugs I made in previous PR's

admin/includes/modules/product_music/delete_product_confirm.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1890)
=> remove extra single quote

admin/includes/languages/english.php
Caused by embedded single quote.  Occurs in Admin->Customers->Customers, edit customer.
=> Fix admin javascript errors in customer javascript messages

admin/category_product_listing.php
#1896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1897)
=> fix hiding of columns

zc_install/sql/demo/mysql_demo.sql, zc_install/sql/install/mysql_zencart.sql
The intention here is to test any new plugin infrastructure so that it would allow something complex like the music type to be easily installed as an addon
=> remove product music type stuff from install

admin/includes/classes/stats_sales_report_graph.php, admin/stats_sales_report_graphs.php
1.5.6 PR: #1794 
1.5.6 issue: #1793
=> Parity: update sales report with 1.5.6 changes

admin/admin_account.php, admin/admin_activity.php, admin/admin_page_registration.php, admin/alt_nav.php, admin/attributes_controller.php
First block of fixes for #1914.
=> Fixing top part of admin page

admin/includes/init_includes/init_languages.php
=> Allow admin to support page load language overrides.

includes/languages/english/shopping_cart.php
Leaving this out will break old templates.
=> Missing define which breaks outdated templates

includes/modules/shipping_estimator.php, includes/templates/template_default/templates/tpl_modules_shipping_estimator.php
testing for `$_SESSION['customer_id']` being php empty or not.
=> Simplify checks of whether customer is logged in, during shipping-estimator

includes/modules/pages/checkout_shipping/header_php.php, includes/modules/shipping_estimator.php, includes/templates/template_default/templates/tpl_modules_shipping_estimator.php
This modified a file that was modified in a previous commit, but wasn't entirely sure how to "separate" but combine all items.  So, result is that if this were committed separately from the previous commit then there would be merge errors involved which I was trying to avoid for all.
=> V156 shipping strict

zc_install/includes/languages/lngEnglish.php
Not positive of the content but wanted to start by avoiding the log
=> Add another zc_install language define

zc_install/ajaxTestDBConnection.php
=> Fix logs created during install

admin/index.php
Go to admin home rather than creating a debug log/blank page when command is misspelled.
=> Handle bad cmd= value

admin/reviews.php, admin/salemaker.php, admin/specials.php, admin/sqlpatch.php, admin/store_manager.php, admin/template_select.php, admin/users.php, admin/view_log.php, admin/whos_online.php
Sorry, for got to send in the PR for this.
=> Final fix for #1914

admin/banner_manager.php, admin/coupon_admin.php, admin/featured.php, admin/includes/javascript/spiffyCal/spiffyCal_v2_1.js, admin/salemaker.php, admin/specials.php
Date check not correctly done in specials.  (Same bug exists in other places; I can fix if you accept this.)
=> Fix date check where spiffyCal is used

admin/includes/modules/product_music/collect_info_metatags.php, admin/includes/modules/product_music/preview_info_meta_tags.php
Update to the form of the product type musica, IF this was the spectacle procedure
=> Fix link in music product-type admin files

docs/0.about_zen_cart.html, docs/1.readme_installation.html, docs/2.readme_how_to_upgrade.html, docs/changed_files-v1-5-0.html, docs/changed_files-v1-5-1.html, docs/changed_files-v1-5-2.html, docs/changed_files-v1-5-3.html, docs/changed_files-v1-5-4.html, docs/changed_files-v1-5-5.html, docs/changed_files-v1-5-6.html, docs/important_site_security_recommendations.html, docs/index.html, docs/whatsnew_1.5.0.html, docs/whatsnew_1.5.1.html, docs/whatsnew_1.5.2.html, docs/whatsnew_1.5.3.html, docs/whatsnew_1.5.4.html, docs/whatsnew_1.5.5.html, docs/whatsnew_1.5.6.html, docs/zen.css, includes/templates/template_default/templates/tpl_zc_install_suggested_default.php
Implements Bootstrap Scaffolding in styling docs for consistency. Follows on from discussion in #1987.
=> Implement Bootstrap Scaffolding for Docs Styling

docs/0.about_zen_cart.html, docs/1.readme_installation.html, docs/2.readme_how_to_upgrade.html, docs/changed_files-v1-5-0.html, docs/changed_files-v1-5-1.html, docs/changed_files-v1-5-2.html, docs/changed_files-v1-5-3.html, docs/changed_files-v1-5-4.html, docs/changed_files-v1-5-5.html, docs/changed_files-v1-5-6.html, docs/important_site_security_recommendations.html, docs/index.html, docs/whatsnew_1.5.0.html, docs/whatsnew_1.5.1.html, docs/whatsnew_1.5.2.html, docs/whatsnew_1.5.3.html, docs/whatsnew_1.5.4.html, docs/whatsnew_1.5.5.html, docs/whatsnew_1.5.6.html
Housekeeping on indentation.
Changes to ZC Team's preferred spaces.
Excluded from #1992 so as not to obscure changes made for that.
=> Fix Indentation in Doc Files

admin/includes/functions/html_output.php
=> Remove redundant zen-href-link if/else

admin/login.php
Removed HTML markup from inside function parameter, so submit button can work.
Reformatted HTML to put line-breaks in the right spots.
=> Fix broken admin login form

docs/1.readme_installation.html, docs/2.readme_how_to_upgrade.html, docs/important_site_security_recommendations.html, docs/index.html, docs/zen.css, includes/templates/template_default/templates/tpl_zc_install_suggested_default.php
Finalises Step 2 of https://github.com/zencart/zencart/pull/1987#issuecomment-450485970.
Left with three CSS files at this stage as directed in [Forum Post](https://www.zen-cart.com/showthread.php?224839-v2-Linking-to-files-in-admin-folder).
=> Finalise Documentation Styling Reset

admin/ezpages.php, admin/includes/languages/english/ezpages.php
=> v2 Make ezpage admin look in new table for title

admin/coupon_admin.php
See https://www.zen-cart.com/showthread.php?224853-Coupon-not-working-1-5-6&p=1352909#post1352909
=> Fix rejected coupon amounts for percent-off

zc_install/sql/updates/mysql_upgrade_zencart_160.sql
=> v2 zc_install upgrade SQL for recent dashboard widgets update

admin/includes/template/AdminLTE2/dist/js/app.js, admin/includes/template/partials/tplDashboardWidgets.php, admin/includes/template/partials/tplWidgetEditForm.php, admin/includes/template/partials/tplWidgetInstallableList.php, admin/includes/template/templates/tplIndex.php, app/Controllers/AjaxDashboardWidget.php, app/library/zencart/DashboardWidget/src/WidgetManager.php
=> Rebuild widgets dynamically on change rather than a redirect

app/library/zencart/DashboardWidget/src/WidgetManager.php
=> Remove string type hinting. Breaks php5.6 compatiblity

includes/modules/featured_products.php, includes/modules/new_products.php, includes/modules/product_listing.php, includes/modules/specials_index.php
... to allow a plugin to make modifications to the generated list-box-contents.
=> Additional centerbox notifiers for plugin use

docs/0.about_zen_cart.html, docs/1.readme_installation.html, docs/2.readme_how_to_upgrade.html, docs/changed_files-v2-0.html, docs/important_site_security_recommendations.html, docs/index.html, docs/whatsnew_2.0.html
Done in preparation for formatting.
=> Fixing HTML validation errors

docs/0.about_zen_cart.html, docs/1.readme_installation.html, docs/2.readme_how_to_upgrade.html, docs/changed_files-v2-0.html, docs/important_site_security_recommendations.html, docs/index.html, docs/whatsnew_2.0.html, docs/zen.css, includes/templates/template_default/templates/tpl_zc_install_suggested_default.php
=> Merge docs dir

includes/templates/responsive_classic/common/main_template_vars.php, includes/templates/responsive_classic/templates/tpl_account_default.php, includes/templates/responsive_classic/templates/tpl_products_next_previous.php, includes/templates/responsive_classic/templates/tpl_shopping_cart_default.php
Determination of whether mobile display needed was repeated
=> Consolidate mobile display determination

includes/languages/english/gv_faq.php
Some storeowners may not use this sidebox. Instead, reference My
Account.
=> Do not reference Shopping Cart sidebox in GV FAQ

admin/includes/auto_loaders/config.core.php, admin/includes/classes/AdminRequestSanitizer.php, includes/autoload_func.php
=> Admin sanitizer htmlspecialchars parameters

admin/products_price_manager.php
Some of these included that $discounts_qty had previously been
used but is no longer in the products_price_manager code and
has been commented out to prevent notifications.
=> Address strict notifications while using products_price_manager

admin/specials.php
This properly closes the `<form>` that is opened using the function `zen_draw_form`.
=> Fix unclosed form element in admin specials.php

admin/includes/functions/functions_prices.php
Align at least some of the admin functions_prices with catalog operation.
Functions modified:
zen_get_products_actual_price
zen_get_attributes_type
zen_get_word_count
zen_get_letters_count
=> Align some of the admin functions_prices with catalog

admin/includes/modules/new_product_preview.php
Addresses strict notifications made for when there is no
img_dir posted nor the flag to overwrite is not set.
=> New Product preview strict notifications

admin/includes/modules/products_previous_next.php
Address strict notifications received on admin/includes/modules/products_previous_next.php
=> strict notice on admin products_previous_next.php

admin/includes/functions/html_output.php, includes/functions/html_output.php
to better help debugging, creates log file using ZC logging function.
also removes global variables no longer used and left over when addressed ENABLE_SSL_ADMIN constant.  from commit 2cb2c07
=> creates logfile prior to die on error in zen_href_link

includes/classes/shopping_cart.php
- ~~I am not sure what the text "et al" means, or should mean, so I removed it for now.~~
- the other two typos are clear
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2107)
=> v156: fix typos in shopping cart class comments

includes/functions/functions_lookups.php
Looking at this query it seems a bit over-complicated.
I ran some tests and I came to the conclusion it can be simplified to the format in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2108)
=> V160: Simplify manufacturers query

admin/includes/modules/delete_product.php
Current category warning list for deleting test product 12 is 
Product Master Category:
DVD Movies > Action
DVD Movies > ActionBig Linked
should be: 
DVD Movies > Action
Big Linked
First reported in https://www.zen-cart.com/showthread.php?224975-v156a-Delete-Product-From-Category-Error
=> Delete list construction needs to re-initialize each iteration

admin/banner_manager.php
Addressed strict notifications
=> v156 banner_manager strict notifications

admin/stats_products_viewed.php
Incorporate retrieval of products_type from product data to eliminate strict notifications.
=> v156 strict notice - admin/stats_products_viewed

admin/stats_products_purchased.php
Address strict notifications received when viewing stats_products_purchased.php
=> v156 strict notice stats_products_purchased

admin/banner_manager.php, admin/mail.php
In the latest update an opening bracket was removed from the if statement
(@mc12345678 )
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2135)
=> 156: Fix missing bracket in banner_manager.php and mail.php

admin/includes/modules/newsletters/product_notification.php
see forum thread: https://www.zen-cart.com/showthread.php?225020-v156a-Typo-db-gt-Execute(-quot-SELCET-DISTINCT&p=1354315#post1354315
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2136)
=> V156: Fix Typo in query on product notifications

admin/includes/modules/product_music/collect_info.php
Align product_music with other strict notification modifications that were incorporated.
=> Align product_music collect_info with fixes to other product types

admin/orders.php
Received a strict notification against admin/orders.php associated with $_GET['cID'] which is addressed by this commit.
=> test for set of $_GET['cID'] in admin/orders.php

admin/includes/languages/english.php, app/Controllers/AbstractLeadController.php, app/resources/lang/default/en/admin/button-forms.php, app/resources/lang/default/en/admin/lead-common.php, app/resources/lang/default/en/admin/pagination.php, app/resources/views/admin/adminLead.blade.php
This is a very basic conversion of admin lead pages to use blade.
Have also used new language translation structures as well
=> Conversion of lead page stuff to use blade/new language files

admin/languages.php
$coupon should be $ezpage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2158)
=> 156: Bug fix, wrong variable

admin/countries.php
The submit buttons are defined as button type instead of submit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2157)
=> 156: Bug fix Submit buttons are wrong type

includes/modules/attributes.php
Strict notification identified when cart has product that could otherwise have attributes, but the item does not have attributes associated with it.
=> v156 includes/modules/attributes.php

admin/layout_controller.php
Addresses strict notifications, updated consistency of update query where values are not forced to be of a specific data type (e.g. sort_order, status, etc..)
=> v156-layout_controller-strict

admin/index_dashboard.php
Address notifications made when using admin/index_dashboard.php while in strict mode.
=> V156 admin index dashboard strict

includes/filenames.php, includes/languages/english.php
This makes it easier to have multiple templates, and tightens up the
code.
=> Use loop instead of repetition to include files

includes/languages/english.php, includes/languages/english/checkout_confirmation.php, includes/languages/english/shopping_cart.php
Consolidate them into the main language file.
=> The out of stock messages are used in multiple places.

admin/layout_controller.php
=> fix extra dot

admin/languages.php
as requested in, and closes #2013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2197)
=> 156: Add notifiers to add and delete extra language related table fields

includes/modules/order_total/ot_coupon.php
=> Add Coupon uses exceeded notifier

includes/classes/payment.php, includes/functions/functions_lookups.php
=> Undefined index: configuration_value

includes/modules/pages/login/header_php.php, includes/templates/responsive_classic/common/tpl_header.php, includes/templates/template_default/common/tpl_header.php
Since the zen_is_logged_in and zen_in_guest_checkout functions are now available ... use them!
=> #2177: Check login status via functions

includes/functions/functions_email.php
Reduces the number of core file changes for EMail Archive Manager.
=> Store HTML email without de-fanging it

admin/products_price_manager.php
https://github.com/zencart/zencart/commit/cb93119c21f38c8ba470e96f0b84d44fad698b3b#commitcomment-32717992
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2210)
=> V156: Fix Typo in admin/products_price_manager.php

admin/customers.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2212)
=> V156: admin/customers.php Fix Typo in query

includes/functions/functions_lookups.php
The WHERE clause is a duplicate of the ON clause in the LEFT JOIN. Therefore the query can be simplified
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2214)
=> ZC156: functions_lookups.php  Update manufacturers query

admin/mail.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2216)
=> zc156: mail.php Remove unmatched closing comments in refactored Javascript

includes/modules/payment/paypal/paypal_functions.php
As identified in this Zen Cart posting: https://www.zen-cart.com/showthread.php?225240-Syntax-error
=> Correct notices in paypay_functions.php

admin/stats_sales_report_graphs.php
Addressed strict notifications; however, appears that a section of code is not even executed.
=> v156 strict notices stats_sales_report_graphs.php

admin/includes/auto_loaders/config.core.php, includes/auto_loaders/config.core.php
=> #2224: Corrects osh_updated_by load point

includes/modules/featured_products.php
- Removing the extra clauses that are already set in the on clause.
- Moving the language clause to the LEFT JOIN
- DISTINCT is not needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2215)
=> ZC156: Optimize featured queries

admin/includes/stylesheet.css, admin/index_dashboard.php
In line with the other changes I gave the Dashboard a more modern look.
This matches the other pages and makes the dashboard easier to read. It is an in between Zen Cart 1.5.5 and 2.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2237)
=> ZC 1.5.6: Give the index dashboard a modern look

admin/includes/modules/product_music/update_product.php
remove the quotes around the integer cast data values.
=> v156-admin-includes-modules-product_music-update_product

includes/modules/order_total/ot_gv.php
refactor SQL query capitalization, use of non-quoted integers
and result verification to prevent strict notifications.
=> v156-includes-modules-order_total-ot_gv

includes/modules/checkout_process.php
predefine variables to also handle strict notifications
=> v156-includes-modules-checkout_process

includes/functions/functions_customers.php
=> v156 includes-functions-functions_customers

includes/modules/pages/product_reviews_write/header_php.php
Initially began with correction to the check of a customer being logged in (strict processing) that led to other review considerations:
require of file not to use parentheses.
Potential of the products_id not being fed to access the page.
Refactoring for code alignment.
Remove else statements where the else action is simple. (assign a default value then modify if conditions warrant an alternate result).
Add notifiers to leverage options available.
=> product_reviews_write header_php

includes/functions/functions_osh_update.php
... due to misspelled variable name.
=> zen_update_orders_history: Correct PHP Notice

admin/modules.php
Addressed strict notifications
=> Change admin-modules email message response

includes/modules/pages/contact_us/header_php.php
within a foreach loop is not offset from the loop itself.
=> Indentation

admin/admin_activity.php, admin/featured.php, admin/geo_zones.php, admin/group_pricing.php, admin/gv_mail.php, admin/reviews.php
Primarily applicable to strict PHP processing; however, intended
to reduce the number of notices generated by the software that
have to be ignored.
=> Admin refactor for cases where $_SESSION, $_GET, or $_POST keys may not be set.

includes/index_filters/default_filter.php, includes/index_filters/music_genre_filter.php, includes/index_filters/record_company_filter.php
consolidated 4 queries in to 1, and only put the difference in an if statement.
modernised the rest of the code, like while to each conversion
see #2282, and #2293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2298)
=> Reworked index_filters

includes/modules/pages/account_edit/header_php.php
Fixes #2370 for account_edit only.  Similar consideration could be made for create_account.
=> Give user feedback when provided invalid ISO-8601 date

admin/record_company.php
Raised in thread: 
https://www.zen-cart.com/showthread.php?225484-1-5-5B-error
=> Fix issue with delete record company in MySQL 5.7

admin/record_artists.php
Tested and found same issue as was resolved in #2386.
=> Handle delete record artist in MySQL 5.7

.gitattributes
This one line will auto-update all edited files to use a single type of  ending (LF), making comparing files easier
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2402)
=> auto update line endings for edited files

admin/music_genre.php
=> Fix delete music genre entry in MySQL 5.7

includes/classes/order.php, includes/modules/attributes.php, includes/modules/order_total/ot_coupon.php
Remove old code or put bracket on new line if old code needed for
reference.  This way, bracket matching will work.
=> Remove some commented code

includes/modules/pages/create_account/jscript_form_check.php, includes/modules/pages/product_reviews_info/jscript_main.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2424)
=> Remove old-style javascript comments

admin/attributes_controller.php, admin/includes/languages/english/attributes_controller.php, admin/includes/languages/english/products_price_manager.php, admin/products_price_manager.php
=> typos in constant names

includes/classes/order.php
=> Correct virtual-order/MySQL error

admin/includes/languages/english.php
=> Add in missing constant ERROR_DIRECTORY_NOT_REMOVEABLE

admin/geo_zones.php
=> Ensure num_zones is set before referencing it

admin/define_pages_editor.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2466)
=> v157 define page editor: remove extra characters behind button

admin/orders.php
Allowing a plugin's observer to
1. Inject additional status-update type inputs into the form at the bottom of the page.
2. Process those inputs as part of the overall order-update processing.
=> Additional admin orders.php notifications

admin/includes/application_top.php, admin/includes/header.php
=> Properly handle STRICT_ERROR_REPORTING in admin

admin/mail.php
=> Fix PHP 7.3 warning when loading admin/mail.php

admin/includes/modules/copy_product.php, admin/includes/modules/product_music/copy_product.php
Creating default object from empty value
=> PHP warning: Creating default object from empty value

admin/category_product_listing.php
=> Initialize $order_by

includes/classes/order.php
Having orders_products_id gives you a unique identifier, which
is really useful for modders.
=> Add orders_products_id field

includes/modules/column_left.php, includes/modules/column_right.php, includes/modules/column_single.php
Required because includes/templates/YOUR_TEMPLATE/sideboxes/tpl_search.php does math on this value.
=> Ensure $column_width is an integer

admin/includes/dist-configure.php
Remind people to place backup and download folders above public_html.
=> Remind on folder location

admin/includes/auto_loaders/config.report_all_errors_admin.php, admin/includes/init_includes/init_report_all_errors_admin.php, includes/auto_loaders/config.report_all_errors.php, includes/auto_loaders/paypal_ipn.report_all_errors.php, includes/extra_configures/enable_error_logging.php, includes/init_includes/init_report_all_errors.php
=> Add lat9's Report All Errors mod

includes/languages/english/account.php, includes/languages/english/advanced_search.php, includes/languages/english/advanced_search_result.php, includes/languages/english/index.php, includes/languages/english/responsive_classic/index.php, includes/languages/english/shopping_cart.php
This value is defined in english.php so the override won't work
=> Remove TABLE_HEADING_QUANTITY override

includes/spiders.txt
1) Added bots from experience and from web search :  https://developers.whatismybrowser.com/useragents/explore/software_type_specific/crawler/10
2) Alpha ordered using Excel
=> Add more bots from web search, alpha ordered

includes/classes/shopping_cart.php
Refactor shopping_cart queries.
Removed unnecessary quotes around values converted to integer.
Set values expected to be an integer as integer.
=> zc157 - shopping cart php notifications for potentially unset session keys

admin/orders.php
... based on the new configuration setting (thanks @scottcwilson).
=> #2504: Admin orders, default customer notify

includes/init_includes/init_add_crumbs.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2514)
=> fix uppercase typo

admin/coupon_admin.php, admin/gv_mail.php, admin/popup_image.php, admin/products_price_manager.php
These tags are old and obsolete, and should be removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2513)
=> admin - remove old language="javascript" tags

includes/classes/order.php
See https://www.zen-cart.com/showthread.php?225646-coupon-popup-not-working
=> Fix for coupon link issue

admin/includes/languages/english/gv_name.php
=> Declare TEXT_GV_REDEEM once only

includes/modules/product_prev_next.php
Established base values to then be modified as applicable for
the conditions originally identified to offer a `$previous_button`,
`$next_item_button`, `$previous_image`, and `$next_item_image`.
=> Rewrite/refactor for strict notifications and simplicity.

admin/category_product_listing.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2535)
=> Remove now-unused $editor_handler from category listing code

zc_install/includes/languages/lngEnglish.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2534)
=> Clean up zc_install quotes and double quotes

zc_install/includes/languages/lngEnglish.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2554)
=> Typo in v157/zc_install/includes/languages/lngEnglish.php

admin/reviews.php
The old button code was still in place, resulting in a faulty display of the button
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2553)
=> Fix button display code on admin reviews page

admin/includes/modules/document_general/preview_info.php, admin/includes/modules/document_product/preview_info.php, admin/includes/modules/product/preview_info.php, admin/includes/modules/product_free_shipping/preview_info.php, admin/includes/modules/product_music/preview_info.php
as mentioned in #2122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2552)
=> remove obsolete $_GET['product_type']

includes/languages/english.php
- "our system" (not "my system") used in all other places.
- in all other places, "down for maintenance" is not capitalized.
=> Language changes for consistency

admin/admin_account.php
See define in admin/includes/languages/english/admin_account.php.
=> Use correct constant from related language file

admin/ezpages.php
=> Add ellipses to truncated ezpages content in sidebar

includes/modules/column_left.php, includes/modules/column_right.php, includes/modules/column_single.php
Completion of work initiated in #2541.
=> Convert templates/common files to use zen_get_module_sidebox_directory

admin/includes/modules/document_general/collect_info.php, admin/includes/modules/document_general/preview_info.php, admin/includes/modules/document_product/preview_info.php
=> Correct document products' editing

includes/index_filters/default_filter.php
As identified in [this](https://www.zen-cart.com/showthread.php?225669-Item-showing-twice-(or-more)&p=1359616#post1359616) Zen Cart forum posting.
=> Correct duplicate, linked products in mfgrs listing

admin/invoice.php, admin/packingslip.php
Crazy ugly looking otherwise.  See attached image in vim, the one true editor.
=> Remove whitespace for vim sake

includes/modules/product_listing.php
=> Check if $_GET parms are set in product_listing.php

includes/languages/english/modules/order_total/ot_coupon.php, includes/languages/english/modules/order_total/ot_gv.php
=> Removes unused defines

admin/includes/languages/english/index.php, admin/index_dashboard.php
=> Show currency code rather than "Dollars"

includes/application_top.php, includes/extra_configures/enable_error_logging.php
First part of fix for issue #2586
=> First part of update to remove old PHP checks

admin/template_select.php
=> Resolve notice on create new association

includes/functions/functions_email.php, includes/languages/english/contact_us.php, includes/modules/pages/contact_us/header_php.php, includes/templates/template_default/templates/tpl_contact_us_default.php
Telephone is indicated as a required field, but it's really not because older templates might not provide it, and I didn't want to break them.  
This is the first part of #2217.
=> Add telephone to contact us

admin/salemaker.php
=> Correct salemaker table header layout

admin/category_product_listing.php
old view of admin screen showing products only: 
new view:
=> Only show Price and Model labels at the product level

zc_install/sql/demo/README.txt, zc_install/sql/demo/demo_cleanup.sql
Allows iterative testing of demo data.
=> Add utility sql script to remove demo data from db

zc_install/sql/updates/mysql_upgrade_zencart_157.sql
Addresses the upgrade aspect of PR #2267.
=> V157 install upgrade val function

includes/modules/attributes.php
This way the whole file is more obviously ignored if not applicable.
Will reformat the file in subsequent PR
=> Do early-return from attributes module

includes/modules/attributes.php
This is a big "diff", but essentially the only change is the indentation and upper/lowercase change on PHP constants.
=> Reformat modules/attributes.php file to PSR2, removing extra indents etc

admin/includes/functions/general.php, includes/functions/functions_general.php, includes/functions/functions_general_shared.php
Now that the admin and catalog finally provide the same
uprid on the admin as it does on the catalog and there is
a consolidation available, this is the simplified (refactored)
version of the function used on both catalog and admin side.
=> Consolidate zen_get_uprid

admin/includes/functions/general.php, admin/includes/languages/english/orders_status.php, admin/index_dashboard.php, admin/orders.php, admin/orders_status.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_157.sql
=> Include sortable orders-status

includes/modules/attributes.php, includes/templates/template_default/templates/tpl_modules_attributes.php
There's essentially no core functionality changes here.
Granted, it does convert a string-based boolean check to actual boolean for 2 vars, affecting the template slightly.
=> Refactor and de-duplicate vars in attributes module

admin/includes/functions/database.php
I noticed this was done for admin/includes/functions/functions_customers.php, so I thought I'd do it for this one too.
=> Add a stub file for the old database.php

zc_install/sql/updates/mysql_upgrade_zencart_157.sql
=> Add ADMIN_NAME_MINIMUM_LENGTH to db

admin/mail.php
=> Correct back button on send email screen

admin/includes/modules/product/preview_info.php, admin/includes/modules/product_free_shipping/preview_info.php, admin/includes/modules/product_music/preview_info.php
In resolution to #2572, #2573 modified the files for document_general
and document_product.  In review of the HTML validation for the
other product types, the same changes were determined necessary.
=> Modify preview_info files to match others

admin/coupon_restrict.php, admin/includes/languages/english/coupon_restrict.php
Allows us to use TABLE_HEADING_MODEL from main language file.
=> Standardize heading names in coupon restriction

admin/orders.php
=> Check $_GET['search_orders_products'] before reference

includes/classes/order.php
=> Ensure shipping_module_code value is "sane".

includes/init_includes/init_db_config_read.php
... as introduced in #2471 and reported [here](https://www.zen-cart.com/showthread.php?225748-File-Upload-Attribute-not-working-in-v1-5-6c&p=1360358#post1360358) on the Zen Cart forums.
=> Correct sanitization of UPLOAD_FILENAME_EXTENSIONS

includes/functions/functions_products.php
... performance improvement for stores with a large number of products.
=> zen_get_product_details: Add LIMIT 1

admin/customers.php
See forum report for this issue at https://www.zen-cart.com/showthread.php?225753-Customer-Summary-Box-showing-first-order-instead-of-last-order
=> Fix incorrect last order reporting in customers screen

email/email_common.css
otherwise it is pushed out to one side.
=> remove padding on disclaimer to make it align correctly with main div.

admin/categories.php
Using a similar construct to that present in the products' `collect_info` methods.
=> Enable additional category inputs

admin/includes/functions/general.php, admin/includes/languages/english/orders.php, admin/orders.php
=> Add download link to order details page for files attached to orders

admin/category_product_listing.php
On The products listing page a link to edit the product is added to the product name
Fixes #2724
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2733)
=> Add edit link to product name

admin/orders.php
Also corrects the PHP error introduced in PR #2726.
```
Parse error: syntax error, unexpected ';', expecting ',' or ')' in C:\xampp\htdocs\zc157\grasS-Qjo-clocK\orders.php on line 137
```
=> Add notifier for admin Orders search-override

includes/modules/order_total/ot_shipping.php
Update `ot_shipping` to perform its additions to the order during the `process` method instead of during class-construction.
Fixes #2743.
=> Ot shipping update

admin/orders.php
... by checking that the $_GET variable isn't empty.
=> Correct admin orders PHP notice

admin/includes/languages/english/email_extras.php, includes/languages/english/create_account.php
admin telephone was in bold
create account missing a comma after honorific
=> minor edits

admin/includes/functions/html_output.php
=> fix broken hidden field

admin/includes/application_bootstrap.php, admin/includes/application_top.php, admin/includes/auto_loaders/config.core.php, admin/includes/psr4Autoload.php, admin/index.php, includes/autoload_func.php, includes/classes/FileSystem.php, includes/classes/InitSystem.php, includes/classes/traits/Singleton.php
refactored to support new plugin system.
=> Refactor initsystem

admin/includes/init_includes/init_languages.php, admin/includes/psr4Autoload.php, admin/index.php, includes/classes/ResourceLoaders/LanguageLoader.php, includes/classes/ResourceLoaders/PageLoader.php
=> Move admin language loading to class based system in preparation

includes/functions/functions_general_shared.php
As described in 
https://www.zen-cart.com/showthread.php?225829-zen_get_uprid-issue-in-1-5-6c
=> Fixes zen_get_uprid issue in 1.5.6c

includes/classes/order.php
These 4 queries are except for the address_book_id parameter the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2770)
=> Consolidate 4 almost equal queries in to 1

admin/customers.php
=> Handles click on red/green icon in customers list

admin/coupon_restrict.php, admin/includes/languages/english/coupon_restrict.php
=> Totally Restructure Coupon Restrict code

admin/category_product_listing.php
- remove comma (bug)
- move  AND statements so it is even more easier to add joins
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2816)
=> Fix category_product_listing.php

admin/category_product_listing.php, admin/includes/stylesheet.css
show categories path on tab title (for identification of multiple tabs)
add popup link to catalog to page title: to open shop view for that category
fix empty class
alt text for linked category icon
new title for linked category icon
incorrect uses of label on radio group replaced with fieldset
renamed search form as clashed with input id "search" when used for label for
new css shrink style for td ID to reduce wasted space
alt tags for images
removed unused table columns for categories
removed button role from cat tr (invalid to have <a href inside button): added pointer for visual cue
=> Admin: Category product listing tweaks and validations

admin/home.php, admin/includes/functions/html_output.php, admin/includes/header.php, admin/includes/modules/document_general/collect_info.php, admin/includes/modules/document_general/preview_info.php, admin/includes/modules/document_product/collect_info.php, admin/includes/modules/document_product/preview_info.php, admin/includes/modules/product/collect_info.php, admin/includes/modules/product/preview_info.php, admin/includes/modules/product_free_shipping/collect_info.php, admin/includes/modules/product_free_shipping/preview_info.php, admin/includes/modules/product_music/collect_info.php, admin/includes/modules/product_music/preview_info.php, includes/templates/template_default/jscript/jscript_framework.php
No functional changes apart from html_output
=> Admin: product editing, minor things for clearing html validation

includes/autoload_func.php, includes/classes/InitSystem.php
really need to get rid of session bound classes
fixes #2820
=> check for session being done in wrong place

admin/includes/application_bootstrap.php, admin/includes/init_includes/init_languages.php
update building of $PHP_SELF
language loading to use $PHP_SELF
fixes #2824
=> admin languages not loading on legacy uri's

includes/classes/navigation_history.php
--> PHP Notice: Undefined offset: -1 in /Users/scott/Sites/gh_demo_157/includes/classes/navigation_history.php on line 98.
=> Nav PHP notice because of reference to element[-1]

admin/includes/application_bootstrap.php, admin/includes/init_includes/init_languages.php
Need to switch index->home
fixes #2827
=> Fix loading of constants on home page

admin/ezpages.php
These additions enable a watching admin observer (e.g. ezpages_metatags) to provide their changes in a seamless manner, no longer requireing core-file overwrites.
=> zc157: Add notifications to /admin/ezpages.php

admin/includes/modules/products_previous_next.php
also duplicated clause 1 for products_name
=> fix: products_previous_next was missing PRODUCT_INFO_PREVIOUS_NEXT_SORT option 6 for sort order

admin/users.php
1) After editing currentuser and update: Php Notice Undefined index: profile
Fixed with
`<td class="profile"><?php echo $userDetails['profileName'] . zen_draw_hidden_field('profile', $userDetails['profile']) ?></td>`
2)  missing table cell when Add User was used: missing the last (actions) empty table cell to match header row.
3) Was missing closing form tag for overall form, for all actions except Delete action, which was a nested form.
Needed to hide main form and closing tag when Delete in use.
4) tfoot was empty on Edit: validation error. Removed it. Only used for Add button.
I found this code very difficult to read and modify with so many ifs on the actions!
=> Admin users.php, minor fixes

admin/includes/modules/move_product.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2851)
=> Remove spaces before opening php tag

admin/coupon_admin.php, admin/gv_queue.php, admin/includes/modules/newsletters/newsletter.php, admin/includes/modules/newsletters/product_notification.php, admin/mail.php, email/email_template_coupon.html, email/email_template_direct_email.html, email/email_template_gv_queue.html, email/email_template_newsletters.html, email/email_template_order_status.html, email/email_template_product_notification.html, includes/functions/functions_osh_update.php
and one error corrected: 
object field->coupon-admin to coupon_admin
=> replacement of hard-coded "Dear" in email_templates by constant EMAIL_SALUTATION

admin/options_name_manager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2853)
=> fix wrong variable

zc_install/sql/updates/mysql_upgrade_zencart_157.sql
=> Missed insertion of GLOBAL_AUTH_KEY in update script

admin/includes/functions/languages.php, admin/includes/init_includes/init_languages.php, includes/init_includes/init_languages.php
Since $_SESSION[''languages_id] can only be an integer, why not type cast it as one on creation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2877)
=> Cast $_SESSION[''languages_id] to an integer

includes/modules/pages/ask_a_question/header_php.php, includes/modules/pages/contact_us/header_php.php
Update the subject pages to use the built-in Zen Cart functions to determine whether/not a customer is logged in.
=> contact_us/ask_a_question: Login checks

includes/templates/template_default/templates/tpl_checkout_success_default.php
change deprecated tag "name" to id
closing form tag in php for IDE happiness
=> minor edits to Checkout success

admin/includes/languages/english/products_price_manager.php, admin/products_price_manager.php
Blue background, main label over to the left, colons after labels.
=> Make Discount Info block consisten wi Price Info block

includes/modules/shipping_estimator.php, includes/templates/template_default/templates/tpl_modules_shipping_estimator.php
Refactors the base module to use now-current indentation/spacing 'rules'.  Updates both the module and its associated template to treat guest-checkout as a not-logged-in mode.
=> Shipping estimator updates for detecting customer login status

includes/modules/shipping_estimator.php, includes/templates/template_default/templates/tpl_modules_shipping_estimator.php
=> zc156: Shipping estimator updates for detecting customer login status

includes/classes/order.php
As discussed in, and fixes #2918
I could only find 2 occurrences
=> Change 0 to false in zen_address_label usages

admin/category_product_listing.php
=> Remove unused code from category_product_listing.php

admin/includes/functions/admin_access.php
Don't force pass change if this flag is unset.
=> SSL switch check only if PADSS_PWD_EXPIRY_ENFORCED == 1

admin/includes/functions/html_output.php
remove border (not HTML5), reformat
=> admin, zen_image_submit: remove border attribute

includes/modules/payment/authorizenet.php, includes/modules/payment/authorizenet_aim.php, includes/modules/payment/firstdata_hco.php, includes/modules/payment/paypal.php, includes/modules/payment/paypal/paypal_functions.php, includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php, includes/modules/payment/square.php, ipn_main_handler.php
=> Refactor to use shared zen_update_orders_history functions

includes/templates/template_default/templates/tpl_checkout_shipping_default.php
See https://www.zen-cart.com/showthread.php?226197-My-site-has-a-weird-issue-with-text-during-check-out&p=1364396#post1364396
=> Fix formatting of checkout page in Chrome

admin/password_forgotten.php
Admin id is an integer so the binvar should also be set to integer
=> Update bindvar value

includes/classes/order.php, includes/classes/shopping_cart.php, includes/functions/functions_customers.php, includes/functions/functions_general.php, includes/functions/functions_gvcoupons.php, includes/functions/functions_lookups.php, includes/functions/functions_prices.php, includes/functions/functions_taxes.php, includes/functions/whos_online.php, includes/init_includes/init_customer_auth.php, includes/init_includes/init_header.php, includes/modules/attributes.php, includes/modules/checkout_process.php, includes/modules/pages/gv_redeem/header_php.php, includes/modules/pages/payer_auth_auth/header_php.php, includes/modules/pages/payer_auth_frame/header_php.php, includes/modules/payment/paypal/tpl_ec_button.php, includes/modules/payment/paypalwpp.php, includes/modules/products_quantity_discounts.php, includes/modules/sideboxes/best_sellers.php, includes/modules/sideboxes/order_history.php, includes/templates/responsive_classic/common/tpl_main_page.php, includes/templates/template_default/common/tpl_main_page.php, includes/templates/template_default/sideboxes/tpl_shopping_cart.php
Use zen_is_logged_in instead of checking for presence of $_SESSION['customer_id']
=> Use zen_is_logged_in() instead of checking $_SESSION['customer_id']

includes/modules/pages/create_account/on_load_main.js, includes/modules/pages/login/on_load_main.js, includes/templates/template_default/templates/tpl_create_account_default.php, includes/templates/template_default/templates/tpl_login_default.php
put closing form tags in php
reformat
=> match names and ids for login and create account forms

admin/includes/modules/document_general/collect_info.php, admin/includes/modules/document_product/collect_info.php, admin/includes/modules/product/collect_info.php, admin/includes/modules/product_free_shipping/collect_info.php, admin/includes/modules/product_music/collect_info.php, admin/product.php
The moved code is identical in all files, and can be placed in product.php to minimize duplicate code
=> Move duplicate javascript and price-tax-calc code to product.php

admin/includes/stylesheet.css
rationalised all h? styles as some were not defined here and so used .less: inconsistent sizes.
removed invalid selectors: checkbox, radio, file
reformatted
note that .btn is unused
=> Admin stylesheet: Rationalised heading styles

admin/includes/stylesheet.css
due to overall color setting on line 28
=> Fix disappearing heading in sidebox

admin/categories.php, admin/includes/modules/update_product_meta_tags.php
Admin->Categories->--->Edit a product metatag and proceed to save it:
--> PHP Notice: Undefined index: products_date_available in
\admin1\includes\modules\update_product_meta_tags.php on line 20.
=> php warnings: edit product and category metatags

admin/includes/languages/english/options_name_manager.php, admin/options_name_manager.php
- html layout update
- type casting
=> Update to option name manager

admin/category_product_listing.php
Mostly refactor:
Align new code to existing structure. 
Provide early detection and remove `if` statement/simplify code.
=> V157 category product listing

admin/includes/functions/general.php
Simple refactor and address strict response for parent_id that could be null/not-set. Especially an issue if the current_category_id is zero, but may also occur if the parent_id has been set to null.
=> V157 admin functions general

admin/includes/functions/general.php, includes/functions/functions_categories.php
Rewrite zen_get_path to be less verbose
And make it same between admin/catalog
=> Rewrite zen_get_path to be less verbose

admin/categories.php
Apparently I missed removing these labels in the last PR
=> Removing some labels form categories.php

includes/application_top.php, includes/templates/template_default/templates/tpl_zc_phpupgrade_default.php
=> Alert when using PHP 5.3 or older due to short-array-syntax requirement

includes/extra_configures/enable_error_logging.php
Refer to in-module comments for naming convention.
=> Update error-logging to group errors by type

admin/product.php
This is no longer needed, and I forgot to remove it in a previous PR
=> Remove onload from product.php

includes/classes/db/mysql/define_queries.php, includes/modules/also_purchased_products.php
See includes/modules/also_purchased_products.php
=> Third argument for sprintf call should be max setting

admin/category_product_listing.php, admin/includes/stylesheet.css
- Update Html head to remove old deprecated files
- fix lay out of the 3 columns above the categories table. This fixes spacing between items, and a more conform code use.
- change image icons for font-awesome icons
- category hover, shows folder opening. clicking the folder or category name opens the next level (as before). I removed the javascript for clicking the entire row, as this in some cases prevents clicking other objects in the row.
- changing the action buttons to proper buttons giving a cleaner look.
- Remove parentheses from requires
also see #3047
=> Layout updates for category product listing

includes/autoload_func.php, includes/classes/InitSystem.php
=> Return autoload object init to autoload_func

admin/attributes_controller.php
Add get parameter to redirect
The missing products_filter was sending the page to the lowest product id after saving
=> Fix redirect URLs in attributes_controller

admin/reviews.php
on delete, when there is more than one review:
--> PHP Notice: Undefined variable: rInfo in ....\zencart-157\admin\reviews.php on line 358
due to checking for is-object on rInfo when it is not set
other easily reviewed fixes included.
=> Reviews: php notice on delete

includes/templates/responsive_classic/templates/tpl_checkout_payment_address_default.php, includes/templates/responsive_classic/templates/tpl_checkout_shipping_address_default.php, includes/templates/template_default/templates/tpl_checkout_payment_address_default.php, includes/templates/template_default/templates/tpl_checkout_shipping_address_default.php
In some scenarios, there could be an extra open form.
=> Address book pages: Ensure form start and end tags match

includes/autoload_func.php
[16-Feb-2020 01:57:37 America/New_York] PHP Notice:  Undefined index: messageStack in /Users/scott/Sites/gh_demo_157/includes/autoload_func.php on line 48
Same notice lin 51.
=> Fix messageStack notices from autoload_func.php

admin/attributes_controller.php, admin/category_product_listing.php, admin/geo_zones.php, admin/options_values_manager.php, admin/stats_customers.php, admin/stats_products_lowstock.php, admin/stats_products_purchased.php, admin/stats_products_viewed.php
It was (un)used in a few more places than just the stats_* files; all gone in this branch.
=> Remove $rows variable not in use in admin files

admin/category_product_listing.php
There was a left over closing tag </i> which needed to be removed
=> Remove extra closing tag

admin/specials.php
Found two bugs and made strict changes,
=> Updates to Specials page changes in prior PR

admin/includes/init_includes/init_languages.php
=> update to use previous variable name

admin/coupon_admin.php
Additionally this needs some html fixes but I'm not doing that (now/at all).
=> Admin coupon admin: bugfixes etc.

admin/includes/classes/split_page_results_new.php, admin/includes/functions/html_output.php, includes/classes/split_page_results.php, includes/functions/html_output.php, includes/templates/template_default/templates/tpl_zc_install_suggested_default.php, includes/templates/template_default/templates/tpl_zc_phpupgrade_default.php, nddbc.html
to lay to rest a long burning issue...
https://www.zen-cart.com/showthread.php?217229-zen_image-Why-the-extra-spaces-in-the-title-attribute
=> remove leading and trailing spaces in title tags

admin/category_product_listing.php, admin/includes/languages/english.php
While the extra constant for meta tags has been added to be consistent with the rest, I think 
review is required for de-duplication/renaming between ICON_... and IMAGE_... constants.
=> admin: category/product listing: add popups/titles to editing buttons

admin/includes/languages/english/product.php, admin/includes/modules/document_general/preview_info.php, admin/includes/modules/document_product/preview_info.php, admin/includes/modules/product/preview_info.php, admin/includes/modules/product_free_shipping/preview_info.php, admin/includes/modules/product_music/preview_info.php
Fixes bug (white screen) introduced in last PR to this file
https://github.com/zencart/zencart/commit/30f9bfc9ee3940556a8eebf99328c5a9c457d862#diff-2d0663a226d3074aec93b3f41745b5cd
and other minor changes...PRs to similar files affected by this bug to follow.
=> Preview info - Product

includes/classes/order.php
This is such a nice practice -let's use it everywhere.
=> Code reformatting

includes/modules/pages/login/header_php.php
This will save people having to look it up by customer id.
=> Putting email address in SESSION data

admin/configuration.php, admin/includes/functions/admin_access.php, admin/product_types.php
small bug.  one can see it here:
https://www.zen-cart.com/showthread.php?226504-Cannot-edit-payment-module-settings-php7-3&p=1366892#post1366892
also need to address it for v156 if planning a new release on it.
=> fixes datetime bug on config

admin/attributes_controller.php
- move closing bracket for if up in the code, so html opening and closing tags match
- add divs with row class, to prevent unwanted collapsing of field rows
=> Attribute Controller UI bug fixes

admin/categories.php
https://github.com/zencart/zencart/issues/3150#issuecomment-605978670
=> update clean of categories_description

admin/includes/languages/english/category_product_listing.php, admin/includes/modules/copy_product_confirm.php, admin/includes/modules/product_music/copy_product_confirm.php
my IT team (all 1 of him) liked this....
=> for a duplicated product, add the suffix DUPLICATE to the name

includes/classes/payment.php, includes/classes/shipping.php
Easier to see the identical patterns when debugging.
In the case of the payment class it makes the code much more like an interface, which could be integrated later particularly by de-duplicating etc.
=> Refactor for early return

includes/classes/payment.php, includes/classes/shipping.php
This allows tools like https://github.com/Zen4All/Zen-Cart-Ship2Pay to not need any core overwrites
=> Add notifier hook for payment and shipping modules

admin/includes/modules/document_general/preview_info.php, admin/includes/modules/document_product/preview_info.php, admin/includes/modules/product/preview_info.php, admin/includes/modules/product_free_shipping/preview_info.php, admin/includes/modules/product_music/preview_info.php
subsequent to this, when collect_info PRs have been calmed down, I suggest
=> add http/s filter for url field user input

admin/includes/modules/copy_product_confirm.php
=> Add notifier to admin product-copy-duplicate processing

admin/featured.php, admin/includes/languages/english/featured.php
I know it's uncomparable to the current version, but it IS comparable to specials.
Matches exactly Specials (minus a couple of unnecessary pricing sections) to give the same layout improvements and easier comparison or even merging in the future.
Usual fixes for php notices, html validations, unbalanced tag...
=> rework of Admin Featured products

includes/classes/shopping_cart.php
In this sprit of #3169, this set of updates is limited to ensuring the following:
* SQL statements are in upper case
* The last entry in an array has a comma, and the closing bracket is on a new line
* File does not end with ?>
In addition, meaningless comments may be removed.
=> Updating SQL syntax

admin/specials.php
=> Specials: fix notice when page not set

admin/includes/languages/english/configuration.php, admin/includes/languages/english/options_name_manager.php, includes/extra_configures/enable_error_logging.php
These are three of four things that cropped up when I started using php7.4 (with Report All Errors).
After quickly opening all the admin menus, there are no more from this superficial check.
=> Duplicated constants

admin/includes/auto_loaders/config.core.php, admin/includes/functions/functions_help.php, admin/includes/header_navigation.php
Works on Admin > Localization > Currencies and Admin > Catalog > Categories/Products.  
Help function could be overridden to open a new page with locally created content as well as default content.
=> built in help for admin

admin/users.php
formatting only: for easy comparison to subsequent PR for admin_account
=> admin: users (reformat only)

admin/includes/languages/english.php
=> Restore required language defines

admin/includes/functions/functions_help.php
Remove help from the home page.
=> Remove help from home page

admin/includes/functions/localization.php, admin/includes/modules/product/collect_info.php, admin/includes/modules/update_product.php
Removes hardcoded YYYY-MM-DD text and uses DATE_FORMAT_DATE_PICKER instead.
Respects settings in DATE_FORMAT_DATE_PICKER for display of available date.
=> show date available hint and date available in localized format

admin/admin_account.php, admin/includes/languages/english/admin_account.php, admin/includes/languages/english/users.php, admin/users.php
Made the files match to easily compare.
To avoid php notice for duplicated constant,
I rationalised the constants between users and admin_account and  included users.php constants into admin_account. Admin account only has its own HEADING_TITLE, so I put a is_defined clause on the user version.
Othewise just cosmetic changes so it looks like admin users.
=> Admin: admin_account matched to users

admin/includes/languages/english.php
=> Add back defines pages editor

admin/options_values_manager.php
=> Update prior PR to options_values_manager.php

docs/zen.css
The gray color that is used currently is almost unreadable.
=> Blacken docs text for old codgers like me

admin/stats_sales_report_graphs.php
Completion of work initiated in #3212
=> Use mnemonics instead of magic numbers

zc_install/includes/classes/class.systemChecker.php, zc_install/includes/languages/en_us/main.php, zc_install/includes/systemChecks.yml
=> Remove unused localdev checks from zc_install

admin/includes/functions/general.php
Fixes #2991, no extra cleanup .
=> Add status to zen_get_countries response array

admin/index_dashboard.php, admin/orders.php
Current query causes a SQL notice.
=> Fix use of reserved words in query

admin/orders.php
=> Set flag outside loop

includes/modules/pages/account_notifications/header_php.php
Fix issue reported on 
https://www.zen-cart.com/showthread.php?226624-PHP-Warning-Account_notification-header_php
=> Fix sizeof test on variable that could be empty

zc_install/includes/languages/en_us/main.php
=> compress installer main language file

includes/functions/functions_general.php
While looking over code, came across this loop where a value is
set and it appears that there is no further need to loop.
This breaks out of the foreach upon result discovery.
=> Exit foreach upon result found

admin/login.php
In theory these changes should help with password-changes when using password vaults.
=> Enhancements to admin autocomplete for pwd managers

admin/includes/functions/admin_access.php
While reviewing changes being made to this file for 1.5.7, noticed
that there are several fields that use the type 'string' when
using the `$db->bindVars` method.  As a result if the associated
sanitized string contained `"NULL"` in the text (of any length),
the string would be sanitized to a null value for database insertion.
In a standard install this will cause a mysql error as the field(s)
can not be set to `null`.
While I have not specifically used `"NULL"` in any such fields under
normal use, I did validate that such usage would be a problem.
I have no personal need for this revision, but seems like it is
unnecessarily stringent and not otherwise described as a "caveat".
=> Allow text to contain NULL

admin/includes/modules/delete_product.php
and other bits, of course.
Fixes #3160
=> Product Delete - revert to all categories pre-selected

admin/includes/languages/english/paypal.php, admin/paypal.php
1 bugfix, one hard coded text replaced and general fettling for html5.
=> Admin: paypal IPN info

admin/coupon_restrict.php, admin/orders.php, admin/stats_products_purchased.php, admin/stats_sales_report_graphs.php
File was moved but scripts referring to it were not updated.
=> Update path of stylesheet_print.css

admin/store_manager.php
bootstrap buttons over the zen_image functions...
=> Store Manager CSS buttons

zc_install/includes/application_top.php, zc_install/includes/localConfig.php, zc_install/includes/modules/pages/database/header_php.php, zc_install/includes/template/templates/database_default.php
Controlled by `/zc_install/includes/localConfig.php`
Closes #3354
=> Additional developer customization of defaults in zc_install UI

admin/includes/languages/english.php, includes/languages/english.php
Capitalisation of the subjects in the item listing in prev-next
other minor stuff as per commit listing
=> english.php, both

admin/includes/languages/english/invoice.php, admin/includes/languages/english/orders.php, admin/invoice.php, admin/orders.php
Fixed only the order details screen.  If approved, I will also change the invoice screen. 
Fixes #3339
=> Only display including tax if store runs with DISPLAY_PRICE_WITH_TAX == 'true'

admin/includes/classes/language.php, admin/includes/init_includes/init_languages.php
Files are the same, so better to just use one.
=> Move to using shared catalog-side language class

admin/orders.php
if post was set, $customer_notified was cast to integer, if not, it was set to '0' as string.
=> admin: orders.php correct casting to integer

admin/includes/functions/general.php
=> Fix error in PR #3322

admin/includes/functions/general.php
Root cause: https://github.com/zencart/zencart/commit/e57384d9f12b6e212ccbb3acd3ba6f65ceb90210#diff-54d4643a07e7e83ca01aafaf92ac8fc3
=> Fix error in #3322

admin/includes/ckeditor.php, admin/includes/functions/html_output.php
=> Fix for CKEditor config to work when store is in a subdirectory

admin/includes/admin_html_head.php, admin/includes/javascript_loader.php
Switch to CDN as preferred load source
=> Use CDN for admin bs/fa/jqui

zc_install/includes/languages/en_us/main.php
and used text_replacement variables
=> installer text

admin/includes/functions/general.php, includes/functions/functions_general.php
Could these not be made identical?
=> functions: zen_set_field_length - remove spaces in tags

admin/includes/auto_loaders/config.core.php, admin/includes/classes/WhosOnline.php, admin/includes/init_includes/init_sanitize.php, admin/includes/languages/english/whos_online.php, admin/index_dashboard.php, admin/whos_online.php
Also simplifies the template code in the UI so it can be modernized more easily.
Also removes a lot of duplicate code and db queries from the dashboard widget.
Additionally, allows creation of extra_datafiles defines for WHOIS_TIMER_INACTIVE etc if overrides are desired.
No visual changes.
Closes #3392
=> Refactor WhosOnline Admin to improve speed

includes/templates/responsive_classic/css/responsive_default.css
=> Fix black bg layout in responsive_classic

admin/attributes_controller.php
=> Admin: attribute controller. Various html corrections

admin/includes/modules/dashboard_widgets/BaseStatisticsDashboardWidget.php, admin/includes/modules/dashboard_widgets/OrderStatusDashboardWidget.php, admin/includes/modules/dashboard_widgets/RecentCustomersDashboardWidget.php, admin/includes/modules/dashboard_widgets/RecentOrdersDashboardWidget.php, admin/includes/modules/dashboard_widgets/SalesReportDashboardWidget.php, admin/includes/modules/dashboard_widgets/SpecialsDashboardWidget.php, admin/includes/modules/dashboard_widgets/TrafficDashboardWidget.php, admin/includes/modules/dashboard_widgets/WhosOnlineDashboardWidget.php, admin/index_dashboard.php
This allows for easy enable/disable and customizing of individual content, without affecting the broader context of the rest of the dashboard
=> Move admin dashboard widgets into separate modules subdir

admin/includes/languages/english/admin_account.php
Issue reported and root cause found by @zcwilt.  
Bad commit: https://github.com/zencart/zencart/commit/3f87e7ab7e938e004c60981ed7f190394da4ae29#diff-87c8c441c978d2aa78985eba54ffe4a6
=> Fixes white screen

admin/includes/languages/english/gv_mail.php, admin/includes/languages/english/gv_queue.php, admin/includes/languages/english/gv_sent.php
Found during investigation of #3448.  Fixed syntax which could lead someone into an error.
=> Specify language include path unambiguously

admin/includes/functions/general.php
=> Fix error from removal of quotation marks

admin/includes/ckeditor.php
add missing semicolon
remove extra space
=> ckeditor minor syntax changes

admin/category_product_listing.php
- Remove unused fields from category, and product queries. Potentially speeding up sites with large numbers of categories, and products
=> Simplify queries

admin/modules.php
change Delete for Remove
refactor row styles to show pointer only where there is a clickable action
minor html fixes
no functional changes
=> Refactor admin modules page

includes/classes/order.php
This is not a complete overhaul. It's just a small rearrangement in preparation for larger changes in the future.
=> Extract order tax calculations into separate methods

includes/languages/english.php, includes/modules/pages/shopping_cart/header_php.php, includes/modules/product_listing.php, includes/modules/product_listing_alpha_sorter.php, includes/modules/responsive_classic/product_listing.php, includes/templates/responsive_classic/templates/tpl_document_general_info_display.php, includes/templates/responsive_classic/templates/tpl_document_product_info_display.php, includes/templates/responsive_classic/templates/tpl_product_free_shipping_info_display.php, includes/templates/responsive_classic/templates/tpl_product_info_display.php, includes/templates/responsive_classic/templates/tpl_product_music_info_display.php, includes/templates/responsive_classic/templates/tpl_shopping_cart_default.php, includes/templates/template_default/sideboxes/tpl_manufacturers_select.php, includes/templates/template_default/sideboxes/tpl_music_genres_select.php, includes/templates/template_default/sideboxes/tpl_record_company_select.php, includes/templates/template_default/sideboxes/tpl_search.php, includes/templates/template_default/sideboxes/tpl_search_header.php, includes/templates/template_default/templates/tpl_advanced_search_default.php, includes/templates/template_default/templates/tpl_checkout_payment_default.php, includes/templates/template_default/templates/tpl_checkout_shipping_default.php, includes/templates/template_default/templates/tpl_document_general_info_display.php, includes/templates/template_default/templates/tpl_document_product_info_display.php, includes/templates/template_default/templates/tpl_product_free_shipping_info_display.php, includes/templates/template_default/templates/tpl_product_info_display.php, includes/templates/template_default/templates/tpl_product_music_info_display.php, includes/templates/template_default/templates/tpl_shopping_cart_default.php
=> Add aria-label cues where labels are not present

includes/modules/order_total/ot_coupon.php
=> Tax reduction should not include shipping if not so configured

admin/includes/modules/dashboard_widgets/RecentOrdersDashboardWidget.php, admin/orders.php
=> Correct grouping of attributes in popover

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_157.sql
If date_viewed is to be a Primary Key, it must be NOT NULL.
UNIQUE won't work with a date key.
=> date_viewed must be NOT NULL for Primary Key

includes/classes/split_page_results.php, includes/languages/english.php
Add aria attributes to pagination links
Closes #3486
=> ARIA updates for pagination

docs/whatsnew_1.5.7.html
and a couple more added
Closes #3483
=> Update What's New - 1.5.7

admin/orders.php, admin/whos_online.php
Useful for plugins like IP Blocker too additional controls
Also useful for swapping out the Whois lookup URL ... which can also be done with `ADMIN_ORDERS_IP_LINKS`
=> Add ADMIN_WHOSONLINE_IP_LINKS notifier hook

admin/includes/classes/WhosOnline.php
=> Part 2 - Fix admin whos-online logging-out the administrator

includes/templates/responsive_classic/common/tpl_header.php
The class .blue was loaded inline for the navMain links.  Not a good practice with colors that change often.
I removed the class="blue" from includes/templates/responsive_classic/common/tpl_header.php.
=> Further Contrast Problems

admin/includes/init_includes/init_errors.php, includes/classes/currencies.php, includes/classes/observers/class.products_viewed_counter.php, includes/functions/functions_general_shared.php, includes/functions/functions_lookups.php, includes/init_includes/init_customer_auth.php, includes/init_includes/init_header.php, includes/init_includes/init_templates.php, includes/modules/ezpages_bar_footer.php, includes/modules/ezpages_bar_header.php, includes/modules/sideboxes/ezpages.php, includes/templates/responsive_classic/common/tpl_footer.php, includes/templates/responsive_classic/common/tpl_header.php, includes/templates/template_default/common/tpl_footer.php, includes/templates/template_default/common/tpl_header.php
This consolidates the repeated lookups for common use
=> Add zen_is_whitelisted_admin_ip() function

admin/orders.php
=> Display order comments on hover
