admin/includes/header.php, admin/includes/template/common/tplHeader.php
Some hosts have disabled shell_exec() for security reasons. Using gethostname() avoids that limitation, giving same results.
Props: @lat9 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/254)
=> Replace shell_exec('hostname') with gethostname()

admin/includes/functions/admin_access.php, admin/stats_customers.php, admin/stats_products_purchased.php, includes/classes/db/mysql/define_queries.php
Not including all SELECTed fields can result in ambiguous GROUP BY results, and is non-standard SQL
Ref: https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/251)
=> MySQL GROUP BY clauses should list all SELECTed columns

admin/includes/classes/class.admin.zcObserverLogWriterDatabase.php, testFramework/dbtests/DbLoggingTest.php, zc_install/sql/install/mysql_zencart.sql
Ref: http://www.zen-cart.com/showthread.php?215713-fatal-error-1101
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/260)
=> MySQL strict mode requires no default value on mediumtext fields

includes/classes/db/mysql/query_factory.php
Add DB_MYSQL_MODE override capability to set MySQL sql_mode for the session
To enable, simply add a define to configure.php:
`define('DB_MYSQL_MODE', 'TRADITIONAL');`
Ref: https://dev.mysql.com/doc/refman/5.6/en/sql-mode.html
Multiple modes can be combined by separating with a comma, for example:
`define('DB_MYSQL_MODE', 'NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY');`
credit to @lhungil for the suggestion
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/263)
=> Add DB_MYSQL_MODE override capability to set MySQL sql_mode for the session

includes/modules/pages/gv_redeem/header_php.php
Correct redeem issues with spaces often caused by copy/paste or customer error in entering redemption codes.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/257)
=> Correct GV redeem issues with spaces

includes/init_includes/init_customer_auth.php
With the `Admin-Configuration->Customer Details->Customer Approval Status - Authorization Pending` setting set to `1 = Must be Authorized to Browse`, a couple problems can occur:
- the in-page ajax handler code may cause the login form to be displayed multiple times on the page.
- if Down-For-Maintenance is enabled, the login page gets stuck in a "too many redirects" loop.
=> Customers-Approval auth setting loops

includes/modules/payment/authorizenet_aim.php
Fix authnet AIM field type in bindVar query preparation
Can't send a `string` to an `integer` field when MySQL is in `strict` mode.
=> Fix authnet AIM field type for MySQL strict mode

includes/functions/sessions.php
Update preg_replace regex to include commas and minus signs for session_id
Ref: http://www.zen-cart.com/showthread.php?215961-Timeout-during-final-step-of-checkout-Solution
=> Update sessions.php to allow session_id to contain comma and dash

admin/categories.php
This segment of code is not needed, and throws an error on PHP 5.4+ due to the object not being defined. Removal is the best option.
=> remove extraneous call to $pInfo

includes/modules/pages/checkout_shipping/header_php.php
Fix detection of whether "cheapest shipping selector" should be triggered
Detection should be based on the 'id' element, not the 'shipping' element alone.
Without this fix the cheapest shipping calculation will never run. Was broken in v1.5.3 and v1.5.4.
=> Fix detection of whether "cheapest shipping selector" should be triggered

includes/functions/functions_email.php
Add "hostname" override for email generator.
Although rare, some heavily "shared" servers are configured to handle sub-sub-domains, and the auto-detection of the email hostname isn't always accurate, especially if SERVER_NAME isn't passed correctly to PHP.
This change allows the ability to specify the hostname to use in Message-Id and Received headers and as default HELO string.
To use: define EMAIL_HOSTNAME in the extra_configures or extra_datafiles folder on both catalog and admin sides.
=> Add "hostname" override for email generator.

zc_install/includes/classes/class.zcDatabaseInstaller.php, zc_install/includes/modules/pages/completion/header_php.php
zc_install has some legacy SQL execution statements that make a call to $this->db->ErrorMsg() which hasn't existed for several years.
This is refactoring to remove those constructs, and to trigger regular logging and error reporting instead.
=> Fix call to nonexistent ErrorMsg() method

includes/classes/db/mysql/query_factory.php
When a database error occurs, we output a generic message, but it still sends a normal 200 response header, which doesn't tell search engines to skip it.
This sends the 503-service-unavailable header to tell SE's to come back later instead of indexing the error message.
(We were already sending the 503 header, but only when also redirecting to nddbc.html when a "not connected" condition was found ... which is too narrow criteria.)
=> Send 503 header on db error message

admin/includes/functions/general.php, admin/includes/init_includes/init_sessions.php, includes/functions/functions_general.php, includes/init_includes/init_sanitize.php, includes/init_includes/init_sessions.php
If all proxy-detections fail to determine the correct IP address, set it to a single dot (.) to denote this fact.
Ref: http://www.zen-cart.com/showthread.php?214518&p=1257981#post1257981
Also moved the sanitization logic into the same function to keep it in context.
=> Ensure IP address is not blank

admin/includes/init_includes/init_file_db_names.php, includes/init_includes/init_file_db_names.php
Update proxy/load-balancer detection to accommodate X-Forwarded-Port headers
While all the existing proxy/load-balancer detections will probably "catch" any proxy forwarded SSL headers, `X-Forwarded-Port` is one additional low-priority case, now added to the list.
=> Update proxy/load-balancer detection to accommodate X-Forwarded-Port headers

includes/modules/payment/paypal/paypal_functions.php
Fix syntax error in paypal-standard for building line-item details
Stray $ symbol
=> Fix syntax error in paypal-standard for building line-item details

admin/admin_activity.php, admin/coupon_admin_export.php, admin/includes/admin_html_head.php, admin/includes/admin_html_head_index.php, admin/includes/init_includes/init_templates.php, admin/includes/languages/english.php, admin/includes/template/common/tplAdminHtmlHead.php, admin/invoice.php, admin/login.php, admin/packingslip.php, admin/password_forgotten.php, admin/salemaker_info.php, admin/salemaker_popup.php, includes/languages/english/meta_tags.php
Removes the Admin `TITLE` logic from the catalog language file, into admin init_templates script, so the catalog-side file is now catalog-only. (Note: the admin still reads the file to allow for some display elements to offer "preview" capability from within the admin)
Uses new constant `ADMIN_TITLE` as distinct from the catalog-side `TITLE`
Builds the name from the `cmd` value, as per submission by @scottcwilson in #307
Catches missing names to allow fallback detection for plugins that might not get upgraded properly
Minor whitespace cleanup to the catalog meta_tags.php language file.
=> Refinements to #144 Admin Title Tags which build upon #307

includes/templates/template_default/templates/tpl_checkout_confirmation_default.php
In current template, "Confirm the Order" button is missing for cart containing all free items. 
Fixes #318
=> Free product checkout - Fixes #318

includes/library/zencart/platform/src/Paginator/AbstractAdapter.php, includes/library/zencart/platform/src/Paginator/AbstractScroller.php, includes/library/zencart/platform/src/Paginator/AdapterInterface.php, includes/library/zencart/platform/src/Paginator/Paginator.php, includes/library/zencart/platform/src/Paginator/adapters/QueryFactory.php, includes/library/zencart/platform/src/Paginator/scrollers/Standard.php, testFramework/unittests/paginator/paginatorAdapterTest.php, testFramework/unittests/paginator/paginatorScrollerTest.php, testFramework/unittests/paginator/paginatorTest.php, testFramework/unittests/phpunit.xml, testFramework/unittests/support/zcPaginatorTestCase.php
This is a refactoring of the previous new paginator classes, which were meant as a replacement for
the old split_page_results classes in admin/catalog.
The classes have been simplified and moved into the autoloaded library directory.
Note also, that I have not removed the old paginator classes, as these are still used by the listingBox
infrastructure. Once that is refactored they will be removed.
Also. There are some nascent docs at 
http://docs.zen-cart.com/index.php/Developer_Documentation/1.6/code_docs/pagination/pagination
=> Initial commit for refactored pagination classes

includes/modules/sideboxes/manufacturers.php
So that it is consistent with other sideboxes
=> Update manufacturers sidebox title to remove <label> for consistency

includes/templates/template_default/common/html_header.php
Empty description or keywords serves no purpose. Skipping if blank.
Similar with title, but I'll argue that title should never be blank, and will rely on core code to always ensure it is set.
=> Skip blank keyword/description metatags

admin/attributes_controller.php, admin/downloads_manager.php, admin/includes/functions/general.php, admin/includes/modules/orders_download.php
Rename zen_orders_products_downloads() to zen_verify_download_file_is_valid() to better capture the meaning of what it's doing.
Added one more place where it's used, too.
=> Rename zen_orders_products_downloads() to zen_verify_download_file_is_valid()

admin/modules.php
Fixes admin/modules.php so that module key counts are correctly checked.  This check was skipped because the if statement was incorrect.
=> Correctly check admin module 'key' counts

.scrutinizer.yml
Something in linkpoint/class.linkpoint_api.php was causing scrutinizer to error out.
=> Fix scrutinizer failures

includes/languages/english/locale.php, includes/modules/downloads.php
Ajeh spotted that the display of MB/bytes on the downloads page had some problems after the commits in #327
=> Fix size/unknown indicators on downloads page

includes/functions/functions_general.php, testFramework/unittests/phpunit.xml, testFramework/unittests/testIssetorArrayCase.php
Some upcoming code in v1.6 needs to test frequently whether an array key exists, and if not set a default value within a ternary structure.
(and we do this is legacy code as well)
As an example
Say we have an array called $somearray, and we want to test that $somearray['key'] exists, and if it doesn't set a default value.
e.g.
if (isset($somearray['key']) {
return  $somearray['key']
} else {
return 'default';
}
or as a ternary
return (isset($somearray['key']) ? $somearray['key'] ? 'default';
In some cases the above, even when used with a ternary can require a line that extends over the 80 character line limit
using the function rewrites the above as
return issetorArray($somearray, $key, 'default')
reducing the code footprint.
It should be noted that this function mimics the upcoming php7 …
=> Add new issetorArray function

includes/library/zencart/platform/src/Paginator/AbstractScroller.php, includes/library/zencart/platform/src/Paginator/AdapterInterface.php, includes/library/zencart/platform/src/Paginator/Paginator.php, includes/library/zencart/platform/src/Paginator/adapters/QueryFactory.php, testFramework/unittests/paginator/paginatorAdapterTest.php, testFramework/unittests/paginator/paginatorScrollerTest.php, testFramework/unittests/paginator/paginatorTest.php, testFramework/unittests/support/zcPaginatorTestCase.php
When testing the paginator classes with real world code (listingbox stuff), I realised that the public interface wasn't good enough.
The constructor required parameters that were not always required (e.g. would be better using method injection)
I've updated code to use the new issetorArray function.
I've updated tests based on the new public interface, as well as updating some doc block stuff
=> Refactoring of paginator classes to provide a better interface

includes/classes/shopping_cart.php
In places such as add-to-cart, an extra GET param `number_of_uploads` gets left on the URI, but serves no purpose since it's used *before* getting to the shopping-cart page.
=> Strip out "number_of_uploads" param when done with it

includes/modules/payment/paypal/paypal_curl.php, includes/modules/payment/paypaldp.php
Fix typo in method call, as identified by @lat9 in http://www.zen-cart.com/showthread.php?208310-paypaldp-php-Invalid-class-variable
=> Fix typo in method call

.scrutinizer.yml, includes/auto_loaders/config.core.php, includes/auto_loaders/paypal_ipn.core.php, includes/classes/sniffer.php, includes/filenames.php, includes/languages/english.php, includes/modules/create_account.php, includes/modules/pages/account_edit/header_php.php, includes/modules/pages/account_password/header_php.php, includes/modules/sideboxes/information.php, includes/templates/template_default/templates/tpl_modules_create_account.php, includes/templates/template_default/templates/tpl_site_map_default.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_160.sql
Notifier hooks have been added so that all former phpBB integration can be handled with custom observer class methods.
Integration note: there are a couple places where global variables like `$external_bb_text` are referenced, but no specific notifier hook is called to set them. This is because the code that 'uses' those variables is already in global scope, and therefore from within your observer class you can simply declare those variables as `global`s, and assign them a value there. Since this is still procedural code, in an observer class it is probably appropriate to do this in `__construct`.
Most other variables are set by simply letting observer class functions set the desired values and pass-by-reference (ie: params 2 - 9 for observer `update` triggers)
ALSO NOTE:
> An advanced …
=> Replace phpBB with hooks for external "forum" systems - Closes #272

.travis.yml, testFramework/unittests/phpunit.xml
This will speed up tests considerably, and Scrutinizer can run the coverage reports separately.
=> Disable code-coverage reporting in TravisCI (in favor of Scrutinizer)

admin/includes/classes/box.php, admin/includes/classes/message_stack.php, admin/includes/classes/table_block.php
e.g.  Call to undefined method messageStack::tableBlock()
=> Fix errors caused by method renaming in tableBlock class

admin/banner_manager.php, admin/ezpages.php, admin/includes/classes/object_info.php, admin/includes/modules/document_general/collect_info.php, admin/includes/modules/document_general/collect_info_metatags.php, admin/includes/modules/document_product/collect_info.php, admin/includes/modules/document_product/collect_info_metatags.php, admin/includes/modules/product/collect_info.php, admin/includes/modules/product/collect_info_metatags.php, admin/includes/modules/product_free_shipping/collect_info.php, admin/includes/modules/product_free_shipping/collect_info_metatags.php, admin/includes/modules/product_music/collect_info.php, admin/includes/modules/product_music/collect_info_metatags.php, admin/newsletters.php
This is part of the php7 updates.
The objectInfo class original constructor was also being called as a method in of itself
So the original refactor (renaming the old php 5.3 constructor) broke a lot of code as there was no longer an objectInfo method.
=> Fix objectInfo class

admin/languages.php
Fix bug from v154 (CHANGE-709) which incremented language_id incorrectly
Ref: http://www.zen-cart.com/showthread.php?215842-Insertion-of-an-additional-language-does-not-copy-existing-category-product-texts&p=1269562#post1269562
=> Fix bug from v154 which incremented language_id incorrectly

includes/classes/shopping_cart.php
Here only a simple check is done for the existence of a record. I do not think all fields are needed to do that
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/390)
=> Why query all fields when only products_attributes_id is needed

admin/banner_manager.php, includes/functions/banner.php
Banners were not firing correctly for enable/disable and incorrect dates were being stored.
This affected the results in the Catalog and Admin.
=> Banners miss fire and set wrong date

admin/developers_tool_kit.php, admin/includes/languages/english/developers_tool_kit.php, admin/includes/template/css/developers_tool_kit.css
Add related-context lines to results in dev toolkit
- shows prev+next 3 lines with search results (user-selectable # of lines)
- bolds the "found" line (styleable via CSS) and actual search text
=> Add related-context lines to results in dev toolkit

admin/includes/init_includes/init_languages.php
check for file existence to avoid log:
[21-Apr-2015 18:04:17 America/New_York] PHP Warning:  include(includes/languages/french/widgets_default.php): failed to open stream: No such file or directory in /Users/scott/Sites/demo_160/admin/includes/init_includes/init_languages.php on line 61
=> widgets_default language file -- Multiple languages create debug logs

includes/classes/order.php
Is it necessary to call for all fields when only 'products_quantity' is used?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/389)
=> Why query all fields when only products_quantity is needed

includes/classes/order.php
This adds the products_attributes_filename field to the resultset for consistency, so that there's no chance the array element will not be defined and throw an error.
=> Additional update to query from PR #389

includes/application_top.php
Removed superfluous variable $customers_ip_address from application_top.php, after search revealed no instances of it being used.
I'm sorry if this minor change is a waste of time, but I really wanted to figure out the workflow for submitting changes so I can do more.  Please let me know if I'm doing everything correctly.
=> Remove unused variable $customers_ip_address from application_top

includes/library/zencart/platform/src/listingBox/boxes/AbstractListingBox.php
The multiple-add-to-cart button was only showing on the "top" of the list, but not also the bottom when the option was set to `3=both`
=> multiple-add-to-cart button was missing from "bottom"

zc_install/sql/install/mysql_latin1.sql, zc_install/sql/install/mysql_utf8.sql, zc_install/sql/updates/mysql_upgrade_zencart_160.sql
Fix misspelling and accents for a few countries.
Note: No accents are used in latin1 mode, hence limited changes to that file.
=> Fix misspelling and accents for a few countries.

testFramework/unittests/testsPasswordHash/PasswordHashTest.php
salt param is obsolete in PHP 7
=> Fix salt errors on PHP 7

includes/library/zencart/Controllers/src/AbstractLeadController.php, includes/library/zencart/Paginator/src/Paginator.php, includes/library/zencart/listingBox/src/PaginatorBuilder.php
The paginator class was only looking for a get parameter of main_page to build URL links
Admin uses cmd=page
Problem was hidden because currently use of new pagination in admin is delivered via ajax
Note. Also browser url is not updated for ajax processed pagination
I intend to address this later, with some other updates to allow for a Cancel buttons on edit/add
=> Ajax paginator in the LEAD classes were not showing the correct URL

includes/library/zencart/QueryBuilder/src/QueryBuilder.php, testFramework/unittests/testsQueryBuilder/QueryBuilderTest.php
Note. Mostly done for code coverage rather than specific testing of returned queries,
however as noted before, having the coverage allows us to update tests based on bugs found.
=> Update unittests for QueryBuilder

includes/templates/template_default/templates/tpl_login_default.php
While code is in place to hide the PayPal checkout button if orders are too large it doesn't hide the introduction text on the login page leading to a confusing paragraph about PayPal with no button to checkout with.
This fixes that.
=> Paypal introduction removed for orders over 10k, 5.5k

includes/library/zencart/listingBox/src/formatters/ListStandard.php, testFramework/unittests/testsListingBox/formatterTest.php
The text input boxes had incorrect product ids attached to them, which meant
that the multi add to cart would send the wrong products ids to the shopping cart.
=> The ListStandard formatter was building incorrect buy now boxes.

extras/curltester.php, includes/modules/payment/authorizenet.php, includes/modules/payment/authorizenet_aim.php, includes/modules/payment/authorizenet_echeck.php
Per Authorize.net developer bulletin July 14, 2015:
>The new Akamai transaction URLs that are available now are:
`https://api2.authorize.net/xml/v1/request.api`
`https://api2.authorize.net/soap/v1/Service.asmx`
`https://secure2.authorize.net/gateway/transact.dll`
=> Authorize.net Akamai endpoint change

admin/customers.php
This double `default:` is redundant (and actually incorrect), so is a bug. Plus, in PHP7 the duplicate will throw a fatal error.
=> Remove double `default` clause (breaks PHP7)

includes/functions/banner.php, includes/modules/sideboxes/banner_box.php, includes/modules/sideboxes/banner_box2.php, includes/modules/sideboxes/banner_box_all.php, includes/templates/template_default/sideboxes/tpl_banner_box.php, includes/templates/template_default/sideboxes/tpl_banner_box2.php, includes/templates/template_default/sideboxes/tpl_banner_box_all.php
- Wraps banners in a `<section class="info-promowrapper">` so can be targeted with CSS styling
- Fixes SQL errors caused by having no active banners in a given group
- Splits logic out of templates more effectively, and simplifies some of the logic
=> Improvements for Banner Boxes (and fixes SQL error)

zc_install/includes/classes/class.systemChecker.php
This causes problems on Ubuntu, and I dont think it will affect the installer on other platforms.
disabaling third/first party cookies in firefox doesn't trigger any errors.
=> Disable the SID check.

includes/modules/payment/paypal/paypal_functions.php, includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php
Previously it only handled fractions if `> 1`. This change allows handling even for `0.5` etc.
=> Fixes #422 fractional quantities

includes/modules/payment/paypalwpp.php
The extra underscore shouldn't be there.
https://developer.paypal.com/webapps/developer/docs/classic/api/merchant/DoExpressCheckoutPayment_API_Operation_NVP/
=> Extra underscore in parameter

includes/modules/payment/paypalwpp.php
The 84.0 implementation applied the PAYMENTINFO_0_ stuff too aggressively in one spot.
This also moves the notifier (added in the 84.0 integration) earlier so that it's more versatile.
=> Make error-handling notifier more functional and fix 84.0 error

includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php
Rearrange PayPal error message email slightly
The EC emails had info about the affected customer as last-line of the email. This moves it to the top.
Also does a quick sanitize of names, just in case.
=> Rearrange PayPal error message email slightly

admin/includes/languages/english.php, admin/layout_controller.php
Fixes #140
NOTE: This page should also be converted to LEAD-style at some point
And this also points out that there are lots of other buttons needing reworking as part of a larger task affecting BC.
=> Change layout-ctrlr buttons to be multi-lang CSS-driven

admin/includes/languages/english.php, admin/includes/languages/english/orders.php
If the order history is missing, the invoice and packingslip pages will only show
TEXT_NO_ORDER_HISTORY, since this define is not available to them.
=> Move message about missing order history to main admin language file

admin/alert_page.php, admin/includes/languages/english/alert_page.php
The retry link is only available if the admin folder has already been renamed but the zc_install has not. (... because we can't do a retry link if we don't know the name of the new admin folder yet)
=> Add retry button to admin alert_page

zc_install/includes/classes/class.systemChecker.php
Tests whether zc_install can be done over https, and if so then redirects accordingly.
This helps the proper auto-detection of setup params, and also causes the db password and all other setup data to be transmitted over https instead of in clear text.
This detection only works with domain-specific certificates, not shared certificates.
=> Force to run zc_install over https if possible

includes/templates/template_default/templates/tpl_checkout_payment_default.php
Fixes #535
Further enhancement could include javascript to disable the submit button until the box is checked ... but only if the feature is enabled
=> Relocate T&C checkbox to be next to submit button

includes/modules/checkout_process.php, includes/modules/payment/paypal/paypal_functions.php, includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php, ipn_main_handler.php
These are some uses of indirect variables/properties/methods and globals which need some disambiguation for PHP 7 compatibility.
Ref: http://php.net/manual/en/migration70.incompatible.php
=> Disambiguation of $$ usage for PHP7 compatibility

extras/curltester.php
This simply adds additional output to the CURL communications info, specifically about the certificate being connected to.  
This occasionally can be helpful when debugging, but I suspect will seldom be needed.
=> Add `i` parameter to curltester for advanced debugging

includes/modules/payment/authorizenet.php
On Sept 8, 2015 Authorize.net disabled the ability to set HTML/javascript/css markup in their custom payment page styling tools, in the interest of security. You can still customize your payment pages, but must do it via the settings in your authorize.net account directly on their website. However, one customization which you might want to pass along with your payments is the URL of the logo you wish to display. This code change allows for your store to send that logo URL.
(Other customization fields are NOT currently passed with payments. Instead, use the tools online in your account at authorize.net)
To activate the logo URL feature, simply add a define for `MODULE_PAYMENT_AUTHORIZENET_LOGO_URL` to the authorizenet.php language file …
=> Add the ability to pass a logo URL ('x_logo_url') to Authorize.net SIM payments

extras/curltester.php, includes/modules/payment/authorizenet.php, includes/modules/payment/authorizenet_aim.php, includes/modules/payment/authorizenet_echeck.php
Using "secure2" instead of "secure" was only an intermediate step until they switched everything over to the new system.
=> Reverse PR #464 - Authorize.net Akamai Servers

includes/classes/shopping_cart.php
This change provides the checking to ensure that a TEXT attribute's character-length is within the bounds of its configuration.  The TEXT input, if found to be too long, is simply truncated prior to allowing the add_cart process to continue ... no message is issued.
Correction is based on this post: https://www.zen-cart.com/showthread.php?218085-Multi-line-TEXT-attribute-size-is-not-checked
=> Check text attribute size

admin/includes/init_includes/init_errors.php
The change to `DIR_FS_LOGS` missed this instance of using the old `DIR_FS_SQL_CACHE`
=> Fixes #561 - leftover zc_install logs triggering warning in admin

.travis.yml
Add OAUTH github support for composer on travis, to support API rate-limiting
=> Travis - Add github OAUTH support for composer to skip rate-limits

zc_install/includes/classes/class.systemChecker.php, zc_install/includes/languages/lngEnglish.php, zc_install/includes/systemChecks.yml
While PHP 5.4 is EOL, the ZC v160 code currently still works on PHP 5.4, so the minimum is being set to 5.4.2 for now (since 5.4.2 fixed the CGI bug)
=> Get rid of zc_install test for PHP CGI bug in PHP 5.4.0/5.4.1

includes/functions/password_funcs.php, zc_install/includes/functions/password_funcs.php
passwords were originally being generated using old style md5 hashes.
and while the passwords would have been updated to bcrypt on subsequent logins
better to get them right from the start.
=> Updating password compatability code

admin/includes/auto_loaders/config.core.php, admin/includes/functions/general.php, admin/includes/init_includes/init_check_parms.php
Test Case: 
https://zen.local/admin/index.php?cmd=product_free_shipping&page=1&product_type=999&cPath=64&pID=172&action=new_product
without my change, will issue a debug log and a blank page.  With my fix, will go to the product but ignore the product_type change.
=> Fixes #69 Guard against modifying product type in URL

includes/autoload_namespaces.php, includes/init_includes/init_header.php, includes/library/zencart/View/src/TplVarManager.php, includes/library/zencart/View/src/View.php
A lot of new code
e.g. ListingBoxes, LEAD stuff, CheckoutFlow use tplVars (Template Variables) to set variables that will be displayed/used in templates.
They need to do this to change the scope of the variables from the class they are created in to the global scope that template files exist in.
The problem is that each infrastructure has to repeat common methods to set/manage template variables.
Better to have common class that managed the template variables.
Further more (at least in catalog side code) we currently need to access things like the messaageStack/BreadCrumbs classes.
Rather than accessing Global stated, again better to pass in a View class that can access these common classes.
=> New View and TplVarManager classes

ajax.php, includes/functions/functions_general.php, testFramework/unittests/testsSundry/HtmlEntityRecurseTest.php
The original fix didn't allow for multiple depth arrays.
see https://www.zen-cart.com/showthread.php?21669124&p=1294488#post1294488
I have based the code on that posted by @lat9 in the thread and added a unittest.
=> Fix UTF8 sequence error in ajax call

zc_install/includes/classes/class.zcConfigureFileReader.php
The zcConfigureFileReader class attempts to read define values via a pattern match.
However the original pattern would match against commented values e.g. starting with //
=> Parsing config file values incorrectly

admin/includes/modules/product_music/copy_to_confirm.php
Since both 'on' and '1' have been used, and different browsers are giving different results, this change accommodates both, and will allow for potentially-missed file changes in upgrades/plugins.
=> Backward compatibility for media-copy checkbox handling

includes/classes/currencies.php, includes/classes/order.php, includes/modules/payment/paypalwpp.php
Ref: https://www.zen-cart.com/showthread.php?218530-PayPal-Express-Checkout-Rounding-issue-causes-quot-Line-item-subtotals-do-not-add-up-quot&p=1294598#post1294598
Not sure I like this line, which completely overrides the tax-inc/exc calcs in the preceding lines:
```php
$tax_add = $currencies->value($tax_add, false, $this->currency);
```
UPDATE: After further study, I'm less bothered about this $tax_add line than I initially thought.
=> Currency override suggestions from @lat9

includes/library/zencart/listingBox/src/formatters/ListStandard.php, testFramework/unittests/testsHtmlOutput/AdminCatalogUrlGenerationTest.php, testFramework/unittests/testsHtmlOutput/CatalogUrlGenerationTest.php
remove incorrect reset for queryfactory
Bug in hhvm for error_log
=> Fixing some hhvm unittest errors

includes/templates/template_default/templates/tpl_shopping_cart_default.php
If an error occurs but the cart is still empty (perhaps because adding to the cart failed), the messages should still be shown at the top of the shopping cart page.
=> Messages should be shown even if cart is empty

zc_install/includes/classes/class.zcConfigureFileReader.php
The problem was that the configure.php file would be loaded as a contigous string, and the regex was trying to anchor at the start of the string.
Need to enable mult-line mode in regex
=> parsing configure.php not working correctly in installer.

includes/templates/template_default/templates/tpl_modules_shipping_estimator.php
Adding the `#view` anchor allows the page to scroll up slightly to reveal the shipping quotes, instead of them silently showing up below-the-fold.
=> Add #view anchor to Shipping Estimator to help with viewport challenges

includes/modules/payment/paypal/paypalwpp_admin_notification.php
Added char-counter to Refund text box
Ref http://www.zen-cart.com/showthread.php?211173-Admin-Order-Details-Paypal-Refund-message-text-box-is-not-limited-to-255-chars
=> Paypal Refund message text box should be limited to 255 chars

includes/classes/ajax/zcAjaxPayment.php, includes/classes/order.php, includes/library/zencart/listingBox/src/DerivedItemManager.php, includes/library/zencart/listingBox/src/formatters/TabularCustom.php, includes/modules/pages/checkout_confirmation/header_php.php, includes/modules/pages/checkout_shipping/header_php.php
These are related to use of $$foo['element'] which need to add the {braces} for specificity
=> Indirect-expression fixes for PHP7

includes/modules/meta_tags.php
These hooks can be used in various ways:
- As in previous versions, hooking `NOTIFY_MODULE_START_META_TAGS` allows one to completely intercept the default metatags generation altogether
- `NOTIFY_MODULE_META_TAGS_BUILDKEYWORDS` allows overriding of just the dynamic generation of keywords
- `NOTIFY_MODULE_META_TAGS_UNSPECIFIEDPAGE` allows the injection of metatags for pages that don't have built-in generation logic in the default module
Also allows an observer on `NOTIFY_MODULE_START_META_TAGS` to change the value of `$metatag_page_name` ... which could force the usual rules to be bypassed (and thus trigger "default"), which can then be intercepted by `NOTIFY_MODULE_META_TAGS_UNSPECIFIEDPAGE` if necessary, to set specific values.
=> CHANGE-465 - Add more notifier hooks to dynamic metatags generator module

admin/includes/functions/general.php
Ref: https://www.zen-cart.com/showthread.php?219015
Now the default range is 5 years "ago" until 10 years "in future"
=> Fix for: zen_draw_date_selector "times out" in 2018

includes/classes/order.php
These additional insert-id values can aid in tracking inventory related to attributes
Per suggestion from @mc12345678 at https://www.zen-cart.com/showthread.php?215320-order-notifiers
=> Add insert-IDs to various order notifier hooks for attribute-related data

admin/includes/extra_configures/security_patch_v154_20151217.php
Add patch to provide additional aggressive `xss` filtering on admin side
NOTE: the admin is already protected against `csrf` issues, so `xss` problems require being logged in with a valid username and password
Credits to Trustwave Security for pointing out these minor risks and helping tighten security overall.
=> Add patch to provide additional aggressive xss filtering on admin side

admin/admin_account.php, admin/gv_mail.php, admin/users.php, includes/templates/template_default/templates/tpl_account_edit_default.php, includes/templates/template_default/templates/tpl_contact_us_default.php, includes/templates/template_default/templates/tpl_gv_send_default.php, includes/templates/template_default/templates/tpl_login_default.php, includes/templates/template_default/templates/tpl_modules_create_account.php, includes/templates/template_default/templates/tpl_password_forgotten_default.php, includes/templates/template_default/templates/tpl_time_out_default.php
Fixes #625 - Treat all email fields as the more mobile-friendly 'email' type
=> Treat all email fields as 'email' type in HTML5 - more mobile friendly

extras/curltester.php
This is only valid until end of Feb 2016
=> Add PayPal's temporary security endpoint test URL to curltester

extras/curltester.php
Apparently although PayPal is promoting their new postback URL, it's still not functioning consistently...
https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1916
=> PayPal's server doesn't seem to be responding. Reverting prior commit.

includes/modules/payment/authorizenet.php
When the module is in Authorize-Only mode, order-status gets overridden to 1-Pending since the payment is indeed actually
=> Add the order-status override to SIM using what AIM does

admin/includes/languages/english/products_price_manager.php, admin/products_price_manager.php
ZC thread: https://www.zen-cart.com/showthread.php?217854-Products-Price-Manager-doesn-t-offer-display-of-prices-and-specials-with-tax
Style used was similar to product_info entry page.
=> Products Price Manager: Add display of taxed prices and specials

admin/includes/ckeditor.php, admin/includes/languages/english/extra_definitions/ckeditor.php
Put CKEditor hooks back into core distro (still must add the actual editor files manually by downloading them from `ckeditor.com` and unzipping and uploading the unzipped `ckeditor` folder to the store's `/editors/` folder.
=> Put CKEditor hooks back into core distro (still must add the actual editor files manually)

includes/templates/responsive_classic/common/tpl_footer.php, includes/templates/template_default/common/tpl_footer.php
Make validator links more versatile for https and not throw error on home page due to mismatched ?/& symbols
=> Make validator links more versatile for https

admin/includes/defined_paths.php
Makes guesses in case the essentials from admin configure.php are missing (such as when someone uses a non-admin configure.php in their admin)
These guesses aren't foolproof, but they're reasonable assumptions which should avoid unnecessary errors from occurring if the end-user makes this mistake. Multiple nested subdirectories might pose problems ... in which case the fix is to actually use the proper configure.php files in the proper locations ... ideally what is generated by zc_install.
=> Add catchalls in case someone puts the catalog configure.php in admin

admin/server_info.php
On tablets the sysinfo page was shrinking text to unreadably small size. This constrains it to a reasonable width.
=> Add constraint to the width of the admin system-info page

admin/includes/languages/english/orders.php, admin/orders.php
Previously any orders whose `orders_status` value didn't match a value in the `orders_status` table would be excluded from display in the Admin.
This now includes those orders, along with an alert which informs the administrator that the order-status is invalid.
(As always, to fix an order in this condition, simply go into the order and do an update to a new order-status using the dropdown menu)
=> Display orders in Admin even if orders_status is invalid (with an alert)

includes/functions/functions_email.php
Email errors will now be logged the same as any other PHP error, in the `/logs/` folder.
This could ultimately deprecate the `EMAIL_FRIENDLY_ERRORS` switch as this basically renders it moot.
Ref: https://www.zen-cart.com/showthread.php?219285-sending-order-emails
=> Log email errors with other PHP errors in /logs/ folder

includes/languages/english/modules/payment/paypaldp.php, includes/languages/english/modules/payment/paypalwpp.php, includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php
Update PayPal Express and Pro to NVP API 201.0 spec
Simply catches a few more error message scenarios
=> Update PayPal Express and Pro to NVP API 201.0 spec

includes/classes/db/mysql/query_factory.php
Null dates need to be passed as `null` instead of `'null'` 
Same with strings.
USAGE NOTE:  For BindVars, for `date` and `string` bindVarTypes, passed values of a string `null` (case-insensitive) will be converted to a literal MySQL `null` instead of treated as a string of the word `'null'`
=> Null dates need to be passed as `null` instead of `'null'`

zc_install/includes/classes/class.zcConfigureFileWriter.php, zc_install/includes/languages/lngEnglish.php, zc_install/includes/modules/pages/admin_setup/header_php.php, zc_install/includes/template/templates/admin_setup_default.php
Add meaningful error messages on-screen if config files couldn't be written properly.
=> Add error reporting to zc_install for problems writing configure.php files

includes/templates/responsive_classic/css/stylesheet.css, includes/templates/responsive_classic/css/stylesheet_colors.css, includes/templates/template_default/css/stylesheet.css, includes/templates/template_default/templates/tpl_account_edit_default.php, includes/templates/template_default/templates/tpl_account_password_default.php, includes/templates/template_default/templates/tpl_contact_us_default.php, includes/templates/template_default/templates/tpl_login_default.php, includes/templates/template_default/templates/tpl_modules_address_book_details.php, includes/templates/template_default/templates/tpl_modules_checkout_new_address.php, includes/templates/template_default/templates/tpl_modules_create_account.php, includes/templates/template_default/templates/tpl_password_forgotten_default.php
Implement placeholders instead of spans for messaging about "required" fields. 
Thanks to @zcadditions for most of this.
And also added "required" attribute to corresponding fields.
=> Change text-based "required" symbols to utilize HTML5 placeholder attributes

admin/attributes_controller.php, admin/includes/functions/general.php, admin/options_name_manager.php, admin/options_values_manager.php, admin/sqlpatch.php, zc_install/includes/classes/class.zcDatabaseInstaller.php
Instead of relying on passing 0 to the auto-increment field name, we specifically avoid mentioning it, which causes MySQL to automatically trigger the auto-incrementing rules.
This should help avoid conflicts in cases of odd MySQL configurations such as `NO_AUTO_VALUE_ON_ZERO` in my.cnf
=> Rewrite the handful of queries using 0 to trigger auto-incrementing

includes/modules/payment/authorizenet_aim.php
Can't have string stored in bigint field, so remove it before storing, to avoid a db error.
Thanks to @numinix for pointing out the problem.
=> Clean comments from transaction id field before storing to db

zc_install/includes/classes/class.zcDatabaseInstaller.php
When zc_install creates new tables, it attempts to set a collation value, but fails if the `db_charset` is blank. This assumes a safe default.
=> Set a default charset during zc_install, for use with creating new tables

admin/includes/header.php, admin/includes/header_navigation.php, admin/includes/languages/english.php
The conditionally-displayed buttons in the Admin header area, beside the store logo, were overlapping on smaller screens. 
They are now reordered, and utilize the responsive framework more intentionally.
=> Fix overlap of admin header buttons

extras/curltester.php, extras/paypal_tlstest.php, includes/modules/payment/authorizenet_aim.php, includes/modules/payment/authorizenet_echeck.php, includes/modules/payment/payeezyjszc.php, includes/modules/payment/paypal/paypal_curl.php, includes/modules/payment/paypal/paypal_functions.php, includes/modules/payment/sagepay_zc/SagepayUtil.php
Some hosts don't yet support proper auto negotiation for modern TLS protocols, so this allows a timeout and then tries again by specifying a hard-coded protocol after logging the problem in the myDebug-xxxxx.log logs.
=> Add CURL fallbacks to support hosting companies that can't do security right

docs/changed_files-v1-5-5.html
I know the 1.5.5 version is live now, but while reading the readme for the changed files etc., I discovered these were missing from the list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/877)
=> missing new files in 1.5.5 documentation

zc_install/sql/updates/mysql_upgrade_zencart_151.sql, zc_install/sql/updates/mysql_upgrade_zencart_153.sql
Fixes chicken/egg problem
Affects upgrades from 150-to-151, and 152-to-153, and already handled 154-to-155
=> Backport fixes for MySQL no-zero-date mode to older zc_install upgrade steps

admin/developers_tool_kit.php
Since introducing the shared folder, they should also be made searchable
in the developers toolkit.
I added paths for the shared folders where the code is looking for
$template_dir.
I also added some missing paths in the language directories
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zc-v1-series/887)
=> Add missing directories

admin/customers.php, includes/classes/db/mysql/query_factory.php, includes/modules/create_account.php, includes/modules/pages/account_edit/header_php.php, includes/modules/pages/address_book_process/header_php.php
Because of the way bindvars worked some form entries would
assume that if the entry contained the string 'null' that the whole entry
should be set as a mysql null.
e.g. If your surname was NullSurname then the bindvars would insert a mysql Null
rather than the proper string
=> Fix bindvars to honor string entries that contain 'null'

zc_install/sql/updates/mysql_upgrade_zencart_153.sql, zc_install/sql/updates/mysql_upgrade_zencart_155.sql
Newer MySQL versions which are configured to enforce no zero-dates will fail to allow schema updates to any fields in the customers table if the `customers_dob` datetime field contains zero-date values.
=> Force change of dob value for old records

includes/templates/responsive_classic/templates/tpl_checkout_payment_address_default.php, includes/templates/responsive_classic/templates/tpl_checkout_shipping_address_default.php, includes/templates/template_default/templates/tpl_checkout_payment_address_default.php, includes/templates/template_default/templates/tpl_checkout_shipping_address_default.php
Also checkout-payment-address screen.
It was displaying 2 continue buttons if no "extra" addresses have been added to address-book.
(Continuation of commit https://github.com/zencart/zc-v1-series/commit/b151f45390c8bd0eb23eb41da3b12480cbe001da )
=> Remove double-continue buttons on checkout-shipping-address screen

admin/includes/functions/general.php, includes/functions/functions_general.php
It has been discovered that some crafted URl's can result
in fmod_round generating a division by zero error. While this
is not a security concern as such, have added a test to ensure
division by zero cannot occur
=> add safety to fmod_round

includes/init_includes/init_category_path.php
Example case, according to @ajeh: 
1. Configure store to always-open-with-specific-category
2. Configure to always-show-that-category
3. Navigate to a non-prod-listing page, such as `main_page=featured_products` and see the extra breadcrumbs for the always-open-with category.
This PR fixes that.
=> Fix extra breadcrumb that was appearing when always-open-with-category is enabled

admin/includes/functions/localization.php
- BOC changed their currency codes to `XYZ_NOON` instead of just `XYZ`
- Also fixes a potential division-by-zero condition
=> Update BOC currency parsing to cope with their data changes

includes/modules/order_total/ot_gv.php
The configuation_key MODULE_ORDER_TOTAL_GV_ORDER_STATUS_ID was never used. GVs use the: DEFAULT_ZERO_BALANCE_ORDERS_STATUS_ID
=> ot_gv fix for extra configuration_keys

includes/classes/language.php, includes/init_includes/init_languages.php, includes/modules/sideboxes/languages.php, includes/templates/template_default/common/html_header.php
This is only to attempt to avoid breaking very old plugins that haven't been upgraded to the newer more consistent syntax used in v160.
=> Add legacy compatibility to adapt for new language-class components

includes/auto_loaders/config.core.php
To dup initial issue, start without this fix with a clean 160 db,
create an account and run an order.  Mailer fails to load and gives
an error log.
=> FIXES #923 Debug log on checkout

admin/includes/classes/AdminRequestSanitizer.php, admin/includes/init_includes/init_sanitize.php, not_for_release/testFramework/unittests/testAdminSanitizationCase.php
Fix strict sanitizer to use ignore group
Also add some fields that should allow entities such as & but were converting to `&amp;`
=> Fix strict sanitizer to use ignore group

ipn_main_handler.php
Submitted to replace a previous pull request that doesn't want to play nice when rebasing from v155 to v160.
Discussion held back on ZC 1.5.1 at https://www.zen-cart.com/showthread.php?214423-Order-status-changes-after-batch-capture-on-PayPal-website where store owner observed that the status of orders that were previously manually updated inside of the ZC admin were lowered once batch capture was performed on PayPal site.
The change proposed above was reported as working at least before the and was added to the added if statement. And statement intent is to apply/allow the old status to remain if and only if the transaction is one that isn't intended to reduce the status. For example, refunding, reversing, denying or failing a transaction should not allow the status to remain elevated …
=> Maintain order status that is above default on PayPal batch capture

includes/init_includes/init_sanitize.php
when an inactive/non-valid product link is clicked, ZC first issues an HTTP response of 302 and then a 404.  as the page no longer exists, there should NOT be a 302 issued prior to the 404.  the 404 gets handled from includes/modules/pages/product_info/header_php.php.  so i am unclear why a 302 is being issued here and then going to the same page.  
this PR removes the 302 response/redirect when an invalid product_id is selected.
https://www.zen-cart.com/showthread.php?220104&p=1311344#post1311344
=> does not redirect on invalid product_id

admin/gv_mail.php
The closing bracket for $zco_notifier->notify was missing missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/960)
=> Add missing closing bracket

admin/includes/template/templates/tplIndex.php
Failure on call to getInstallableWidgets because of login timeout
occurs silently, so the user has no idea what's happening.  This
redirects them to re-authenticate.
Testing: 
- login to admin
- open a new tab on an admin page, and logout on that tab.
- on first tab, press Add Widget button.  With this fix, you'll be redirected to login.
=> Fixes Add Widget when logged out

admin/sqlpatch.php
Without this change, sqlpatch commands with two spaces
following the initial verb will fail.  This is confusing
to users and leads to disinformation about how well
sqlpatch works (vs PHPMyAdmin).
Fixes #951
=> Making sqlpatch less space sensitive

testFramework/unittests/testsSundry/AdminLoggingTest.php
These changes were required so that this test could be
run stand alone without running the entire suite, i.e.
```
phpunit --filter testAdminLoggingCase testFramework/unittests/testsSundry/AdminFunctionsGeneralTest.php
```
I am writing documentation on how to create and modify tests, and
I want to use this as an example.
=> Changes to make test runnable in insolation

admin/includes/application_bootstrap.php, includes/functions/whos_online.php, includes/init_includes/init_file_db_names.php
Some server engines don't set `PHP_SELF` reliably, so using `SCRIPT_NAME` appears to be more reliable and compatible.
As for compatibility, here's a simple reference: http://php.about.com/od/learnphp/qt/_SERVER_PHP.htm
=> Change references to $_SERVER['PHP_SELF'] to $_SERVER['SCRIPT_NAME']

admin/includes/template/partials/specialMenu/tplStandardLinks.php
When clicking the link Storefront, the user is directed to the Storefront as expected, but in the same screen, which is not the way it used to work in the old link. I suggest putting the targent="_blank" back in the link
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/984)
=> Suggest adding target

admin/includes/extra_configures/system_inspection.php
Using the system inspection page, I came across these values that were missing from the build in arrays
Very handy tool :smile:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/985)
=> Adding missing buid in values

includes/modules/payment/authorizenet.php, includes/modules/payment/authorizenet_aim.php, includes/modules/payment/authorizenet_echeck.php
According to previous communication, Authorize.net was going to switch to Akamai on June 30 "automatically". But they've delayed that due to many vendors not being prepared.
To benefit from the improved reliability sooner than later, this simple URL change is all that's required in ZC.
=> Authorize.net has changed their rollout plan for Akamai

admin/includes/template/templates/tplAdminLead.php
The part just below adminLeadContainer had spacing that was all
out of alignment.
NOTE: This only affects "View Source"; it would not be visible to normal users who are not looking at the the created HTML.
=> Fix HTML Formatting of LEAD pages (top)

admin/includes/template/templates/tplAdminLead.php
Using  'isPaginated' => false in the  listingQuery should
prevent the dropdown for “Max number of items per page” showing up.
=> Do not display Max # Rows Dropdown if no Pagination

admin/includes/modules/category_product_listing.php, includes/functions/compatibility.php, includes/functions/functions_categories.php, includes/functions/functions_lookups.php
Reduce some cyclomatic complexity of some functions by removing (some) duplication.
Change treatment of integer values to be integers instead of strings.
Deprecate some duplicates.
(Addendum to #967 which consolidated functions files)
=> Optimizing some category-lookup-related functions

admin/includes/template/AdminLTE2/dist/css/AdminLTE.css
The extra space gives an error on code validation (in NetBeans). I am not sure is it will actually fail to load the gradient in IE, but all the examples I examined do not have this extra space.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1014)
=> Space will fail validation

includes/library/zencart/listingBox/src/formatters/TabularProduct.php
Occasionally in product listings shopowners may want to put the product-description on a separate row below product details.
This came about from a discussion with @ajeh awhile back.
=> Alternate layout to allow description on second row in prod listings

zc_install/includes/languages/lngEnglish.php, zc_install/includes/modules/pages/completion/header_php.php, zc_install/includes/nginx_conf/.gitignore, zc_install/includes/nginx_conf/ngx_server_template.txt, zc_install/includes/nginx_conf/zencart_ngx_http.conf, zc_install/includes/nginx_conf/zencart_ngx_server.conf
When zc_install replaces the original file every time it is run, it makes code maintenance complicated. This splits it out into separate files: a template, and an output file.
=> Split the nginx config into input-template and output-conf files

includes/modules/checkout_process.php
In rare and unexplained circumstances tax calculations may not fire properly on shipping.
Changing the load-order to match the order used in other stages of checkout appears to help prevent this.
Long discussion at https://www.zen-cart.com/showthread.php?220280-Shipping-tax-not-added-in-order-confirmation-possible-bug&p=1312461#post1312461
=> Reorder load-order of components in checkout_process

includes/library/zencart/DashboardWidget/src/WidgetManager.php
If user's widget is defined in db table but class is missing, a fatal error was occurring.
Now it just displays an empty widget without crashing.
=> Prevent fatal error if widget class is missing

includes/library/zencart/QueryBuilder/src/QueryBuilder.php, includes/library/zencart/QueryBuilderDefinitions/src/definitions/ReportStatsCustomers.php
fix required by: Stats customers report should be ordered by total descending
Fixes #1040
=> orderby and groupby clashing in report generator

includes/modules/template_dependency_modules.php
Issue new to 1.6.0 relating to shared folder.
=> Fixes #1054 Log created when template does not exist

zc_install/includes/languages/lngEnglish.php, zc_install/includes/template/templates/system_setup_default.php
Uses a more intense color and tells them follow up will be needed:
```
'As soon as possible, you should install an SSL certificate, and update your configure.php files.'
```
=> Warn the user on the system_setup page to get a certificate

admin/includes/application_bootstrap.php, includes/application_top.php, zc_install/includes/application_top.php, zc_install/includes/systemChecks.yml
Given that `session.use_trans_sid` can be disabled at the application level, let's do that automatically, instead of leaving it up to the end-user to have to figure out how to change `php.ini`
=> Automatically disable session.use_trans_sid

admin/includes/functions/admin_access.php
Some calls to `constant(foo)` were throwing errors if certain language defines were not present.
These changes simply skip those entries instead of throwing errors. 
(Alternatively a future enhancement could be to throw an exception or log an error instead, to help people troubleshoot why their widgets or menu items aren't showing up.)
=> Protect against undefined widget/page defines in admin menu functions

includes/functions/functions_general.php
Fixes #973 using suggestion by @torvista
=> Windows server, php-generated utf-8 days with accents not displayed correctly

includes/library/zencart/QueryBuilderDefinitions/src/definitions/AbstractLeadDefinition.php
Without this fix, you get
PHP Fatal error:  Call to a member function getCurrentPage() on null in
includes/library/zencart/QueryBuilderDefinitions/src/definitions/AbstractLeadDefinition.php on line 43
if you don’t specify  'isPaginated' => true in the $listingQuery.
=> Permits no setting of pagination.

admin/.htaccess, admin/includes/.htaccess, admin/includes/template/.htaccess, cache/.htaccess, docs/.htaccess, download/.htaccess, editors/.htaccess, email/.htaccess, extras/.htaccess, images/.htaccess, images/uploads/.htaccess, includes/.htaccess, logs/.htaccess, media/.htaccess, pub/.htaccess, zc_install/.htaccess
This allows for compatibility with both Apache 2.2 and 2.4 without requiring the (deprecated) apache compatibility module installed in apache.
=> Allow for apache 2.4 .htaccess "auth" rules

admin/includes/template/dashboardWidgets/tplDefault.php, includes/library/zencart/DashboardWidget/src/Logs.php
This will be good for headers or footers.  In the case of logs, the
last message was squeezed  because it didn't fit in a single column.
=> Provides ability to have full-width messages

admin/includes/functions/html_output.php, admin/includes/init_includes/init_header.php, admin/includes/template/common/tplHeader.php, admin/includes/template/common/tplMainMenu.php, admin/includes/template/dashboardWidgets/tplSalesGraphReport.php, admin/includes/template/dashboardWidgets/tplWhosOnline.php, admin/includes/template/partials/specialMenu/tplStandardLinks.php, admin/includes/template/partials/specialMenu/tplUserDropdown.php, admin/includes/template/partials/tplAdminLeadListOutput.php, admin/includes/template/templates/tplSystemInspection.php, admin/stats_sales_report_graphs.php
A few instances of the deprecated function have crept back in since the original PR.
This cleans these up and additionally, comments out the function with a view to ensure devs do not use it in the core code. This can be uncommented before releasing back into the wild and will make sure it is indeed deprecated in the core.
=> Stop use of deprecated "zen_href_link" in Admin Folder - Updates #937

admin/includes/functions/functions_crud.php, admin/includes/languages/english/orders_email.php, admin/includes/modules/orders_download.php, admin/orders.php, includes/classes/language.php, includes/classes/order.php, includes/functions/functions_lookups.php, includes/library/zencart/CheckoutFlow/src/flowSteps/Process.php, includes/modules/checkout_process.php, ipn_main_handler.php
Move queries out of `/admin/orders.php` and share them from the main `order` class, as part of data automatically queried when an order is retrieved.
=> Consolidate admin order-update/search logic into shared order class

zc_install/includes/classes/class.zcDatabaseInstaller.php, zc_install/includes/languages/lngEnglish.php, zc_install/includes/template/partials/partial_modal_progress_bar.php, zc_install/includes/template/templates/database_default.php, zc_install/sql/install/mysql_zencart.sql
This fix causes the installer to abort if there is an SQL error during install.
Fixes #528
=>  zc_install - db install errors don't halt installer #528 

includes/library/zencart/Controllers/src/AjaxDashboardWidget.php
Given that the process of adding a selected widget to the dashboard doesn't require rendering that widget until the page is ready, calling the template isn't necessary. And, since the prepared vars from the widget class haven't been loaded, the vars aren't ready for the template and thus an error is logged.  Alternate fix would be to run the `loadClass` method, but that appears to be wasted CPU activity, hence these lines are simply disabled at the moment.
=> Fix error-log on widget-install

admin/includes/functions/admin_access.php
This allows one admin to reset another's password and get them out of locked_out state.
=> Fixes #1135 Updating password resets locked_out time

includes/functions/functions_email.php
Only triggered when passing a string for the array of content to HTML emails.
Thanks to @Dave224 https://www.zen-cart.com/showthread.php?220755
=> Fix rare invalid-string-offset errors in functions_email

includes/modules/pages/payer_auth_verifier/header_php.php
Thanks @lat9 for catching these stray instances
=> Fix indirect vars for PHP 7 compatibility

includes/templates/classic/css/stylesheet.css, includes/templates/template_default/css/stylesheet.css, includes/templates/template_default/templates/tpl_modules_checkout_steps_standard.php
They don't take you to the page shown, so it's misleading to
display them as links.
=> Labels in checkout steps should not be links

includes/functions/sessions.php
It should not be used as a return value lest someone "check it".
=> session_write_close is a void function

zc_install/includes/classes/class.zcDatabaseInstaller.php, zc_install/includes/languages/lngEnglish.php
Defines were spelled inconsistently, and language file definitions were missing.
=> Fix language constants in zc_install

admin/includes/functions/admin_access.php
I now understand the function **_sess_gc()** will clean up any expired database sessions entries based on time().
The question is, if the zen_session_destroy() function call is still **necessary** in the calling stack from original code base in v160 ?
```
zen_session_name zenAdminID
zen_session_start
_sess_open /var/lib/php5/sessions zenAdminID
_sess_read o3ro312cjh4adoa5a0lsekect4
_sess_gc
zen_session_name
_sess_write o3ro312cjh4adoa5a0lsekect4
_sess_close
zen_session_name zenAdminID
zen_session_start
_sess_open /var/lib/php5/sessions zenAdminID
_sess_read o3ro312cjh4adoa5a0lsekect4
zen_session_name
zen_session_destroy
_sess_destroy o3ro312cjh4adoa5a0lsekect4
_sess_close
zen_session_name
zen_session_name zenAdminID
zen_session_start
_sess_open /var/lib/php5/sessions zenAdminID
_sess_read …
```
=> #1138 There was a security error msg NOT shown after excessive logins

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_160.sql
the current widget_key for banner statistics is incorrect (banner_statistics versus banner-statistics) causing the banner statistics dashboard widget to not display
=> fixes banner statistics widget-key in dashboard_widgets_to_users

includes/languages/english.php, includes/languages/english/advanced_search.php, includes/languages/english/advanced_search_result.php
This relocation allows the defines to load on pages other than the search page, and prevents minor PHP notices about missing constants when the js validation error text is built for those other pages.
It may unfortunately cause a bit of grief to translators of language packs. Apologies.
Closes #1257
=> Move search-validation language texts to english.php

includes/classes/order.php
Added comments to demonstrate how to specify an alternate admin-only order confirmation email template, directly in order.php class.
=> Add instructions for alternate admin order-confirm email template

includes/classes/payment.php
Ref: https://www.zen-cart.com/showthread.php?220961-collectsCardDataOnsite-payment-class-not-creating-correctly-named-hidden-fields
Thanks @lat9
=> Fix javascript selector ids for collects-card-data field

docs/changed_files-v1-5-5.html, docs/whatsnew_1.5.5.html, includes/modules/pages/checkout_shipping/header_php.php
Fix checkout_shipping: No method chosen after cart goes from virtual to mixed
Thanks @lat9
Ref https://www.zen-cart.com/showthread.php?220727-checkout_shipping-No-method-chosen-after-cart-goes-from-virtual-to-mixed
=> Fix: checkout_shipping: No method chosen after change virtual to mixed

.travis.yml, composer.json, testFramework/unittests/testsSundry/DiscountCouponsTest.php
With this, one can type `composer tests` to run the unit test suite, without needing to remember the other parameters that are required.
=> Fix broken unit test and add composer script for running tests

admin/orders.php
Add some notifiers to allow:
1) Additional action-buttons to the order-edit view.
2) Additional icons to the order-listing legend
3) Additional icons, based on the above legend, to prefix an order's listing row
4) Additional "action" icons to be added to the order's "action" column.
=> Additional order notifiers

includes/modules/payment/paypal.php, includes/modules/payment/paypal/paypal_functions.php
PayPal is enforcing changes effective January 18, 2017
=> Avoid sending a thousands-separator for PayPal Standard transactions

admin/includes/modules/prod_cat_header_code.php, admin/product.php
Product-type detection logic wasn't cascading to delete/copy modules. 
Moving it up a step, and removing the interception in products.php makes it more universal.
Ref: https://www.zen-cart.com/showthread.php?221596-product_type-incorrectly-set-in-admin-product-php&p=1323232#post1323232
=> Move product-type detection logic up a step, so it cascades to other types

zc_install/includes/classes/class.zcConfigureFileWriter.php
The constant was added in v150, so upgrades from prior versions were getting this set to blank, resulting in errors.
Ref https://www.zen-cart.com/showthread.php?221539-upgrade-DB_CHARSET-is-blank
This commit also includes same safety check for empty db-type.
=> Prevent DB_CHARSET from being set to blank during upgrades

includes/modules/payment/authorizenet.php, includes/modules/payment/authorizenet_aim.php, includes/modules/payment/authorizenet_echeck.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_139.sql
While the Authorize.net specifications indicate the transaction_id will be a numeric BIGINT value, other emulators (such as E-Processing) use string values, which trigger type errors. Changing to `varchar(32)` to accommodate this emulator anomaly.
=> Change transaction_id field for authorizenet history to varchar

includes/functions/functions_email.php
For consistency, TLS should always be port 587, and SSL always port 465.
(More and more hosts are converting to TLS, because it's way more secure than SSL.)
Also removed X-Mailer header signature, to avoid unnecessary disclosure.
Various code commenting updated/added.
Also updated related docs:
https://www.zen-cart.com/wiki/index.php/Troubleshoot_-_Email_Problems
https://www.zen-cart.com/wiki/index.php/Troubleshoot_-_Understanding_Causes_Of_Lost_Emails
=> Standardize TLS connectivity for email

includes/library/zencart/DashboardWidget/src/SalesGraphReport.php, includes/library/zencart/ListingQueryAndOutput/src/definitions/ReportStatsCustomers.php, includes/library/zencart/QueryBuilder/src/QueryBuilder.php
1. Rewrite the `select`/`having` logic for the salesgraph widget
2. Reframe the Stats-Customers report to specify the fields for `select`/`group by`, and rework the QueryBuilder to not use `*` as the `select` fields for the `main join table`, since the `groupBy` param would then need to list all those fields as well (ie: not `c.*`, but rather `c.customer_id, c.customer_gender, c.customer_first_name, c.customer_last_name, etc etc etc` in order to comply with `full group by` rules.
Closes #1213
=> Fix group-by problem in admin reports/widgets

includes/functions/functions_taxes.php
I don't actively use these tax groups but came to my attention due to "A non-numeric value encountered" notice in PHP 7.1
Effective result should be the same as the text would have evaluated to 0
=> Tax rate and description reversed for cases where there is no active tax rate

admin/includes/functions/html_output.php, app/Controllers/AbstractAdminController.php, testFramework/behat/features/bootstrap/ZenCartSpecificSteps.php, testFramework/behat/features/testFeatures/testInstaller.feature
Send emails need to be suppressed as we don't have any email environment in Behat
The deprecation of zen_href_link in admin needs to be revisited due to use of common code between admin/store
The reset install method in Behat was copying across the dist-configure which generated errors as there was then no database credentials
=> Fix some problems that cause multiple error logs to be generated

zc_install/includes/classes/class.zcDatabaseInstaller.php, zc_install/sql/updates/mysql_upgrade_zencart_139.sql
Prior to ZC 1.5.5, the zc_installer included code to process the upgrade
script from ZC 1.3.8 to 1.3.9; however, in the redevelopment for ZC 1.5.5,
operations did not include processing SQL commands such as only DROP TABLE
though DROP TABLE IF EXISTS was supported.  This code was replaced and
expanded to support DROP TABLE and DROP TABLE IF EXISTS.
Also the code did not support the SQL command of RENAME TABLE.
To support the revised code the ZC 1.3.9 sql (upgrades 1.3.8 to 1.3.9)
required minor modification as well.
No other related/earlier SQL was identified as needing this change.
Fixes #1386
=> Support table prefixes for 1.3.8 upgrade in zc_installer

zc_install/includes/systemChecks.yml
... because this field has changed and requiring it to be of the old schema may throw false errors during upgrades
=> Remove authnet test from v139 upgrade step

zc_install/includes/classes/class.zcDatabaseInstaller.php
In the upgrade sql for from version 1.3.8 to 1.3.9 as provided in ZC 1.5.5, there are a few sql queries that include an internal sql query.  When evaluating a line that reads `FROM this_table);`.  The existing code will remove the ending semicolon; however, then it considers the right parenthesis as part of the table name.  It appears that there are three potential solutions:
1) place the parenthesis on the next line.
2) add a space into the sql query file between the table name and the following characters within the sql query itself.
3) add a space into the sql query as read from the file.
This commit addresses internally adding one space at the end of the sql query as it was read from the file.  It does not consider that there might be multiple such internal queries in that one row, so …
=> Add one time right parenthesis separation

admin/products_price_manager.php
In issue #750, the price manager data entry was modified to support display
of the specials price for both gross and net costs instead of just for
one or the other.  Unfortunately in that proposal, the ability to enter
a value with a percentage was not maintained.  Today when trying to test
other operations, I realized my oversight and worked to correct it.
This commit will disregard tax differences in data entry if a percent is
entered and apply the same percentage to both fields, otherwise if the
data entered is a number, then the appropriate "conversion" as applicable
will be performed while typing.
=> Restore price manager entry of specials by percent

includes/classes/payment.php
Line is missing a closing semi-colon.
=> Add semicolon to includes/classes/payment.php javascript

includes/classes/db/mysql/query_factory.php
There are many times when a SELECT query needs to pull from the database, bypassing the cache.  The current interface is pretty clumsy:
`$db->Execute ("SELECT ...", false, false, 0, true);`
This update adds cache-bypass forms of the Execute and ExecuteRandomMulti methods.
=> Add cache-bypass forms of Execute method

admin/includes/init_includes/init_sanitize.php
The image file is not sanitized similar to the products image as well the
manufacturers_url will convert an ampersand `&` to ampersand `&amp;`.  With this
sanitization, an ampersand (for example in a URI) will not be rewritten.
This was discovered while helping out with a manufacturer plugin and is
discussed in the ZC forum at:
https://www.zen-cart.com/showthread.php?222079-Cannot-modify-header-information-headers-already-sent&p=1328124#post1328124
Although, there a different/additional sanitization was suggested for manufacturers_name to be equivalent to products_name.
=> Incorporate sanitizer code related to manufacturers.

includes/modules/payment/authorizenet_aim.php
Authorize.net AIM functionality is supported only when the site supports SSL communication with the client. The suggestion for setup in the ZC forum for a site that is to be hosted entirely by SSL is to modify the includes/configure.php file such that 1) HTTP_SERVER begins with https: and to change ENABLE_SSL to false. In the current and past versions of ZC to include version 1.5.5 and below, authorize.net AIM is disabled to the customer if ENABLE_SSL was false (not true is the actual test). This commit adds a check that if HTTP_SERVER doesn't begin with https: then if the remaining/existing checks evaluate as true that the payment module would be set to false/be disabled. This continues to support the store front side of offering payment communication securely as offered by current SSL. …
=> AIM - update module to work with https when ENABLE_SSL is set to false

includes/functions/functions_general.php, includes/init_includes/init_sessions.php
When testing to set Force Cookie Use capability, we're not passing all the parameters that are also used by the logic which sets the session cookie. This syncs them to be the same.
=> Sync parameters for setting/testing cookies

includes/functions/functions_email.php
After relocating PHPMailer files to the "vendor" folder, the language files are no longer found in the "classes/support" directory. This code change lets them be loaded from the default location instead of triggering a file-not-found condition.
=> Patch language path folder for PHPMailer

includes/classes/shopping_cart.php, includes/classes/split_page_results.php, includes/functions/functions_general.php, includes/templates/template_default/common/main_template_vars.php, includes/templates/template_default/listingboxes/tpl_listingbox_productliststd.php, includes/templates/template_default/listingboxes/tpl_listingbox_tabular.php, includes/templates/template_default/sideboxes/tpl_no_notifications.php, includes/templates/template_default/sideboxes/tpl_yes_notifications.php, includes/templates/template_default/templates/tpl_modules_listing_display_order.php, includes/templates/template_default/templates/tpl_product_reviews_default.php, includes/templates/template_default/templates/tpl_product_reviews_info_default.php
Most use of $_GET should be accessed via zcRequest ... or use other vars already sanitized by the Request class or other filters.
=> Refactor to use new request class vars instead of direct $_GET vars

includes/functions/functions_taxes.php
Resolves: `PHP Warning:  A non-numeric value encountered in /includes/functions/functions_taxes.php on line 172`
=> Fix bug: when not logged in, tax zone defaults gave string instead of zero

includes/functions/plugin_support.php
Now, by default, it will ignore any non-numeric version characters (ie: v155b will match v155e, because letters are stripped before comparing)
=> Add minor-version match specificity flag to plugin version checking

includes/init_includes/init_languages.php
Addresses an odd and rare situation that could maybe exist.
Basically, if the language selection is set to the browser, the browser
returns a language that is not installed, and if the store no longer has
a language assigned to a language['id'] of 1 (as could be seen if
installed a new language and then removed the base language).
Other than a specific/direct database edit that could cause an issue such
as a default no longer being defined or to disrupt the language table
assignment of an appropriate language_id to the default language, then this
should ensure that the language['id'] would be set if the browser does not
come back with a favorable result.
=> Assign default language in an odd/rare situation.

admin/backups/.gitignore, admin/backups/.htaccess
Add .gitignore/.htaccess to admin backups dir
This helps keep db backups out of version-control, and specifically denies unauthorized downloads.
=> Add .gitignore/.htaccess to admin backups dir

includes/functions/functions_general.php
Found while reviewing other code and seeing this new functionality.
The action taken within the function `is_coupon_valid_for_sales` did not coincide with some of the associated code comments.  These have been updated to reflect either the action or the meaning for reaching/being at that area.
=> Update internal notes of is_coupon_valid_for_sales

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_156.sql
strict schema rules don't like a "default" value on text/blob fields, including tinytext
=> Restore no-default on tinytext fields - partial reversal of #1470

includes/functions/functions_general.php
Nested arrays for get/post values are not used internally in any way that needs re-echoing to the page. Skipping them to avoid throwing false errors when bots/probers do unauthorized stuff.
Ref https://www.zen-cart.com/showthread.php?222694
=> Ignore sub-arrays in zen_get/post_all_get_params

admin/store_manager.php
Rework the `master_categories_id` reset to use original insert order, for greater accuracy during resets.
~~Stores that use 3rd-party import tools to add/delete products and categories can end up with products linked to invalid master-categories.
This new repair button finds those products and sets them to the first-found category to which that product is linked.~~
=> Store Manager - improve repair of invalid master_categories_id

includes/library/zencart/ListingQueryAndOutput/src/filters/SearchResults.php
i'm throwing caution to the wind...
it does not seem like we need field prefixes on db tables here, and in fact they are the cause of the search result errors in v160.  hard coding them here seems to be a problem.
if for some reason we want to keep these hardcoded table prefixes, then it seems that we would need to add them to:
includes/database_tables.php 
although i have not tested that.
=> fixes #1483 search results

includes/functions/functions_lookups.php
This is a modified version of the code proposal that fixes #1454.
The operation of the testing has been simplified to having only two returns instead of a series of logic "tests" of when false should be returned providing true if and only if a price `options_values_price` is identified as being non-zero, otherwise false.
=> Alternative ensurance that attributes have values

zc_install/includes/nginx_conf/ngx_server_template.txt
Previous regex would match /store/downloads/xyz.txt for instance and given position early in conf file, would be executed before the downloads folder location.
=> Negate '/' match after store folder in location regex

includes/functions/functions_general.php
zen_datetime_overlap offers the ability to identify the overlap relationship
between two provided date ranges with consideration of the frame of
reference by which to make the comparison.  Ie. should dates be compared
with concern of their overlap in the future, in the past only or an
overlap existing at all.
The function was originally considered to support the addition of specials
to a product such that it would not be possible from the admin entry point
to insert a new special that does not overlap with an existing (active)
special.  At least initially until it is determined/decided that specials
can be applied to specials for example.
This is/was also discussed in the ZC forum at: https://www.zen-cart.com/showthread.php?222038-Can-there-be-more-than-one-quot-Special-quot-for-a-product
=> Add function to identify the presence of a date span overlap

includes/modules/pages/document_general_info/main_template_vars.php, includes/modules/pages/document_product_info/main_template_vars.php, includes/modules/pages/product_free_shipping_info/main_template_vars.php, includes/modules/pages/product_info/main_template_vars.php, includes/modules/pages/product_music_info/main_template_vars.php, includes/templates/responsive_classic/templates/tpl_document_general_info_display.php, includes/templates/responsive_classic/templates/tpl_document_product_info_display.php, includes/templates/responsive_classic/templates/tpl_product_free_shipping_info_display.php, includes/templates/responsive_classic/templates/tpl_product_info_display.php, includes/templates/responsive_classic/templates/tpl_product_music_info_display.php, includes/templates/template_default/templates/tpl_document_general_info_display.php, includes/templates/template_default/templates/tpl_document_product_info_display.php, includes/templates/template_default/templates/tpl_product_free_shipping_info_display.php, includes/templates/template_default/templates/tpl_product_info_display.php, includes/templates/template_default/templates/tpl_product_music_info_display.php
Update product main_template_vars to include the buy_now_qty and template file to reference previously collected data.
Adding the result of the zen_get_buy_now_qty into the product main_template_vars removes the processing (and potential modifications necessary to support alternate processes) from the template page.  This allows the template to present the information that is needed/expected without relying on additional processing or dependency on internal functions (that may need modification to support expected/desired result).
This has also been considered as a way to solve an issue that can occur when using the product option type Grid as offered by Products attributes grid where specifically the use of units or minimum quantities are intended to only impact the individual attribute …
=> Mc12345678 remove zen_get_buy_now_qty from template (#13)

includes/modules/shipping_estimator.php
[04-Oct-2017 10:27:35 America/New_York] PHP Fatal error:  require(): Failed opening required 'includes/modules//pages/popup_shipping_estimator/jscript_addr_pulldowns.php' (include_path='.:/Applications/MAMP/bin/php/php5.6.29/lib/php') in /Users/scott/Sites/demo_160/includes/modules/shipping_estimator.php on line 24
=> Fixes debug log created when require on missing file is attempted.

includes/modules/additional_images.php, includes/modules/main_product_image.php
Applies the same notifier updates to the v160 branch as previously pushed to v156, allowing Image Handler and any large-image plugins (e.g. Fual Slimbox, ColorBox) to also benefit from the change.
=> v160 image handler

admin/customers.php
Additional notifiers used by the VAT4EU (and other) plugins to modify the admin's Customers->Customers handling.
=> v156: Additional /admin/customers.php notifiers

includes/modules/order_total/ot_coupon.php
When a coupon has been entered,
the store is not 100% https (HTTP_SERVER is not https:),
and the checkout_payment page is viewed, the page link for the coupon
information (popup link) is generated as http: only and can cause mixed
content warnings.
=> Coupon link not https/mixed content

includes/modules/pages/document_general_info/main_template_vars.php, includes/modules/pages/document_product_info/main_template_vars.php, includes/modules/pages/product_free_shipping_info/main_template_vars.php, includes/modules/pages/product_info/main_template_vars.php, includes/modules/pages/product_music_info/main_template_vars.php, includes/templates/template_default/templates/tpl_document_general_info_display.php, includes/templates/template_default/templates/tpl_document_product_info_display.php, includes/templates/template_default/templates/tpl_product_free_shipping_info_display.php, includes/templates/template_default/templates/tpl_product_info_display.php, includes/templates/template_default/templates/tpl_product_music_info_display.php
Update product main_template_vars to include the buy_now_qty and and template file to reference previously collected data
Adding the result of the zen_get_buy_now_qty into the product main_template_vars removes the processing (and potential modifications necessary to support alternate processes) from the template page.  This allows the template to present the information that is needed/expected without relying on additional processing or dependency on internal functions.
This has also been considered as a way to solve an issue that can occur when using the product option type Grid as offered by Products attributes grid where specifically the use of units or minimum quantities are intended to only impact the individual attribute selections not the overall "product".
=> Mc12345678 move function call to zen_get_buy_now_qty out of template

admin/includes/classes/box.php
Looks like this has not been used since Zen Cart 1.0 was released, and can be safely removed
It used to build the old Osc menu structure
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1549)
=> removing obsolete menuBox function

admin/includes/defined_paths.php
This missing define causes a messagestack warning when a editor is selected by default (configuration->store->HTML Editor)
This started after https://github.com/zencart/zencart/commit/a803651f9ec532cef7456b010c0b9542e1787be1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1554)
=> Add missing define for editors

includes/templates/responsive_classic/common/tpl_header.php, includes/templates/template_default/common/tpl_header.php
Adding `, HEADER_LOGO_WIDTH, HEADER_LOGO_HEIGHT` allows the defined dimensions (from language file) to control display of logo.
Fixes #1548
=> Fix incorrect use of logo image height and width in tpl_header.php

admin/login.php
These 2 tags will help a user when accessing the admin on a mobile phone or tablet.
Normally on these devices the first character will automatically be a capital. This is very annoying (to me) having to think about this every time I log in.
Also no spell check should be done.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1561)
=> add  autocapitalize="none" and spellcheck="false" to Login fields

admin/includes/functions/general.php, includes/functions/functions_general.php
Ensure that the admin versions of the functions are the same as their storefront counterparts.
Also re-factors the functions and changes the use of the deprecated "each()" function to use their foreach() equivalent.
=> zc156-Align admin zen_get_prid/zen_get_uprid, fixes #1559.

includes/application_top.php
Adds php error reporting if `DEBUG_AUTOLOAD` (used for debugging files in the `auto_loaders` folder) is turned on. 
Fixes #1557
=> Turn error reporting on if autoloader-debug is on

admin/product.php
This piece of code can be made simpler by removing the outer 'if' end 'elseif' conditions. The only thing they really do is take a pile of stuff, and split it two piles, before making the pile even smaller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1565)
=> Simplify conditions in admin/product.php

includes/classes/shopping_cart.php
In #1163, an issue with updating the cart was identified.
The solution to that issue (#1164) prevented assigning the maximum product
to the cart on update and instead would result in the last acceptable
quantity remaining in the cart instead of going "out-of-bounds".
This corrects the issue(s) discussed in those two threads by minorly
rearranging the `actionUpdateProduct` code to perform the cart decrease actions
before any cart increase actions and specifically for mixed product as
that is a situation where two or more cart products can/do depend on
each other.
Fixes #1373 for ZC 1.5.6. This was corrected for ZC 1.6.0 via https://github.com/zencart/zencart/pull/1374
=> Provide maximum product on shopping cart product update.

admin/attributes_controller.php, admin/downloads_manager.php, admin/includes/classes/AdminRequestSanitizer.php, admin/includes/functions/general.php, admin/includes/init_includes/init_sanitize.php, includes/classes/observers/auto.downloads_via_aws.php, includes/classes/observers/auto.downloads_via_redirect.php, includes/classes/observers/auto.downloads_via_streaming.php, includes/classes/observers/auto.downloads_via_url.php, includes/languages/english.php, includes/modules/downloads.php, includes/modules/pages/download/header_php.php, includes/templates/template_default/templates/tpl_modules_downloads.php
Merges #327 and #347
- added support for AWS-hosted downloads (files on AWS S3) ... simply give `aws:bucketname/filename.ext:number_of_bytes` as the filename in attributes controller or download-manager
- added support for URL-based downloads, such as Dropbox or any other http/https URL which requires no authentication by the customer (NOTE: offers no theft prevention)
- cleaned up the My Account list of downloads, for simpler styling
- changed both admin and catalog to allow observers to provide details of file availability
- moved download-by-redirect and download-by-streaming to observer class
Notes:
- If using with Dropbox, set the `&dl=0` to `&dl=1` on the "sharing link" that Dropbox gives you, so that the file is immediately downloaded for the customer.
- If sharing from Google …
=> Allow downloadable files to be hosted externally, including AWS

includes/functions/functions_prices.php
In several of the price functions, both the special and sales price is sought.
Both are obtained through the same function `zen_get_products_special_price` with a switch to either return only the specials price (true) or to return the overall special price (false) (sale price if present otherwise special price if a special, and false if neither)
If a product is not on special and does not have a sale then the returning result is `false` and therefore there is no further determination of the special necessary (ie. no further database query needed). If the result is anything other than `false`, then there may be a special and the value of that special (if present) remains to be determined.
While there remain other means of gaining efficiency in this process (such as returning all data …
=> Reduce db queries for prices

admin/attributes_controller.php
Add notifiers in the admin/attributes_controller related to adding attributes to identify that an attribute has been added or updated and to provide the products_attributes_id of that attribute.
=> V156 Add Notifier to Attributes Controller

admin/includes/functions/functions_prices.php
The catalog and admin includes/functions/functions_prices.php files have the same function (zen_get_attributes_qty_prices_onetime; however, it has been implemented differently between catalog and admin and during strict testing/operation a debug log would be generated.
=> More aligning admin zen_get_attributes_qty_prices_onetime with catalog

admin/includes/attributes_preview.php
Changes have been made to the store side attributes display file but have not been carried over to the admin "equivalent".  This aligns them.
=> Under review: Align admin attributes_preview with catalog

includes/classes/order.php
Allows an observer to make last-minute updates to the order's address/tax information before the products' pricing.
=> Additional order-class notifier

includes/classes/categories_ul_generator.php
The global $language_id is unused and removed.
Replaced the tab with spaces
Cleaned up the sql query, by removing unnecessary characters and aligning lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1589)
=> ZC156: remove unused global, and replace tabs with spaces

includes/languages/english/button_names.php, includes/languages/english/checkout_success.php, includes/templates/template_default/templates/tpl_checkout_success_default.php
Instead of making the language-string contain tiny text-only links, add specific obvious buttons so people know how to take action.
=> [v156] Add MyAccount and ContactUs buttons to checkout-success page

zc_install/ajaxLoadMainSql.php, zc_install/includes/EXAMPLE_custom_settings.php, zc_install/includes/admin-configure-template.php, zc_install/includes/catalog-configure-template.php, zc_install/includes/classes/class.zcConfigureFileWriter.php, zc_install/includes/classes/class.zcDatabaseInstaller.php, zc_install/includes/cli_controller.php, zc_install/includes/languages/lngEnglish.php, zc_install/includes/modules/pages/database/header_php.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_156.sql
Note: the cases where the field length was changed instead of the index are either primary keys or fields whose length can afford to be shorter.
Supporting 256 chars in db requires MySQL 5.0.3 or newer.
=> Core schema changes to accommodate utf8mb4 index length limits

admin/orders.php
Allows an admin observer to include its additional "legend" icons and add to the left-hand legend-icons on a per-order basis.
=> Additional admin/orders notifiers

admin/whos_online.php
fixed url construction for options from v155 style to new in v160:
old:
admin/whos_online.php
new:
admin/index.php?cmd=whos_online
=> [v160] Fixes #1611 URL construction in whos online

admin/languages.php
These three queries can be simplified. The selection of the id can be
done in the same table as the selection of name/description.
This reduces load on the database significantly. For the categorie
table, with the default demo categories, from 0.0018 to 0.0005 seconds.
This is over 3 times faster.
Old Query:
New query:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1626)
=> Simplify queries on creating a new language

includes/modules/pages/checkout_payment/header_php.php
The checkout_shipping process is expected to support moving on through
the checkout process if a shipping method is identified. If
$_SESSION['shipping'] is set to false through a call to $shipping->cheapest()
where the only available shipping method is instore (or whatever else has
been set to be ignored in that class), then a shipping method will not be
forced if the URI is then entered to goto checkout_payment.  The same is true
in the current configuration if all shipping methods are disabled or there
are no shipping methods defined.  (That it be possible to continue through
checkout without ever having selected a shipping method nor one being
available.)
=> Force return to checkout_shipping if shipping method not selected.

admin/includes/extra_configures/enable_error_logging.php, includes/extra_configures/enable_error_logging.php
Due to the way that the log records are currently formatted, it's sometimes "difficult" to connect the actual error to the backtrace information.  This change modifies the formatted output, grouping the debug-backtrace information with the PHP information, making it easier to debug/determine what's going on.
Also includes some re-factoring.
=> v156-Enhance log formatting

admin/configuration.php, admin/modules.php
The message "Warning: 0 weight is configured for Free Shipping and Free Shipping Module is not enabled" is intended to warn the admin that the setting _Configuration->Shipping/Packaging->Order Free Shipping 0 Weight Status_ is enabled but the `freeshipper` shipping module is not enabled.
Unfortunately, the message does **not** currently appear if `freeshipper` is installed but disabled.  This PR makes that correction in both the admin's configuration.php and modules.php scripts.
=> Zero-weight/freeshipping Admin Alert might not appear

admin/includes/functions/general.php, admin/includes/functions/html_output.php
This change handles the changes needed to get the input fields styling
inline with the updated layout of the configuration pages etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1649)
=> Add form-control markup to Admin input field helpers

includes/modules/additional_images.php
Add to the link-creating notification, allowing an observer to inject not only the to-be-displayed link but also the parameters used in that rendering.
=> v156-additional-image-notifiers

admin/customers.php
Align the v156 admin Customers->Customers notifiers with those present in the `develop` branch; includes minor reformatting.
=> #1651-v156-admin-customers-notifiers

admin/customers.php, includes/functions/functions_customers.php
Align the `develop` branch to provide the same notifications for Customers->Customers processing as the v156 branch.  Note that some functionality has been moved to the storefront/common functions_customers.php module.
=> #1651-dev-admin-customers-notifiers

includes/functions/functions_lookups.php, includes/functions/functions_prices.php, includes/functions/functions_taxes.php, includes/functions/html_output.php
Add notifiers to various "base" functions, enabling observers to modify (or in some cases replace) those functions' processing and return values.  This will enable many plugins to remove the need for core-file overwrites, allowing for an easier Zen Cart upgrade path.
Please note that many of the notifier strings are in use by various plugins; please don't change the names and/or "payload".
=> v156-notifiers-for-base-functions

includes/modules/payment/firstdata_hco.php
As identified in this forum thread:
https://www.zen-cart.com/showthread.php?223791-Payeezy-HCO-HASH-error
payments appear to be collected; however, not recorded in ZC because
the hash value comparison does not pass.  Per technical support when
performing the hash comparison, the total price of the purchase is to
be incorporated into the hash with two decimal places applied.
The current code will round to 2 decimal places but if the value ends with
a zero, then that zero is dropped from right to left up to the decimal
point. This corrects that specific comparison.
=> Correct FirstData HCO price hash comparison

includes/classes/categories_ul_generator.php
When a category has no siblings, $this->data[$category_id] is not set
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1675)
=> Undefined offset $this->data[$category_id]

includes/classes/payment.php
php is complaining about not used modules.
PHP Notice:  Trying to get property of non-object in /includes/classes/payment.php on line 172
PHP Notice:  Undefined index: freecharger in //includes/classes/payment.php on line 172
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1676)
=> Trying to get property of non-object in /includes/classes/payment.php

includes/functions/functions_taxes.php
Add a notifier to the `zen_get_tax_locations` function, enabling an override.  Enables "Edit Orders" (and possibly other plugins) in admin-side order reconstruction.
=> Add zen-get-tax-locations-notifier

includes/templates/responsive_classic/sideboxes/tpl_information.php
Haven't reviewed past installations to determine how this came to be different; however, the maximum was to be compared against `$j` instead of `$n`. That said, almost wonder if foreach should be used instead.
=> Fix error found during review for strict errors.

includes/modules/additional_images.php, includes/modules/main_product_image.php
Since some plugins incude the image-related modules in a function context, need to "globalize" the use of the $zco_notifier object.
Fixes #1687
=> Globalize zco_notifier for image modules

admin/includes/init_includes/init_languages.php
Update the languages' initialization script to use `is_file` instead of `file_exists`.
=> #1697-v156-correct-cron-warning

admin/developers_tool_kit.php
If item sought is near the end of the file and the search attempts to view more lines above and below the found line, then the default store would attempt to find data beyond the length of the file and result in a strict PHP notice, this corrects that issue.
=> Prevent exceeding length of file search developers toolkit.

admin/includes/functions/general.php
- added  a dash and spaces between the categorie name and id
- clean up query -> removed single quotes 
- used foreach in favour of while loop
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1706)
=> Add dash and spaces to admin categories pulldown for readability

includes/classes/order.php
Casting the value as float prevented some php 7.1 error logs
=> Make order shipping_cost float 

admin/includes/extra_configures/stats_sales_report_graphs.php
…es.php
That definition is not needed on the admin side because of its equivalent catalog definition.
Found via strict related reporting where reporting was set to not report this type of issue; however, still came through for some reason.  Removing the define on the admin or conditionally defining it on the catalog side resolved the issue.
=> Remove duplicate define for sales-report-graph

admin/coupon_restrict.php
The array key is missing the single quotes around the word "text". It is apparently now a major bug, as the code also seems to work fine without them. So no need to fix in earlier versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1709)
=> Add missing quotes to array key in coupon_restrict

includes/modules/checkout_new_address.php
... so it's preserved over the notification, assuming that an observer is likely to be performing additional database actions of its own.
Fixes #1711
=> Preserve address_book_id through notification

includes/templates/responsive_classic/common/html_header.php
Check for jquery in current template before attempting inclusion
If this still fails, pull from template_default.
=> Add extra fallback check for jquery inclusion

includes/classes/db/mysql/query_factory.php
In ZC 1.5.5, the iterator class was implemented allowing the use of foreach
to cycle through query results.  To support this operation, the rewind
module was written to use the Move($position) method which was written to
allow query results to be returned as both a key=>value response as well
as a position=>value response.  Therefore, the initial reset of the query
results would produce an array of both the key=>value pair and position=>value
pair.  Then when the MoveNext method was used, the key=>value pair would
be updated; however, the position=>value pair remained constant.
This commit adds continued support for code that intentionally used the
Move($position) to access the integer based field result and to also
prevent adding the integer based results to the Move($value) method …
=> v156 Remove integer key data from iterator results

admin/attributes_controller.php
Attributes were not saved properly due to missing product_id, current_category_id, and attribute_id. also see #1673, #1531, #1511
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1720)
=> Fix missing product_id, current_category_id, and attribute_id

zc_install/ajaxTestDBConnection.php
Attempted install from scratch with admin/includes/local/configure.php containing 
define('ADMIN_BLOCK_WARNING_OVERRIDE', '1');
This breaks the install, but no error is given because the installer is looking at `$errorList['newDatabaseCheck']` which is not set.
=> Show errors created during db test connection

zc_install/includes/languages/lngEnglish.php, zc_install/includes/template/templates/index_default.php
The install index page always says there are issues even when the only thing that shows up is a 'Pro Tip'. This PR adds logic to only show the header saying there is an issue when there are actual issues itemised as opposed to tips.
=> [v156] Refine Error Heading Display

admin/includes/init_includes/init_html_editor.php
I'm the maintainer of the tinymce plugin.  It comes in a folder without an underscore.  Removing the underscore from the main code will make things a little easier to maintain.
=> removed underscore from tiny_mce

includes/functions/plugin_support.php
the array $data['error'] itself can be an array, a boolean, or text.
The use of print_r outputting as text will allow the full set of data
to be pushed which in this case is a triggered error.
=> Modify handling of version check errors to provide text only results

includes/modules/pages/document_general_info/main_template_vars.php, includes/modules/pages/document_product_info/main_template_vars.php, includes/modules/pages/product_free_shipping_info/main_template_vars.php, includes/modules/pages/product_music_info/main_template_vars.php
While reviewing product types for potential strict reporting issues,
identified that other product types did not appear to properly capture
the $products_manufacturer information which led to other aspects in
need of update.
=> Align product type code across all types

includes/functions/functions_customers.php
Remove a strict notice from zen_address_format and other in file cleanups.
While addressing the strict notice report also adjusted sql statement(s)
to form the sql statement to not have quotes when assigning integers.
=> Remove extra quotes from integers in address lookup query

admin/includes/modules/document_general/collect_info.php, admin/includes/modules/document_product/collect_info.php, admin/includes/modules/product/collect_info.php, admin/includes/modules/product_free_shipping/collect_info.php, admin/includes/modules/product_music/collect_info.php
As part of the new product management admin design, the specific file
for each product type has been removed.  To move forward in processing
non-basic product types, the associated form needs to redirect to
an existing "controller" which is the FILENAME_PRODUCT location.
Fixes #1747.
=> Push page direction after initial view to next page.

includes/modules/payment/paypalwpp.php
In my cart, the redirect is failing which means the customer sees a blank page with no message.  This just adds the message in.
=> Show message on die in case zen_redirect fails

email/email_template_checkout.html, email/email_template_contact_us.html, email/email_template_default.html, email/email_template_gv_queue.html, email/email_template_gv_send.html, email/email_template_low_stock.html, email/email_template_password_forgotten.html, email/email_template_welcome.html
Styling exists for this block in email_common.css but it was not applied in any of the templates.
=> Use styling the $EXTRA_INFO block

includes/classes/vendors/PHPMailer/PHPMailerAutoload.php
The _autoload function has been deprecated in PHP 7.2.x, unfortunately this
file is associated with a larger project, but in PHP 7.2.x this caused an
issue.
=> PHPMailer 5 handler backward-compatibility break

admin/includes/modules/document_general/collect_info.php, admin/includes/modules/document_general/preview_info.php, admin/includes/modules/document_product/collect_info.php, admin/includes/modules/document_product/preview_info.php, admin/includes/modules/product/collect_info.php, admin/includes/modules/product/preview_info.php, admin/includes/modules/product_free_shipping/collect_info.php, admin/includes/modules/product_free_shipping/preview_info.php, admin/includes/modules/product_music/collect_info.php, admin/includes/modules/product_music/preview_info.php, admin/product.php
…fication.
In #1736, the admin/product.php file was modified to assign the product
type based on first the url containing an assigned products_id (pID), and if
that is not present, then to pick up on a posted value (product_type).
Then in #1747, the problem identified was that it was not possible to
transition from a non-basic product type to the preview of information.
The solution proposed supported previewing information; however, because of
the above logic and posting the data instead of clicking a link, the
product type defaulted to a standard product in admin/product.php.
This works for product that have already been assigned/created and for the
first click from the categories_to_products listing to create a new product.
However, a product's id is not assigned until the product is …
=> Pass product_type as form field with product collect_info.php

includes/functions/functions_taxes.php
The missing global gave a fatal error on making an order
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1780)
=> fix missing globals

admin/category_product_listing.php
Saw this code section that looked like it could use "improvement".  I haven't asked anyone if there is/would be problems with others code caused by making this change instead of just leaving it alone.  Looked liked something that could be improved upon and so I changed it.
There is duplication in the code to identify the product types that can be removed by reworking some of the variables and operations.  The effect of this modification is that there is no longer a variable created called `$product_types_array` that would only exist if there were no product restrictions, there is no longer a specific variable generated `$restrict_types` to identify the specific restricted product types (or absence of them).
Also applied the PHP 5.6+ use of `[]` for array declaration instead of `array()` …
=> Revise product type check

includes/classes/db/mysql/query_factory.php
In #1633, there had been some ideas proposed, one of which was to
add a parameter to the call to the Move method that would specifically
rewind the query results and not offer the integer based field keys.
The functionality within the Move method was basically returned to its
previous state and the additional parameter was identified as unnecessary.
This removes the parameter and associated comment for "cleanliness".
=> Remove unnecessary code from refactor of Move in method rewind

admin/includes/functions/general.php
Back in what looks like #92, a statement was added to
admin/includes/functions/general.php within the zen_products_lookup
function to test if the database query resulted in no results by
checking for the End Of File (EOF) flag being set true.
It appears though that the wrong variable was tested.  The
current value tested is the lookup_field's result which has not
yet been processed to give an EOF style answer.  It would
seem that instead the product_lookup query result should be used
and if that result is at the EOF, then to return an empty quote,
otherwise return the desired field.
That said, the visual logic could be improved such that if there are no
values to be returned then there is no need to assign $return_field to
anything and that it could be moved outside.
=> Refactor zen_products_lookup()

includes/modules/pages/download/header_php.php
As @mc12345678 so kindly pointed out on the OPC repo (https://github.com/lat9/one_page_checkout/issues/151), there's a discrepancy between the `includes/modules/pages/download/header_php.php` provided by the plugin and zc156 (on which the plugin's downloads-handling is based).
That is due to the fact that the zc156 repo's version of the module hasn't been updated to provide that handling, which this PR corrects.
=> Downloads: Redirect to timeout using SSL

admin/attributes_controller.php
Appears that in the rebuild of the attributes_controller that a variable
was written out incorrectly ($products_options_array was used instead of
$products_options_query). Based on further search of the file and
the just-in-time application of the code, this commit appears to be the
best/right fit for this issue that had thrown warnings while in strict
mode.
=> Fix refactor error in attributes_controller

admin/includes/modules/update_product.php
$_GET['product_type'] is empty, and $_POST['product_type'] is passed from the preview page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1791)
=> Fix refactoring: Replace $_GET['product_type'] with $_POST['product_type']

includes/classes/db/mysql/query_factory.php
While attempting to identify the cause, path, and history of queries
in a plugin, I found it necessary to identify the source of the
query(ies) beyond what is provided by the default logging.  At one point
I had corrected a relatively obvious source, but in so doing I lost any
additional markers of the flow path.  Adding the backtrace information
to this log (location within output is welcome to be moved as necessary)
greatly added useful information.
While such logs are already lengthy, this has been incorporated at the
moment as a feature that can be enabled by adding a constant and defining
it to not be falsey.  If this feature is considered accepted then I think
that in the logging section of the configuration menu, it would be worth
adding an additional option to include this data …
=> Support adding debug backtrace data to DB Transaction log

zc_install/includes/classes/class.systemChecker.php, zc_install/includes/classes/class.zcDatabaseInstaller.php, zc_install/includes/systemChecks.yml, zc_install/includes/template/templates/index_default.php, zc_install/sql/updates/mysql_upgrade_zencart_156.sql
Note - in the SQL updates, the parser requires a space to exist after a tablename, so it can't be followed by just a closing-parenthesis `)`. Must have a space first.
=> Fix strict errors in zc_install

admin/includes/auto_loaders/config.core.php, admin/includes/languages/english/extra_definitions/orders_status_updates_admin.php, admin/orders.php, includes/auto_loaders/config.core.php, includes/functions/functions_lookups.php, includes/functions/functions_osh_update.php, includes/functions/html_output.php, includes/languages/english/extra_definitions/orders_status_updates.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_156.sql
Updates to a couple of storefront function files to include similarly-named functions to those available in the admin.  This allows the actual function for this processing to be used in both admin and storefront environments.
=> Add updated_by tracking to orders status history

includes/modules/pages/address_book_process/jscript_addr_pulldowns.php, includes/modules/pages/checkout_payment_address/jscript_addr_pulldowns.php, includes/modules/pages/checkout_shipping_address/jscript_addr_pulldowns.php, includes/modules/pages/create_account/jscript_addr_pulldowns.php
As noted in https://www.zen-cart.com/showthread.php?224511-Configuration-gt-Customer-Details-gt-State-Always-display-as-pulldown, the element id `stText` was removed in 1.5.5, which causes javaScript errors (which in turn breaks the correct selection of the state).  This fix checks for the existence of the element prior to updating it, so the selected state now appears in the dropdown.
To test, you must first set admin->configuration->customer details-> State - Always display as pulldown? to true.
=> Ensure element stText is present in DOM prior to updating

admin/includes/languages/english/server_info.php, admin/server_info.php
Showing the name of the database currently in use by Zen Cart in the version check is a nice timesaver for clients who have many databases in their account.
=> Display name of database in Version check

includes/classes/site_map.php
And $load_from_database = true can probably also be removed as it is also unused.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1834)
=> remove unused variable $languages_id in site-map

includes/modules/pages/contact_us/header_php.php
- Adjusted the spacing/alignment of code, though only to two spaces each.
- Applied PHP 7.x style array handling changing from `array()` to `[]` in all instances.
- Reworked the generation of `$send_to_email` and `$send_to_name` to remove the dependency on the source email from having the format of: `NAME TO DISPLAY <email@address>` where if the section of `<>` was missing then no email would be sent and a debug log would likely be created.  This modification generally expects that a proper email address has been entered in either `EMAIL_FROM` or `CONTACT_US_LIST`.  There is no change to the presence/absence of a validation check of the email address being properly entered.
- Converted use of logic and to && and added parentheses to maintain historical identification and clarity of the …
=> Refactor Contact_us header_php.php

includes/functions/functions_taxes.php, includes/modules/order_total/ot_coupon.php, includes/modules/order_total/ot_shipping.php
functions_taxes.php: Allow override of zen_get_tax_rate return value.
ot_coupon.php: Indicate that the coupon processing is starting and then, for each product, notify whether/not the product qualifies for the discount.
ot_shipping.php: Allow override of the shipping tax, since it can vary from one location to another.
=> Additional tax-handling notifications

includes/classes/upload.php
"File too large" failure messages not appearing during admin product edit.
=> Fix error messages from upload class when used by admin

includes/modules/ezpages_bar_footer.php, includes/modules/ezpages_bar_header.php, includes/modules/sideboxes/ezpages.php
Some of the prior refactoring of while-not-eof code to foreach evidently was incomplete, leaving some `->fields` references behind.
=> Fix prior refactor of ezpages modules

includes/functions/functions_email.php
While this undocumented constant is rarely used, changing its purpose may have unexpected side effects for dev environments.
Now if `DEVELOPER_OVERRIDE_EMAIL_STATUS` is defined as `'false'` then it will abort sending any emails initiated by `zen_mail()`.
Note that it must be defined separately for admin and catalog, usually in an extra_configures file.
Closes #1850
=> Improve undocumented developer override of email status

admin/configuration.php
Only show the first 40 chars of a long config value so screen won't get messed up.
=> Shorten display of long config values

admin/includes/functions/general.php
Function accidentally removed during refactoring.  Required back to fix #1823.
=> Add back missing function

includes/modules/shipping/perweightunit.php
Ref: https://www.zen-cart.com/showthread.php?223895-PHP-Warning-A-non-numeric-value-encountered-in-perweightunit-php-on-line-105&p=1350948#post1350948
=> Typecasting for perweightunit

admin/includes/stylesheet.css
This margin in interfering with the look of button-groups, like on the orders page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/1877)
=> Remove extra margin on buttons

admin/product_types.php
Logic depends on having `$_GET['ptID']` unset; initializing it introduced problems.
=> Product types does not show a default right hand side window

admin/salemaker.php
The more info link (displayed when a category is already contained in other salemaker sales)
was enclosed inside the checkbox class. This meant clicking on the more info link would toggle the checkbox state.
Have moved it to its own column. While the css may not be perfect, think this is good enough just for release
=> fix more info link on salemaker

includes/modules/pages/checkout_payment/jscript_square.php
If the Square payment method is enabled, but not loaded (e.g. the 'freecharger' payment method is active) or if Square has zone restrictions (and the current billing zone is outside of the restrictions), don't load the payment method's jQuery processing, since it will "pollute" the jQuery pool.
=> zc156: Square jQuery no-load

admin/includes/languages/english.php
Embedded carriage return means message is not properly formatted on mobile.  Carriage return not required; works fine without it.
=> Embedded break tag not needed

includes/modules/ezpages_bar_footer.php, includes/modules/ezpages_bar_header.php, includes/modules/sideboxes/ezpages.php
Initializing these variables prevents myDebug-xxx.log files related to "PHP Warning: sizeof(): Parameter must be an array or an object that implements Countable" for ezpages headers, footers, sideboxes and mobile-menus.
Ref: https://www.zen-cart.com/showthread.php?224723-Parameter-must-be-an-array-or-an-object-that-implements-Countable
=> Prevent ezpages "countable" warnings in logs

includes/auto_loaders/config.core.php
script has a language dependancy for DATE_FORMAT_LONG
it may be that the line with the dependancy could just be removed
but for now just easier to change loading order to after language stuff is initialized
=> change loading order for init_counter

admin/includes/classes/class.admin.zcObserverLogEventListener.php
I have seen this fail when the string was too long.
=> check length of attention field before inserting into db

testFramework/unittests/testsSundry/AdminLoggingTest.php
#1928 added a call to `zen_field_length`, which caused problems for unit checks.   Fixed by mocking return value.
=> Fix unit test issue introduced with use of length check

admin/includes/init_includes/init_category_path.php
Generally speaking, it seems that when given the opportunity to read
something from the uri and from the posted page data, that the information
to keep/capture should come and normally comes from the posted page data.
As such, this commit modifies the sequence of testing to assign the `$cPath`
on page load such that a modification to the page's uri would not affect
the cPath.
=> v156 post before get on cPath assignment

admin/product.php, admin/stats_sales_report_graphs.php
Without the fixes in this PR, scripts appear above the opening <head> tag. 
Thanks to @Zen4All for reporting this bug.
=> These files have the original incorrect ordering of headers

includes/classes/order.php
EMAIL_TEXT_TELEPHONE doesn't get populated to email template.
This change fixes it.
=> Missing EMAIL_TEXT_TELEPHONE in order email

zc_install/includes/classes/class.zcDatabaseInstaller.php, zc_install/sql/updates/mysql_upgrade_zencart_156.sql
There have recently been multiple posts to the ZC forum about the upgrade process not completing successfully even though the screen message alludes to everything being done.  While some of the issues appear to be related to date or datetime fields having '0000-00-00' stored in them (beyond the date_modified field already addressed) also identified a few items as captured in the comments for each commit of this pull request.  One of the issues was that the sql statement to left join a table did not account for the `DB_PREFIX`.
EDIT: Recommend a method to evaluate the table data stored to see if the table's field definition is date or datetime and then if it could support a value of `0000-00-00` and if not then to modify the value either to `null` (if supported) or `0001-01-01`, though …
=> V156 zc install - add parser for left join queries

includes/classes/shopping_cart.php
Wrong parameters passed. 
As reported by @lat9 at: https://www.zen-cart.com/showthread.php?224245-Shopping-cart-class-invalid-function-parameters
=> Fix price-onetime function call parameters

includes/templates/responsive_classic/templates/tpl_ajax_checkout_confirmation_default.php
For payment methods which invoke the ajax in-page confirmation HTML swap, the normal "reload the page and position to the top" doesn't occur, thus leaving the customer looking at a lower (possibly suddenly blank) section of the page (where they were entering card details and clicking a submit button).
This update causes it to scroll to the top after the page content is updated.
=> Add scroll-to-top on ajax confirmation page

includes/functions/functions_categories.php
Because of this, it's impossible to descend into subcategories.
=> Fixes #1991 - cPath not set when categories page first drawn

admin/includes/stylesheet.css
Bootstrap collapses the tables borders, however they are reset on zencart css
In my opinion, they look better with collapsed borders. 
+others :
**TH** elements already are set to bold, so font-weight bold for dataheadings could be removed from the css file. 
The **H1** is set to be 16px by zencart css, however **H2** is set to 30px by bootstrap. Visually is not pretty. Example: the H4 on side box are 14px ... 2px less than H1.
Of course none of this is actually urgent but, I guess with time it could be altered. 
Or not.
=> Propose Update on admin css tables borders +others

admin/includes/languages/english/product.php
The products page in Admin->Catalog->Categories products needs this
define.
=> Admin define TEXT_IMAGE_NONEXISTENT missing in product.php

admin/languages.php
Since the ez-page are now multilingual, the new table should also be updated when adding or removing a language
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2012)
=> Add extra sql queries for ez pages during language deletes

zc_install/includes/systemChecks.yml
Without this fix, the 1.5.6->2.0 upgrade does not work; thinks it is still needing 1.5.5->1.5.6. 
Upgrade to version 1.5.6 completed.
Could not update to version 1.6.0. We detect that you currently have v1.5.5, and must perform the updates to get to version 1.5.6 first.
=> Correct field type in zc_install check, allowing upgrade to complete

admin/specials.php
Attempting to cast as `int` a non-existent $_GET parameter caused a
notice to be logged.  This uses the empty to circumvent the
casting if the value is set to a falsey value; however, still
kept the `int` cast because if the expectation was that `'manual'`
could be text and the desire was to evaluate that when cast to
an integer it is 0, then take a particular action.  I am not
familiar with that parameter so did not want to remove it and
its evaluation without further discussion.
=> v156 admin/specials.php strict notice $_GET['manual'] not set

admin/define_pages_editor.php
Addressed identified strict operations notices received while
maintaining operability with PHP 5.6 as some options may be
modified to a PHP 7.x style detector/selector.
=> v156 - admin/define_pages_editor strict notices and PHP 5.6

app/Model/ConfigurationSettings.php, app/Model/ConfigurationSettingsToWidget.php, app/Model/DashboardWidgets.php, app/Model/DashboardWidgetsToUsers.php, app/library/zencart/DashboardWidget/src/WidgetManager.php, includes/database_tables.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_160.sql
The intention is that in the future we can re-use the configuration
settings table as part of the overall configuration system, and not just
for dashboard widgets.
=> Renaming some tabled/models for configuration settings

admin/includes/functions/general.php
Identified by a self-implemented coding error that attempting to
access this function with a non-existent products_id caused a
mydebug notice (in strict mode) to be logged for
`$check_products_category->fields['master_categories_id']`
not existing.  Execution continued apparently, but it seems that
it could be improved.  Also removed the text casting quotes around
the values and ensured each were cast as an integer.
=> Refactored zen_get_categories_name_from_product.

admin/ezpages.php
It is possible that $page_error could be set to true but then
set to false while looping through the languages. This removes the
$page_error variable being set to false to outside of the loop.
=> Admin - initialize error variable in ezpages manager

admin/includes/init_includes/init_templates.php
Check for the string "Admin" at the start of the name before adding it as a prefix.
=> Prevent "Admin Admin" from being in a page title

zc_install/sql/updates/mysql_upgrade_zencart_156.sql
It seems that in the "code" that processes the update sql that there is some benefit in knowing the status executing the sql queries.  When a query is written over multiple lines, log reporting does not occur if the processing code is not told to expect multiple lines.
This adds a multiple line notification to all queries that extend over multiple lines for the ZC 1.5.6 update sql.
=> Add additional reporting for multi-line queries

includes/classes/order.php
When in this arrangement $customer_address, $shipping_address, and
$billing_address are undeclared.  This means that every field
of $this->customer, $this->delivery, and $this->billing would
need to be assigned to a "default" value.
I thought that this had been proposed previously as in with #1952.
=> Not logged in, product in cart, strict processing and shipping estimate

admin/includes/languages/english/product.php
This was a leftover from my Cittins module, which should not be in the core file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2069)
=> Remove extraneous plugin defines

includes/modules/payment/authorizenet.php, includes/modules/payment/authorizenet_aim.php
NOTE: This still uses their legacy MD5 Hashing approach.
NOTE2: The ability to configure an MD5 Hash keyphrase in the merchant's Authnet account is disappearing end of Jan 2019, and the new SHA code will be required instead.
(Existing MD5 keyphrases will still be supported until "a date not yet determined")
=> Update Authorize.net modules to use hash_hmac hashing for HMAC

includes/classes/shipping.php
testing `empty()` v `!is_array()`.  empty seemed to work fine.
i would love to get all files into unix line feeds as opposed to windows....  but it seems so easy for me to screw things up in git.  so apologies about the line change on the time stamp.  i blame my IDE!
=> addresses error when shipping module comes back w empty response

admin/includes/keepalive_module.php
i have tested and verified this works...  it creates the camefrom url with 1 `?` and then uses the `&` for seperating parameters.  it also trims the last `&`.
as @Zen4All previously commented on, the `<?=` directive is NOT affected by the short tag being turned on or off since php 5.4.  so i opted to not change all of that code and leave it as is....  which seems clean to me.
in addition, i did move the `'` for the camefrom var to outside of the `$camefrom` as suggested by @drbyte and being consistent with the existing code.
=> Change keepalive loginURL to camefrom v index on timeout

admin/includes/functions/general.php
Recently a forum member identified a problem with ZC 1.5.6 where an error was thrown I think on line 208 indicating that parameter 6 was expected to be an integer; however, a string was provided.  Now that I have had a look at the software on a larger screen, it appears that the issue stems from `$year` not being cast as an integer.
=> Cast the year in zen_date_short to int

admin/includes/functions/general.php
I have been trying to track down how a `date` field in a plugin ended up being stored with `0000-00-00` and at least the last place where assignment was made, a Zen Cart date function was used in a similar manner as other `date`/`datetime` functions.  Looking into the associated admin date functions, it appears that if the `datetime` of `0001-01-01 00:00:00` or an empty string (possibly by loose comparison) was fed into the functions then false is returned; however, there is no similar review/response if the result were `0000-00-00 00:00:00` which at least currently for `date` and `datetime` fields is considered to not be acceptable.
Perhaps a similar review should be done for a year of 1, month of 1, day of 1 and empty for the other three fields. Reason? A `date` field may have …
=> Return false from date functions evaluated to 0000-00-00 00:00:00

admin/includes/modules/document_general/collect_info.php, admin/includes/modules/document_product/collect_info.php, admin/includes/modules/product/collect_info.php, admin/includes/modules/product_free_shipping/collect_info.php, admin/includes/modules/product_music/collect_info.php
Fix a typo in the class.
conrol-label should be control-label
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2103)
=> Correct css class typo in admin product-type collect_info screens

admin/includes/functions/functions_prices.php, includes/functions/functions_prices.php
Identified in https://www.zen-cart.com/showthread.php?224923-Attribute-pricing-display-all-fouled-up, if a product is `priced by attribute`, the default resulting price (of each attribute) included the `products_price`.  Removing the `products_price` from the attribute price response restores the previous default functionality; however, doing that for all situations causes the result of the name of this function (`zen_get_attributes_price_final`) to not be possible.  Added a parameter that defaults to the historical ZC response of not including the `products_price` in the final result.  This solution resolved the observed condition and may maintain the overall desired resolution made by pull #1404.  If not, then the subtraction/addition should be that of zen_get_discount_calc without the …
=> v156 correct display of attribute price for priced-by-attribute

includes/classes/order.php
Currently, the address shown as the delivery address for an order to be shipped using Store Pickup is the customer's default address.  This is misleading.
=> Do not show home address as delivery address for pickup orders

admin/developers_tool_kit.php
Address other strict notifications when searching not using the last row of search options.
A convenient debugging tool had been added that allowed the
display of lines above and below the line that contains the
result; however, if any other search tool option is chosen
from the screen, then no default set of values is identified and
in strict php processing a notification is made.  This at least
supports defaulting to a sanitized value of the $default_context_lines
when the context_lines are not otherwise provided.
=> Fix PHP strict error in developers toolkit search

admin/salemaker.php
javascript function session_win1 seemed to not be
referenced/used and was causing a strict notification related to
the non-existent variable $category.  Couldn't find where it
was expected to be defined, so commented it out.
The remainder address notification messages received while PHP
strict mode enabled.
=> Strict notification addressing on admin/salemaker.php

admin/salemaker_popup.php
Chasing down a strict notification when viewing the salemaker popup
noticed that after application of this fix ($deduction_type_array
not defined), the type of discount for the sale was shown instead
of being blank.
=> Deductions dropdown in salemaker popup

includes/classes/shipping.php
In #2078 and then in #2104, an evaluation was added to prevent further processing of the current shipping method if that method did not provide quotes when determining method offering the cheapest rate.  The initial solution exited the `cheapest` method without allowing the class method to evaluate any valid collected data. 
I then, without recognizing that the action response of leaving the `foreach` by *any* method would prevent further shipping module processing, suggested a `break` so that at least the remaining code would be processed.  Considering that the goal of the `cheapest` method is to provide a result based on all available methods and with a lot of additional work outside of the method the result could be obtained, operating the method in this way is sub-optimal.
This …
=> Cheapest method of shipping class should move to next method when method has no quotes

admin/products_to_categories.php
Correct one mistake made in #1604 of the 7,700 additions and 10,077 removals.
Returns the admin user to the category list showing the product in question.  If the product is in the first page then the entire category is displayed with the product in the list, if the product is in a subsequent page, then just the product is displayed. (Separate issue?)
=> Direct Details button to product's category product listing

admin/coupon_admin.php
Total Github newbie...
Constant name without "_EMAIL" aren't for customers.
TEXT_COUPON_PRODUCT_COUNT_PER_QUANTY isn't defined.
=> Coupon Email constant wrong

admin/banner_manager.php
As reported in the forum https://www.zen-cart.com/showthread.php?225007-156a-admin-banner-manager-missing-quote-in-parameter&p=1354230#post1354230
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2123)
=> 156: Add missing double quote at the end of a class

admin/products_price_manager.php
In PR #2093, an `isset` was added to attempt to address strict notifications; however, the logic used in this area seems to be reversed in comparison to some other date related comparisons.  As a result, the added logic works in reverse as desired.  This pull sets the date to `'0001-01-01'` if the data is not posted or if it is posted and has no value in it.  If there is something of value posted, then that date will be processed.
=> Correct logic mistake of PR 2093

admin/template_select.php
Discussed in issue #2118.  This removes the action from the URI once the database has been updated to prevent restoring from a timeout where the parameter `action=save` was on the uri for `template_select.php`.
=> v156 Remove action=save from uri after saved

admin/customers.php, zc_install/sql/demo/mysql_demo.sql
As mentioned in forum thread https://www.zen-cart.com/showthread.php?225009-v156a-Customers-function-trouble-and-mysql_demo-sql-has-wrong-data&p=1354237#post1354237
I am not sure if we should add an updates sql for updates of zen cart, as this might add more problems then it fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2124)
=> v156: Fix missing reviews parameter in $cInfo object

admin/customers.php
Likely a better fix is to set $customers_dob earlier in processing than to just test/check at the point of display.
=> address unset $customers_dob when viewing admin/customers.php

admin/includes/modules/document_general/preview_info.php, admin/includes/modules/document_product/preview_info.php, admin/includes/modules/product/preview_info.php, admin/includes/modules/product_free_shipping/preview_info.php, admin/includes/modules/product_music/preview_info.php
If the page is loaded without posting information, notifications
may get thrown for attempting to assign an array to an undefined
value, this pre-sets the items allowing the values to have
some pre-existing value to carry through if present otherwise
to assign to an empty array.
=> initialize some vars in preview_info pages

includes/modules/pages/advanced_search_result/header_php.php
When searching is performed from the store side, the results go through `includes/modules/YOUR_TEMPLATE/product_listing.php`.  That module includes an evaluation of whether the product is not call for price.  This commit will modify the result of that area of code for product that are call for price and not allow adding the product to the cart directly from the results page (as the result may identify that basically the product information page should be seen before allowing it to be added to the cart based on the product being call for price) 
This affects the line below having this content: `                $listing->fields['product_is_call'] == 0` where previously (in a an environment that would allow usage of a non-assigned/non-declared variable) to evaluate as true at this inspection …
=> Results from advanced search missing product_is_call

zc_install/includes/template/templates/index_default.php
This was identified by PanZC2020 at the following forum thread:
https://www.zen-cart.com/showthread.php?225023-Undefined-variable-errorHeadingFlag&p=1354326#post1354326
This commit incorporates my interpretation of how to address the
issue.
=> Fix a strict php notice in zc_install

admin/specials.php
Funny this never was reported, but when using the pre add feature, the $specials_price variable is never set. This results in a database error because $specials_price is not a proper decimal.
Removing the variable will result in sql using the default value for the field (0.0000)., and thus continuing to the next page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2159)
=> 156: Admin specials - Using pre add results in error

includes/modules/sideboxes/search_header.php
Removes the strict notification associated with loading the sidebox and $show_search_header not being set (yet). Replaced a loose verification against equaling `true` with `!empty`.
Also refactored the file while I was here:
- Removed the closing php tag.
- Removed the parentheses around require.
- Separated parameters in the calling functions so that one space was after a comma with no space before the comma.
- Changed the capitalization of the SQL text to capitalize SQL commands/key words.
=> v156 Search header sidebox strict notice

includes/modules/shipping_estimator.php, includes/templates/template_default/templates/tpl_modules_shipping_estimator.php
Prevent strict notices when not logged in and no methods returned from shipping
=> Prevent strict notices when not logged in and no methods returned from shipping

admin/products_price_manager.php
it is confusing and aggravating that products price manager *appears* to be configurable before pressing the edit button WHEN IT IS NOT.  The data should be shown in read only mode to reflect the state of the screen.
=> PPM should show fields as read only when not in edit mode

includes/modules/shipping_estimator.php
Some shipping modules depend on this value being set.   If it is not set, the estimator will show different results than the shipping page, which will be confusing and annoying to customers.
=> Set subtotal before retrieving shipping quotes

includes/functions/functions_gvcoupons.php
If no data is in the table then it is possible that no field
answer is provided which throws a notice.
=> Strict error with coupon lookup

admin/index_dashboard.php
Can't seem to find the thread; however, there was a report that
when dates were modified to support a different "location" this
caused data to be incorrectly displayed on the index_dashboard.
This modification ensures alignment between the dates used to
compare and determine what to display.
=> Substitute a constant for hard code in dealing with dates.

includes/classes/order.php
Maintains $products_attributes to be defined as an array (to
potentially support plugin reference/use of the variable but
ensures that the value is updated only when there are attributes
expected to be present.
=> Corrects strict notice when processing download attributes

includes/classes/upload.php
Found a log being generated if attempt to access a page that would
normally be the one just after an upload, but where it was
landed at without posting data.  As a result, this patch
appears to resolve the logged messages and would assign a
value if one existed.
Example to reproduce would be something like accessing:
admin/product.php?cPath=4&pID=1&action=new_product_preview
=> Correct upload warning when no file uploaded

includes/classes/order.php
When the order's payment method doesn't supply an auto_code and/or transaction_id, PHP notices are logged when generating the order's "extra orders email" block:
```
--> PHP Notice: Undefined property: moneyorder::$auth_code in C:\xampp\htdocs\zc156posm\includes\classes\order.php on line 1135.
--> PHP Notice: Undefined property: moneyorder::$transaction_id in C:\xampp\htdocs\zc156posm\includes\classes\order.php on line 1135.
```
=> Correct PHP notices, extra orders email to

includes/templates/template_default/templates/tpl_account_history_info_default.php
When a virtual order is displayed in the `account_history_info` page, the "Delivery Address" block is empty (except for the heading) and the following PHP Notice is logged:
```
#1  zen_address_format() called at [C:\xampp\htdocs\zc156posm\includes\templates\template_default\templates\tpl_account_history_info_default.php:128]
#2  require(C:\xampp\htdocs\zc156posm\includes\templates\template_default\templates\tpl_account_history_info_default.php) called at [C:\xampp\htdocs\zc156posm\includes\templates\vinos_rc\common\tpl_main_page.php:171]
#3  require(C:\xampp\htdocs\zc156posm\includes\templates\vinos_rc\common\tpl_main_page.php) called at [C:\xampp\htdocs\zc156posm\index.php:97]
--> PHP Notice: Undefined index: format in C:\xampp\htdocs\zc156posm\includes\functions\functions_customers.php …
```
=> Correct PHP Notice account-history-info (virtual)

includes/modules/order_total/ot_shipping.php
If the order's shipping is free (e.g. the order is virtual) there are a couple of PHP Notices logged since the **free** shipping-module has no instance:
```
--> PHP Notice: Undefined index: free in C:\xampp\htdocs\zc156posm\includes\modules\order_total\ot_shipping.php on line 59.
--> PHP Notice: Trying to get property of non-object in C:\xampp\htdocs\zc156posm\includes\modules\order_total\ot_shipping.php on line 59.
```
=> ot_shipping::__construct, PHP Notice when shipping is free_free

includes/classes/order_total.php, includes/modules/checkout_process.php
During `checkout_process`, PHP notices are thrown for order-total modules that don't include a `credit_class` property:
```
--> PHP Notice: Undefined property: ot_subtotal::$credit_class in C:\xampp\htdocs\zc156posm\includes\modules\checkout_process.php on line 110.
--> PHP Notice: Undefined property: ot_subtotal::$credit_class in C:\xampp\htdocs\zc156posm\includes\classes\order_total.php on line 210.
```
=> Correct order_total::credit_class notices

includes/functions/functions_email.php
If the email address in EMAIL_FROM isn't preceded by a name, in some cases the default name "Root User" will be used.
=> Ensure from name is set in zen_mail, especially for cron

includes/classes/shopping_cart.php
Corrects an issue generated by pull #1556.
Use of the internal variable `flag_duplicate_quantity_msgs_set`
without clearing it prior to its next expected use
(within `get_products`) causes the message to not be displayed
although it is expected to at least display one time.
=> Supports allowing outside control to prevent duplicate messages

includes/modules/checkout_new_address.php
If, during the checkout process, a customer chooses to change their shipping or billing address, selecting one of the addresses currently in their address book, a PHP Notice is generated since the new-address form has not been filled out:
```
[18-Mar-2019 08:14:05 America/New_York] PHP Notice:  Undefined index: firstname in C:\xampp\htdocs\zc156posm\includes\modules\checkout_new_address.php on line 30
```
=> Correct checkout_new_address notices

includes/modules/payment/paypalwpp.php
The processing currently forces a creation of the shipping address returned from PayPal.  Add a notification to allow a plugin (e.g. One-Page Checkout) to bypass this processing.
This will allow interoperation with OPC when a customer has chosen to use a "temporary" address for their order's ship-to address.
=> paypalwpp: Allow address-creation to be bypassed

admin/stats_products_purchased.php
The products names should be retrieved form the products_ordered table, as deleted products will return an empty name.
This may potentially return more results, because if a product name has been changed, it will show up as a new result. But overall the results are mor accurate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2229)
=> Improve query for better results for products purchased report

includes/init_includes/init_database.php
--> PHP Warning: Use of undefined constant USE_PCONNECT - assumed 'USE_PCONNECT' (this will throw an Error in a future version of PHP) in includes/init_includes/init_database.php on line 23.
=> Fix PHP 72. warning with use of PCONNECT

includes/modules/payment/paypal/paypal_curl.php
--> PHP Warning: Use of undefined constant PAYPAL_DEV_MODE - assumed 'PAYPAL_DEV_MODE' (this will throw an Error in a future version of PHP) in /includes/modules/payment/paypal/paypal_curl.php on line 409.
=> Fix PHP Warning in 7.2 with use of PAYPAL_DEV_MODE

includes/modules/order_total/ot_shipping.php
When a store has configured `ot_shipping` to provide free shipping on amounts over a certain value, a PHP Notice is thrown if neither of the 'national' or 'international' checks are found to be (bool)true.
```
PHP Notice:  Undefined variable: pass in C:\xampp\htdocs\zc156posm\includes\modules\order_total\ot_shipping.php on line 37
```
The correction is to initialize the value of `$pass` prior to the switch.
=> Correct ot_shipping PHP notice

includes/templates/responsive_classic/templates/tpl_modules_mobile_menu.php
as reported on the forum
https://www.zen-cart.com/showthread.php?225343-myDEBUG-file-created-from-responsive-classic-template-(stock)&p=1356969#post1356969
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2285)
=> ZC 1.5.6 bug fix: Change to fix warning when $var_linklist is empty

includes/modules/shipping_estimator.php
As identified in issue #2234, if:
- a user is logged in, 
- has gone beyond the `shopping_cart` page, 
- has changed the destination (`sendto`) address,
- has returned to the `shopping_cart` page, and
- the store is setup to display the potential shipping charges on the `shopping_cart` page.
Then when they arrive back at the shopping cart page, the selection determined to be active is the customer's default address that is then carried through the remainder of the checkout process until the customer again changes the selection.  This commit chooses the selection that was previously made/available.
Also, for a customer that is not logged in and because of PR #1952, if the shipping estimator is presented on the shopping cart page, the zip code is not provided and a country has been …
=> v156 Shipping Estimator retain ship-to selection after cart edit

includes/classes/ajax/zcAjaxPayment.php, includes/functions/audience.php, includes/init_includes/init_ipn_postcfg.php, includes/init_includes/init_templates.php, includes/languages/english.php, includes/modules/payment/paypalwpp.php, includes/modules/shipping_estimator.php
These files are pulling in language files without using `zen_get_file_directory()`, which can lead to inconsistent results.
=> Check template dir for language file

admin/includes/classes/VersionServer.php
In VersionServer.php there are two calls to json_encode that pass a boolean value of true as the options parameter. The documentation for json_encode on php.net specify that the options parameter is of type integer that specifies a bitmask. It's not clear to me the effects, if any, of passing a boolean value.
Removing the options parameter from these two calls provides compatibility with PHP 5.2 since this parameter was added in PHP 5.3. I found this necessary when upgrading Zen Cart from 1.3.9h (modified to run on PHP 5.2) to 1.5.5f.
=> Cleanup json_encode calls in VersionServer.php

admin/login.php, admin/password_forgotten.php
Instead of using a hardwired image for admin login and admin password forgotten pages, use the logo configured for the regular admin pages.
=> Make logo for admin login use the one defined for rest of admin

includes/classes/ajax/zcAjaxPayment.php, includes/modules/pages/account/header_php.php, includes/modules/pages/account_edit/header_php.php, includes/modules/pages/account_history/header_php.php, includes/modules/pages/account_history_info/header_php.php, includes/modules/pages/account_newsletters/header_php.php, includes/modules/pages/account_notifications/header_php.php, includes/modules/pages/account_password/header_php.php, includes/modules/pages/address_book/header_php.php, includes/modules/pages/address_book_process/header_php.php, includes/modules/pages/advanced_search_result/header_php.php, includes/modules/pages/checkout_confirmation/header_php.php, includes/modules/pages/checkout_payment/header_php.php, includes/modules/pages/checkout_payment_address/header_php.php, includes/modules/pages/checkout_shipping/header_php.php, includes/modules/pages/checkout_shipping_address/header_php.php, includes/modules/pages/checkout_success/header_php.php, includes/modules/pages/contact_us/header_php.php, includes/modules/pages/create_account_success/header_php.php, includes/modules/pages/download/header_php.php, includes/modules/pages/gv_redeem/header_php.php, includes/modules/pages/gv_send/header_php.php, includes/modules/pages/logoff/header_php.php, includes/modules/pages/payer_auth_verifier/header_php.php, includes/modules/pages/product_info/header_php.php, includes/templates/responsive_classic/templates/tpl_modules_mobile_menu.php, includes/templates/template_default/templates/tpl_modules_shipping_estimator.php, includes/templates/template_default/templates/tpl_time_out_default.php
Newer PHP versions will throw an error if a variable is referenced
that does not exist.  A user that is not logged in results in
`$_SESSION['customer_id']` not being defined.  The path forward
is to use the function zen_is_logged_in to determine if a user
is logged in.  This function supports a notifier and on a per
page basis it is possible to determine the page accessed when
the notifier fires.  This standardizes other modifications that
have been made to prevent error notification by changing
`!$_SESSION['customer_id']` and `empty($_SESSION['customer_id'])` to
just use `zen_is_logged_in`.
=> Standardizes zen_is_logged_in usage

includes/classes/message_stack.php
Ensures accessing the session messageToStack by way of a non-error creating function of empty instead of !.
=> Strict error fix in messageToStack

includes/functions/functions_email.php
Ensures accessing the session customers_host_address by way of a non-error creating function of empty instead of !.
=> Strict fix by using empty()

includes/functions/html_output.php
Identified that in outputting html that when processing the countries
when the desired state of an if statement was met that the loop
was directed to continue processing instead of leaving the
loop where no further processing was necessary.
This breaks the loop instead of continuing.
No known specific error, is only a code improvement.
=> Change continue to break in foreach loop for countries processing

admin/gv_sent.php
Page did not present proper information if there were no
certifcates that had been sent.  This does remove the right
side box (which would have no buttons if there were no
associated records) when there are no certificates tracked as
being sent. Also reduces notices related to strict PHP processing.
=> gv-sent uninitialized object

admin/option_name.php
Update **_Catalog->Options Name Sorter_** to recognize additional option types by gathering the information from the `products_options_types` table for display.
=> Options Name Sorter, recognize additional option types

admin/products_to_categories.php
Because of a change in presenting the products_to_categories page where the master category can not be deselected and the design consideration that if a store has one or more categories that a product is not to be in a category that has categories (specifically not in the root category of the store), this commit fixes #2311 and ensures that a product has both a `master_categories_id` and is listed in the table `products_to_categories` if for some reason the products_to_categories page is reached for the product and the product initially did not have a `master_categories_id` set to something other than ''.
Of course, this file can not be accessed if product is in place with a master_categories_id of 0 and it is desired to link the product to other categories and possibly remove it from the …
=> Update products_to_categories.php issue #2311

admin/customers.php
When displaying a customer's record, the DOB if set to be displayed/used does not get displayed when editing the record.  This corrects that. For some reason the variable `$customers_dob` was being used which would be appropriate on update as it is set in the `update` action, but not on edit where the variable is not set.
=> Admin Customers DOB not displayed on edit

admin/includes/init_includes/init_sanitize.php
As reported on the forums, if the DTK's search string contains "special" HTML characters, those characters will be sanitized into their HTML entities, resulting in "no results found" when, if fact, there should be.  Add an opt-out in the admin's init_sanitizer to correct this.
=> Correct over-sanitization of DTK search string

includes/modules/pages/account_edit/header_php.php
Although I do not see where the `customers_email_format` could be set to `NONE` or `OUT`, the variable `$email_pref_out` does not exist at
the point of the logic test.  The result is that at least in an environment with strict notification, the standard page load results in generation
of a PHP notice.
=> Strict fix for email pref default

admin/coupon_admin.php
When you want to create a coupon that's only valid for free shipping, you enter the coupon amount as 0 (or 0.00).  Somewhere in the process, that value gets changed to an empty string ('') which is an invalid numeric value and results in a MySQL error when the coupon is being recorded in the database.
This PR forces the amount value to be a valid numeric when that value is 'empty' (e.g. either 0, 0.00 or an empty string).
=> Coupon admin:  Can't add Free Shipping only coupon

admin/includes/functions/general.php
If the `is_coupon_valid_for_sales` function is called with an invalid coupon-id, then a PHP Notice is thrown because no data is returned on from the db's SELECT clause.
=> Correct PHP Notice on coupon-valid check

includes/modules/pages/page/header_php.php
if `$vert_links[]` is assigned it is given a non-zero value.  This commit prevents the notice provided in strict operation of testing for a non-existing array key by use of `[$key+1]`.
=> v156 strict notice: check that vert_links key exists

includes/modules/order_total/ot_coupon.php
Fixes #2353
There are two changes in this update:
1. `ot_coupon::get_order_total`: The shipping tax shouldn't be subtracted from the overall value, as that value represents the amount of tax to be **removed** from each tax-group.
2. `ot_coupon::calculate_deductions`: Don't `unset` a tax-group with a 0-value; results in PHP Notice if shipping tax class is unique and the coupon gives free shipping.
=> Free shipping coupon w/ taxed shipping

admin/category_product_listing.php
in a default install of ZC 1.5.6a+ on this page.
I navigate to other admin pages and do not have an unclosed tag
(meaning I don't appear to have an extra tag somewhere above the
main body code).
I was asked to "prove" it, though don't know exactly how I can
do that other than possibly show the source code possibly with
my private information obscured.
I have again installed the code to a new site location and applied demo products.  When looking at this page using Firefox Developer, I receive the following message: Source map error: request failed with status 404
Resource URL: https://template7.mc12345678.com/v156/sWeet-jmg-atTic/includes/css/bootstrap.min.css
Source Map URL: bootstrap.min.css.map'
On Microsoft Edge I receive an unexpected end tag for the </div> at "line" 1363.  I've …
=> unmatched end tag

includes/languages/english.php, includes/modules/pages/account_edit/header_php.php
Similar to #1518, but for account edit.  If using a mobile device, the date is presented with a date selector (though still haven't been able to get the date selector to populate with the known/existing date) that stores the date locally/internally using ISO-8601 format which in the previous format would prevent updating the record.  This at least allows updating the record, though it seems that the user would have to re-enter the birthdate.
It appears that in jscript_responsive_framework.php the line associated with the dob:
`$('input#dob').clone().attr('type','date').insertAfter('input#dob').prev().remove();`
causes the attribute of `value` to get cleared once the type is modified to date. In briefly trying to address this in light of upcoming distribution, I haven't come up with a …
=> v156 account_edit recognize ISO-8601 DOB

docs/changed_files-v1-5-6.html, includes/templates/template_default/templates/tpl_modules_address_book_details.php, includes/templates/template_default/templates/tpl_modules_checkout_new_address.php
On the subject page, when using 'pulldown states', there's a space missing between HTML attributes, causing validation issues:
```
<select name="zone_country_id" id="country" placeholder="*"onchange="update_zone(this.form);">
```
This issue has been around for a while!
=> zc156b: address_book_process, HTML validation

zc_install/sql/updates/mysql_upgrade_zencart_153.sql, zc_install/sql/updates/mysql_upgrade_zencart_155.sql
This guy's point is well taken: 
https://www.zen-cart.com/showthread.php?224820-Database-upgrade-fails-when-upgrading-my-1-5-3-to-1-5-6&p=1355473#post1355473
Suggest merging this into 156 (in case there's a 156c patch) as well as 1.5.7.
=> Don't specify countries_id on INSERT

admin/developers_tool_kit.php
zen_display_files return code is checked on line 669 so we should ensure
that it always returns a value
=> Add return value to zen_display_files

admin/whos_online.php
If the unsetting location was on purpose (to provide a downstream
indicator about the success of decoding the session data), then
please ignore this commit (and please leave comment for
historical sake :)). Otherwise, it seems like the variable
`$backup` is not needed elsewhere after this assignment and
should be removed at each assignment.
=> Always unset temp variable in whos_online

admin/tax_classes.php
The doctype contained "public", which should not be there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2404)
=> Fix typo in doctype

admin/attributes_controller.php, admin/includes/languages/english/attributes_controller.php, includes/classes/shopping_cart.php
As identified in the Zen Cart forum:
https://www.zen-cart.com/showthread.php?225489-Setting-up-a-product-with-a-single-required-file-upload-attribute
This offers a way to honor marking an File attribute as required.
<strike>This does not yet address the option name being identified as
Text when it is a file attribute.</strike> <- Addressed by this [commit](https://github.com/zencart/zencart/pull/2408/commits/0bc618a3a2a34de95545f03a9c71200e5413bcf1).
Note, if two or more files are marked as required that this
will "upload" all files identified; however, if any required
file is not uploaded, then none of the uploaded files get
attached to a store product and would need to be uploaded again.
Not sure yet if/how to address this, but maybe another will be
able to help or "accept" that issue. …
=> Supports required file uploads.

admin/includes/banner_tools.css
The img/ folder doesn't exist, nor do the referenced images
=> Remove references to missing images in banner_tools.css

docs/0.about_zen_cart.html, docs/1.readme_installation.html, docs/2.readme_how_to_upgrade.html, docs/changed_files-v1-5-0.html, docs/changed_files-v1-5-1.html, docs/changed_files-v1-5-2.html, docs/changed_files-v1-5-3.html, docs/changed_files-v1-5-4.html, docs/changed_files-v1-5-5.html, docs/changed_files-v1-5-6.html, docs/important_site_security_recommendations.html, docs/index.html, docs/whatsnew_1.5.0.html, docs/whatsnew_1.5.1.html, docs/whatsnew_1.5.2.html, docs/whatsnew_1.5.3.html, docs/whatsnew_1.5.4.html, docs/whatsnew_1.5.5.html, docs/whatsnew_1.5.6.html
This is no longer needed and not HTML5.
=> Remove un-needed imagetoolbar tag in docs

includes/init_includes/init_ipn_postcfg.php
As reported in this (https://www.zen-cart.com/showthread.php?220781-One-Page-Checkout-Support-Thread&p=1358543#post1358543) Zen Cart forum posting.
Added that missing **/** to correct the error.
=> Fatal Error at ipn_postcfg.php

admin/includes/languages/english/reviews.php, admin/reviews.php
usual validation issues: aligns, alt tags. Removed font tag from constants
removed unnecesary tables
changed Products Column title to Product
135 simplified form-group for layout
235 added columns products model and language flag (if a second language pack is installed) to the table
Why? Occasionally I find people leaving reviews in spanish via the english gui... this helps to spot that .
261 removed unnecessary closing space
264 changed default order to last written instead of by product order
Why? Who cares about old reviews, you can search for the product. The only time you go in here is to do something with the last ones.
266 $reviews_query_raw; Phpstorm complained about the space before this quotation mark: p.products_id "
296 added languages_id
306 added products_model
325 moved tr …
=> admin reviews

zc_install/includes/modules/pages/completion/header_php.php
doCompletion() returns no result, so result shouldn't be saved.
=> Don't use result of void function

admin/includes/languages/english/attributes_controller.php, admin/includes/languages/english/extra_definitions/stats_sales_report_graphs.php, admin/includes/languages/english/options_name_manager.php, admin/includes/languages/english/options_values_manager.php, admin/includes/languages/english/products_price_manager.php, admin/includes/languages/english/users.php
These all get spat out by Report All Errors.
These are the only ones not fixed.
TEXT_GV_REDEEM
If this is removed from gv_name, then 
admin->Discounts->Mail Gift Certificate gives an error as it is undefined.
admin->Discounts->Gift Certificates sent gives an error as it is undefined.
On the Admin-Payment modules page, there are 100 duplicated paypal constants errors!
The Catalog side needs a lot of TLC in this respect that someone else will need to do!
=> Admin: removal of constants already defined in main language file

includes/init_includes/init_db_config_read.php
Blocks script injection into fields used in Javascript validation.
=> Ensure MIN  and MAX values from groups 2 and 3 are integer

includes/init_includes/init_ipn_postcfg.php, includes/modules/payment/paypalwpp.php
Recommended for backport to 1.5.6
=> Language inclusion requires slash before filename

includes/templates/responsive_classic/common/main_template_vars.php
The majority of variables such as `$template` and `$template_dir` are set in the early loading process of Zen Cart; however, `$detect` is provided for responsive template use and is loaded in the common/html_header.php file.  Unfortunately, in processing of `index.php`, the template directory is searched using the `$current_page_base` for an override folder to possibly override `html_header.php`.  If that file is overridden, then execution of the `common/main_template_vars.php` file will fail at the use of `$detect` if that override does not set it to a class that supports the methods `isMobile()` and `isTablet()`.  
The current version of the file "assigns" `$layoutType` to `'legacy'` basically if the `common/html_header.php` file is overridden without defining `$layoutType` and then …
=> v156b-c/v157 Ensure $detect is set when html_header.php overridden

admin/includes/functions/html_output.php, includes/functions/html_output.php
The current `zen_draw_pull_down_menu()` function only accepts `$values arrays`, starting with an index of 0. In not all cases `$values` will start with 0, resulting in a wrong out put.
By replacing the `for ($i=0, $n=sizeof($values); $i<$n; $i++) {` with a `foreach` the `$values` array can have any value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2470)
=> v157 modify pull down menu function

includes/modules/pages/account_edit/header_php.php
Fixed #2464.
Created a variable specifically to pass the sanitized information to the observer and then deleted the variable.  This maintains the notifier as previously provided while still providing sanitized information to the second parameter (editable by design of the observer class beginning in Zen Cart 1.5.3) but is then unset to not affect the subsequent storage of the original provided `$email_address`.
=> v157 PHP 7.3 notice of non-variable passed by reference

includes/classes/payment.php
=> Prevent `Parameter must be an array` error on checkout confirmation page

includes/init_includes/init_sanitize.php
A portion of includes/init_includes/init_sanitize.php is not
executed on the first load to a site, leaving follow on code to
respond instead of this change.  Not sure if this is to in some
way improve first page load time or if wasn't something simply
expected to be handled later but was offerred an opportunity
during routine navigation.
=> Perform products_id validate on first load/session not started.

admin/includes/languages/english.php, includes/functions/audience.php, includes/languages/english.php
Recent additions of adding a closing slash have been accepted
with double quotes (`""`) instead of single quotes (`''`)
or `DIRECTORY_SEPARATOR`. This makes the usage consistent and
easier to locate if a search is necessary other than a
regex that looks for either type of quotes.
=> Provide consistent use of added `zen_get_file_directory` calls

includes/functions/functions_lookups.php
Found when single product was in a category and no previous/next
result was available, the query returned no result processable
by zen_image and resulted in no `products_image` field result
and a strict php notice.
=> Do not process zen_image if no products_image record.

zc_install/ajaxLoadUpdatesSql.php, zc_install/includes/languages/lngEnglish.php
When I went to test the upgrade, the new version had not yet been defined in the `$updateList`, so the message was confusing (since one of the strings which were embedded in the error message were blank). 
Instead of saying:
[we] must perform the updates to get to version 1.5.6 first.
it said, 
[we] must perform the updates to get to version first.
=> Improve upgrade message

admin/developers_tool_kit.php
Built off of the addition to remember the text that had been
entered, these changes intend to remember any entry made as part
of the most recent search.  It does not store/restore all data
that is on the page, just that of an area that was last searched.
=> DevelopersToolkit - Remember the values that were entered during search

admin/products_to_categories.php
All results for `$_GET['products_filter']` and `$products_filter`
are set to an `integer` `(int)`, thus seems the default not found
value should also be set to an integer which in this case is `0`.
=> Set value to an number instead of empty quotes if no value.

includes/classes/payment.php
The way that the code had been revised makes subsequent
operations initially unnecessary but necessary if the first
is not executed.
=> Remove unnecessary tests if action performed.

zc_install/includes/classes/class.systemChecker.php
Resolves 
[07-Jul-2019 03:33:16 America/New_York] PHP Notice:  Undefined index: methods in /Users/scott/Sites/gh_demo_157/zc_install/includes/classes/class.systemChecker.php on line 163
=> Fix PHP Notice when no db checks defined yet in zc_install

includes/modules/pages/checkout_confirmation/jscript_double_submit.php, includes/modules/pages/checkout_confirmation/jscript_main.php, includes/modules/pages/checkout_payment/jscript_double_submit.php, includes/modules/pages/checkout_payment/jscript_main.php
Fixes #2536 PADSS_AJAX_CHECKOUT means checkout confirmation javascript not loaded so submit once protection is missing.
=> Ensure submitonce() is available on payment page

includes/functions/functions_general.php, includes/templates/responsive_classic/common/tpl_header.php, includes/templates/responsive_classic/templates/tpl_modules_mobile_menu.php, includes/templates/template_default/common/tpl_header.php
Using `require(DIR_WS_MODULES . 'sideboxes/search_header.php');` means a sidebox template override will be ignored.
=> Respect overrides in includes/modules/sideboxes

zc_install/sql/install/mysql_latin1.sql, zc_install/sql/install/mysql_utf8.sql, zc_install/sql/updates/mysql_upgrade_zencart_157.sql
Italy should have address format 5, not 1.   Originally reported in 
https://github.com/zencart/zencart/issues/271
Fix backported from v2.
=> Fix Italy address format

zc_install/sql/install/mysql_zencart.sql
It makes no sense that they have access to the customers and orders screen but not the mail screen.
=> Order Processor role should have access to mail as well

admin/includes/functions/admin_access.php, admin/includes/init_includes/init_admin_auth.php
Non superusers who are allowed to use the Tools->Banner Manager page should also have access to the banners statistics page, but there's no checkbox for this page, so we'll use Banner Manager as a proxy.
=> Extra check for non super user access to banner statistics page

includes/classes/observers/auto.non_captcha_observer.php, includes/modules/create_account.php, includes/modules/pages/contact_us/header_php.php, includes/modules/pages/product_reviews_write/header_php.php, includes/templates/responsive_classic/templates/tpl_product_reviews_write_default.php, includes/templates/template_default/templates/tpl_contact_us_default.php, includes/templates/template_default/templates/tpl_modules_create_account.php, includes/templates/template_default/templates/tpl_product_reviews_write_default.php
This is a reduced version of davewest's non-captcha spam trap catcher, which only handles URL detection and dynamic fieldname for honeypot.
It does NOT handle the slider or other human-detection questions. Those can be added by using the Addon to replace core functionality.
=> Build in basic version of DaveWest's non-captcha spam detection

includes/functions/functions_products.php, includes/init_includes/init_general_funcs.php, includes/modules/pages/document_general_info/header_php.php, includes/modules/pages/document_general_info/main_template_vars.php, includes/modules/pages/document_product_info/header_php.php, includes/modules/pages/document_product_info/main_template_vars.php, includes/modules/pages/product_free_shipping_info/header_php.php, includes/modules/pages/product_free_shipping_info/main_template_vars.php, includes/modules/pages/product_info/header_php.php, includes/modules/pages/product_info/main_template_vars.php, includes/modules/pages/product_music_info/header_php.php, includes/modules/pages/product_music_info/main_template_vars.php
Split out the code for handling 404 Header responses so it can be intercepted with an Observer if needed.
Added ability to define a constant PRODUCT_THROWS_200_WHEN_DISABLED to boolean `true` without needing an Observer, if a Store wishes to allow a product to display even when disabled.
A 404 will still trigger if the product doesn't actually exist in the db.
A 410 can be triggered by setting `products_status` to `-1` in custom code, without needing an observer for the 410 response.
This change should also reduce queries on product page.
Fixes #1699
=> Provide the option of not going to 404 when product status is 0

admin/includes/languages/english/modules.php
No longer happens due to increased awesomeness in Zen Cart. :)
=> Remove unused message WARNING_MODULES_MISSING_KEYS

includes/functions/functions_email.php
For email templates that include the $EXTRA_INFO block, a customer's email displays an empty but styled div, as identified in this thread:
https://www.zen-cart.com/showthread.php?225671-Hide-empty-div-in-emails
Code addition for /includes/functions/functions_email.php by @lat9 is in post [#19](https://www.zen-cart.com/showthread.php?225671-Hide-empty-div-in-emails&p=1359711#post1359711).
=> Hide empty div in customer emails

admin/includes/functions/html_output.php, admin/includes/languages/english.php, admin/includes/stylesheet.css
Parameter ignored in some cases; fixed display of fields so that when used it would appear to the right rather than below the field. 
Part of the fix for #2578
=> Properly handle form-input $required parameter on admin side

includes/functions/html_output.php, includes/languages/english.php
Parameter was ignored in various places, and related define was missing.  Part of the fix for issue #2578.
=> Fully support $required parameter in catalog

zc_install/includes/languages/lngEnglish.php, zc_install/includes/systemChecks.yml, zc_install/index.php
First part of fixing #2586 - don't let them get started with less than 5.6.
=> Enforce PHP 5.6 as a minimum in the installer

admin/sqlpatch.php
Commands such as 
`ALTER TABLE  customers ADD foo text default NULL;`
(2 spaces after TABLE) fail currently; this PR fixes it.
=> Handle multiple spaces before tablename in Install SQL Patches

includes/modules/pages/checkout_shipping/header_php.php
I have seen cases where the first is set but not the second, leading to a notice in PHP 7.3.
=> Check both shipping and shipping id

admin/category_product_listing.php
See bug report: https://www.zen-cart.com/showthread.php?225704-v156c-cannot-reenable-all-product-when-enabling-category&p=1359899#post1359899
Ref: #2301
=> Display product options when enabling disabled category

admin/includes/functions/configuration_checks.php, admin/includes/languages/english/configuration.php
The database creation specifies a set of error strings for min max checks.  None of the strings (such as TEXT_MAX_ADMIN_ADDRESS_BOOK_ENTRIES_LENGTH) have been defined, so the check just returns successfully even though the test would fail.  Creating a default check will fix this for the time being.
=> Handle error string not defined in val_function check

admin/includes/functions/general.php, admin/includes/header.php, admin/sqlpatch.php
Part 2 of #2586.  
Note that some of the removed checks were actually wrong; they used OR where they should have used AND.
=> Removing old PHP Version checks

admin/includes/functions/admin_access.php, admin/modules.php, includes/modules/payment/square.php
This parameter should be blank, STORE_NAME or STORE_OWNER - not an email address.  This would be more consistent with the other calls to `zen_mail`.
=> Improve consistency with first param in calls to zen_mail

admin/includes/functions/general.php, includes/functions/functions_categories.php, includes/functions/functions_lookups.php, includes/functions/functions_taxes.php
These changes make the code a bit more self documenting with the new stricter handling of strings vs arrays in PHP7.
=> Function signatures - init arrays to array instead of string

admin/includes/languages/english.php, admin/includes/languages/english/category_product_listing.php, admin/includes/languages/english/coupon_restrict.php, admin/includes/languages/english/downloads_manager.php, admin/includes/languages/english/featured.php, admin/includes/languages/english/invoice.php, admin/includes/languages/english/orders.php, admin/includes/languages/english/packingslip.php, admin/includes/languages/english/product.php, admin/includes/languages/english/products_price_manager.php, admin/includes/languages/english/products_to_categories.php, admin/includes/languages/english/reviews.php, admin/includes/languages/english/specials.php, admin/includes/languages/english/stats_products_purchased.php, includes/languages/english.php, includes/languages/english/advanced_search.php, includes/languages/english/advanced_search_result.php, includes/languages/english/document_general_info.php, includes/languages/english/document_product_info.php, includes/languages/english/featured_products.php, includes/languages/english/index.php, includes/languages/english/product_free_shipping_info.php, includes/languages/english/product_info.php, includes/languages/english/product_music_info.php, includes/languages/english/products_all.php, includes/languages/english/products_new.php, includes/languages/english/responsive_classic/index.php, includes/languages/english/shopping_cart.php
This is PR #623 from 2.0.  Make it easier to change the string "Product Model", which clients do ask for.
=> Consolidate language-defines for Product Model

includes/modules/attributes.php, includes/templates/template_default/templates/tpl_modules_attributes.php
Observer hooks can be used to set `data-x="y"` properties on html fields, which can later be leveraged by front-end clients to control display/selection dependencies.
=> Add observer hooks, and field-data-properties to Attributes module

admin/includes/functions/general.php, includes/functions/functions_general.php
As identified in [this](https://www.zen-cart.com/showthread.php?225679-PHP-Fatal-error-1406-Data-too-long-for-column-ip_address-at-row-1&p=1359685#post1359685) Zen Cart forum thread.
Use the built-in PHP `filter_var` function to fully vet the incoming IP address.  The change specifies the IP filter types to make the processing more obvious.
If an invalid IP is found, set (as current) the IP value to a single dot and issue a notification allowing follow-on code to catch and possibly record the invalid access.
=> Sanitize IP addresses via filter_var

admin/includes/modules/copy_product_confirm.php, admin/includes/modules/document_general/collect_info.php, admin/includes/modules/document_product/collect_info.php, admin/includes/modules/product/collect_info.php, admin/includes/modules/product/preview_info.php, admin/includes/modules/product_free_shipping/collect_info.php, admin/includes/modules/product_free_shipping/preview_info.php, admin/includes/modules/product_music/collect_info.php, admin/includes/modules/product_music/copy_product_confirm.php, admin/includes/modules/product_music/preview_info.php, admin/includes/modules/product_music/update_product.php, admin/includes/modules/update_product.php
1.  Add notifiers to each product type's `collect_info` enabling observers to seamlessly add more product-related fields.
2.  Add notifiers to the various `copy_to_confirm` and `update_product` modules, to work with the above additions
3.  Update various `preview_info` modules to product valid HTML
=> Additional notifiers and valid HTML on previews

admin/includes/functions/configuration_checks.php, admin/includes/languages/english/configuration.php
This adds a generic message to handle the values that are in the
minimum configuration group and the values that are in the
maximum configuration group if a specific error message is not
already defined.
Two methods of processing are presented, my less preferred is
commented out. Less preferred because it seems to involve more
code though perhaps is easier to "read".
Partially fixes #2632 by at least providing a generic define for each, still think
need to address overrides and developer incorporation.
=> Add dynamic error messages for val_function validations

includes/classes/order.php
1.  When download _is_ enabled, gather **all** the `products` table fields, like when it isn't.
2.  Remove single-quotes from database actions on integer fields.
3.  Use `ExecuteNoCache` instead of all the additional parameters (improves readability)
4.  Combine product's quantity and status update into a single query.
5.  Use `LIMIT 1` for performance for sites with large product definitions.
=> Order-class/low-stock refinements

includes/modules/pages/account_history_info/header_php.php
1.  Simplify initial order-id sanitization
2.  Limit order-check to a single order (performance for large stores)
3. Gather **all** fields from the `orders_status_history` table; available for template overrides' usage.
=> account-history-info: Additional fields

includes/classes/order.php
This could be desired, for instance, if an admin is placing an order on behalf of a customer.
=> Enable customer order-confirmation email to be skipped/bypassed

admin/category_product_listing.php
fixes #2614
- This will remove the too "aggressive" hiding of columns.
- Additionally I removed the obsolete type="text/css"
- adding col-xs-12 to class, to prevent empty class (and easier upgrade to future BS4)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2713)
=> Put back the missing columns on product catalog list in admin

includes/modules/additional_images.php
Between this and a Colorbox plugin observer, caused a php notice with this plugin.
Image Handler observer also expects it.
=> missing parameter large_link expected by colorbox and image handler plugins

includes/modules/pages/advanced_search_result/header_php.php
If a customization provides additional clauses for the search, this notification enables that customization to override the "is anything selected" check in the `advanced_search_results` page's handling.
Otherwise, if none of the built-in search parameters are set, the customization's additional clause gets ignored.
=> Enable additional search-clause

admin/orders.php
In 1.5.4 and below, the label for the button that goes to the order details page was Details.  In 1.5.5 (carried over to 1.5.6), it was changed to Edit.  This seems confusing since people will mistake it for order edit, which it's not.  Let's switch it back to Details.
=> Make order details button say Details, not Edit

admin/includes/languages/english/orders.php, admin/orders.php
Currently, when displaying an order in the admin, the order number _is_ present but in relatively small text within the order's details.
Update the order's detailed display to include the order number in the level-1 heading so that it's more obvious to admin staff.
=> Display order number in heading

admin/gv_mail.php
In #2332, an incorrect resolution for strict PHP notices was provided by assigning the default value for dropdown selection to be an `integer`.  At this point in the code, the `customer` is the id associated with individual to be selected when the gv_mail page has een entered. The id is either the e-mail address or the standard name such as `All%20Customers`.  This restores the default selection of email address dropdown.
This also affects ZC 1.5.6b and ZC 1.5.6c.
=> Admin - Correctly select default email recipient

admin/orders.php
- "Simplify" the order-listing's navigation, splitting into 3 equal sections for medium/large display.
- Add a notifier to enable additional 'nav' buttons to be inserted to the left or right of the listing navigation.
- Additional notifiers for the order-status-history block, primarily in support of "Ty Package Tracker"
=> Additional notifications for admin/orders.php

includes/classes/shopping_cart.php
When updating the cart-contents, PHP notices similar to the following were being thrown:
```
--> PHP Notice: Undefined index: cart_delete in C:\xampp\htdocs\zc157\includes\classes\shopping_cart.php  on line 1773.
--> PHP Notice: Undefined index: id in C:\xampp\htdocs\zc157\includes\classes\shopping_cart.php on line 1857.
```
=> Correct shopping_cart PHP notices

includes/modules/pages/address_book_process/header_php.php
When creating a _new_ address-book entry, fields expected by `tpl_modules_address_book_details.php` aren't present.
=> Correct PHP notices for address_book_process

includes/modules/pages/password_forgotten/header_php.php
Generating a notice similar to
```
[14-Aug-2019 14:53:24 UTC] Request URI: /forgotten-password?action=process, IP address: xx.xx.xx.xx
#1 require(/home/site/mystore/includes/modules/pages/password_forgotten/header_php.php) called at [/home/site/mystore/index.php:36]
--> PHP Notice: Undefined index: login_attempt in /home/site/mystore/includes/modules/pages/password_forgotten/header_php.php on line 23.
```
=> Correct password_forgotten PHP notice

admin/password_forgotten.php
- Check for login_attempt prior to use
- Correct 'spelling' of resetToken variable.
=> admin/password_forgotten: Correct PHP notices

includes/templates/template_default/templates/tpl_discount_coupon_default.php
Generating a notice similar to the following on initial entry to the page (no post data):
```
[14-Aug-2019 20:23:35 UTC] Request URI: /discount-coupons, IP address: xx.xx.xx.xx
#1 require(/home/store/mystore/includes/templates/template_default/templates/tpl_discount_coupon_default.php) called at [/home/store/mystore/includes/templates/my_rc/common/tpl_main_page.php:174]
#2 require(/home/store/mystore/includes/templates/my_rc/common/tpl_main_page.php) called at [/home/store/mystore/index.php:97]
--> PHP Notice: Undefined index: lookup_discount_coupon in /home/store/mystore/includes/templates/template_default/templates/tpl_discount_coupon_default.php on line 27.
```
=> Correct PHP notice on discount-coupon lookup

includes/modules/payment/paypal/paypalwpp_admin_notification.php, includes/modules/payment/paypalwpp.php
Correcting various PHP notices thrown during admin Customers::Orders processing when the order has been placed via the `paypalwpp` payment method.
Note that testing was done using US-based PayPal processing; I don't know if there are additional, optional response elements for the PayFlow side of things.
=> Correct paypalwpp notices

admin/orders.php
Order product search was only searching product names 'beginning with" the search term. This changes it to include the term "anywhere" in the product name.
As identified in [this](https://www.zen-cart.com/showthread.php?225835-Searching-orders-for-product-name) Zen Cart posting.
=> Expand order product search

admin/attributes_controller.php
You may want to prepare a download product before the zip file is completely ready.  With this change, it will show up as a red entry in Downloads Manager and can be fixed at a later time.  I have used this step-saver in a few releases and wanted it to be considered as a core change.
=> Allow a filename attribute to be added with a missing filename

admin/includes/functions/admin_access.php
If a plugin is removed from a store and the use of the plugin has been authorized for a non-superuser admin-profile, admins using that profile can no longer sign in.  For instance, if the Sales Report was previously installed, the following PHP issues are logged on the admin login attempt:
```
[26-Aug-2019 07:42:36 America/New_York] Request URI: /myadmin/index.php, IP address: 127.0.0.1
#1  constant() called at [C:\xampp\htdocs\zc156c\myadmin\includes\functions\admin_access.php:837]
#2  zen_get_admin_menu_for_user() called at [C:\xampp\htdocs\zc156c\myadmin\includes\header_navigation.php:56]
#3  require(C:\xampp\htdocs\zc156c\myadmin\includes\header_navigation.php) called at [C:\xampp\htdocs\zc156c\myadmin\includes\header.php:257]
#4 …
```
=> Limited-profile admin can't log in after plugin removed

includes/languages/english/modules/payment/paypalwpp.php, includes/modules/payment/paypalwpp.php
Tell the customer to make direct payment to the email address of the store.  If this is wrong, it can easily be changed since it's in a language file.
=> Add further instruction to PayPal error message

includes/modules/pages/advanced_search_result/header_php.php
Created over 10 years ago and may have been in one of the earlier releases but not found in 1.5.5 series.
Allows system to take the customer straight to the product's page when only a single product is the result of their search.
=> Allow search to jump directly to product if only 1 result found

includes/classes/split_page_results.php, includes/modules/pages/account/header_php.php, includes/modules/pages/account_history/header_php.php
While a "hidden" admin-only order-status comment is excluded from display catalog-side, the "Order Status" name was being displayed, which might not be appropriate for customer to see.
This PR changes it to show the last non-hidden order-status-name in the My Account page and the My Account History page (which is accessed by clicking the Show All Orders) from the My Account page).
=> Exclude "hidden" order-status updates from account-history

admin/orders.php
I just upgraded to 1.5.6 and noticed an issue introduced with #1550.  
```
Request URI: /admin/orders.php?oID=12345&action=update_order
#1  mktime() called at [/admin/includes/functions/general.php:3303]
#2  zen_date_diff() called at [/admin/orders.php:203]
--> PHP Warning: mktime() expects parameter 6 to be int, string given in /admin/includes/functions/general.php on line 3303.
```
* Update an order with downloadable products to "UPDATE" status
* Get the warning in the logs and date does not update correctly.
It happens because the `$check_status->fields['date_purchased']` is undefined in the call to
`zen_date_diff` on `line 203`
**NOTE**: would also happen inside `if ($order->info['payment_module_code'])` block... on `line 169`
**NOTE**: the `customers_name` and …
=> add missing $check_status query on update_order action

admin/options_name_manager.php, admin/options_values_manager.php
These two file were using their own split page routine. After some investigation, I thought this could be replaced with the standard splitPageResults class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zencart/zencart/2825)
=> Options Editors - make use of splitPageResults class

includes/languages/english.php, includes/languages/english/account_history_info.php, includes/languages/english/checkout_success.php, includes/languages/english/shopping_cart.php
The subject constant is currently defined in the `account_history_info`, `checkout_success` and `shopping_cart` pages' page-specific language files.  Consolidate into the base language file.
=> Consolidate TEXT_OPTION_DIVIDER definition

admin/category_product_listing.php
Here the blue icon is an add-on.
To keep these icons vertically aligned, I added a transparent icon left of the green status when the product is not linked/yellow icon is missing and so push any new ones/the blue one left.
=> admin, category listing: add blank icon in place of yellow icon when unlinked to preserve spacing

admin/attributes_controller.php, admin/includes/modules/products_previous_next_display.php, admin/products_price_manager.php, admin/products_to_categories.php
The entire prev_next block was build into a <tr> tag (rather than a complete table).
Simplified this to a div and removed the enclosing table tags from the three files that use this.
Also corrected a missing /div in products_to_categories and a minor validation error with a separator width in the infobox.
=> admin: prev-next removed as table layout

includes/templates/responsive_classic/templates/tpl_checkout_payment_address_default.php, includes/templates/responsive_classic/templates/tpl_checkout_shipping_address_default.php, includes/templates/template_default/templates/tpl_checkout_payment_address_default.php, includes/templates/template_default/templates/tpl_checkout_shipping_address_default.php
If a customer has only one entry in their address-book, the 'Select current address' section of the `checkout_payment_address` and `checkout_shipping_address` pages renders the `</form>` for that section, even though the `<form>` has not been opened.
The issue is present in both the `responsive_classic` and `template_default` templates' versions.
Noting that the issue is also present in the zc156 branch; suggest backport.
=> zc157: Correct misplaced form closure when only 1 address-book entry

admin/category_product_listing.php, admin/includes/languages/english.php, admin/includes/languages/english/category_product_listing.php
add missing icon alt/title text used in category_listing.php
fix required for php notice when disabling categories if no subcategories, due to $_POST['set_subcategories_status'] not being set.
Reworked the code so
a) the evaluation for subcategories/products status is done once: it was mistakenly inside the category tree loop.
b) status updates are only done when a subcategories/products status **change** has been selected.
=> Admin category listing: enable/disable subcategories and products

admin/includes/functions/general.php
admin: make products select drop-down/select field ordered as prev-cat-next order navigation buttons when used on the same page (attribute controller, products to categories and products price manager)
: sort order defined by admin switch PRODUCT_INFO_PREVIOUS_NEXT_SORT
=> admin: make products select drop-down/select field ordered as prev-cat-next order

includes/modules/order_total/ot_coupon.php
Query already includes a clause ensuring coupon_type is not 'G' we don't need to check it in the `if` block processing the results.
=> Remove redundant coupon_type check

includes/modules/pages/checkout_success/header_php.php
Identified as an issue in forum at: https://www.zen-cart.com/showthread.php?225965-Checkout-success-array-error
Back portable to v1.5.6.
=> Fix notices associated with prod notifications on checkout_success

admin/includes/functions/admin_access.php
This array was modified already to move the closing paranthesis to the next
line, but the ending comma was not included on the previous line.
=> Code formatting

admin/includes/functions/general.php
If the query returns no results, then attempting to obtain `configuration_value` from the query results causes a PHP notice that will become an error in the future.  By assigning a value to `$lookup_value` first and then reassigning to an alternate value if there is a record returned, no notice/error is generated.
=> Refactor to eliminate php notice

admin/includes/init_includes/init_db_config_read.php
Until the `configuration_key` is inserted into the database, a php notice that is expected to become an error in the future is issued.  This at least allows continued execution while the `configuration_key` is still not yet inserted without throwing the notice.  It also will mean that the internal code will not be executed if the `configuration_key` is removed from the database in the future.  I have not yet seen how this `configuration_key` is used in the code, to possibly advise of anything different.
=> Fix PHP notice on empty query result

includes/modules/pages/checkout_payment/jscript_main.php
If there is only one payment method (say Authorize AIM), there isn't a group of radio buttons with name "payment" that you can inspect to see if one is checked - there's only  one hidden field named "payment".  So an additional test is required in the onsite payment check.
=> Fix js check for onsite payment when only 1 module available

includes/modules/payment/paypalwpp.php
... that cause a PHP fatal error due to the missing `$this->`.
=> Correction to paypalwpp changes posted last month

includes/templates/template_default/templates/tpl_checkout_payment_default.php
without this fix, the payment page order summary is squeezed.   See attached image.
=> Fix address/amount layout on payment page

admin/banner_manager.php
If a banner includes _no_ image (only HTML text), PHP notices similar to the following are thrown:
```
[19-Oct-2019 10:14:46 America/Chicago] Request URI: /myadmin/banner_manager.php?page=1&action=upd, IP address: 127.0.0.1
--> PHP Notice: Undefined variable: banners_image in C:\xampp\htdocs\mystore\myadmin\banner_manager.php on line 116.
[19-Oct-2019 10:14:46 America/Chicago] Request URI: /myadmin/banner_manager.php?page=1&action=upd, IP address: 127.0.0.1
--> PHP Notice: Trying to get property of non-object in C:\xampp\htdocs\mystore\myadmin\banner_manager.php on line 116.
```
... since the `$banner_image` object is not created/available in that case.
=> Correct banner-manager PHP notices

includes/templates/template_default/jscript/jscript_framework.php
I note that phpstorm complains about quite a few more minor things in this file, for which I not qualified to "correct"...someone should have a look.
=> remove unnecessary semicolon from jscript_framework

includes/classes/shopping_cart.php
The return value from `zen_get_products_quantity_mixed` can be one of (bool)true, (bool)false or (string)'none'.
Using a simple equality check for the function's return value results in an unwanted entry to the following code section when the product does not have attributes since both 'none' and (bool)true will trigger a condition 'match'.
=> Shipping-cart, use 'exactly equal to' comparison

includes/modules/payment/payeezyjszc.php
... since the `transaction_id` is not present in the response when the transaction is not authorized.
=> Payeezyjszc, correct PHP notice when txn is declined

includes/modules/payment/paypal/paypal_functions.php, includes/modules/payment/paypal/paypalwpp_admin_notification.php, includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php
paypaldp.php:
Line 1162: Check for variable presence prior to use.
Line 1842: (starting) Check for L_ERRORCODE0 presence prior to use.
Line 1851: Check for L_ERRORCODE0 presence prior to use.
Line 1863: (starting) Account for lack of session information when loaded during admin orders' processing.
paypal_functions.php
Line 53: Check for payment_type variable presence prior to use.
Lines 77-87: Move usage of txn_id since it might not be set.
paypal_admin_notifications.php
Lines 172-185: Shipping address might not be present, e.g. a virtual order.  Initialize values for subsequent use
paypalwpp.php
Lines 327-330: Initialize PAYMENTREQUEST_0_PAYMENTACTION prior to use
Line 386-388: PAYMENTREQUEST_0_SHIPTOCITY isn't set for virtual orders.
Line 782: $_GET['token'] might not be present
Line …
=> Fixes #2889: Correcting various PayPal-related PHP notices

includes/modules/payment/paypal/paypal_functions.php, includes/modules/payment/paypal/paypalwpp_admin_notification.php, includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php
paypaldp.php:
Line 1162: Check for variable presence prior to use.
Line 1842: (starting) Check for L_ERRORCODE0 presence prior to use.
Line 1851: Check for L_ERRORCODE0 presence prior to use.
Line 1863: (starting) Account for lack of session information when loaded during admin orders' processing.
paypal_functions.php
Line 53: Check for payment_type variable presence prior to use.
Lines 77-87: Move usage of txn_id since it might not be set.
paypal_admin_notifications.php
Line 49: Use empty() to check variable presence.
Line 103: Ditto
Lines 163-169: 'BUSINESS' might not be populated, check first
Lines 172-185: Shipping address might not be present, e.g. a virtual order.  Initialize values for subsequent use
Line 190: NAME -> SHIPTONAME
Line 195: SHIPTOSTREET2 is an optional entry, check …
=> Fix #2889: Correcting various PayPal PHP notices (zc156)

includes/modules/pages/advanced_search_result/header_php.php
... when `$_GET['keyword']` isn't supplied.  Also simplifies the initial "any variables set" check.
=> advanced_search_result: Correcting PHP notice

admin/options_values_manager.php
Seeing notices similar to the following:
```
[03-Nov-2019 09:31:28 America/Chicago] Request URI: /myadmin/options_values_manager.php?action=add_product_option_values&value_page=6, IP address: redacted
--> PHP Notice: Undefined variable: check_dups in /home/mystore/public_html/myadmin/options_values_manager.php on line 101.
```
=> options_values_manager: Correcting PHP notice

admin/includes/init_includes/init_errors.php, admin/includes/languages/english.php
I was deliberating if the developer disable email switch was simply a duplication of the admin switch, but it has its use, placed in a /local/configure.php.
=> add message stack texts for developer email testing notifications

admin/paypal.php
1. Check for sort/filter fields' presence prior to creating hidden fields.
2. There's no such field as `paypal::payment_status_name`.
3. Use zen_get_all_get_params for split-page links' display.
=> admin/paypal.php, correcting PHP notices

includes/languages/english/gv_faq.php, includes/modules/pages/gv_faq/header_php.php, includes/templates/template_default/templates/tpl_gv_faq_default.php
Ensure that $_GET['faq_item'] is always set to something to support
the switch/case operation.
Assign default values to variables before they are used in the
template.
Use/apply the review of an individual being logged in or possibly
a guest to at least eliminate notices of testing an unassigned variable.
Either place a value of zero or the value of the $_GET['gv_no'].
=> Eliminate php notices when viewing gv_faq

includes/modules/shipping_estimator.php
Seeing logs similar to:
```
[16-Nov-2019 14:22:49 America/Chicago] Request URI: /index.php?main_page=shopping_cart, IP address: 127.0.0.1
#1  require(C:\xampp\htdocs\mystore\includes\modules\shipping_estimator.php) called at [C:\xampp\htdocs\mystore\includes\templates\temp\templates\tpl_shopping_cart_default.php:211]
#2  require(C:\xampp\htdocs\mystore\includes\templates\temp\templates\tpl_shopping_cart_default.php) called at [C:\xampp\htdocs\mystore\includes\templates\temp\common\tpl_main_page.php:190]
#3  require(C:\xampp\htdocs\mystore\includes\templates\temp\common\tpl_main_page.php) called at [C:\xampp\htdocs\mystore\index.php:97]
--> PHP Notice: Undefined index: countries_name in C:\xampp\htdocs\mystore\includes\modules\shipping_estimator.php on line 86.
[16-Nov-2019 14:22:49 …
```
=> Shipping Estimator, correct PHP notice when country not selected

includes/modules/pages/address_book_process/header_php.php
Seeing logs similar to
```
[16-Nov-2019 13:06:56 America/Chicago] Request URI: /my-account/address-book/address-details?delete=59482, IP address: 127.0.0.1
#1  require(C:\xampp\htdocs\mystore\includes\modules\pages\address_book_process\header_php.php) called at [C:\xampp\htdocs\mystore\index.php:36]
--> PHP Notice: Trying to get property of non-object in C:\xampp\htdocs\mystore\includes\modules\pages\address_book_process\header_php.php on line 326.
```
on the 'Confirm deletion' path of the page's processing.
=> address_book_process: Correct PHP notice on address removal

admin/includes/functions/general.php
For each of the dropdowns, there's no space before the 'selected' attribute, generating invalid HTML.
=> zen_draw_date_selector: Missing space between html attributes

admin/includes/functions/general.php, includes/functions/functions_categories.php
replacement of admin while/movenext, add of missing sort_order to admin select, removal of unnecessary quotes around integers (as suggested by a real developer).
Shortly I shall be posting a PR with expansion to this function in conjunction with products to categories, so I thought I should get them the same prior to that.
=> equalise functions zen_get_categories catalog/admin

includes/classes/order.php
Some stores' customizations need to know when the cart-to-order process begins.  Add a notification to indicate that process start, in a similar manner to all the other 'primary' order-related processes.
=> Order class, notification when the cart-to-order process begins

includes/init_includes/init_add_crumbs.php
The module currently includes the `?>` followed by a blank line.
=> init_add_crumbs, remove trailing PHP 'end'

includes/modules/pages/popup_attributes_qty_prices/header_php.php
As identified in [this](https://www.zen-cart.com/showthread.php?225843-popup_attributes_qty_prices-page-missing-NAVBAR-title) Zen Cart posting.
=> Correct 'missing breadcrumb' on popup attr page

includes/templates/template_default/templates/tpl_customers_authorization_default.php
without this change, you get the notice, 
PHP Warning: Use of undefined constant OTHER_CUSTOMERS_AUTHORIZATION_ALT - assumed 'OTHER_CUSTOMERS_AUTHORIZATION_ALT'
=> Fix spelling of alt tag

includes/auto_loaders/paypal_ipn.core.php
The changes provided in #2813 have broken the ipn_main_handler.php since it's got a special loader prefix (paypal_ipn) and the associated auto-loader hasn't been updated to remove the loading of the classes that are now preloaded by application_top.php.
Fixes #2961
=> Remove elements from ipn_main_handler auto-loader

admin/includes/functions/general.php, admin/includes/modules/copy_product_confirm.php, admin/includes/modules/product_music/copy_product_confirm.php
Returns false if unacceptable conditions occur.
Returns true if copy is successful, even if a duplicate causes a skip
Addresses concern raised in https://github.com/zencart/zencart/pull/2971#issuecomment-569550040
=> Refactor zen_copy_products_attributes() to return a status

includes/functions/functions_customers.php
Neither admin nor customer can fix a bad entry in this field once ACCOUNT_SUBURB is set to false, so don't show it in the order data.
Scenario: 
- ACCOUNT_SUBURB is set to true
- Customer enters a bad value in address line 2
- ACCOUNT_SUBURB is set to false
- Bad value cannot be fixed by customer, and appears when their address is shown in order data.
=> If ACCOUNT_SUBURB is not true, don't show suburb

admin/includes/functions/general.php, admin/includes/modules/copy_product_confirm.php
Enabling a watching observer to keep track of additional option-related fields when attributes are copied or removed.
Also adds a notification to indicate that a product is being copied, allowing an observer to copy additional product-related fields, too.
=> Additional attribute-management notifications

includes/init_includes/init_templates.php
In this context, "Admins" are defined as "IP addresses allowed to do maintenance".
Pass `&t=template_name` on the URL and that template will be used for the duration of that Session.
Open multiple private-browsing (aka incognito) browser tabs to use multiple sessions simultaneously with different templates, for comparison.
=> Allow admins to switch templates for dev/testing

includes/templates/responsive_classic/common/html_header.php, includes/templates/responsive_classic/common/main_template_vars.php, includes/templates/responsive_classic/common/tpl_main_page.php, includes/templates/template_default/common/html_header.php, includes/templates/template_default/common/main_template_vars.php, includes/templates/template_default/common/tpl_main_page.php
While the templates aren't useful when accessed directly, and default configs deny access to the files implicitly, if those protections are bypassed the templates will output undesired, unhelpful, and unwanted content. This can lead to unwanted side effects including but not limited to visitor/customer confusion.
=> Prevent invalid template access even when bypassing apache

includes/modules/pages/checkout_payment/jscript_main.php, includes/modules/pages/checkout_payment/jscript_pmt_support.php
This could potentially help make it easier to customize the ajax response markup specific to a given template
(eg minimize changes to zcAjaxPayment class by stuffing wrapper HTML into the javascript used to output the response)
Ref https://github.com/zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c/commit/c45d5f38e27fac19eee3a0012190e8272ce39124#r36733927
=> Split checkout-payment jscript files

admin/includes/auto_loaders/config.core.php, admin/includes/classes/message_stack.php
Creates a method for adding data from the session as that code was removed from the `__construct` and loads the class earlier in processing to support using `$messageStack` and its `add` method earlier in code processing to include providing messages when using early loaded functions.
Doesn't completely fix the referenced issue, but provides a method/process to be able to do so.
=> admin instantiate message stack earlier

includes/functions/functions_email.php
Submitting with $block as an empty string is a way to prevent sending HTML email, but it needs this additional check.
=> Don't add to block array if it's not an array

admin/categories.php
In the last PR @torvista made some good edits to fix html validation errors. Unfortunately IMHO this broke the common Zen Cart lay-out.
These are my changes to "fix" that:
- restore column widths:
- 3 for labels
- 6/9 for inputs
- remove unwanted, and unneeded labels for multi-language input fields. The icons are not labels.
This may be nit picking, but my goal is to create a uniform product, which looks more professional.
=> fix page lay-out

admin/store_manager.php
=> Remove extra '/' in paypal logs directory in Store Manager

admin/category_product_listing.php
excuse me, but this PR addresses two issues.  but they are very close.  as stated here:
https://github.com/zencart/zencart/issues/3038#issuecomment-579799467
if one searches for products or categories and changes the sort order, the search term(s) are lost.  i'm a believer that changing the sort should retain the search.
in addition, my experience is admins more likely search for products, as opposed to categories.  categories once set up are infrequently changed as compared to products.  when someone is searching in the admin, i think they are looking for a product and therefore the search selection should be for product as opposed to a category.
=> keep search when resetting sort and use product sort for search

admin/includes/functions/general.php
default: shows the single category name
added optional parameter to show the full category path
=> zen_get_master_categories_pulldown: allow show full path

admin/includes/languages/english/category_product_listing.php, admin/includes/modules/copy_product.php, admin/includes/modules/copy_product_confirm.php
Allows to open a duplicate product for editing, after the copy
Someone asked for this in the forum, can't find the thread, seemed a good idea.
=> Adminn Copy Product - add edit duplicate checkbox

admin/includes/languages/english/specials.php, admin/specials.php
Main changes:
Originally adding a special by product ID created a new special, then went to the update screen with no option to Cancel (as it required a deletion). Changed that to use the insert screen.
Reformatted to offer Add by pID as equal option (instead of hidden at the bottom of an unrelated infobox).
Status buttons are disabled as links when dates are set.
Clicking on a special in the table list went straight to edit instead of showing the infobox: fixed.
Improved error messages and texts in general.
Make product selection and price fields required.
Fixes for html validation/unbalanced divs etc.
Did not replace spiffycal with datepicker as issues are still outstanding for that.
Todo: table sorting.
=> update for Admin Specials

admin/includes/languages/english/product.php, admin/includes/modules/document_product/preview_info.php, admin/includes/modules/product/preview_info.php, admin/includes/modules/product_free_shipping/preview_info.php, admin/includes/modules/product_music/preview_info.php, includes/functions/functions_prices.php
When the product is not in the cart, the default quantity displayed (buy now quantity) that has a minimum greater than the number of units is adjusted to the quantity identified as a multiple of the units that is greater than or equal to the minimum.  
This also adds two notifications when adding/editing product to identify that the minimum is greater than the number of units and is not a multiple of the units and the other is if the minimum is below the number of units.
The "ideal" situation for a standard cart seems to be for the minimum to be a multiple of the units, either equal to it or a factor of it.  This may not be the case if two different products_id (e.g. 1 and 2) are used to meet the number of units.  Such use would likely affect the admin product entry, but would still …
=> Ensure multiple-qty min/max is enforced in increments of multiples

admin/customers.php
the separation of first name and last name in the customers table has always made searching difficult.  if you had a customer names ```matt king```  and yet, you had many matts and matthews as well as many kings, how can one find the customer?
by separating the keywords into an array, and then searching each of the search fields for each element of that array makes finding that customer way easier IMO.
=> allows multi-word customer search

includes/modules/order_total/ot_coupon.php
Issue https://github.com/zencart/zencart/issues/3069 Not really a "fix" since everything actually works fine but an extra shorthand control structure is removed to help the code style/readability. Also, the function that got this tweak was reformatted to PSR2 standard. Other changes in the file past line 167 are just whitespace related.
=> Tidies ot_coupon credit_selection method

admin/configuration.php
A cart I was working on had the contact us dropdown set to 
Sales <sales@theXXXXXstore.com>, GeneralMailbox <XXXXX@theXXXXXstore.com>
the value shown in the admin configuration page is truncated, which meant it showed up as 
Sales <sales@theABCDEstore.com&amp;g...
Performing the truncation on the **original** string, then running `htmlspecialchars` resolves this issue: 
Sales <sales@theABCDEstore.com>, Ge...
=> Fix display of long config settings when truncated

admin/includes/init_includes/init_cache_key_check.php
in attempting to get my v157 test environment up; i ran into:
too many redirects 301 error 
when trying to get to the admin.  i was able to chase this down to a missing key.  the modified script in this PR, attempts to modify the key; but there is no check if the key is there.
considering we are already looking at this key and attempting to modify it, it only makes sense that we should look if it is there.  unfortunately, i have seen this error on the boards, with blame on the hosting company, and/or .htaccess file; when in theory it could be the store owner who has messed up an install or upgrade.
very easy to test.  delete the key, you will see the error.  apply this patch, and the error disappears.
=> fixes admin too many redirects

admin/includes/functions/admin_access.php, admin/includes/languages/english.php
This change allows people to sort specific menus (tools and reports by default) using an alpha sort rather than the numeric sort which is used by default.  Functionality can be disabled by removing entries from the NAME_SORTED_MENUS define in the main language file. 
The motivation for this change is that these two menus are the most often added to by modders, and the menu lists can quickly become long and unwieldy.
=> Allow override of sort order for admin menus

admin/includes/languages/english/products_to_categories.php, admin/products_to_categories.php
This is effectively a new file.
The version I have been using for years was heavily modified by Conor.
The process of de-Ceon-ing,  to get it more like existing code was very time-consuming (for me) and I ended up revising all of it. It proved unworkable to try and maintain structure equal to the original for comparison references, so it's futile to try.
Still, I believe it was worth the effort to improve this page as I think it is very powerful and under-utilised/not noticed by many users.
I understand this will require a lot of effort to review, but nowhere near what I have invested in it, so please bear that in mind while swearing under your breath. I've tried to do the best I can as a non-professional developer.
There is no commit history as I had to create a new branch for this PR: I …
=> Products to Categories

admin/includes/languages/english.php, admin/includes/languages/english/gv_name.php
Current inclusions order causes gv_sent.php to create notices for this constant.
=> Fixes #2791 TEXT_GV_REDEEM notices

includes/languages/english.php, includes/modules/order_total/ot_coupon.php
I actually found one undefined constant (TEXT_INVALID_COUPON_ORDER_LIMIT) on the way!
Examples (note this is a frigged output to see all the error messages at once):
order of constants in language file now matches useage order.
=> Changes to error messages for adding invalid coupon in checkout payment

admin/includes/stylesheet.css
Long values like table rate shipping rates can now be viewed since they will wrap.  (Before they would cut off at one line.)
=> Allow long configuration values to be displayed

includes/functions/functions_osh_update.php
Otherwise, if multiple status updates occur within a single page-processing, multiple notifications with a status-change indicated  _might_ be issued.
=> zen_update_orders_history: Bypass cache on database query

admin/orders.php
Augmenting the submission for #2818 to pull the query from the database (since the status could have been updated during the `zen_update_orders_status` processing) and to add a 'LIMIT 1' for performance.
=> admin/orders.php: Ensure that order's status information is "fresh".

includes/modules/pages/account_edit/header_php.php
In 1.5.6, the query() function in includes/classes/order.php simplifies the order select by simply doing a `SELECT * `.  This eases the burden when upgrading a shop which has added fields to the orders table.  This change is made in the same spirit.
=> Simplify by doing select *.

includes/functions/functions_email.php
Enables the setting of additional cc:/bcc: addresses.  Note that observers need to check that `$p2` isn't null (i.e. previous release) when attaching to the notification.
=> Update zen_mail, enabling the $mail object to be updated via observer.

includes/autoload_func.php
In
https://github.com/zencart/zencart/pull/3072
A check clause was added to stop a php notice, but it was added around **all** of the case 'objectMethod':
Consequently this never fired the class->method add_session as that item is never in the SESSION array for stacked messages: it's called  "messageToStack".
Also, the previous PR from Wilt added 
if (!is_object($_SESSION[$objectName]))
which causes an php warning as again, SESSION messageToStack does not exist.
In my limited understanding, I don't think that check is needed, as the method messagestack->add_from_session is then used, which **does** check for the correct item (messageToStack).
Works for me, but I am not very aware of the big picture so....
=> Bugfix: Messagestack add_session not working

admin/includes/modules/copy_product_confirm.php
The current copy logic will miss additional fields added to the products table.  Copying all fields (except for the ones requiring special handling) means this fill will need less frequent customization.
=> Copy * instead of specific fields on product copy

includes/modules/pages/ask_a_question/header_php.php, includes/modules/pages/product_free_shipping_info/main_template_vars.php, includes/modules/pages/product_info/main_template_vars.php, includes/modules/pages/shopping_cart/header_php.php
These files have already been changed in 1.5.7 - may as well finish the cleanup.
There are more files that have already been changed but haven't had these fixes: 
**in storefront:** 
column_left.php
column_right.php
column_single.php
create_account.php
meta_tags.php
order_total/ot_coupon.php
order_total/ot_gv.php
payment/authorizenet.php
payment/authorizenet_aim.php
payment/firstdata_hco.php
payment/paypal.php
payment/paypal/paypal_functions.php
payment/paypaldp.php
payment/paypalwpp.php
payment/square.php
product_prev_next.php
products_quantity_discounts.php
shipping/freeoptions.php
shipping_estimator.php
sideboxes/best_sellers.php
sideboxes/order_history.php
sideboxes/whos_online.php
**in admin:** 
featured.php
currencies.php
geo_zones.php
products_price_manager.php
gv_queue.php …
=> Misc cleanup: uppercase SQL, remove obsolete comment and end array on new line

includes/classes/message_stack.php
Provides refactoring of code, then moves the `$_SESSION['messageStack']` 'removal' to the class `size` method so that session-based messages aren't lost on a redirect.
Fixes #3171
=> Messagestack losing session messages (catalog)

admin/includes/languages/english.php, admin/includes/languages/english/attributes_controller.php, admin/includes/languages/english/options_name_manager.php, admin/includes/languages/english/options_values_manager.php, admin/includes/languages/english/products_price_manager.php
Removed the following unused constants from admin side files: 
PHP_DATE_TIME_FORMAT
ICON_METATAGS_ON
ICON_METATAGS_OFF
JS_OPTIONS_VALUE_PRICE
JS_OPTIONS_VALUE_PRICE_PREFIX
JS_PRODUCTS_NAME
JS_PRODUCTS_DESCRIPTION
JS_PRODUCTS_PRICE
JS_PRODUCTS_WEIGHT
JS_PRODUCTS_QUANTITY
JS_PRODUCTS_MODEL
JS_PRODUCTS_IMAGE
JS_SPECIALS_PRODUCTS_PRICE
JS_ZONE
JS_ORDER_DOES_NOT_EXIST
IMAGE_BACKUP
IMAGE_FILE_MANAGER
IMAGE_ICON_STATUS_GREEN_LIGHT
IMAGE_ICON_STATUS_RED_ERROR
IMAGE_LOCK
IMAGE_NEW_FILE
IMAGE_NEW_FOLDER
IMAGE_NEW_TAX_ZONE
IMAGE_PERMISSIONS
IMAGE_RESTORE
IMAGE_UNLOCK
IMAGE_CHECK_VERSION
IMAGE_ICON_LINKED_CATEGORY
ICON_PRODUCTS_PRICE_MANAGER
ICON_CURRENT_FOLDER
ICON_FILE
ICON_FILE_DOWNLOAD
ICON_PERMISSIONS
ICON_PREVIOUS_LEVEL
ICON_RESET
TEXT_DISPLAY_NUMBER_OF_ADMINS
WARNING_BACKUP_CFG_FILES_TO_DELETE …
=> Remove unused constants from admin language files

admin/categories.php, admin/includes/functions/general.php, admin/includes/languages/english/categories.php
Bugfix: from prior PR. When no image is defined, no option is presented to delete it so the POST img_delete is not created/passed and a warning is triggered on the preview page.
After reviewing the three options in the image section (delete /upoad new / use existing), I decided to simplify it, rather than just added isset.
The manual filename entry uses the selected subdirectory, which was not evident (not to me anyway), and no check was made on the filename existing: added check and corresponding messagestack texts.
The image shown on the page was at full size: added parameters to zen_info_image to allow use of responsive class.
Added file info (path, sizes, weight) to image info.
=> Admin: category image changes

admin/includes/languages/english/email_extras.php, email/email_template_order_status.html, includes/functions/functions_osh_update.php
Extends #1670 so that a message may be added to admin order update emails as well.
=> Extend order message to handle admin order updates

admin/includes/functions/functions_help.php, admin/includes/header_navigation.php
Fixes notice about `help_page` parameter reported by @torvista.
=> Remove unused parm from help call; add dashboard help

zc_install/includes/systemChecks.yml
Checking shipping_method causes upgrade issues for users of the popular Advanced Shipper mod.  Changing to another field gives the same level of validation without the issues.
=> Check coupon_name instead of shipping_method

admin/includes/modules/product/collect_info.php
Having autocomplete enabled can block the widget, as shown in this image:
=> Turn off autocomplete for this field

admin/options_values_manager.php
As reported in #2973 This fixes a bug in the options_values_manager.php
This happen on creating a new value when selecting an option from the filter dropdown that contains no values first.
The problem is that the ```$value_id``` sits inside a ```foreach``` that is never fired on empty options. 
Moving the query that sets ```$value_id``` outside the ```foreach``` fixed the error on pressing insert
@torvista : This is the fix we talked about through email
=> Bug fix to prior PR: wrong value_id value in options_values_manager.php

admin/includes/init_includes/init_sanitize.php
Fixes ##2794.  Note that this fix does not include email addresses, which are fixed with val_functions in 1.5.7. 
Please note that this fix is targeted to 1.5.7 only because it assumes the val_functions will fix the email address sanitization.
=> Properly sanitize configs which could contain meta characters

zc_install/sql/updates/mysql_upgrade_zencart_157.sql
zc_install/sql/updates/mysql_upgrade_zencart_156.sql 
did not do the required table changes for upgrade_exceptions
Adding them in the 1.5.7 upgrade.
=> SQL update for upgrade_exceptions table

includes/templates/responsive_classic/common/html_header.php
There are so many versions of JQuery flloating around and this one causes...
***************************
index.php?main_page=product_info&cPath=81_1_3&products_id=1:22 A parser-blocking, cross site (i.e. different eTLD+1) script, https://code.jquery.com/jquery-3.3.1.min.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
*************************
removing  original line 140 solves this problem for our sites.
=> Change from document.write of JQuery to forced CDN load

admin/attributes_controller.php
=> Reverts #2775 - wrongly specifying "missing_file" when saving attributes

zc_install/includes/classes/class.zcDatabaseInstaller.php
Fixes #3278.
While not every possible combination was researched, the SQL statement provided in #3278 is very specific and results in executing the default portion of the function evaluation.  An earlier consideration was to swap the sequence of the `ADD` and `DROP` such that if `DROP` occurred, then the result was the reverse of the field existing in the table so that the function resolved to allow the line to be executed.  This though directly resolves the condition that led to finding the problem...
=> [zc_install] Respect line if field exists and table is being modified

admin/includes/header_navigation.php
Why use an inline style when a Bootstrap helper class is available
=> Change styling on admin help button

admin/includes/stylesheet.css
I found the keepalive "broken" on legacy pages because jAlert.css was not being loaded.
=> fix keepalive alert for legacy pages

includes/classes/shopping_cart.php
`shopping_cart::get_products()`:
When the db query is customized to check only for products which match certain criteria, not aborting this loop will cause incorrect empty entries in the resulting array, and will trigger numerous "index not found" notices.
Checking for validity allows skipping the unnecessary processing of this large section of code and avoids false entries.
=> ShoppingCart: Skip loop through products if db query is empty.

docs/0.about_zen_cart.html, docs/1.readme_installation.html, docs/2.readme_how_to_upgrade.html, docs/important_site_security_recommendations.html
Note: The file docs/important_site_security_recommendations.html should really be removed and replaced with an htaccess redirect to the new location, 
https://docs.zen-cart.com/user/security/security_recommendations/ 
Alternately, the file content could be removed and a simple link could be left in, redirecting the user to this new location.
=> Update old tutorials links to docs site

admin/includes/functions/general.php
These areas of code had been touched/modified, but the last element
did not have a comma included as desired for PSR.
=> Add final comma to modified arrays.

admin/attributes_controller.php
When there are more attributes attached to a product then fit on a page, during editing. We get a form in a form. This will result in the update button no longer working. You can press it, but nothing happens.
=> Bug fix: non working update button in attributes controller

includes/functions/functions_email.php
This allows plugins to provide guidance in setting the outgoing email format when the format cannot be determined or needs other information.
=> Add notifier hook to aid in determining email format

admin/orders.php
disable payment and shipping modules, import db to ZC157, upgrade, view orders: php notice
PHP Notice: Undefined variable: module in /.../admin/orders.php on line 665.
`        if (is_object($module) && method_exists($module, 'admin_notification')) {`
=> orders - fix php notice for rare situation when all modules are disabled

admin/includes/functions/general.php
Allows use of `zen_add_tax` by people who truly want the tax added, irrespective of the value of DISPLAY_PRICE_WITH_TAX_ADMIN.
=> Force adding of tax even if DISPLAY_PRICE_WITH_TAX_ADMIN not set

admin/includes/functions/admin_access.php
Removed the quotes around the integer cast value.
Reverted to the all capital letter mysql NOW.
=> Conform SQL syntax formatting

zc_install/includes/classes/LanguageManager.php, zc_install/includes/languages/lng_info_en_us.php
Use separate files for language info data to allow for easier adding of new languages
=> Installer: separate files for language info data

includes/classes/order.php
If a product's first (or only) attribute is a checkbox-type one, the low-stock check on order completion fails since the associated options_id value is formatted similar to '45_chk21'.
=> Correct type-conversion error during low-stock check

admin/options_name_manager.php
There has been a push to remove any/all comments in files; however,
these comments provide assistance in matching the code to the
onscreen display.  If they are found to be incorrect then they
should be updated instead of simply removed.
=> Restore original code comments

admin/includes/functions/general.php
Where values in a SQL statement are expected to be an integer,
the value is cast to an integer, and was previously surrounded
by single quotes, the additional quotes have been removed and
in a few cases, the value is now cast to `int` and in a few other
cases the `zen_db_input` function sanitization was replaced with
casting to `int`.
There may still be some efficiencies to be gained within a function
to where the original value would be cast to an integer one time
and then used throughout instead of cast to int on each access.
I did not fully touch conversion of SQL statements to use all
capital letters for words such as `SELECT`, `UPDATE`, `SET`, etc...
=> Remove convert string to integer in query.

includes/classes/shopping_cart.php
This removes the excess quotes (string casting) from around
variables that are cast to integers and expected to be stored
in the database as integers.  Previous result was value
(potentially a string) was cast to an integer, then encapsulated
into quotes which makes database treat as a string that then
is to be stored into an integer type datatype so requiring
additional conversion by the database to int. This reduces
the additional two conversions though only one was really
processing related (conversion of string back to integer).
=> Remove conversion from integer cast variables

includes/templates/responsive_classic/css/responsive_mobile.css, includes/templates/responsive_classic/css/responsive_tablet.css
Without these fixes, price and title are displayed on two separate lines for shipping options and for order totals.
=> Fix Responsive Classic styling of shipping options + OT lines

admin/coupon_admin.php, admin/includes/languages/english/coupon_admin.php
=> Coupon admin page shows empty brackets in sidebar if no coupons

zc_install/includes/classes/LanguageManager.php
fixes non-display of language select drop down
https://github.com/zencart/zencart/pull/3355#issuecomment-621050003
=> installer language: add return array

includes/languages/english/checkout_success.php
This define should not have been removed in the cull of #3209.  It is not currently used by the vanilla distribution but is still used by popular older templates.
=> Add back TEXT_SEE_ORDERS which is used by older templates

admin/options_values_manager.php
For consistency, the buttons on the Options Values page need to be changed to reflect Edit versus Update.  The system correctly presents an Update button AFTER the option value is edited.
With Update versus Edit, the user is confused as to where to go to edit the value.  Setting the button to Edit will match the same look on the Option Names page.
=> Button(s) on Option Values Page should be Edit

admin/includes/functions/general.php, admin/includes/languages/english/orders.php, admin/orders.php
I've been using a dirtier version of this for many moons, but based on language id, not code.
So while I've been pre-update modifying it to use language_code, I decided to put it out for persusal, while it's fresh in my mind. Maybe it's not ideal, but it works for me.
Two birds killed with this one, the infobox is modified to allow sending emails directly from it. Stolen from Quick Status Update long ago.
The form action includes the language parameter, and so 
if the admin language is different to the order language, the admin language is changed to the order language for the update/email sending, and restored back to the admin language on the redirect.
Single language sites should see nothing apart from the email option in the infoBox.
I modified the language lookups to allow lookup by …
=> Admin - order status update - send email in order language

includes/extra_datafiles/products_viewed_counter.php
This will speed up db-internal caching and help improve performance on busy sites.
Caveat: the (rarely-used) products-viewed report in the Admin will not have any counter data to display.
Alternative: 3rd party analytics tracking tool is more beneficial.
Root cause: db schema deficiency causes race condition: when a product-page is visited, the record in the products table gets its viewed-counter updated, which makes the db's cache for that row no longer valid, which means it must redo its lookup of that record on the next visit instead of loading it from the db's internal cache. A schema change to put the field in another relational table would prevent the race condition. 
But an external analytics tool can track all this and much more, so better to use that instead.
=> Disable products_viewed tracking by default

admin/category_product_listing.php, admin/orders.php
Fixes #3304
This uses the on-page action ideas offered by @lat9 in #3304, with some variations to use named classes for excluded columns.
Closes #3377 
Closes #3378
=> Make Admin category/products and orders table rows clickable again

admin/includes/classes/split_page_results.php
Hide Prev on page 1 and Next on last page
I decided to hide them rather than not use them, to preserve spacing, maybe.
fixes https://github.com/zencart/zencart/issues/3381
I note that the IDE is complaining that the filename is not the same as the classname....
=> admin: splitPageResults hide PREV when on page 1

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_156.sql, zc_install/sql/updates/mysql_upgrade_zencart_157.sql
As @mc12345678 figured out, DROP wasn't working in prior versions of the upgrade software, so the Zen Cart 1.5.6 drop of the final_price field wasn't actually working. 
Now that that bug has been fixed (in #3282), we can correctly update the schema.  I have removed the DROP from 1.5.6 so upgraders in the future won't do it twice. 
Fixes (truly fixes!) #3278
=> zc_install - Sync SQL updates (tested back to 1.5.1)

includes/templates/template_default/templates/tpl_modules_shipping_estimator.php
fix for php notice when no shipping module selected/available: check existence of array first.
fixes #3433
=> php notice shipping estimate when no modules enabled

includes/templates/template_default/templates/tpl_checkout_shipping_default.php
--> PHP Notice: Undefined offset: 3 in ...\public_html\zencart-157\includes\templates\template_default\templates\tpl_checkout_shipping_default.php on line 56.
--> PHP Notice: Trying to access array offset on value of type null in .....public_html\zencart-157\includes\templates\template_default\templates\tpl_checkout_shipping_default.php on line 56.
=> tpl_checkout_shipping: php notice when undefined icon

admin/orders.php
Remove join on orders_total table for preparing the paginated list of orders.
The join is an expensive operation in this case because of the way the schema is built.
This change relies on the `order_total` field in the `orders` table to show the amount instead.
The only downside to this change is that any mods doing bespoke changes may cause this data to be out of sync if they fail to update the `orders` table when updating `orders_total` entries. They should have already been doing that anyway, but this will expose their deficiency if it exists.
=> Speed up the Admin orders listing (remove query join)

includes/templates/responsive_classic/common/tpl_main_page.php, includes/templates/template_default/common/tpl_box_default_left.php, includes/templates/template_default/common/tpl_box_default_right.php, includes/templates/template_default/common/tpl_box_default_single.php, includes/templates/template_default/common/tpl_main_page.php
This avoids invalid contents due to tampering.
Templates that rely on different units can change the units if needed directly in their own template code that's already being heavily customized.
=> Force template column widths to use px units.

admin/includes/auto_loaders/currency_cron.core.php
Fixes #3455.
Now that admin/includes/application_bootstrap.php does a bunch of includes, the load list for currency cron needs to be slimmed down.
=> Fixes currency_cron failures

includes/modules/pages/featured_products/header_php.php, includes/modules/pages/specials/main_template_vars.php
There are some queries that require providing a specific field or set of fields when splitting the page results.  While this edit does not add all available parameters of the `splitPageResults` class, it does add the next one.  At this time, the parameters to the class are: `$query, $max_rows, $count_key = '*', $page_holder = 'page', $debug = false, $countQuery = ""` with the first two already considered in the previous code.
=> Add count_key for splitpageresults notifier

admin/stats_products_purchased.php
The new query has been used since Zen Cart 1.5.6; it's time to remove the old query.
=> Remove deprecated query

includes/init_includes/init_sanitize.php, zc_install/includes/functions/general.php
Since PHP 5.4 the automatic registering of globals no longer happens, making parsing them unnecessary.
=> Remove deprecated globals code

includes/init_includes/init_sanitize.php
There's no need for these to be strings.
Caveat: upgraders who have written custom code which relies on this variable will get false positives until they change their code to refer to the new variable name and check for boolean.
Two plugins affected: `FAQ Manager` and `360 view`
=> Rename $_SESSION['check_valid'] and switch to boolean

includes/templates/responsive_classic/css/stylesheet_colors.css
The colors for the present responsive_classic stylesheets_colors.css do not meet the standards for readability in accessibility tests.
An example of where it stood can be seen by going to //webaim.org/resources/contrastchecker/.  Enter #FFFFFF on the right and #05A5CB on the left.  The contrast ratio is 2.89:1 which fails all five situations.  Changing #05A5CB to #364fb5 results in a 7.13:1 ratio and passes all situations in which the font might be used.
Also, changing the hover color for the navCatTabs menu is required to up the contrast during a hover over that menu.
There are other colors affected as well.  One would think that red on white would not be a problem.   Yet, replace the #364fb5 with #FF0000 (red), and the ratio is 3.99:1.  Another fail.  Thus, the standard for specials and …
=> Fix Color Contrast in Responsive_Classic

docs/1.readme_installation.html, docs/2.readme_how_to_upgrade.html
Fixes #3316 
I will reiterate my suggestion that these files be replaced by links to the FAQ; it's a bad idea to have two sources of truth.  No one is setting up a Zen Cart on Mars; people *always* have access to the Internet.  The existence of these files is an anachronism.
=> Updating docs directory files to match online FAQs

admin/orders.php
On the order details screen, when using a phone, hide these fields:
- all tax fields and model from the order table 
- customer notified and updated_by from the history table
=> Hide some fields in admin>orders>order details on phones

admin/includes/languages/english/template_select.php, admin/template_select.php, includes/init_includes/init_templates.php
This revising was instigated by my confusion at not understanding the process of using t=template for admin/development use.
This has been resolved by renaming the infoboxes to better reflect their function and adding extra information.
Also:
Associations can only be added when there are un-associated languages still to be added.
An option to remove the t=override was added.
Usual html cleanups.
=> Admin-template select: revision for clarifications

admin/includes/functions/functions_prices.php, includes/functions/functions_general.php, includes/functions/functions_prices.php, includes/modules/payment/paypal/paypal_curl.php, includes/modules/payment/paypal/paypal_functions.php
This in preparation for PHP 8 compatibility:
```
Declaring a required parameter after an optional one is deprecated. 
```
=> Fix function signatures so "no required after optional"

admin/includes/classes/WhosOnline.php, admin/whos_online.php
When inspecting cart of a not-logged-in user it could logout the admin due to session content mismatching due to customizations of catalog session variables.
Fixes #3491
No plans to backport to prior versions.
(While this isn't directly backportable to older versions because it's done in a different file, the concept can probably be replicated easily if it were needed.)
=> Fix admin whos-online logging-out the administrator

includes/templates/responsive_classic/css/stylesheet_colors.css
took color call out of  includes/templates/responsive_classic/templates/common/tpl_header.php and added the proper calls in includes/templates/responsive_classic/css/stylesheet_colors.css for the #navMain link hovers.
=> Color Contrast in #navMain

includes/modules/payment/square.php
if the transaction completes successfully, the `$result->getErrors()` on line 1100 returns something other than an array.  probably empty....  this will address that situation.
=> fixes countable error

admin/paypal.php
last merge #3430 removed the td tags around the infobox...but it was still in a table:
This commit changes the wrapping table for divs.
And updates the header.
=> admin:paypal fix: missing td tags around infoBox

admin/includes/admin_html_head.php, admin/includes/stylesheet.css
This allows one to "drop in" a Bootstrap 3 theme replacement (`bootstrap.min.css` file) from one of the many 3rd party theming sites.
One can also delete the local file if CDN loading is preferred.
=> Admin - Load localized CSS overrides if present

admin/product.php
Fixes #3513 : "Product update after timeout during preview zeros fields"
/cc @lat9
=> Prevent product-preview from zeroing data when stale

includes/modules/pages/product_music_info/main_template_vars_product_type.php
This makes links in the current distribution using target="_blank" ether use the noreferrer or point to "acceptable risk/known" sites.
=> music-product noreferrer for 508 target="_blank"

includes/extra_configures/enable_error_logging.php
Two items here, one is discussed: https://github.com/zencart/zencart/commit/e87391bbf17368be5f4c0d64518c193d9a35434a#r39297222
The other is a result of seeing how this works and making it possible for the operation to remain as it was for those interested.  Kept the default the same as has been provided (to split out the files), but made it admin controllable to be able to make sense of the data in a logical sequence rather than by some sort of file convention.
=> V157 enable error logging static

includes/classes/order.php
The order should know which order it is!
The `$this->orderId` and `$this->info['order_id']` are now set upon querying the db to retrieve the order, and after creation of a new order.
The former approach of passing `$order_id` or `$zf_insert_id` to the various functions in this class will be deprecated in a future version.
=> Add $this->orderId property to order class

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_157.sql
There's no "unique" index on the admin_profiles table.
This means someone can insert multiple entries of the same name, but have different controls associated with them.
Adding a unique index to the table solves the problem of potential ambiguity.
Closes #3540
=> Set unique-index on admin profile names

admin/includes/languages/english/password_forgotten.php, admin/password_forgotten.php
If multiple email addresses exist in admin user accounts, users will be prompted to also provide the username in order to request a reset.
Also, now when failed resets happen an email alert is sent.
Fixes #3546
Default display:
Updated display if duplicate emails exist:
=> Improve admin pwd resets when duplicate emails exist

admin/includes/functions/admin_access.php
Fixes #3572 :
If an admin user requests a password reset,
a temporary password is generated with an expiry token and emailed to them.
The new password can be used until the token expires,
but the old password no longer works ... until the reset token expires.
This `else ... $error = false` resets the `$error = true` triggered earlier when the login attempt is being made against a non-expired reset token: when logging in with the "old" pwd the login against the reset-token fails and is recorded as an error, thus this reset is necessary when the login passes against the original token.
All this becomes moot once the reset-token expires, as it falls back to only checking against the original token.
=> Fix to allow admin pwd to work while reset token exists

admin/includes/modules/dashboard_widgets/SalesReportDashboardWidget.php, admin/includes/modules/dashboard_widgets/TrafficDashboardWidget.php, admin/index_dashboard.php, admin/stats_sales_report_graphs.php
As mentioned here (https://developers.google.com/chart/interactive/docs/basic_load_libs#updateloader), the code loading the chart scripts should be updated.
And while updating I also updated the html head.
More Updates queued for ZC1.5.8
=> Update library loader code to remove google jsapi

admin/reviews.php
Fixes https://www.zen-cart.com/showthread.php?226842-Edits-to-reviews-lost-when-returning-from-preview
- Edit page no longer leads to a Preview screen: updates are saved directly.
- Clicking on a row opens the preview page to see actual review content. Added an Edit button to that screen.
- Preview page "back" button now correctly goes back to the List of reviews
- confirmed that the other buttons ("see review in catalog", and "edit product in admin") go to correct pages
=> Fix admin Reviews page: remove preview-on-save and add Edit button

zc_install/includes/classes/class.zcDatabaseInstaller.php, zc_install/includes/localConfig.php
When doing local dev sometimes it's helpful to override some default configuration table settings, without having to use custom .sql files.
This offers the ability to set those when developer mode is on. For new installs only.
=> Add developer-mode array of configs to override on new installs

includes/classes/class.base.php, includes/classes/traits/EventManager.php
This introduces a new naming convention for Observer class method names which respond to Notifier calls.
This allows IDEs (text editors) to run a (case-insensitive) search for a notifier name and find these methods which relate to those notifiers.
The new pattern/flow is that when a Notifier hook is triggered it will fire an Observer method using the first method name matching the following pattern/order:
1. `snake_cased_name_of_notifier_event()` ... as long as the name starts with "notify_" or "notifier_" (as is the standard convention already)
2. `updateCamelCasedNameOfNotifierEvent()`
3. `update()`
EDIT: 
Function signatures remain the same in all 3 implementations.
=> New Observer method lookup pattern for Notifiers

includes/classes/order.php
Renaming now because an alias has been registered for it starting in v1.5.7
Supercedes and closes #3593
=> Fix misspelling of notifier NOTIFIY_ORDER_CART_SUBTOTAL_CALCULATE

includes/classes/class.base.php, includes/classes/traits/EventManager.php
```
1) ObserverAliasingTest::testObserverAliasing
Non-static method base::getStaticProperty() should not be called statically
```
=> Fix Non-static method base::getStaticProperty() should not be called statically

includes/functions/functions_general.php
Instead of redirecting to the contact us page, redirect to the now built-in Ask a Question page, since the product information is available and can be used to save a step in this transaction.
Fixes #3341
=> Use Ask a Question for call for price

includes/templates/template_default/templates/tpl_modules_address_book_details.php
Current logic will incorrectly show Ms as the salutation if the cart is run for a time with Customer Details > Salutation set to false, then flipped back to true.   Need to check each value explicitly.
=> Explicitly check and set gender based salutations

includes/classes/shopping_cart.php, zc_install/sql/demo/README.txt, zc_install/sql/demo/mysql_demo.sql
- Correct test data set to ensure single product single attribute product has an associated file download
- Update documentation on data set
- Update shopping cart: 
- build attributes array for defaultable attributes products added from listing page.
- correct in cart quantity in that situation.
- permit add from listing page when Buy Now button is used (vs Multiple Products Qty Box). 
Fixes #3626
=> Fixes default attribute issues

admin/includes/header.php
Currently, opening Admin > Tools > Define Pages Editor does not correctly open the define page (instead it shows includes/local/skip_version_check.ini).  First reported here: 
https://www.zen-cart.com/showthread.php?226877-Define-Pages-Editor-only-opens-includes-local-skip_version_check-ini
=> Fix define pages editor

admin/includes/modules/product_music/update_product.php, admin/includes/modules/update_product.php
Support product update if incorrectly formatted date provided 
Addresses: https://www.zen-cart.com/showthread.php?226900-v157-DATE_FORMAT_DATE_PICKER-error-if-date-format-change-and-update-product&p=1370184#post1370184
When storing a product without an available date and using a format other than `yy-mm-dd`, the update action failed because `$dt===false` and `false->format` doesn't exist.
Alternative solutions considered: testing against the existence of the method `format` of the variable `$dt` as part of this resolution, providing admin feedback (likely in the preview area or as a redirect here when such a failure occurs.
The same problem appears to occur if an invalid date format is provided: E.g. if using `dd-mm-yy` for `DATE_FORMAT_DATE_PICKER` and a date is entered as `dd/mm/yy` …
=> V157 admin product avail datepicker vs empty or malformed dates

admin/includes/css/login.css, admin/includes/css/stylesheet.css
Because the file stylesheet.css is now loaded on the page, some tweaks needed to be done to make the look the same as in ZC 1.5.7
=> Update css for login page

admin/includes/functions/html_output.php
`<span class="alert">*</span>` creates layout messes, and still doesn't enforce required entry in fields.
Passing the `required` attribute tells the browser to alert when the field is left empty, and skipping the `<span>` prevents the layout issues.
=> For "required" input fields, use browser validation instead of just text indicator

includes/classes/traits/NotifierManager.php
I discovered this bug associated with 1.5.7 where
if a notifier was observed by more than one observer, then it
seems that either a secondary observer was not executing or
if it was, data was lost... This allows the notifier to be
executed through multiple observers and not lose the data that
was originally transferred.
Issue was seen with installation of both stock by attributes
and products with attributes image swap.  Both were listening
to the notifier: `NOTIFY_ATTRIBUTES_MODULE_START_OPTION` but
only SBA's version was execute while attribute image swap was
not executing and in strict mode there were notices thrown that
variables were not defined/declared...
=> Allow observer to be executed from multiple files

admin/includes/functions/admin_access.php
looks like comparison is done on the wrong side.
8 years ago, ```$page``` was defined as without extension:
https://github.com/zencart/zencart/blob/8e14368e080b910a120f6e2ec3d8a8c7dc1b9f11/admin/includes/init_includes/init_admin_auth.php#L55
7 years ago, a fix was implemented to address those `modders` who included the '.php' in their filename:
https://www.zen-cart.com/showthread.php?207650-Antibugging-in-admin-function-check_page%28%29
only problem is that the constant is the one that has the .php at the end.  so now the comparison is for ```filename.php.php == filename```
this PR fixes that.  and allows ```modders``` to continue to mess up with '.php' in their filenames without unintended negative consequences.
=> check page strip of .php suffix done on wrong side

admin/includes/functions/general.php
... as distributed in various plugins currently, e.g. Sitemap XML.  Credit given to Andrew Berezin (rip).
=> Include zen_cfg_read_only configuration-helper function

admin/template_select.php
This can happen during an upgrade when the custom template has not yet been created.
=> Admin template_select: Prevent notice when template dir does not exist

admin/categories.php, admin/category_product_listing.php, admin/includes/functions/general.php, admin/includes/init_includes/init_category_path.php, admin/products_to_categories.php, includes/classes/categories_ul_generator.php, includes/classes/category_tree.php, includes/classes/site_map.php, includes/functions/functions_categories.php, includes/init_includes/init_category_path.php, includes/modules/categories_tabs.php
Instead of using `'0'` to denote the "top"/root/parent category, use the `TOPMOST_CATEGORY_PARENT_ID` constant.
This will improve clarity in code when checking whether a `category_id == '0'` vs being 0 for some other reason.
It also allows, in theory, for a different parent/root to be set for other reasons (such as an MPTT category structure, or nested sub-groupings .... neither of which are planned/forecasted on any roadmaps).
=> define TOPMOST_CATEGORY_PARENT_ID = 0

includes/modules/payment/paypalwpp.php
Using MySQL 5.7, the cast to float was not being applied to the result of the if statement, but instead basically to the if test and a fatal error to be logged (and possibly/eventually a duplicate order number to be generated). This corrects the casting to apply to whatever result is to be used for `settle_amount`.
Applies to ZC 1.5.6 also...
=> Force conversion to float

includes/modules/payment/paypalwpp.php
Closes #3693 
Finally figured it out... There were a series of commits made for ZC 1.5.7 to add some "functionality" (processing/storage of `$this->amt` when `$this->responsedata['PAYMENTINFO_0_SETTLEAMT']` is not available). In making the commits, there was one mistake made (absence of `$this->` from `$this->responsedata['PAYMENTINFO_0_SETTLEAMT']`; however, it had been accidentally added to `urldecode` in the original commit (https://github.com/zencart/zencart/commit/03bb26ba50d7fecd472ccda0f1affe55e3ad4f37). When this discrepancy was identified (the absence of `$this->` from `$this->responsedata['PAYMENTINFO_0_SETTLEAMT']`), it was corrected with another commit (https://github.com/zencart/zencart/commit/75bb26f76d75753b7c3d70d5e4bc4b19b5becf2a#diff-1b7e5e4f394173368732a571b5c8a0d5R539); …
=> Remove excess $this->

admin/includes/application_bottom.php, app/Console/Commands/MakeDefinesCommand.php, app/Models/PluginControl.php, app/Models/PluginControlVersion.php, app/Providers/AppServiceProvider.php, app/artisan, app/composer.json, app/vendor/composer/autoload_psr4.php, app/vendor/composer/autoload_static.php, includes/application_bottom.php, includes/classes/PluginManager.php, includes/classes/ResourceLoaders/ArraysLanguageLoader.php, includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php, includes/classes/ResourceLoaders/CatalogFilesLanguageLoader.php, includes/classes/ResourceLoaders/FilesLanguageLoader.php, includes/classes/ResourceLoaders/LanguageLoader.php, includes/classes/ResourceLoaders/PageLoader.php, includes/classes/order_total.php, includes/classes/payment.php, includes/classes/shipping.php, includes/classes/template_func.php, includes/init_includes/init_sanitize.php, includes/init_includes/init_templates.php, includes/languages/english.php, includes/modules/require_languages.php, includes/templates/responsive_classic/common/main_template_vars.php, includes/templates/template_default/common/main_template_vars.php, index.php
**move catalog language loading to new resource loader classes**
This includes allowing overrides from plugins
**updates to allow array language files in catalog code**
This includes allowing overrides from plugins
**some initial changes to support plugins in catalog**
Allows plugins to do catalog pages e.g. index.php?main_page=myPluginPage
**language debugging tools in application_bottom.php**
Leaving these in for now. won't show unless a define is present
**move code for creating array files from zcgo to artisan**
** /default ** implies "use these lang defines in the active template"
=> catalog language loading and plugin support 

includes/functions/functions_lookups.php
This allows customizing control over whether a certain product should display an add-to-cart button.
eg: checking "date-available" or stock-on-hand, or other things that might have been customized such as inclusion in a certain marketing campaign, etc.
=> Add NOTIFY_GET_PRODUCT_ALLOW_ADD_TO_CART notifier hook

includes/functions/functions_lookups.php
This allows customizing control over whether a certain product should display an add-to-cart button.
eg: checking "date-available" or stock-on-hand, or other things that might have been customized such as inclusion in a certain marketing campaign, etc.
Appends to https://github.com/zencart/zencart/pull/3698
=> Add NOTIFY_GET_PRODUCT_ALLOW_ADD_TO_CART notifier hook (part 2)

includes/classes/observers/auto.non_captcha_observer.php, includes/functions/password_funcs.php
All pre PHP 7 checks can be removed now that we are fully PHP7. 
Fixes #2586.
=> Remove old PHP checks

admin/options_values_manager.php
The drop down has no default so $GLOBALS[$name] was used in function zen_draw_pull_down_menu.
But this only works/is set when the option name has at least one values associated. 
So after selecting an option name with no values as a filter, the add value dropdown would always show the first option, not the one selected.
This is the simplest fix, as I don't know how $GLOBALS[$name] gets set when there **are** values associated with a name....
=> admin: option name manager, set selected in drop down

admin/includes/application_bootstrap.php, app/Providers/AppServiceProvider.php, includes/application_top.php, includes/illuminate_bootstrap.php
Allow Laravel to take over reporting/logging but only if allowed to
and only during the lifetime of a Laravel request cycle
on return and if we are continuing with Zen Cart, reset the error handler
and reporting levels
=> Fix error logging/reporting

admin/includes/languages/english/lang.plugin_manager.php, includes/classes/PluginManager.php, includes/classes/PluginSupport/BasePluginInstaller.php, includes/classes/PluginSupport/Installer.php, includes/classes/PluginSupport/ScriptedInstaller.php, includes/classes/TableViewControllers/PluginManagerController.php
For upgrades we currently only allow a class based scripted Installer class and not a plain sql file to process any changes to the 
database.
This is done for simplicity. 
If we allowed plain sql files then there would need to have a sql file for each upgrade version step, and process these sequentially 
with the possibility of failure at each step. 
Using a ScriptedInstaller class throws the responsibility on to the plugin maintainer to write code that check the version being installed and the currently installed version and intelligently upgrading any tables/alter tables and data seeding.
=> updates to allow plugin upgrades

includes/classes/message_stack.php
... deferring the 'reset' of the session-based message-stack until the message-output phase.
The issue reported was a result of 'missed functionality', i.e. that the class' `size` method might be called without a subsequent `output` one.  This change simply moves the session-based messages' reset to the `output` method.  
The assumption is that since the messages are to be output that we've entered the rendering phase of a page-load so any session-based messages will either be output at this time or are no longer pertinent.
=> Fixes #3740

includes/classes/payment.php
In the refactoring of the payment module, the determined `$function` was incorrectly passed to the associated function instead of the data that was passed into the parent function (`$zf_order_id`) causing issues as identified in: https://www.zen-cart.com/showthread.php?226988-parameter-zf_order_id-is-not-being-transferred-into-the-after_order_create-method.
=> $function incorrectly provided for $order_id

admin/plugin_manager.php, app/Providers/AppServiceProvider.php, includes/classes/PluginManager.php
Currently code would die with a fatal error
Move inspectAndUpdate to service provider.
if zc_plugins doesn't exist the plugin manager page will throw a warning
leaving for now as I have a refactor branch that will address
=> Safety code when zc_plugins directory has been removed or never existed

admin/developers_tool_kit.php, admin/includes/languages/english/developers_tool_kit.php
Adds a selection to the All Files search to allow for searching the zc_plugins directory structure.
Fixes #3718
=> Extend dtk all-files lookup to include zc_plugins

admin/modules.php, includes/classes/ResourceLoaders/LanguageLoader.php
Function name is misspelled and non existent return value is checked.
=> Fixes shipping module installation

admin/orders.php
i think these conditionals are better for Card on File transactions; enforcing a standard on other payment modules seems somewhat arbitrary.
furthermore, i left in this masking function.  however, again enforcing a standard as to how a payment module stores a representation of a credit card number seems heavy handed.  i think masking should only be presented for a valid credit card number.
finally, perhaps we can refactor the ```cc_validation``` class at some point and allow direct calling of the ```is_valid``` method for use here?
=> Admin orders suppress empty payment details display 

admin/category_product_listing.php
Removes the query join to products_to_categories, which is unnecessary in this context, and returning false empty searches.
Fixes #3729
=> Allow admin product search to find products even with invalid master_categories_id

admin/category_product_listing.php
p2c is still needed in order to show cross-linked categories
Updates #3786
Updates fix to #3729
=> While admin product search ignores master cat, product listing needs it

admin/includes/functions/general.php
... essentially removing the pre-rounding done in the admin that causes various calculations to "go off".
Suggest backport to zc157.
=> Align admin's zen_add_tax with the storefront calculations

includes/application_top.php
Identified in https://www.zen-cart.com/showthread.php?227001-PHP-Notice-Undefined-index, there is the possibility that `$spider_flag` is never set, which is then used/called/expected in https://github.com/zencart/zencart/blob/d0c6806c0ced2ac8f3d5c28369e76e70ac99a6d8/includes/application_top.php#L223.  This can happen first if `Force Cookie Use` is set to `true`, and then even if it is set to a value `!= 'True'` then if `block spiders` is `!= 'True'` the variable `$spider_flag` is not set and can/will cause an issue at the above line.
`$spider_flag` is initially set to `true` so that later in the above code, the visit is excluded unless the session is identified as being started by a non-"spider" visitor.
Alternatively, it seems that …
=> Ensure $spider_flag is set

admin/includes/init_includes/init_sessions.php, includes/init_includes/init_sessions.php
The way Zen Cart operates this will almost always need to be set to `lax`, so no config switch is being added for it at this time.
Fixes #3721
=> Set the samesite cookie parameter

admin/category_product_listing.php
the store side has a better product search than the admin side.  similar to the work done on the admin customer search, this makes much more sense to me, and makes it easier for admins to find products.
it would be nice to more mimic the store side but the store side function ```zen_parse_search_string``` is not available.
```$keywords``` is assigned well above this line, and i do not see it in use in this script.
finally, it might behoove us, considering the plethora of functions inherent in ZC, to consider refactoring this logic into a function; the function takes 2 arrays as inputs: column names and keywords; and returns a find string for use in all of these areas.
i see this var ```$keywords``` used in the following scripts, and somehow having a function that creates the where clause …
=> improve admin product search

admin/includes/classes/object_info.php
It would be faster and still probably completely safe to just return a string without checking but just in case I added a check.
Doing this means that we can use the Type compatibility check in phpStorm (and other debuggers).
=> Update objectinfo annotations to avoid code-inspect false-positives

includes/classes/db/mysql/query_factory.php
This method never caches anything anyway, so we don't need all the caching args.
ALERT: Some plugins may need to be changed if they passed these (ignored) arguments, but removing the arguments in plugin code remains backward compatible since these were optional args anyway.
Also one could argue that we've never needed the `ExecuteRandomMultiNoCache()` method at all. I'd like to remove it, but not sure whether it's actually used by any plugins. Deprecating it here for now.
=> Shorten args for ExecuteRandomMulti and deprecate ExecuteRandomMultiNoCache

admin/invoice.php, admin/orders.php, admin/packingslip.php, admin/reviews.php, includes/classes/order.php, includes/functions/database.php, includes/functions/functions_general_shared.php
It's only being used for screen output, not db-related.
Therefore should use zen_output_string_protected() instead.
=> Deprecate zen_db_output()

includes/modules/attributes.php
Fixes #3734
Understand that there may be other considerations because the internal `$selected_attribute = false;` is no longer in the inner loop and that this may be placed on hold while still mulling it over.  Either an alternate value/variable for dropdowns, moving code back to elsewhere within the inner loop, acceptance that a value may be retained in the inner loop that may affect an altered attributes interface, or...
=> Allow dropdowns to display a defaulted value.

includes/modules/order_total/ot_gv.php
The `tax_groups` element is a key-value array of `group_name=>rate`.
Built in 
https://github.com/zencart/zencart/blob/0ef00490a5cde1805d1cea5ae0175d057612a8fc/includes/functions/functions_taxes.php#L149
.. which is called by
https://github.com/zencart/zencart/blob/0ef00490a5cde1805d1cea5ae0175d057612a8fc/includes/classes/order.php#L544-L545
... which in turn sets it into `$order->info['tax_groups']` as used in ot-gv:
https://github.com/zencart/zencart/blob/0ef00490a5cde1805d1cea5ae0175d057612a8fc/includes/modules/order_total/ot_gv.php#L332-L334
=> Fix undefined index tax_groups error in ot-gv

includes/languages/english/brands.php, includes/templates/template_default/templates/tpl_brands_default.php
The initial implementation didn't account for stores that have
- No brands defined
- No brands featured
- No brands other than those featured
=> Brands: Correcting PHP notices and empty sections
