admin/attributes_controller.php

fixes https://github.com/zencart/zencart/issues/3511
I note that in days of old: up to and including 13/1/2020, this default was set by a variable.
14/1/2020 it became hard coded after a merge.

attributes controller: change  "delete image" default to no

---

docs/whatsnew_1.5.7.html

With the contrast changes and target="_blank" fixes, we now comply with basic Accessibility Standards.

Add Accessibility Compliance to What's New

---

docs/whatsnew_1.5.7.html

Simplify instructions around responsive_classic

---

includes/functions/whos_online.php

Possibly closes #3421
/cc @mc12345678

Exclude ajax pages from whos-online updates

---

includes/templates/responsive_classic/common/tpl_header.php
includes/templates/responsive_classic/css/responsive_mobile.css
includes/templates/responsive_classic/css/stylesheet.css
includes/templates/responsive_classic/css/stylesheet_colors.css

Show shopping-cart indicator when cart has contents

---

admin/attributes_controller.php

Fix search form in attributes controller

---

admin/includes/languages/english/invoice.php
admin/includes/languages/english/orders.php

remove duplicate constants

---

admin/includes/languages/english/countries.php
admin/includes/languages/english/layout_controller.php
includes/languages/english/checkout_success.php
includes/languages/english/extra_definitions/document_general.php
includes/languages/english/gv_faq.php

missing space, deprecated tags, br / to br as an aside

Language file - misc - constants

---

admin/includes/languages/english/extra_definitions/orders_status_updates_admin.php
admin/includes/languages/english/invoice.php
admin/includes/languages/english/orders.php
admin/includes/languages/english/packingslip.php
includes/languages/english/checkout_process.php
includes/languages/english/extra_definitions/orders_status_updates.php

as per 
https://www.zen-cart.com/showthread.php?226687-Use-of-quot-order-quot-instead-of-quot-invoice-quot&p=1368580#post1368580

"Invoice" to "Order"

---

admin/product.php

Check needs to be inverted

---

admin/includes/modules/document_general/preview_info.php
admin/includes/modules/document_product/preview_info.php
admin/includes/modules/product/preview_info.php
admin/includes/modules/product_free_shipping/preview_info.php
admin/includes/modules/product_music/preview_info.php

so on back also custom fields are filled in collect info page. Without the need of editing these files

Make product preview db query more generic

---

includes/languages/english/ask_a_question.php
includes/modules/pages/ask_a_question/header_php.php
includes/templates/responsive_classic/templates/tpl_document_general_info_display.php
includes/templates/responsive_classic/templates/tpl_document_product_info_display.php
includes/templates/responsive_classic/templates/tpl_product_free_shipping_info_display.php
includes/templates/responsive_classic/templates/tpl_product_info_display.php
includes/templates/responsive_classic/templates/tpl_product_music_info_display.php
includes/templates/template_default/templates/tpl_ask_a_question_default.php
includes/templates/template_default/templates/tpl_document_general_info_display.php
includes/templates/template_default/templates/tpl_document_product_info_display.php
includes/templates/template_default/templates/tpl_product_free_shipping_info_display.php
includes/templates/template_default/templates/tpl_product_info_display.php
includes/templates/template_default/templates/tpl_product_music_info_display.php

`&products_id=` is now `&pid=`

Shorten GET param for new ask_a_question module

---

admin/profiles.php
admin/users.php

Correct inclusion of stylesheet

---

admin/includes/admin_html_head.php
admin/includes/javascript/product.php
admin/includes/javascript_loader.php
admin/product.php

This update adds the ability to load multiple javascript and/or css files. The have to start with the page name you want the file to load on.
For example ```admin/includes/javascript/product_extraJscript.js``` will now load on product.php.
The modification will make it easier for mod makers to include their css or javascript to a page.
Also added the ability to load php javascript files

Admin: Add ability to handle multiple per-page javascript/css files

---

includes/classes/FileSystem.php
includes/classes/PluginManager.php
zc_install/sql/install/mysql_zencart.sql
zc_install/sql/updates/mysql_upgrade_zencart_157.sql
zc_plugins/DisplayLogs/v3.0.0/manifest.php

Added field to track the Zen Cart contribution ID.
This will allow call home to find new version updates
Increase some field sizes 
Added helper function to FileSystem class to allow loading
of plugin local ccs/js file.
addresses #3563 and and #3564

Updates to plugin infrastructure

---

admin/includes/classes/Paginator.php

use cmd rather than main_page for paginator

---

admin/includes/application_top.php
includes/application_top.php
includes/autoload_func.php
includes/classes/InitSystem.php

Add back ability to debug autoloader.

---

admin/define_pages_editor.php
admin/includes/header.php
index.php

PHP Warning: Invalid argument supplied for foreach() in /admin/includes/header.php on line 77.

Fix PHP Array Warning

---

includes/classes/class.base.php
not_for_release/testFramework/unittests/support/zcObserverAliasTest.php
not_for_release/testFramework/unittests/support/zcObserverAliasTestObject.php
not_for_release/testFramework/unittests/testsSundry/AdminLoggingTest.php

simple aliasing for notifier eventID

---

admin/countries.php

- Sorts to show enabled countries first
- Country Name column is now a fixed-width so columns don't jump around when changing status
Both of these changes make it much faster/simpler to manage enabled/disabled countries status

Countries editor: sort by active

---

admin/includes/languages/english/categories.php

used in messages re adding a category filename manually.

Add missing language defines for manual add of category images

---

includes/templates/responsive_classic/templates/tpl_checkout_confirmation_default.php
includes/templates/template_default/templates/tpl_checkout_confirmation_default.php

Ensure stock_check array entry is set prior to display

---

includes/modules/pages/checkout_confirmation/header_php.php
includes/modules/pages/checkout_shipping/header_php.php

Don't double sanitize customer comments

---

includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php
includes/templates/responsive_classic/templates/tpl_modules_products_featured_listing.php
includes/templates/responsive_classic/templates/tpl_modules_products_new_listing.php

extraneous quote - fixes #3640

new/featured/all pages not adding to cart.

---

includes/modules/pages/checkout_success/jscript_main.php

Missing javascript.  Checkout with a coupon and you'll see the link on the checkout success page gives a JS error.

Coupon Popup link on checkout success page does not work

---

admin/includes/functions/functions_help.php

Recommended for backport to 1.5.7a.

Add help link for plugin manager

---

admin/categories.php
admin/category_product_listing.php
admin/includes/functions/functions_metatags.php
admin/includes/modules/copy_product.php
admin/includes/modules/document_general/collect_info_metatags.php
admin/includes/modules/document_product/collect_info_metatags.php
admin/includes/modules/product/collect_info_metatags.php
admin/includes/modules/product_free_shipping/collect_info_metatags.php
admin/includes/modules/product_music/collect_info_metatags.php
admin/includes/modules/product_music/copy_product.php

6 functions reduced to 2
Might remove these remaining 2 in a later refactor related to classes

Refactor metatags functions to reduce duplication

---

admin/includes/header.php
admin/includes/init_includes/init_languages.php

In order for the new file structure in the laguages to work with multiple languages, two files needed a little update.

Fix multi language capability

---

admin/includes/languages/english/lang.email_extras.php

I think that during the automatic conversion of this file, the date function got mangled.

fix date function in lang.email_extras.php

---

includes/classes/TableViewControllers/PluginManagerController.php

Otherwise you would have to re-enable a plugin just to uninstall it.

The uninstall option should be present in the disabled state

---

admin/includes/init_includes/init_templates.php
admin/template_select.php
includes/functions/functions_templates.php

Removes all non-pagination-related queries into separate functions

Extract template functions from template_select

---

admin/includes/application_bootstrap.php
includes/application_top.php

allow plugins to load from extra_configures directory

---

includes/classes/FileSystem.php

This helps avoid dozens of warnings.

Check if directory before proceeding

---

includes/functions/functions_products.php

Remove product_status from query using p.*

---

includes/classes/order.php

Comma after last item, closing paren on new line per coding standard so people can easily add items.

Make arrays easy to add to

---

admin/category_product_listing.php

... as identified in [this](https://www.zen-cart.com/showthread.php?226934-Status-button-not-showing-on-mobile&p=1370451) Zen Cart posting.
Suggest back-porting to zc157.

Admin categories/products listing, display Status ... always

---

includes/templates/responsive_classic/common/tpl_columnar_display.php
includes/templates/template_default/common/tpl_columnar_display.php

- is_array returns a boolean, not suitable for a > comparison.

Correct tpl_columnar_display.php comparison

---

includes/languages/english/product_reviews_write.php
includes/modules/pages/product_reviews_write/header_php.php
includes/templates/responsive_classic/templates/tpl_product_reviews_default.php

Ref: https://www.zen-cart.com/showthread.php?209670-reviews-confirmation

Display a confirmation that a product review was received

---

includes/classes/db/mysql/define_queries.php
includes/modules/also_purchased_products.php

Fixes #3805 - error in removing hardcoded limit.

Remove LIMIT from also purchased query

---

admin/coupon_admin.php

Undefined variable error caused by typo

---

admin/options_values_manager.php

incorrect variable was used so the column was blank.

sort order missing during delete

---

admin/category_product_listing.php

I simplified the message instead of printing the array.

Code referenced non-existent field

---

includes/classes/observers/auto.non_captcha_observer.php

Prevent store URL from accidentally being treated as spam

---

includes/modules/pages/index/header_php.php

... as identified in [this](https://www.zen-cart.com/showthread.php?227008-Deleted-category-results-in-noindex-nofollow) Zen Cart bug report.
Suggest back-port to zc157; the base module had no change in the transition to zc158.

Corrects missing/disabled categories result in noindex,nofollow

---

includes/modules/pages/index/header_php.php

... using the same changes as [this](https://github.com/zencart/zencart/pull/3819) Pull Request.

zc157: Address missing/disabled categories' display on the storefront

---

includes/classes/db/mysql/define_queries.php
includes/modules/also_purchased_products.php

Fixes #3805 - also purchased products broken

---

admin/includes/application_bootstrap.php

As was done in 1.5.8. @zcwilt Please review and merge - need this in 1.5.7a.

Load extra_configures as well as extra_datafiles

---

includes/modules/pages/document_general_info/jscript_textarea_counter.js
includes/modules/pages/document_product_info/jscript_textarea_counter.js
includes/modules/pages/product_free_shipping_info/jscript_textarea_counter.js
includes/modules/pages/product_info/jscript_textarea_counter.js
includes/modules/pages/product_music_info/jscript_textarea_counter.js

Add space in message before # of characters allowed

---

includes/classes/order.php

initialize attributes array

---

admin/downloads_manager.php
admin/includes/languages/english/lang.downloads_manager.php

Warn if downloadable product misconfigured

---

laravel/app/Console/Commands/ZencartConvertDefines.php
laravel/app/Console/DefinesConverter/DefinesNodeVisitor.php

Move to use nikic/php-parser for analyzing input files
and building of define value

Update to artisan command for converting legacy language files.

---

includes/modules/order_total/ot_gv.php

Note: looks as though ot_coupon has the same issue (l. 106) but wanted to get this one in the pipeline first.

undefined variable $tax

---

admin/includes/functions/functions_help.php

Dynamically determine whether to show help for categories or categories_products

---

admin/includes/modules/copy_product_confirm.php

v157: Remove duplicate notifier on product duplication (fixes #3865)

---

admin/customers.php
includes/classes/Customer.php

replace hardcoded ```4``` with ```$status```
see #3915

Fix bug: if the value is 0, the field value is empty. 

---

includes/modules/responsive_classic/ezpages_bar_header.php

You may not want ezpages in your header bar in desktop view, but you still need them in
the hamburger menu.

EZPages display control for mobile

---

admin/includes/functions/html_output.php

This css class was in the wrong place, and should only be in the span on line 286

remove extra alert-danger from class

---

admin/ezpages.php
admin/includes/css/stylesheet.css
admin/includes/functions/general.php

Updates to ezpages.php

---

admin/manufacturers.php

Updates for manufacturers.php

---

admin/salemaker_info.php

Current code gives a 500 error due to old style language file reference.

Finish language refactoring for salemaker_info

---

includes/modules/shipping/flat.php
includes/modules/shipping/freeoptions.php
includes/modules/shipping/freeshipper.php
includes/modules/shipping/item.php
includes/modules/shipping/perweightunit.php
includes/modules/shipping/table.php

Since there were no changes 1.5.7 to 1.5.8, I recommend back-porting to 1.5.7.

Add update_status method to shipping modules. Fixes #3874.

---

admin/sqlpatch.php

Correct strict PHP error

---

admin/countries.php

Updates to countries.php

---

includes/init_includes/init_templates.php

Current code does not work.  This works as tested with 
http://localhost:8888/gh_demo_158/index.php?main_page=index&t=classic
then 
http://localhost:8888/gh_demo_158/index.php?main_page=index&t=off
Suggested for backport with low priority.

Simplify private testing for templates

---

includes/classes/shopping_cart.php

https://github.com/zencart/zencart/pull/3954#commitcomment-42856155

properly init var

---

admin/includes/css/stylesheet_print.css
admin/includes/header_navigation.php
admin/orders.php

Fixes unwanted separators and borders, removes unwanted display content from printout.

Improve printed order appearance

---

admin/stats_customers_referrals.php

- Only show the title Discount Coupon ID # if there is actually a coupon on the order
- Use the label "View" rather than "Edit" for the button opening the order.

Small improvements to the Customers Referral report

---

admin/banner_manager.php

Updates to banner_manager.php

---

admin/invoice.php
admin/packingslip.php

Add images to invoice and packing slip

---

admin/includes/modules/dashboard_widgets/SalesReportDashboardWidget.php
admin/stats_sales_report_graphs.php

Implements changes discussed in https://www.zen-cart.com/showthread.php?227300-Sales-report-with-graphs-non-english-characters-encoded

Reduce over-encoding of non-english characters in graph output

---

includes/modules/create_account.php
includes/modules/pages/login/header_php.php

Simplify login path

---

admin/mail.php
includes/functions/audience.php

Backporting of #4026 to 1.5.7.

[157] Corrections in "audiences" processing

---

includes/.htaccess

Allow woff2 to be served

---

admin/ezpages.php

Fixes #4033 
- standardize names of forms to reflect what they do
- correct check and hidden variables in footer form.

Correct admin/ezpages handling of footer status

---

includes/modules/create_account.php
includes/modules/pages/login/header_php.php

[158] Simplify login path

---

includes/modules/payment/paypalwpp.php

For additional information, see [this](https://www.zen-cart.com/showthread.php?220781-One-Page-Checkout-Support-Thread&p=1374106#post1374106) Zen Cart posting.

[157] Additional notification for paypalwpp

---

includes/functions/functions_general.php

... correcting an HTML validation issue when used.

[157] Add space between HTML attributes for zen_field_length

---

includes/classes/FileSystem.php

Ensure correct sub-directory for plugin relative path

---

admin/includes/application_bootstrap.php

Re-enable use of /admin/includes/local/configure.php without the duplicate-constant warnings at the top of each page:
```
Notice: Constant HTTP_SERVER already defined in C:\xampp\htdocs\mysite\myadmin\includes\configure.php on line 17 
Notice: Constant HTTP_CATALOG_SERVER already defined in C:\xampp\htdocs\mysite\myadmin\includes\configure.php on line 33 
Notice: Constant HTTPS_CATALOG_SERVER already defined in C:\xampp\htdocs\mysite\myadmin\includes\configure.php on line 34 
Notice: Constant ENABLE_SSL_CATALOG already defined in C:\xampp\htdocs\mysite\myadmin\includes\configure.php on line 39 
Notice: Constant DIR_WS_CATALOG already defined in C:\xampp\htdocs\mysite\myadmin\includes\configure.php on line 46 
Notice: Constant DIR_WS_HTTPS_CATALOG already defined in …
```

[157] Prevent duplicate-constant warnings when using /admin/includes/local/configure.php

---

includes/functions/functions_categories.php

fixes https://github.com/zencart/zencart/issues/3891

fix for non-display of category dropdown for option values sorter

---

admin/orders.php
admin/reviews.php

Small fix to prevent JavaScript error.  Fixes #4058.

[157b] Remove init() calls from files which no longer define this function

---

admin/specials.php

incorporates previous PRs (which seem correct to me), and corrects undefined index.
Closes #4075 
Closes #4076 
can we get some notifiers in here?  i'm tired of modifying this code every release and doing it on featured as well.   
lets think of the community as well as ourselves.
i am not a fan of this:
https://github.com/zencart/zencart/blob/3d19adc47e8030fc02498a9bef707ea09afd8194/admin/specials.php#L318-L320
i like the comment, but just because there is a `global` setting and someone wanted it sorted by model?  how about those people that do not use model?  can we think of them?

#4075, #4076 and addresses undefined index

---

admin/store_manager.php

Undefined variable: one change.
Html changes : moved forms and hidden fields inside td, removed deprecated tags, put closing form tags in php,  removed unneeded br

Store Manager. Fix php notice and html validations

---

admin/invoice.php

Make invoice comments wider to use less paper

---

admin/includes/init_includes/init_report_all_errors_admin.php
zc_install/sql/updates/mysql_upgrade_zencart_158.sql

move report all error config values to update script

---

admin/products_price_manager.php

Correct empty "for"s where labels were used incorrectly.
Missing id
Remove readonly from select
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly
br / to br

Products Price Manager, minor HTML corrections

---

admin/salemaker.php

while i was here....
i do not know why, but i greatly prefer css buttons to those zen_image gifs.  seems like these 2 were hanging around...

Salemaker - replace zen_image with css buttons

---

includes/classes/Customer.php
includes/modules/create_account.php
zc_install/sql/install/mysql_zencart.sql
zc_install/sql/updates/mysql_upgrade_zencart_158.sql

Log customer IP for fraud/spam/abuse tracking, and delete if customer requests to be forgotten.

Log customer IP for fraud tracking

---

admin/includes/functions/extra_functions/load_php_polyfills.php

Fixes issue reported by @torvista in https://github.com/zencart/zencart/pull/4142 comment.

Remove leftover file

---

admin/orders.php

Recommended for backport to 1.5.7.

Fixes SQL statement error

---

admin/developers_tool_kit.php

[158] Find zc_plugins when searching Catalog/Admin or Admin

---

admin/developers_tool_kit.php

Updating zc157 to find `zc_plugins` files when searching for All files Catalog/Admin or Admin as well.
Ref: #4165

[157] Find zc_plugins files for 'all'/'admin' DTK searches

---

admin/includes/modules/dashboard_widgets/RecentCustomersDashboardWidget.php
zc_install/sql/install/mysql_zencart.sql
zc_install/sql/updates/mysql_upgrade_zencart_158.sql

Improve slow query: customers list in Admin Dashboard

---

includes/modules/create_account.php

similar to
https://github.com/zencart/zencart/issues/2687

create account: fix for php notice when fax not in use

---

admin/category_product_listing.php

Additional notifications added for the admin's Category/Product listing, enabling an observer to
- Handle additional form-actions
- Insert columns into the _products_ listing, both before and after the Quantity column

[158] Additional notifiers for category_product_listing.php

---

admin/category_product_listing.php

[157] categories_products_listing notifiers (again)

---

admin/modules.php

Note: origin issue not exploitable without knowing the admin directory name and being fully logged in as a valid administrator.

Fix CVE-2021-3291

---

admin/includes/modules/copy_product.php

move admin module copy product notifier outside of conditional

---

includes/functions/html_output.php

Correcting zen_image default sizing

---

admin/downloads_manager.php

Found during investigation of #4089.

Display warning icon even if product not selected

---

admin/options_name_manager.php

form_id gets used when not set.  and i'm a fan of passing an empty array to a function as opposed to converting the empty string to an empty array in the function prior to processing it.

Pre-declare form_id

---

admin/category_product_listing.php

Add $product to data notifiers so global not required in observers.

Add $product to notifier in category_product_listing.php

---

docs/changed_files-v1-5-7.html
docs/whatsnew_1.5.7.html

Small doc fixes and improvements for 1.5.7c

---

admin/modules.php

At the end of the code three lines are duplicated. This PR removes them

Remove double closing tags

---

includes/templates/responsive_classic/common/html_header.php
includes/templates/template_default/common/html_header.php

I needed to do this long ago for some obscure issue with a payment module, but it is also recommended (and highlighted by Edge Developer Tools Console Issues).
https://webhint.io/docs/user-guide/hints/hint-meta-charset-utf-8/?source=devtools

Move charset to start of head

---

includes/functions/functions_categories.php

no reason to continue processing once found in category.

early-return once product found in category

---

admin/includes/classes/AdminRequestSanitizer.php

Fix typo in debug output

---

admin/customers.php

Corrects data in customers infobox

---

includes/modules/pages/product_reviews_write/header_php.php
includes/templates/template_default/templates/tpl_product_reviews_write_default.php

For cases when form has an error/does not get submitted (reg: reCaptcha).

reviews write: make rating and review text sticky.

---

admin/attributes_controller.php
admin/banner_manager.php
admin/categories.php
admin/category_product_listing.php
admin/countries.php
admin/customers.php
admin/downloads_manager.php
admin/ezpages.php
admin/featured.php
admin/includes/css/stylesheet.css
admin/includes/languages/english/lang.layout_controller.php
admin/includes/modules/dashboard_widgets/WhosOnlineDashboardWidget.php
admin/includes/modules/document_general/preview_info.php
admin/includes/modules/document_product/preview_info.php
admin/includes/modules/product/preview_info.php
admin/includes/modules/product_free_shipping/preview_info.php
admin/includes/modules/product_music/preview_info.php
admin/manufacturers.php
admin/options_name_manager.php
admin/orders.php
admin/reviews.php
admin/specials.php
admin/sqlpatch.php
admin/store_manager.php

This PR is ment to move a lot of the "style" attributes in to CSS classes. For now I limited this to:
- text color
- font weight
- vertical alignment
Changes are only made on the admin files.
The new classes have been added to the stylesheet

Move styles to css classes

---

includes/functions/functions_search.php

addresses open parenthesis in search term #4302

---

includes/functions/functions_search.php

based on conversation in #4343, this makes sense to me.

add var to indicate how to start build_keyword_search

---

admin/coupon_admin.php

leading ampersand creates notice in admin/includes/classes/split_page_results.php on line 296
PHP Notice: Undefined offset: 1

remove extra ampersand added during previous refactor

---

admin/invoice.php
admin/packingslip.php

Left align text fields and headers in invoice and packing slip

---

includes/templates/responsive_classic/templates/tpl_account_default.php

Center view button

---

includes/classes/shopping_cart.php

Add notifiers for successful add to cart in case one wants to hook additional actions based on product(s) added to cart

Add more notifiers to shopping_cart for after-add/update

---

includes/modules/order_total/ot_coupon.php

fixes ot_coupon issues in #4339

---

admin/customers.php

Unless I am missing something, while there are notifiers to add the form field and check it, there does not seem to be one to actually insert it...

admin, customer: notifier for addition of extra customer data to sql array

---

includes/modules/pages/shopping_cart/header_php.php

Saves a core file update for those who would like to display it on the shopping cart page in the products area.

Add model to the data passed to shopping cart template

---

includes/modules/pages/product_info/main_template_vars.php

#4399 
2nd commit for attempt at reformatting based on 'our' code style...

address php notices in Product info

---

admin/countries.php

fixes https://github.com/zencart/zencart/issues/4349

ZC158: admin, countries: fix handling of page as letter instead of number

---

includes/classes/Customer.php

Incorrect use of text field from orders_total

---

admin/manufacturers.php

No functionality changes. Prior to adding some notifiers.

manufacturers: minor code revisions.

---

admin/customers.php

Without this, there is an empty "for" generated.
Not using isset as this parameter should be there.

add missing value for "for" into notifier

---

admin/manufacturers.php

Otherwise there is no check for an empty field.

Admin, manufacturer: add required to manufacturer name field

---

admin/includes/application_bootstrap.php
admin/plugin_manager.php

only call on plugin_manager page.
See #4014

Remove call to inspectAndUpdate from every requuest and

---

includes/modules/pages/product_reviews_write/header_php.php

... as indicated by its cautionary message (No HTML allowed).

Ensure that any HTML in a product review's text is properly cleaned.

---

admin/invoice.php

If #4447 is merged as-is, this can be closed.  I didn't realize @brittainmark was going to add these flags back.

Ensure show flags are initialized in invoice.php

---

admin/category_product_listing.php

I got an error" Undefined array key "flag" for this line. Could not replicate it but I think it needs refactoring so the isset gets parsed first.

admin, category_product_listing, action 'setflag": remove ambiguity

---

includes/languages/english.php

Reference: https://english.stackexchange.com/questions/2794/punctuation-with-units

Should have a space before units

---

includes/classes/order.php

Suspect this was a copy & paste error from 8 lines above.

Carriage return not needed - this is HTML data

---

admin/developers_tool_kit.php

Address missing label and aria text information

Address missing/inconsistent HTML characteristics

---

includes/modules/meta_tags.php

Using the same logic of the breadcrumbs in `header_php.php`

Display correct page title on address book process

---

admin/includes/application_bootstrap.php

I am not sure that this is the correct way to deal with this issue and whether other lines need to be added as well.
i.e. more than just functions ??
I am not aware of the overall thinking here so am just really pointing out a possible area of error.

application_bootstrap.php - loading of plugin functions

---

admin/includes/languages/english/lang.manufacturers.php
admin/manufacturers.php

TABLE_HEADING_ID is ripe for rationalisation to main language file in due course, I think.

admin, manufacturers, add column title for ID to listing page

---

zc_install/ajaxAdminSetup.php
zc_install/includes/template/templates/admin_setup_default.php

Running PHP 8.0, was installing a brand new store to a new database and
using demo product. Received installation notices that were resolved
when I made these changes.

Correct notices during installation

---

admin/category_product_listing.php

fixes: https://github.com/zencart/zencart/issues/4455

admin, category_product_listing, change category status: correct parameter order

---

includes/modules/category_row.php

Having a notifier would make the integration of a plugin like Automatic Category Images possible with no core file changes. 
https://www.zen-cart.com/downloads.php?do=file&id=1977

Add notifier for category image

---

admin/manufacturers.php

If someone uploads a full size manufacturer image, it bloats out the sidebar unless this precaution is taken.

Display mfr image with small dimensions

---

includes/modules/order_total/ot_coupon.php

Fix #4470 ot_coupon cart check not always correct

---

laravel/app/Models/Configuration.php

overriding of defining of configuration values so some can be defined as integer

create array of configVals for int config #4317

---

admin/orders.php

Based on IDE inspections, prior to submitting a functional mod to allow batch updates of multiple orders (multi-language) from the order listing page.

ZC158, admin, orders: multiple minor non-functional revisions

---

includes/classes/productPulldown.php

remove duplicate sort array element w incorrect value #4543

---

admin/category_product_listing.php
includes/functions/functions_prices.php

Skip price display for categories (as is done with model).

Fixes #4287, Handle categories returned by search

---

includes/functions/html_output.php

PHP Notice when Create-account default country is 'None'.

---

admin/featured.php

Fixes issue on page 
http://MYSITE.com/admin/index.php?cmd=featured&action=new&preID=2 
as shown below:

Fixes layout of featured add by product id page

---

admin/specials.php

Same issue and root cause as #4564

Broken layout on add special by id page

---

zc_install/includes/languages/en_us/main.php
zc_install/includes/systemChecks.yml

Added erroemessage to main.php
Added folder writable to systemChecks.yml and made fail level.

Fixes #4538 nginx_conf directory needs to be writable

---

includes/languages/lang.english.php

fix two definitions on one line, repeated definition and trim whitespace

Storefont main language file minor corrections

---

includes/languages/english/lang.checkout_success.php

Already in main language file.

Storefont language duplicate definition

---

includes/modules/payment/paypal/paypal_functions.php

This time for sure.
Fixes #4493

Fix missing fee on chargeback reimbursement

---

includes/functions/functions_files.php
includes/modules/shipping_estimator.php

Fix direct inclusion of estimator lang file

---

admin/developers_tool_kit.php

i always felt that error message was misleading.

fix fatal error from #4588 and correct incorrect message

---

admin/orders.php
includes/functions/audience.php
includes/functions/functions_files.php
includes/init_includes/init_ipn_postcfg.php
includes/modules/payment/paypal/tpl_ec_button.php
includes/modules/payment/paypalwpp.php

Completion of work required by issue #4595; continues work started in PR #4583.

Fix direct inclusion of language files

---

admin/gv_sent.php
admin/includes/functions/general.php

gv_sent report shows in the sidebar:
Senders ID: 31707
...
Customer Id: 15
Would be much more useful if associated email was also shown.

Show email as well as customer id

---

includes/init_includes/init_customer_auth.php
includes/languages/lang.english.php

remove EMP_SHOPPING_FOR_MESSAGE_SEVERITY

---

includes/languages/lang.english.php

remove unused TEXT_CLOSE_WINDOW

---

includes/languages/lang.english.php

This define is used in includes/functions/functions_osh_update.php which can be called on the storefront side.

Add language define

---

includes/classes/productPulldown.php

what @torvista wants, he gets....
i think its better.

output model first when sorted by model

---

admin/coupon_restrict.php
email/email_template_checkout.html
email/email_template_contact_us.html
email/email_template_coupon.html
email/email_template_default.html
email/email_template_direct_email.html
email/email_template_gv_mail.html
email/email_template_gv_queue.html
email/email_template_gv_send.html
email/email_template_low_stock.html
email/email_template_newsletters.html
email/email_template_order_status.html
email/email_template_password_forgotten.html
email/email_template_product_notification.html
email/email_template_welcome.html
includes/templates/responsive_classic/common/html_header.php
includes/templates/template_default/common/html_header.php
includes/templates/template_default/templates/tpl_zc_install_suggested_default.php
includes/templates/template_default/templates/tpl_zc_phpupgrade_default.php
nddbc.html
not_for_release/zc_plugins/ModList/1.4.0/admin/mod_list.php
not_for_release/zc_plugins/ModList/1.4.1/admin/mod_list.php
zc_install/includes/template/common/html_header.php
zc_plugins/DisplayLogs/v3.0.0/admin/display_logs.php

remove type="text/css">

---

admin/includes/languages/english/modules/newsletters/lang.product_notification.php
admin/includes/modules/newsletters/product_notification.php

I did not understand this screen until I read the code!:
So I added text and changed the layout:

Tools>Newsletter>Product Notifications>Send: add text, change layout

---

includes/languages/english/lang.audience.php

Ensure $define is defined

---

admin/includes/init_includes/init_errors.php

The sanitation was a previous request:
https://github.com/zencart/zencart/pull/2906#issuecomment-549954573
but was incorrectly coded at the time.

correct email sanitation on DEVELOPER_OVERRIDE_EMAIL_ADDRESS

---

admin/includes/languages/lang.english.php
admin/server_info.php

This can be handy when troubleshooting a site - saves the step of pulling the config.

Show DIR_FS_CATALOG in Version page

---

admin/orders.php

`$oID` is cleansed and well established at the top of this script.  continuously casting it to integer makes little sense from a coding standpoint.
the order class is needed here:
https://github.com/zencart/zencart/blob/0b1ff5a1c7c8ef420e7acecc2af5dddd9a41889a/admin/orders.php#L409
and in the current iteration, it is null.  this refactor fixes that oversight.
hopefully in the future, we can eliminate many of these sql queries within this switch action and simply use the order object.

refactor to correct null order in notifier

---

includes/modules/pages/down_for_maintenance/header_php.php

as discussed:
https://github.com/zencart/zencart/issues/4701

Down for Maintenance, remove clause causing refresh error for whitelisted IP

---

includes/init_includes/init_sanitize.php

Fixes bad URL:
index.php?inc_subcat=0&keyword=1&main_page=advanced_search_result&page=7&search_in_description=1&sort[]=20a
Reported in 
https://www.zen-cart.com/showthread.php?228698-Error-logs-generated-from-Microsoft-IP

Redirect to home on bad URL

---

admin/orders.php

... required for seamless "Super Orders" integration.

Additional notifications for /admin/orders.php

---

includes/classes/pulldown.php

i have found the count of the sql results to be useful in further development.

add count for pulldown results

---

includes/functions/html_output.php

... as identified in [this](https://www.zen-cart.com/showthread.php?228769-Empty-entries-in-countries-dropdown-menu&p=1387797#post1387797) Zen Cart forum posting.

Correcting countries' dropdown when a top-of-list country is disabled.

---

admin/orders.php

do not call admin notification if payment not enabled

---

admin/reviews.php

reviews currently generates fatal error.  apparently i (and maybe @torvista) missed this file when working on the new pager.

fix group by for new pager

---

includes/classes/shipping.php

Shipping class, enable `storepickup` to be quoted as cheapest if it's the only method available.

---

includes/modules/pages/brands/header_php.php
includes/templates/template_default/templates/tpl_brands_default.php

v158: Update 'brands' page processing for template 'independence'.

---

admin/salemaker_popup.php

Remove old style language include

---

includes/classes/order.php

v158: Correcting extraneous quotes in options' values

---

admin/admin_activity.php

preventing strict error as reported here:
https://github.com/zencart/zencart/issues/4743

admin activity: verify gzinflate result

---

includes/classes/order.php
includes/functions/functions_addresses.php

functions_addresses needed 1 small change.  #4709

country info consistent: order class query #4709

---

includes/classes/navigation_history.php

V158 Correct navigation history warnings

---

ipn_main_handler.php

v158: Correcting PHP debug logs when 'paypal_here' IPN received

---

admin/includes/classes/stats_sales_report_graph.php

Fixes #4786
Refactoring and correcting various PHP Deprecation logs.

V158 sales reports graphs deprecations

---

includes/modules/pages/shopping_cart/jscript_addr_pulldowns.php
includes/templates/template_default/jscript/zen_addr_pulldowns.php

v158: Correcting zen_address_pulldowns.php

---

includes/templates/template_default/templates/tpl_modules_shipping_estimator.php

I was correcting for the possible empty value, but then I don't find $extra created anywhere.

tpl_modules_shipping_estimator.php: remove unused $extra

---

includes/modules/pages/address_book_process/header_php.php

To test it I had to reduce the max address constant while the edit page was already open.

replaced deprecated function call

---

admin/includes/application_bootstrap.php
includes/application_top.php

Handle databases with prefixes in 1.5.8

---

includes/modules/payment/paypaldp.php
includes/modules/payment/paypalwpp.php

v158: Resurrecting PayFlow-UK processing

---

admin/product_types.php

[28-May-2022 15:28:05 America/New_York] Request URI: /gh_demo_158/admin/index.php?cmd=product_types&page=1&ptID=1&action=save, IP address: ::1
#1  require(/Users/scott/sites/gh_demo_158/admin/product_types.php) called at [/Users/scott/sites/gh_demo_158/admin/index.php:11]
--> PHP Notice: Undefined index: catalog_add_to_cart in /Users/scott/sites/gh_demo_158/admin/product_types.php on line 37.

Fix undefined index in product_types.php

---

admin/includes/application_bootstrap.php
includes/application_top.php
includes/functions/zen_define_default.php

v158: Adding `zen_define_default`.

---

admin/orders.php
docs/whatsnew_1.5.8.html

- clarify remark in what's new and point to doc file for overides in orders.php.

Documentation changes

---

admin/admin_activity.php

fixes: https://github.com/zencart/zencart/issues/4848

admin_actity: revert empty to zen_not_null

---

admin/customers.php
admin/includes/languages/english/lang.customers.php

This can be super helpful to see if bad guys are attacking from the same IP.

(optionally) show registration IP in customers listing

---

admin/includes/extra_datafiles/dist-site_specific_admin_overrides.php
admin/invoice.php
admin/packingslip.php

Added notifiers for additional columns to packing slip.
Removed change default values notifiers to use site_specific_admin_overrides
Added $attr_img_width to site_specific_admin_overrides
Removed training ?> from invoice and packing slip
Fixes #4846

Syncronise and stream line packing slip and invoice notifiers

---

admin/orders.php
includes/templates/template_default/templates/tpl_account_history_info_default.php

v158: Correct "Raw HTML" displayed for admin-entered order comments

---

includes/classes/ViewBuilders/BaseController.php

Add missing method outputMessageList

---

includes/templates/template_default/templates/tpl_modules_shipping_estimator.php

As reported in this Github comment:
https://github.com/zencart/zencart/commit/74b97cbdcc616f4d9f58ea8823f14a1957d0ab8a

Fix accidentally dropped echo

---

includes/languages/english/html_includes/responsive_classic/define_main_page.php

This removes the width setting from code so that it can be controlled in CSS

Remove hardcoded width setting for .home-image from HTML

---

admin/admin_activity.php
admin/includes/languages/english/lang.admin_activity.php

Why?
Recently I had reason to check specific user activity and this was useful.

admin activity: add admin user filter

---

admin/includes/modules/delete_product.php

Deselect master category on linked product delete

---

admin/customers.php
includes/classes/Customer.php

v158: Correct processing surrounding customer's lifetime value

---

includes/functions/functions_email.php

Remove unused variable emodules_array

---

admin/admin_page_registration.php

Fix root cause of #4892

---

admin/admin_activity.php

as recommended here
https://github.com/zencart/zencart/pull/4860#issuecomment-1156653809

admin activity initialise $confirmation_needed

---

includes/modules/payment/paypal/paypal_admin_notification.php

v158: paypalwpp/admin, recognize that some fields might be NULL

---

admin/includes/css/server_info.css
admin/includes/languages/english/lang.server_info.php
admin/server_info.php

based on
https://github.com/lat9/database_server_info/issues
as discussed
https://github.com/zencart/zencart/issues/4924

admin, server_info: add database variables info from plugin

---

includes/init_includes/init_sanitize.php

V158 update storefront sanitization checks

---

admin/admin_activity.php

as recommended https://github.com/zencart/zencart/pull/4860#issuecomment-1156653809

admin activity: maintain selections if no records found

---

includes/classes/Customer.php

customer class fix typeError

---

admin/gv_mail.php

v158: Remove gv_no duplicating when sending Gift Certificates

---

includes/classes/payment.php
includes/modules/checkout_process.php
includes/modules/pages/checkout_confirmation/header_php.php
includes/templates/responsive_classic/templates/tpl_checkout_confirmation_default.php
includes/templates/template_default/templates/tpl_checkout_confirmation_default.php

v158: Correcting various PHP Warnings/errors when "credit covers"

---

includes/classes/ResourceLoaders/ArraysLanguageLoader.php
includes/classes/ResourceLoaders/LanguageLoader.php

... as seen in this load of the `create_account` page:

v158: Remove duplicate language file loads, performance improvement.

---

admin/admin_activity.php

safe strict comparisons
null coalesc
remove unnecessary casting
remove unneeded "where" assignment (improved "where" clause coming next).
add brackets to if

admin_activity: misc syntax, no functional changes

---

includes/languages/english/lang.button_names.php
includes/modules/sideboxes/currencies.php
includes/modules/sideboxes/manufacturers.php
includes/modules/sideboxes/music_genres.php
includes/modules/sideboxes/record_companies.php
includes/templates/responsive_classic/css/stylesheet.css
includes/templates/responsive_classic/css/stylesheet_colors.css
includes/templates/responsive_classic/jscript/jscript_sidebox_select_form.php
includes/templates/template_default/jscript/jscript_sidebox_select_form.php
includes/templates/template_default/sideboxes/tpl_currencies.php
includes/templates/template_default/sideboxes/tpl_manufacturers_select.php
includes/templates/template_default/sideboxes/tpl_music_genres_select.php
includes/templates/template_default/sideboxes/tpl_record_company_select.php

Partial (sidebox-only) corrections for #4879.

V158 sidebox select form submit

---

includes/modules/shipping_estimator.php

syntax tidies, no functional changes:
short array syntax
safe strict comparisons
correct method name
null coalesce
list to []
Can be squashed after review.

module shipping estimator tidy syntax

---

admin/includes/application_bottom.php
includes/application_bottom.php

v158: Correcting PHP deprecations when language-loader debug is enabled

---

includes/modules/checkout_process.php

as reported https://github.com/zencart/zencart/issues/4988#issuecomment-1176428282

checkout_process, order->create: remove surplus parameter

---

admin/includes/header.php

from the html validator:
i thought @torvista was the html validator prince....

validate html

---

admin/category_product_listing.php
admin/featured.php
admin/specials.php

Remove unused variable causing log

---

includes/classes/FileSystem.php

Refactor listFilesFromDirectoryAlphaSorted so it is not a duplication of listFilesFromDirectory
with the sort parameter.
Remove the sort parameter from listFilesFromDirectory

Refactoring listFilesFromDirectoryAlphaSort

---

includes/classes/ResourceLoaders/SideboxFinder.php
includes/modules/column_left.php
includes/modules/column_right.php

Fix sidebox override

---

admin/category_product_listing.php

quotes were opened in html but closed in php, so confusion.

cat-product listing: balance html/php syntax (flagged by IDE as error)

---

admin/gv_mail.php

Closing </b tag missing bracket.

close html tag

---

includes/classes/zcDate.php

v158: Correcting zcDate class debug-ouput

---

includes/templates/template_default/templates/tpl_gv_send_default.php

Freshen the base template for the `gv_send` page, then ensure that the 'to_name' input is properly sanitized.

V158 gv send refactoring

---

admin/includes/admin_html_head.php
laravel/app/Models/PluginControl.php

Refactor locations of plugins.
Adjust admin head to reflect change in absolute location.
fixes #5029

zc_plugins include file locations

---

includes/languages/lang.english.php

v158: Main language file, globalize $locales

---

includes/classes/Customer.php

v158: Correcting `Customer` class for use by admin/customers.php

---

admin/featured.php
admin/includes/application_bootstrap.php
admin/includes/functions/general.php
admin/specials.php
includes/functions/functions_categories.php

As noted in https://www.php.net/manual/en/changelog.strings.php 
Fixes #4449

v158: Adding ENT_COMPAT - default changed in PHP 8.1

---

includes/modules/order_total/ot_tax.php

reformat to PSR standard ot_tax

---

includes/modules/order_total/ot_tax.php

addresses comments in #5065.
i'm just not sure about changing conditionals being the same as what is contained here in the docs:
https://docs.zen-cart.com/dev/contributing/coding_standards/#when-to-reformat-an-entire-file
which is what i was trying to do.

add stict typing and function visibility

---

includes/classes/ViewBuilders/PluginManagerController.php

fixes #5045
required for new #5031 (will update number if necessary)

fix unique_key

---

includes/modules/product_listing.php
includes/modules/responsive_classic/product_listing.php
includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php
includes/templates/responsive_classic/templates/tpl_modules_products_featured_listing.php
includes/templates/responsive_classic/templates/tpl_modules_products_new_listing.php
includes/templates/responsive_classic/templates/tpl_product_reviews_default.php
includes/templates/responsive_classic/templates/tpl_product_reviews_info_default.php
includes/templates/template_default/templates/tpl_modules_products_all_listing.php
includes/templates/template_default/templates/tpl_modules_products_featured_listing.php
includes/templates/template_default/templates/tpl_modules_products_new_listing.php
includes/templates/template_default/templates/tpl_product_reviews_default.php
includes/templates/template_default/templates/tpl_product_reviews_info_default.php
nddbc.html

This is a fix of the mess I made in #4960 
I think maybe I learned a little today,

Placing a Title into More Info buttons.

---

includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php
includes/templates/responsive_classic/templates/tpl_modules_products_new_listing.php
includes/templates/template_default/templates/tpl_modules_products_all_listing.php
includes/templates/template_default/templates/tpl_modules_products_new_listing.php

v158: Use correct define for products-all/new listings

---

admin/includes/modules/copy_product_confirm.php

Fixes #4963
Also includes some array() to [] conversions and changes some fuzzy comparisons to exactly-equal-to

v158: Correcting PHP deprecation when copying products

---

includes/templates/template_default/templates/tpl_site_map_default.php

link was broken, pointed to featured instead or featured_products

ZC158 fix: sitemap featured products link

---

admin/category_product_listing.php
admin/includes/languages/english/lang.category_product_listing.php

Of course I expect a bun-fight, so don't hold back.
I've just added to the existing, but perhaps a rethink would be better.
Feel free to submit your own preferred lists and maybe we'll get to a consensus.
Not doing the sql for the default until that point.
A sort of the lang array would be a separate PR.

admin: category-product listing, add more sorting options

---

zc_install/includes/systemChecks.yml

remove pdoSqlite from system checks

---

admin/category_product_listing.php

mainly strict comparisons  
null-coalesce  
expansion of a nested ternary operator  
removal of unnecessary checks of $action
removal of optional/default parameters from function calls
short array syntax

category-product listing basic review

---

admin/media_types.php

remove ->fields from media types field to correct warning.
fixes #5112 
Part of #5085 separated to make easier to understand. let me know if you want me to stop breaking #5058 down.

fix warning file

---

includes/templates/responsive_classic/templates/tpl_shopping_cart_default.php
includes/templates/template_default/templates/tpl_shopping_cart_default.php

With an array of to-be-required files, this enables multiple plugins/site-specific-changes to include their specific content.

v158: Enable extra content to be included on the shopping_cart page

---

admin/includes/modules/document_general/collect_info.php
admin/includes/modules/document_product/collect_info.php
admin/includes/modules/product/collect_info.php
admin/includes/modules/product_free_shipping/collect_info.php
admin/includes/modules/product_music/collect_info.php

Second breakdown #5085 to make it easier to understand, if
you don't want me to do this please let me know.

Correct inputtype to inputmode

---

includes/classes/categoryPulldown.php
includes/classes/productOptionsPulldown.php
includes/classes/productPulldown.php
includes/classes/pulldown.php

add documentation; reformat to default from cs.symfony.com

---

includes/classes/ProductConfigurationSwitch.php
includes/classes/categoryPulldown.php
includes/classes/productOptionsPulldown.php
includes/classes/productPulldown.php
includes/classes/pulldown.php

Add missing comment blocks

---

admin/orders.php

Remove stray </td> tag to enable HTML5 validation
Fixes #5130

Stray end tag

---

admin/sqlpatch.php

Replacing the head detail with admin_html_head.php and removing init from body tag fixes the issue.
fixes #5135

sqlpatch HTML5 compliant

---

admin/includes/modules/product_music/collect_info_metatags.php

Typo remove _

---

admin/orders_status.php

Fix #5155
Add missing ->fields to $orders_status

Add ->fields

---

admin/orders_status.php

Change from $oID to avoid confusion with orders_id

Change $oID to $oSID

---

includes/classes/ResourceLoaders/SideboxFinder.php

PHP8.2 Define Parameters SideboxFinder

---

includes/templates/responsive_classic/css/stylesheet_colors.css

This matches and corrects the color and hover color for the navEZPages and the pagination on any product page with more than the set items for display.

Clean up some link and hover color contrast

---

admin/categories.php

Aids readability and makes a copy  & paste error less likely.

Put array entries on new line

---

admin/customers.php

Reformatting for PSR-12.

---

includes/classes/ResourceLoaders/PageLoader.php

- $installedPlugins
- $mainPage
- $fileSystem
Part of #5103

PHP8.2 Define Parameters PageLoader

---

admin/includes/languages/english/lang.plugin_manager.php
includes/classes/ViewBuilders/PluginManagerController.php

Fixes #5047
Added check to see if plugin directory removed and if not create an error message for the stack.

Cleanup error

---

admin/gv_queue.php
admin/gv_sent.php

Add isset($gInfo) to check set before use.
fix #5138

Check $gInfo set

---

includes/classes/category_tree.php

All set to private only used in class
- $box_categories_array = [];
- $categories_string;
- $tree = [];

PHP8.2 Define Parameters catgory_tree

---

includes/classes/template_func.php

$info set to private array. 
I cannot find any use of parameter.

PHP8.2 Define Parameters template_func

---

includes/modules/pages/account_notifications/header_php.php

Set to blank if notify not present.

---

includes/modules/order_total/ot_coupon.php
includes/modules/order_total/ot_group_pricing.php

Check Tax_Groups Set

---

includes/modules/order_total/ot_cod_fee.php

Check session payment set ot_cod_fee

---

includes/classes/payment.php

All public as used outside of class
Part of #5103 
NB. I am doing the payment modules separately as all very different.

PHP8.2 Define Parameters payment

---

includes/modules/payment/cod.php

Set to protected not required outside module
- $_check
Set to public used outside module
- $code
- $description
- $enabled
- $order_status
- $title
- $sort_order

PHP8.2 Define Parameters Payment Method COD

---

includes/modules/payment/moneyorder.php

- $_check;
Set to public
- $code;
- $description;
- email_footer
- $enabled;
- $order_status;
- $sort_order;
- $title;
Part of #5103

PHP8.2 Define Parameters Payment Method moneyorder

---

includes/modules/payment/firstdata_hco.php

- $_check
- $_logDir
- $authorize
- $gateway_currency
- $reportable_submit_data
Set to public
- $auth_code;
- $code;
- $description;
- $enabled;
- $form_action_url;
- $moduleVersion = '1.04';
- $order_status;
- $sort_order;
- $submit_extras
- $title;
- $transaction_id;
Part of #5103

PHP8.2 Define Parameters Payment Method firstdata

---

includes/templates/responsive_classic/css/jquery.mmenu.all.css

I know this is from elsewhere but I could not find the **exact** elsewhere to correct the error at source.

responsive template, jquery.mmenu.all: add missing commas

---

admin/coupon_admin_export.php
admin/includes/attributes_preview.php
admin/includes/javascript/spiffyCal/spiffyCal_v2_1.js
admin/includes/modules/document_general/preview_info_meta_tags.php
admin/includes/modules/document_product/preview_info_meta_tags.php
admin/includes/modules/product/preview_info_meta_tags.php
admin/includes/modules/product_free_shipping/preview_info_meta_tags.php
admin/invoice.php
admin/media_manager.php
admin/store_manager.php
admin/whos_online.php

Remove valign and replace with css where necessary.
Fix #5179

HTML5 valign

---

includes/modules/order_total/ot_loworderfee.php

Check Sales Tax defined
fix #5202

Check order info tax group set

---

includes/classes/PluginSupport/PluginErrorContainer.php

All set to protected.
If this is part of laravel it suggests that they could be private.

PHP8.2 Define Parameters PluginErrorContainer

---

admin/coupon_admin.php
admin/gv_mail.php
admin/includes/modules/newsletters/newsletter.php
admin/includes/modules/newsletters/product_notification.php
admin/mail.php
admin/newsletters.php

Remove the \<span class="tt"> and add the class to the preceding element.

Remove <span class="tt">

---

includes/classes/PluginSupport/ScriptedInstaller.php
includes/classes/PluginSupport/ScriptedInstallerFactory.php

All set to protected
- $dbConn
- $errorContainer
part of #5103

PHP8.2 Define Parameters ScriptedInstaller

---

admin/includes/classes/object_info.php

Add in missing $_POST parameters
Note: I have still not added #[AllowDynamicProperties] Just in case I have missed some more.
fix #5230

Missing $_POST parameters

---

includes/classes/ViewBuilders/TableViewDefinition.php

PHP8.2 Define Parameters TableViewDefinition

---

includes/functions/functions_categories.php

Check parameter before $db->Execute

---

includes/classes/order.php

Fix order creation in PHP 8.2

---

includes/classes/ViewBuilders/DataTableDataSource.php

set $tableDefinition to protected
no changes needed

PHP8.2 Define Parameters DataTableDataSource

---

includes/classes/ViewBuilders/BaseController.php
includes/classes/ViewBuilders/PluginManagerController.php

Add array [] to $infoBox
set to protected
- $pluginManager
- $installerFactory
part of #5103

PHP8.2 Define Parameters BaseController

---

includes/classes/Filters/SelectWhereFilter.php

Set to ptotected
- $filterDefinition = []; -$options = [];
- $parameters =[];

PHP8.2 Define Parameters SelectWhereFilter

---

includes/classes/Filters/FilterManager.php

- $filterDefinitions
- $filterFactory
- $filters
Part of #5103

PHP8.2 Define Parameters FilterManager

---

admin/newsletters.php

check $_POST['audience_selected' set

---

admin/includes/modules/newsletters/newsletter.php
admin/includes/modules/newsletters/product_notification.php

- set to protected
- $content_html
- $content 
- $query_name 
- $title
- set to public 
- $show_choose_audience
- $queryname changed to $query_name
- $query_name set to protected
Part of #5103

PHP8.2 Define Parameters newsletters

---

admin/includes/classes/LaravelPaginator.php
admin/includes/classes/split_page_results.php

- change to protected
- $letterGroupLength
- set to protected 
- $current_page_number 
- $number_of_rows 
- $number_of_rows_per_page 
set to protected
- $cmd
- page_name
Part of #5103

PHP8.2 Define Parameters Split_page_results

---

includes/classes/PluginSupport/BasePluginInstaller.php

PHP8.2 Define Parameters BasePluginInstaller

---

admin/includes/modules/product/collect_info.php

Final fix from issue reported in #5239.

Fix object after edit/preview/back

---

admin/includes/init_includes/init_sanitize.php

The list of configs which allow special characters should be modifiable via an observer.

Notifier to extend special configs list

---

includes/classes/breadcrumb.php
includes/functions/functions_products.php

set _trail to protected
modify to use class function removeLast() instead of directly accessing the class parameter.

PHP8.2 Define Parameters breadcrumb

---

includes/classes/categories_ul_generator.php

- All protected
- $document_types_list removed as not used

PHP8.2 Define Parameters zen_categories_ul_generator

---

includes/classes/cc_validation.php

All set to public as used by payment calsses

PHP8.2 Define Parameters cc_validation

---

includes/classes/currencies.php

PHP8.2 Define Parameters currencies

---

includes/classes/upload.php

set to public
- $filename
set to protected
- $file
- $destination
- $extensions
- $message_location
- $permissions
- $tmp_filename

PHP8.2 Define Parameters upload

---

includes/classes/site_map.php

PHP8.2 Define Parameters zen_SiteMapTree

---

includes/classes/products.php

Removed unused parameters $modules, $selected_module

PHP8.2 Define Parameters products

---

admin/includes/functions/datepicker.php
admin/products_price_manager.php

Set true in zen_prepare_date

---

admin/products_price_manager.php

Correct typo.

---

admin/includes/functions/html_output.php
includes/functions/html_output.php

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel

select does not allow rel element

---

admin/ezpages.php

Fix edit icon on ezpages

---

includes/modules/payment/paypalwpp.php

use method get_content_type

---

includes/classes/shipping.php

Check for error

---

includes/modules/order_total/ot_gv.php

Do Not Process Customer GV Details If Not Logged In Or in Guest Checkout

---

includes/functions/functions_search.php

Test: Add product called "Tim's Coffee"
Search for "Tim's Coffee"

Allow apostrophes in search string

---

includes/classes/message_stack.php

Required for plugins and templates which modify this property.

Change visibility of $messages

---

includes/modules/payment/square.php

I have done the minimum to this as it is supposed to be going.
Public
- $order_status
Protected
- $_logDir
- $transaction_status
- $sdkApiVersion
- $_check, $gateway_currency
part of #5103

PHP8.2 Define Parameters square

---

includes/modules/payment/paypal.php

**Not been able to test. My PayPal test environment is screwed up.** 
Changed to public
- $code
- $description
- $enabled
- $title
New protected
- $_check
- $pdtData
- $totalsum
- $transaction_amount
- $transaction_currency
New public
- $codeVersion
- $form_action_url
- $order_status
- $sort_order
- $transaction_id
Part of #5103

PHP8.2 Define Parameters paypal

---

includes/modules/payment/paypalwpp.php

Some trapping of missing data that sometimes occurs and causes debug logs.

paypalwpp: handle missing data from Paypal

---

admin/category_product_listing.php

Fix Copy on paginated results

---

includes/classes/vendors/square/connect/lib/Model/CreatePaymentRequest.php

Square php8.1 complience add  #[\ReturnTypeWillChange]

---

includes/modules/featured_products.php
includes/modules/new_products.php

fix #5345
I have not changed the logic as it seemed unnecessary, can do if you want.

Correct Centerbox Title

---

includes/functions/functions_email.php

Do Not Include Error Message in Sprintf

---

includes/init_includes/init_sanitize.php

v158: Cast $_GET variables to string prior to sanitizing

---

zc_install/sql/updates/mysql_upgrade_zencart_156.sql
zc_install/sql/updates/mysql_upgrade_zencart_157.sql
zc_install/sql/updates/mysql_upgrade_zencart_158.sql

Patch for #5343.  True fix is in #5342.

Fix "duplicate column" issue in Tools > EZPages

---

admin/ezpages.php

Log:
```
[22-Oct-2022 13:54:14 Australia/Sydney] Request URI: /249vT5hFrM7u/index.php?cmd=ezpages, IP address: 124.185.77.181
#0 /home/client/public_html/249vT5hFrM7u/ezpages.php(761): zen_debug_error_handler()
#1 /home/client/public_html/249vT5hFrM7u/index.php(11): require('/home/client/...')
--> PHP Warning: Undefined variable $ezInfo in /home/client/public_html/249vT5hFrM7u/ezpages.php on line 761.
```

Handle empty list of ezpages

---

includes/modules/payment/paypalwpp.php

https://www.zen-cart.com/showthread.php?229086-Error-during-PP-checkout

Fix forum-reported PayPal Checkout deprecated log

---

includes/functions/functions_products.php

As reported in 
https://www.zen-cart.com/showthread.php?229093-upgrade-process-(product-page-manfuacturer-image-issue)

Fix bug in zen_get_products_manufacturers_image

---

admin/includes/init_includes/init_category_path.php
includes/init_includes/init_category_path.php
includes/init_includes/init_non_db_settings.php

Move define for TOPMOST_CATEGORY_PARENT_ID

---

admin/includes/classes/Paginator.php
admin/includes/functions/extra_functions/add_cookie_path_switch.php
admin/includes/init_includes/init_html_editor.php
admin/includes/modules/dashboard_widgets/RecentOrdersDashboardWidget.php
admin/includes/modules/delete_product_confirm.php
admin/orders.php

These are the affected files in the admin EXCEPT the includes/fonts and includes/javascript/flot files.

Remove " />" from admin

---

editors/ckeditor/config.js

remove slash from selfclosingtag in ckeditor fixes #5385

---

includes/functions/functions_general_shared.php

Use empty instead of length check

---

includes/index_filters/default_filter.php

remove unnecessary isset and simplify clause

---

includes/modules/payment/paypalwpp.php

--> PHP Warning: Undefined array key "RESULT" in /includes/modules/payment/paypalwpp.php on line 3148.
etc.

Fix undefined array key logs in paypalwpp.php

---

includes/init_includes/init_sanitize.php

fix sanitize notifier

---

includes/modules/pages/search_result/header_php.php

add arguments to search results notifiers

---

includes/modules/payment/authorizenet_aim.php

Issue 1:
```
[21-Nov-2022 21:26:07 UTC] Request URI: /index.php?main_page=checkout_process, IP address:  ... 
#1 /home/client/public_html/site/_livesite/includes/modules/payment/authorizenet_aim.php(648): str_replace()
#2 /home/client/public_html/site/_livesite/includes/modules/payment/authorizenet_aim.php(437): authorizenet_aim->_sendRequest()
#3 /home/client/public_html/site/_livesite/includes/classes/payment.php(288): authorizenet_aim->before_process()
#4 /home/client/public_html/site/_livesite/includes/modules/checkout_process.php(98): payment->before_process()
#5 /home/client/public_html/site/_livesite/includes/modules/pages/checkout_process/header_php.php(13): require('/home/client...')
#6 …
```

Fixing PHP8 issues with authorizenet_aim.php

---

includes/modules/payment/paypal/paypal_currency_check.php

Bypass "transaction must be under $10K" PayPal check on admin side

---

admin/attributes_controller.php

Future-proof attributes-controller notifications

---

admin/includes/modules/document_general/collect_info.php
admin/includes/modules/document_product/collect_info.php
admin/includes/modules/product/collect_info.php
admin/includes/modules/product_free_shipping/collect_info.php
admin/includes/modules/product_music/collect_info.php

Correct notification inconsistency between new/update products

---

includes/modules/pages/password_forgotten/header_php.php

sorry, deleted the log.  It was missing key on includes/modules/pages/password_forgotten/header_php.php line 32

Ensure email is set in password forgotten

---

includes/modules/pages/page/header_php.php

Fixes log 
```
--> PHP Warning: Undefined array key "id" in /home/client/public_html/site/includes/modules/pages/page/header_php.php on line 21.
```

Add check for page id parameter

---

admin/attributes_controller.php

fixes: https://github.com/zencart/zencart/issues/5443

Attribute controller: add missing field current_category_id

---

admin/banner_manager.php

Minor code tweaks, no functionality changes yet.
To squash after being reviewed.

Banner manager

---

includes/functions/functions_categories.php

fixes #5451 
i would suggest @torvista review prior to merge.

fix on full path in pulldown

---

includes/modules/payment/paypalwpp.php

Fixes #5463 
Credit to @proseLA for debugging this.
As discussed in https://www.zen-cart.com/showthread.php?229183-paypalwpp-php

Change access modifiers for PP vars

---

admin/banner_manager.php
admin/includes/css/banner_tools.css

added cursor so you get a pointer on the line.
This is the last item for basic changes.

Banner Manager: html validation remove role from tr

---

admin/includes/init_includes/init_sanitize.php

move search to WORDS_AND_SYMBOLS_REGEX sanitize

---

includes/functions/functions_general_shared.php

Add alias for old name

---

includes/modules/attributes.php

Fixes #5468
Cherry pick of d65a89e3688f39ed7878d798639183d03e3134cc to add to v1.5.8.

Fixes default for dropdown Attributes not respected

---

includes/classes/PluginSupport/BasePluginInstaller.php
includes/classes/PluginSupport/Installer.php
includes/classes/ViewBuilders/PluginManagerController.php

Cannot access protected property $errorContainer when installing plugin

---

admin/orders.php

admin, orders: fix for adding string to number

---

admin/includes/modules/product/collect_info.php

no functional changes, yet.
To squash and mirror to other collect_info

Collect info: minor code simplification

---

admin/downloads_manager.php
admin/includes/extra_datafiles/dist-site_specific_admin_overrides.php
admin/includes/modules/dashboard_widgets/RecentOrdersDashboardWidget.php
admin/invoice.php
admin/orders.php
admin/packingslip.php

Add missing overrides to dist_site_sepecific_overides 
Moved $zen_date_debug to end !!! Should it be there at all?!!! 
Move all overrides to top of using file and made operation consistent
Added $recentOrdersMaxRows 
Fixes #4852

Update Admin Overrides

---

admin/category_product_listing.php

use case is for various URL rewriting scenarios.

add notifier to category prod listing for skip actions

---

admin/includes/modules/document_general/collect_info.php
admin/includes/modules/document_product/collect_info.php
admin/includes/modules/product/collect_info.php
admin/includes/modules/product_free_shipping/collect_info.php
admin/includes/modules/product_music/collect_info.php

equate collect_info to /product and short array syntax for product_music

Add products_id to $pInfo for other product types

---

admin/category_product_listing.php
admin/coupon_admin.php
admin/downloads_manager.php
admin/featured.php
admin/includes/modules/search_box.php
admin/reviews.php
admin/specials.php

This reduces code repetition in multiple files

Implement search-box module into most files.

---

includes/modules/pages/page/header_php.php

- Removed unused code for horizontal page links. This solves the unused and undefined variables
- Removed brckets around `require` statement
- shorthand array notation
resolves zencart/zencart/#5552

clean up code page.php

---

includes/templates/responsive_classic/templates/tpl_page_default.php
includes/templates/template_default/templates/tpl_page_default.php

- fix code indentation and spacing
- replace `and` with `&&`
- replace `sizeof` with `count`

Code clean up ez-page templates

---

admin/includes/modules/products_previous_next.php
includes/functions/functions_categories.php
includes/functions/functions_products.php
includes/modules/product_prev_next.php

no change in functionality.  40 lines of code reduction.  makes use of function available for use by plugin authors...

refactor product info sort into function

---

includes/templates/template_default/templates/tpl_checkout_confirmation_default.php

template_default: checkout_confirmation_default, add missing echo

---

includes/functions/functions_products.php

zen_get_uprid, simplify and return string

---

admin/includes/admin_html_head.php

Enable plugins/zc_plugins to use admin/css/*.php

---

admin/includes/admin_html_head.php
admin/includes/css/dist-site-specific-styles.php

Enable site-specific admin .css customizations

---

admin/product_types.php

use null coalesc
correct method name "insert"
add parameter list new box();
replace ternary test
short array syntax
remove silence operator

admin, Product Types: misc non-combative changes

---

includes/functions/functions_products.php

get_uprid: Check for empty string is needed

---

admin/reviews.php

Correct admin reviews average rating fatal error

---

admin/countries.php

... as reported in [this](https://www.zen-cart.com/showthread.php?229309-Admin-Locations-Taxes-Countries-cannot-edit-country-not-on-first-page) Zen Cart forum bug-report.

Admin countries, correct missing page= on pages other than first

---

includes/functions/functions_products.php

fixes https://github.com/zencart/zencart/issues/5611

fix delete sql

---

admin/includes/languages/lang.english.php
admin/orders.php

Correct invalid warning when order's paid via GV/DC

---

includes/functions/functions_products.php

Use case: replacing placeholders/boilerplate texts embedded in the description.

add notifiers to allow modification of product description/other product fields

---

admin/coupon_admin.php
admin/define_pages_editor.php
admin/ezpages.php
admin/includes/modules/document_general/collect_info_metatags.php
admin/includes/modules/document_product/collect_info_metatags.php
admin/includes/modules/product/collect_info_metatags.php
admin/includes/modules/product_free_shipping/collect_info_metatags.php
admin/mail.php
admin/newsletters.php

I've checked each of these, to ensure they make no different to the display, which is set by css.

Admin: remove cols/width from function textarea calls

---

admin/includes/modules/copy_product.php
admin/includes/modules/move_product.php
includes/init_includes/init_non_db_settings.php

#5625: Correcting TOPMOST_CATEGORY_PARENT_ID definition and usage

---

includes/functions/functions_gvcoupons.php

#5624: Correcting `is_product_valid` parameter typing

---

admin/coupon_admin.php

As identified in [this](https://www.zen-cart.com/showthread.php?229327-Coupon-Admin-Multiple-Reports) Zen Cart forum bug-report

Correct coupon_admin/multiple reports PHP warning

---

includes/functions/functions_strings.php
includes/modules/pages/redirect/header_php.php

... and the `fixup_url` function to use https:// rather than http:// if the current page's request-type is 'SSL'.
Fixes #5630.

#5630: Correcting manufacturer's URL redirection

---

includes/modules/pages/product_reviews/header_php.php
includes/modules/pages/reviews/header_php.php

... not arbitrary hardcoded number.

Review pages should not pull a substring of review text

---

admin/category_product_listing.php

Fixes issue raised in 
https://www.zen-cart.com/showthread.php?229358-In-admin-categories-sort-category-status-enable-error

Fix admin product sort order issue

---

includes/modules/pages/account_edit/header_php.php

--> PHP Warning: Undefined variable $customers_referral in /home/client/public_html/includes/modules/pages/account_edit/header_php.php on line 119.

Fix log for undefined variable

---

admin/sqlpatch.php
includes/templates/template_default/templates/tpl_modules_downloads.php

as found by tool 
https://github.com/torvista/Zen_Cart-Find_Extra_Spaces

remove extra blank lines at end of files

---

includes/templates/responsive_classic/templates/tpl_document_general_info_display.php
includes/templates/responsive_classic/templates/tpl_document_product_info_display.php
includes/templates/responsive_classic/templates/tpl_product_free_shipping_info_display.php
includes/templates/responsive_classic/templates/tpl_product_info_display.php
includes/templates/responsive_classic/templates/tpl_product_music_info_display.php

If there is no product image then there will not be any additional images. Therefore why process the additional image code.

products image efficency

---

includes/functions/functions_email.php

as per functions spec:
https://github.com/zencart/zencart/blob/f987315e8f91cf051a548a30db8539c89886b954/includes/functions/functions_dates.php#L51

correct date format for functions zen_date_long/zen_date_short

---

admin/coupon_restrict.php

it's @torvista's world.  we are just living in it.
Follow up to #5676

Admin, Coupon Restrict bis 

---

includes/classes/Customer.php

Fix setDefaultAddressBookId's update

---

admin/modules.php

if someone went to the trouble to set `ADMIN_CONFIGURATION_KEY_ON` to on; lets show the key names in the module settings.

see module key names if flag is on

---

admin/coupon_restrict.php

admin, Coupon Restrict: add Back button

---

admin/coupon_restrict.php

...since it's already touched.

coupon_restrict: short array syntax

---

admin/manufacturers.php

Fixes #5699
(No insert option in admin when manufacturers list is empty)

Fixes missing insert button in Admin > Manufacturers

---

includes/functions/functions_lookups.php
includes/modules/meta_tags.php

#5693: Correcting PHP notices for customers auth

---

includes/modules/payment/authorizenet_aim.php

Authorize.net/AIM, correcting order-status-updates for void/auth/capt

---

includes/modules/pages/redirect/header_php.php

Redirect page updates and corrections

---

includes/functions/functions_prices.php

Add a notification for the subject function, enabling a site to override the default salemaker sale behavior, e.g. enabling the site to include products linked to a sale category.
Also restores the commentary that describes what the 'sale_deduction_type' values actually mean.

Add a notification for zen_get_products_special_price

---

includes/modules/pages/reviews/header_php.php

Fixes #5732
Line 26 in `\includes\modules\pages\reviews\header_php.php` deleted because it was duplicated on line 27

Remove duplicated line

---

admin/manufacturers.php

This will enable site-specific handling to add and manage new fields in the `manufacturers` table.

Admin manufacturers.php, add notifications

---

admin/mail.php

Fix #5723
Email with + sign in the address is not handled when sent from admin to a single customer.

Email with + sign in it not handled in single customer email from admin

---

includes/functions/functions_customers.php

fixes: https://github.com/zencart/zencart/issues/5554

remove unused sprintf parameter from $greeting_string

---

includes/functions/functions_email.php

fixes: https://github.com/zencart/zencart/issues/5689

functions_email: cast value to string

---

admin/includes/modules/document_general/collect_info_metatags.php
admin/includes/modules/document_product/collect_info_metatags.php
admin/includes/modules/product/collect_info_metatags.php
admin/includes/modules/product_free_shipping/collect_info_metatags.php

fixes: https://github.com/zencart/zencart/issues/5602

admin, collect_info_metatags: restore ids to metatag input fields

---

admin/option_name.php

admin: Option Name Sorter, correct column count

---

includes/functions/functions_general.php
includes/languages/english/html_includes/define_ask_a_question.php
includes/languages/english/lang.ask_a_question.php
includes/modules/pages/ask_a_question/header_php.php
includes/templates/template_default/templates/tpl_ask_a_question_default.php

This is a solution for call for price. A better solution may be to create a separate document for call for price. If that is the considered opinion I am happy to do that instead.
Did not want to wait for major release
Fixes #5748

Add Call For Price To Ask A Question

---

includes/classes/db/mysql/query_factory.php

Fixes #5722
- suppresses E_WARNING which triggers logging, on simpleConnect()
- dies sooner on connect()

When $db connection is down, generate fewer logs

---

admin/includes/modules/document_general/collect_info_metatags.php
admin/includes/modules/document_product/collect_info_metatags.php
admin/includes/modules/product/collect_info_metatags.php
admin/includes/modules/product_free_shipping/collect_info_metatags.php

wrapped long lines, easier to see in code and with comparison, not easy to see here.
No functional changes.

short array syntax, mirror formatting

---

includes/functions/functions_dates.php

Force zen_date_diff to return an int

---

includes/functions/functions_exchange_rates.php

Handle empty response to ECB currency inquiry

---

admin/attributes_controller.php
admin/downloads_manager.php
admin/index_setup_wizard.php

remove legacy calls to init()

---

includes/functions/functions_general.php
includes/templates/classic/css/stylesheet_css_buttons.css
includes/templates/responsive_classic/css/stylesheet_css_buttons.css
includes/templates/template_default/css/stylesheet_css_buttons.css

zenCssButton

---

admin/includes/languages/english/lang.salemaker_info.php
admin/options_name_manager.php
admin/users.php
includes/classes/productPulldown.php
includes/init_includes/init_add_crumbs.php
includes/modules/shipping/item.php
includes/templates/template_default/templates/tpl_zc_install_suggested_default.php
includes/templates/template_default/templates/tpl_zc_phpupgrade_default.php

Somehow tab characters were introduced into these files instead of the routine 2 or 4 spaces. This exchanges those tab characters for the associated spaces.

Replace tab with space

---

admin/includes/classes/AdminRequestSanitizer.php

Original design of the admin sanitizer associated with PRODUCT_URL_REGEX was written to directly support only the data type that is specifically used by Zen Cart which is a language based array of values. Use of this filter type on a non-array variable causes errors.
Four methods of resolution came to mind:
1. Other software attempting to use this filter should make the data an array, filter it, then return it to not being an array.
2. Add/expand filtering by use of class overriding.
3. Add an additional filter that only addresses stringss (not arrays). This appears would complicate the code and control. Either the new code would reference the existing (logging a "non-existent" sanitization) or would effectively duplicate the code such that a change in one would require a change in the …

v158b Add string PRODUCT_URL_REGEX sanitizing

---

admin/manufacturers.php

Enable additional actions for Catalog :: Manufacturers

---

admin/server_info.php

admin, server info: correct $nbsp;

---

includes/classes/Customer.php

Customer class, minor reformatting

---

includes/version.php
zc_install/ajaxLoadUpdatesSql.php
zc_install/includes/modules/pages/database_upgrade/header_php.php
zc_install/includes/systemChecks.yml
zc_install/includes/version.php
zc_install/sql/install/mysql_zencart.sql
zc_install/sql/updates/mysql_upgrade_zencart_200.sql

Satisfies db portions of #5601 and #5727
Tested with upgrade and fresh install.

Initial v2.0.0 upgrade

---

admin/configuration.php
admin/countries.php
admin/currencies.php
admin/customer_groups.php
admin/downloads_manager.php
admin/ezpages.php
admin/geo_zones.php
admin/group_pricing.php
admin/languages.php
admin/orders_status.php
admin/product_types.php
admin/products_expected.php
admin/tax_classes.php
admin/tax_rates.php
admin/zones.php

Follow on from #5915 same fixes #5905 for rest of admin
additionally customer_groups.php had missing space.

Adding listbox role to rest of admin files

---

includes/init_includes/init_add_crumbs.php

- Indentation 4 spaces
- Align db queries
- $db->execute changed to $db->Execute
Refactoring coming next ... once this is merged.

Reformat init_add_crumbs.php

---

includes/classes/db/mysql/query_factory.php

Fix nddbc path not defined in zc_install

---

includes/modules/pages/account/header_php.php
includes/modules/pages/checkout_success/header_php.php
includes/modules/pages/gv_faq/header_php.php
includes/templates/template_default/sideboxes/tpl_shopping_cart.php

Reduces extra queries when data is already retrieved.

GV Balance code normalized to use loaded $customer data

---

admin/orders.php

Use ipdata.co instead of dnsstuff for order validation

---

admin/customer_groups.php
admin/includes/languages/lang.english.php

Changed row action to just select row (remove &action="edit")
Removed edit delete buttons from rows
Change icon so Arrow is selected row
Add information icon to not selected rows
Before
After

Change customer groups look and feel to use font Awesome

---

includes/modules/shipping_estimator.php

shipping estimator module - formatting etc, no functional changes

---

admin/includes/classes/stats_sales_report_graph.php
admin/includes/functions/general.php
admin/includes/modules/dashboard_widgets/OrderStatusDashboardWidget.php
admin/invoice.php
admin/orders.php
admin/packingslip.php
admin/stats_sales_report_graphs.php

refactor use of orders status array

---

includes/modules/shipping_estimator.php

fixes: https://github.com/zencart/zencart/issues/5945

modules/shipping_estimator: fix unused continue

---

includes/functions/functions_addresses.php
includes/modules/payment/paypal.php
includes/modules/shipping_estimator.php

https://github.com/zencart/zencart/blob/e4f09fc8c95da5f7b4b7d96a13b8949d9427e2be/includes/functions/functions_addresses.php#L50

zen_get_countries requires country_id as int

---

includes/classes/Customer.php
includes/functions/functions_addresses.php
includes/modules/pages/create_account_success/header_php.php
includes/modules/shipping_estimator.php
includes/templates/template_default/templates/tpl_modules_checkout_address_book.php

https://github.com/zencart/zencart/blob/5861302f484acbee6515b1ca7186cc960b80ecf5/includes/functions/functions_addresses.php#L251
and that's the end of fettling modules/shipping_estimator

zen_get_address_format_id, parameter country_id: cast to int as per type hint

---

admin/define_pages_editor.php
admin/includes/application_bootstrap.php
admin/includes/init_includes/init_file_db_names.php
admin/includes/init_includes/init_general_funcs.php
admin/modules.php
admin/newsletters.php
includes/application_top.php
includes/classes/InitSystem.php
includes/classes/ResourceLoaders/AdminFilesLanguageLoader.php
includes/classes/ResourceLoaders/SideboxFinder.php
includes/functions/functions_files.php
includes/init_includes/init_file_db_names.php
includes/main_cart_actions.php
includes/modules/extra_definitions.php
includes/modules/pages/document_general_info/main_template_vars.php
includes/modules/pages/document_product_info/main_template_vars.php
includes/modules/pages/product_free_shipping_info/main_template_vars.php
includes/modules/pages/product_info/main_template_vars.php
includes/modules/pages/product_music_info/main_template_vars.php
zc_install/includes/application_top.php

Sort all auto-loaded "extra" folders by alphabetical

---

includes/modules/payment/paypal.php
includes/modules/payment/paypaldp.php
includes/modules/payment/paypalwpp.php

as discussed here: https://github.com/zencart/zencart/issues/5957

paypal modules: remove version checks

---

includes/functions/functions_files.php

as reported here
https://github.com/zencart/zencart/issues/5985

fixes admin product image subdir dropdown bug

---

includes/templates/template_default/templates/tpl_modules_shipping_estimator.php

tr tags: IDE was unable to balance the tr tags as correct, this is easier to read.

shipping estimator template: non-functionality changes

---

admin/category_product_listing.php
admin/includes/languages/english/lang.category_product_listing.php
includes/classes/ajax/zcAjaxAdminSessionChange.php

show/hide images on the admin catalog/product page

---

includes/templates/responsive_classic/templates/tpl_modules_mobile_menu.php

... unlike the information sidebox.

Responsive-class mega-menu not honoring about-us link flag

---

includes/functions/functions_customers.php
includes/functions/functions_gvcoupons.php
includes/modules/pages/checkout_confirmation/header_php.php
includes/modules/pages/checkout_payment/header_php.php
includes/modules/pages/checkout_payment_address/header_php.php
includes/modules/pages/checkout_shipping/header_php.php
includes/modules/pages/checkout_shipping_address/header_php.php
includes/modules/pages/product_reviews_write/header_php.php
includes/modules/sideboxes/shopping_cart.php
includes/templates/template_default/sideboxes/tpl_shopping_cart.php
includes/templates/template_default/templates/tpl_checkout_payment_default.php
includes/templates/template_default/templates/tpl_product_reviews_write_default.php

The typechecking added here to the `Customers` class is probably sufficient to resolve those errors.
However, I've also included additional fixes to reduce ambiguity.
Fixes #5981

Rename $customer var to avoid conflicts and ambiguity

---

admin/includes/languages/english/lang.product.php
admin/product.php
includes/functions/functions_products.php

No edit missing product

---

includes/classes/currencies.php

Recover when displaying orders placed in no-longer-supported currencies

---

admin/coupon_admin.php

pursuant to a conversation on the [forum,](https://www.zen-cart.com/showthread.php?229500-Admin-Discount-Coupons-Search&p=1395244#post1395244) i have included a more comprehensive searching facility for the coupon admin.
i have preserved the redirect for when a single coupon is found (now on line 57), although if we could get the message into the message stack (and is it really needed), i think we can safely remove the redirect.
at some point, it REALLY would be nice to separate all of the db calls into their own class.  unfortunately i do not have the time nor energy to do it at this point.

use boolean searching for coupon admin

---

includes/classes/shipping.php

Fix: Cheapest shipping not selected when storepickup is the only method and has multiple prices

---

admin/featured.php
admin/specials.php

For years we have been trying to get rid of shortcode, and now we are introducing it again?

Formatting

---

includes/modules/shipping_estimator.php

Otherwise, single-quotes in the state will result in a MySQL error.

Sanitize hand-entered state value on shipping-estimator

---

includes/classes/categories_ul_generator.php

Fix to https://github.com/zencart/zencart/commit/db2f6b96f2c2b4bf568116ece4b9b51924641401#commitcomment-134604989 provided by drbyte.

Prevent error when no categories, in categories_ul_generator.php

---

includes/modules/checkout_new_address.php
includes/modules/create_account.php

Fixes #6018.  Refer to individual commits for additional details.

Missing zone

---

admin/whos_online.php

Finish refactoring of whos_online page links.

---

includes/modules/pages/featured_products/header_php.php

as mentioned and closes https://github.com/zencart/zencart/issues/6109

remove unused array $featured_products_array

---

includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php
includes/templates/responsive_classic/templates/tpl_modules_products_featured_listing.php
includes/templates/responsive_classic/templates/tpl_modules_products_new_listing.php
includes/templates/template_default/templates/tpl_modules_products_all_listing.php
includes/templates/template_default/templates/tpl_modules_products_featured_listing.php
includes/templates/template_default/templates/tpl_modules_products_new_listing.php

No longer throws PHP type error, so fixes #6106

Remove unnecessary str_repeat() when setting is '0'

---

includes/modules/payment/paypaldp.php
includes/modules/payment/paypalwpp.php

Enable 'retirement' of paypaldp/paypalwpp

---

zc_install/includes/classes/class.zcDatabaseInstaller.php

This seems like a long-standing bug.

zc_install SQL for configuration_group

---

includes/classes/shopping_cart.php

Mistakenly left in when pushed for the Wholesale Pricing updates.

Remove debug code from shopping-cart class

---

includes/classes/order.php

Correct prices-with-tax tax calculations

---

admin/category_product_listing.php

Remove duplicated 'link' icon

---

admin/categories.php

Resolve TODO regarding TOPMOST_CATEGORY_PARENT_ID

---

includes/modules/pages/document_general_info/header_php.php
includes/modules/pages/document_product_info/header_php.php
includes/modules/pages/product_free_shipping_info/header_php.php
includes/modules/pages/product_info/header_php.php
includes/modules/pages/product_music_info/header_php.php

Force product_info pages to use proper product-type-handler page

---

includes/classes/shopping_cart.php

Correct required TEXT field's message

---

includes/index_filters/default_filter.php
includes/index_filters/music_genre_filter.php
includes/index_filters/record_company_filter.php
includes/languages/lang.english.php
includes/modules/listing_display_order.php
includes/modules/pages/featured_products/header_php.php
includes/modules/pages/products_all/header_php.php
includes/modules/pages/products_new/header_php.php
includes/modules/pages/specials/header_php.php
includes/templates/responsive_classic/templates/tpl_index_product_list.php
includes/templates/template_default/templates/tpl_featured_products_default.php
includes/templates/template_default/templates/tpl_index_product_list.php
includes/templates/template_default/templates/tpl_modules_listing_display_order.php
includes/templates/template_default/templates/tpl_modules_product_listing.php
includes/templates/template_default/templates/tpl_products_all_default.php
includes/templates/template_default/templates/tpl_products_new_default.php
includes/templates/template_default/templates/tpl_specials_default.php

Fixes #6185 
Most of it is fixed by the changes to `default_filter.php`.
Also added a new dropdown choice, "Recommended", which uses the store-owner-determined `product_sort_order`

Refine default-sort-order dropdown selection

---

not_for_release/testFramework/Support/Traits/DatabaseConcerns.php
not_for_release/testFramework/Support/zcFeatureTestCase.php

using migrations misses PR's that update the sql

Use zc_install database intaller rather than migrations

---

includes/templates/template_default/sideboxes/tpl_currencies.php

add label (accessibility) to currencies sidebox

---

includes/extra_datafiles/dist-site_specific_overrides.php

From https://github.com/zencart/zencart/pull/6158

dist-site_specific_overrides.php: add $show_contact_us_instead_of_continue

---

includes/init_includes/init_coupons.php

Ignore HTTP_REFERER test if it matches HTTPS_SERVER.

---

includes/templates/responsive_classic/css/stylesheet_colors.css
includes/templates/responsive_classic/css/stylesheet_image_modals.css
includes/templates/responsive_classic/modalboxes/tpl_image.php
includes/templates/responsive_classic/modalboxes/tpl_image_additional.php
includes/templates/template_default/css/stylesheet_image_modals.css
includes/templates/template_default/modalboxes/tpl_image.php
includes/templates/template_default/modalboxes/tpl_image_additional.php
includes/templates/template_default/templates/tpl_modules_main_product_image.php

Add "close" icon and product name to image modal

---

admin/includes/languages/english/lang.orders.php
admin/orders.php
includes/classes/order.php

Admin orders show unit/total weight

---

includes/extra_datafiles/dist-site_specific_overrides.php

re: https://github.com/zencart/zencart/issues/6194#issuecomment-1922696805

add $show_table_header_row

---

admin/includes/functions/general.php
includes/classes/language.php
includes/templates/responsive_classic/common/html_header.php
includes/templates/template_default/common/html_header.php

This tidies up the code, reduces public-access of internal variables by providing getters that allow consolidation and reduction of db queries scattered across code.
It also opens the opportunity to do slightly less complicated looping through languages via future refactoring of other areas of code.
The consolidation also makes it easier to embrace ISO standards from within the class, also in future changes.

Refactor Language class

---

admin/configuration.php
admin/includes/languages/lang.english.php
admin/modules.php

Remove USPS shipping module 'artifacts'

---

admin/server_info.php

Correct DB-server variables' display

---

admin/includes/languages/english/lang.option_values.php
admin/option_values.php
includes/functions/functions_attributes.php
not_for_release/testFramework/FeatureAdmin/TestAdminEndpoints/AdminEndpointsTest.php

fixes: https://github.com/zencart/zencart/issues/5355
following on from [here](https://github.com/zencart/zencart/pull/5426)
Decided to work on one option at a time, to try and make it easier....so the rest will follow to complete the file overhaul.
For sites with more than one language, the selection is offered:

Admin, Option Values Sort: Add language handling for update by Option Name

---

includes/functions/functions_categories.php

Incorporate attribute filters to product pulldowns

---

includes/classes/MeasurementUnits.php
includes/psr4Autoload.php

Helper functions for use with shipping modules

Convert between weight/distance units

---

admin/coupon_admin.php
admin/coupon_referrers.php
admin/includes/functions/functions_help.php
admin/includes/init_includes/init_sanitize.php
admin/includes/languages/english/lang.coupon_referrers.php
admin/includes/languages/lang.english.php
includes/classes/CouponValidation.php
includes/database_tables.php
includes/filenames.php
includes/init_includes/init_coupons.php
zc_install/sql/install/mysql_zencart.sql
zc_install/sql/updates/mysql_upgrade_zencart_200.sql

Due to catalog-side query lookups that cannot use an index, this approach may be more performant.
Ref #6193
Ref #6211

Move coupon referrers to separate db table

---

admin/coupon_admin.php

Handle deletes for coupon_referrers

---

includes/functions/functions_templates.php
includes/init_includes/init_templates.php
includes/modules/category_row.php
includes/templates/classic/template_settings.php
includes/templates/responsive_classic/template_settings.php
includes/templates/template_default/template_settings.php
zc_install/sql/install/mysql_zencart.sql
zc_install/sql/updates/mysql_upgrade_zencart_200.sql

This allows template-specific override capability.

Add template-specific settings support

---

admin/includes/languages/english/lang.coupon_admin.php

Goes with PR #6258, update help text for new UI.

Fix coupon referrer tooltip help text for new UI.

---

includes/functions/banner.php

Takes responsive_classic from Lighthouse Accessibility score of 96 to 100.

Adding aria-label to banner URL

---

admin/coupon_admin.php

Loading it inside the loop allows it to relate to the specified coupon correctly, including the loop's fallback to rendering data for the first one in the list.
Fixes #6267

Relocate loading of referrer data in coupon listing

---

includes/extra_datafiles/dist-site_specific_overrides.php
includes/filenames.php
includes/init_includes/init_common_elements.php
includes/languages/english/html_includes/define_accessibility.php
includes/languages/english/lang.accessibility.php
includes/languages/lang.english.php
includes/modules/pages/accessibility/header_php.php
includes/modules/sideboxes/information.php
includes/templates/responsive_classic/templates/tpl_modules_mobile_menu.php
includes/templates/template_default/templates/tpl_accessibility_default.php

Provides a page for storeowners to make an accessibility statement about their site, which some lawyers are now recommending.

Accessibility page

---

admin/includes/css/stylesheet.css

Remove outdated conflicting textarea width:auto CSS style

---

includes/modules/payment/paypaldp.php

paypaldp - avoid logs on possible empty response data

---

includes/modules/payment/paypaldp.php

Continuing work from #6278.  Completes work for #6250.
158 users seeking to backport these fixes- please see this note: 
https://github.com/zencart/zencart/pull/6278#issuecomment-1974848472

More paypaldp - avoid logs on empty response data

---

admin/countries.php

Fix lookup when country name starts with an accented character

---

zc_install/sql/updates/mysql_upgrade_zencart_200.sql

Change SQL syntax to accommodate MariaDB 10.3

---

includes/modules/product_listing_alpha_sorter.php
includes/templates/responsive_classic/templates/tpl_index_product_list.php
includes/templates/template_default/sideboxes/tpl_manufacturers_select.php
includes/templates/template_default/templates/tpl_index_product_list.php
includes/templates/template_default/templates/tpl_modules_listing_display_order.php

add aria-label to select blocks

---

admin/sqlpatch.php
zc_install/includes/classes/class.zcDatabaseInstaller.php
zc_install/sql/updates/mysql_upgrade_zencart_200.sql

Fix sql upgrades when table prefixes exist

---

ipn_main_handler.php

Fixes #6315 - Failed order when PayPal Standard not installed, under PHP 8.1

ipn-handler - catch undefined constant

---

includes/classes/order.php
includes/classes/shopping_cart.php
includes/modules/pages/shopping_cart/header_php.php

Correct order tax calculations

---

includes/templates/responsive_classic/css/stylesheet.css

Make links use underline decoration

---

zc_install/includes/languages/en_us/main.php
zc_install/includes/systemChecks.yml

Add zc_install check for `intl` extension

---

includes/index_filters/default_filter.php
includes/index_filters/music_genre_filter.php
includes/index_filters/record_company_filter.php
includes/modules/listing_display_order.php

Fix SNAF specials sort dropdown

---

admin/coupon_admin.php

Blank admin coupons search page

---

admin/orders.php

once fettled, I'll add it to the other two instances in this file.

allow arrays for NOTIFY_ADMIN_ORDERS_ADDRESS_FOOTERS

---

admin/includes/javascript/orders.php
admin/orders.php

Skip "copy" button for shipping address when blank

---

includes/templates/responsive_classic/css/stylesheet.css

Category Tab: add css for selected category

---

admin/customers.php

Restoring NOTIFY_ADMIN_CUSTOMERS_LISTING_ELEMENT signature

---

admin/coupon_admin.php

Fixes admin coupons listing bug

---

includes/functions/functions_dates.php

--> PHP Warning: Undefined variable $date_separator_idx in /home/client/public_html/includes/functions/functions_dates.php on line 185.

fix undefined variable debug log

---

includes/modules/product_prev_next.php

... like Products' Pagination.

Enable a plugin to override product_prev_next

---

includes/modules/product_listing.php

Enable products' names to be overridden on listings

---

includes/classes/shopping_cart.php

such good var names, and yet errors occur...
this error started here 636d4a3acd8

bug fix for in cart check

---

includes/classes/ZenShipping.php
includes/modules/shipping/flat.php
includes/modules/shipping/freeoptions.php
includes/modules/shipping/freeshipper.php
includes/modules/shipping/item.php
includes/modules/shipping/perweightunit.php
includes/modules/shipping/storepickup.php
includes/modules/shipping/table.php
includes/modules/shipping/zones.php
includes/psr4Autoload.php

if approved i can reformat the modified shipping files.

refactor shipping modules

---

admin/attributes_controller.php

Attributes controller, display of ampersands

---

includes/modules/payment/paypaldp.php

--> PHP Warning: Undefined array key "CVV2MATCH" in /home/client/public_html/store/includes/modules/payment/paypaldp.php on line 997.

Fix PHP8 log

---

includes/templates/template_default/templates/tpl_modules_upcoming_products.php

Correct upcoming-products' centerbox misalignment

---

includes/modules/payment/paypal/paypalwpp_admin_notification.php

[21-Apr-2024 12:45:01 America/Indiana/Indianapolis] Request URI: /admin/index.php?cmd=orders&oID=39303&action=edit, IP address: 73.5.197.200, Language id 1
#0 /home/client/public_html/includes/modules/payment/paypal/paypalwpp_admin_notification.php(133): zen_debug_error_handler()
#1 /home/client/public_html/includes/modules/payment/paypalwpp.php(623): require('/home/client/p...')
#2 /home/client/public_html/admin/orders.php(740): paypalwpp->admin_notification()
#3 /home/client/public_html/admin/index.php(11): require('/home/client/p...')
--> PHP Warning: Trying to access array offset on value of type bool in /home/client/public_html/includes/modules/payment/paypal/paypalwpp_admin_notification.php on line 133.
[21-Apr-2024 12:45:01 America/Indiana/Indianapolis] Request URI: …

Fixing PHP 8 logs in PayPal-Admin-Notification template

---

includes/functions/functions_products.php
includes/modules/pages/products_new/header_php.php
includes/modules/sideboxes/whats_new.php
includes/templates/responsive_classic/sideboxes/tpl_categories.php
includes/templates/responsive_classic/templates/tpl_modules_mobile_menu.php
includes/templates/template_default/sideboxes/tpl_categories.php

Remove zen_get_products_new_timelimit()

---

admin/includes/attributes_preview.php
admin/includes/functions/general.php
includes/classes/shopping_cart.php
includes/functions/functions_products.php
includes/modules/attributes.php
includes/modules/column_single.php
includes/modules/pages/shopping_cart/header_php.php
includes/templates/template_default/popup_attributes_qty_prices/tpl_main_page.php

As reported in https://www.zen-cart.com/showthread.php?230070-Testing-v2-0-0-Upgrade-Issues-Errors-When-Loading-Order-Details

Fix ANSI mode issues

---

admin/includes/languages/english/lang.template_select.php
admin/template_select.php
includes/functions/functions_templates.php

If a template has a `template_settings.php`, enable it to be viewed in the admin.

Enable `template_settings.php` to be viewed in admin

---

admin/index_setup_wizard.php

Hide empty zone field when appropriate, in setup wizard

---

admin/includes/functions/general.php
admin/includes/init_includes/init_languages.php
includes/auto_loaders/config.core.php
includes/psr4Autoload.php

This helps address the chicken/egg problem being introduced in #6370 ... avoiding the need to do a bunch of if/else coding that PSR4 will handle automatically.

use PSR4 for language class

---

includes/classes/order.php

fixes #6410 
Correct calculation error when prices are displayed with tax and multiple taxes apply.

Correct 'multiple taxes' calculation error

---

admin/coupon_admin.php

```
#1  require(/Users/scott/sites/gh_demo_200/admin/coupon_admin.php) called at [/Users/scott/sites/gh_demo_200/admin/index.php:16]
--> PHP Warning: Undefined variable $coupon_referrer in /Users/scott/sites/gh_demo_200/admin/coupon_admin.php on line 1015.
```

Fix PHP8 warning

---

admin/coupon_admin.php

Fixes #6437
Happens on older sites with lots of coupons, many disabled.

Selecting from page 2 of coupons can fail in some cases

---

includes/classes/CouponValidation.php

Add notifier to coupon product check.

Coupon notify

---

admin/includes/functions/admin_access.php
admin/includes/languages/english/lang.users.php
admin/users.php

Show pass last changed date in admin users

---

includes/modules/sideboxes/ezpages.php
includes/modules/sideboxes/more_information.php

Similar to PR #6443, but for the "More Information" and "Important Links" sideboxes.  Includes minor reformatting/refactoring.

Notifier to insert "More Information" and "Important Links" sidebox links

---

includes/modules/shipping/flat.php
includes/modules/shipping/freeoptions.php
includes/modules/shipping/freeshipper.php
includes/modules/shipping/item.php
includes/modules/shipping/perweightunit.php
includes/modules/shipping/storepickup.php
includes/modules/shipping/table.php

In the style of `upsoauth.php`. 
Note: `zone.php` does not yet have an `update_status` function so I'll do that separately.

Add notifier for shipping modules so sites can create exceptions

---

admin/index_dashboard.php

Notifier hook `'NOTIFY_ADMIN_DASHBOARD_WIDGETS'` allows widget list to be altered and appended-to. 
Can specify `'column'`, `'sort'`, `'visible'` and `'path'` properties for each widget.
Fixes #6448
An encapsulated plugin will need to register its widget by specifying the complete widget directory path, including version number.

Add notifier hook to admin dashboard to allow custom widgets

---

includes/modules/shipping/zones.php

create an update_status function.

Structure zones like other shipping modules

---

includes/functions/functions_prices.php

this file is close to working in strict mode

function_prices: cast constant/string to int for number_format

---

extras/ipncheck.php

Hasn't been touched in a long time ... this does some cleanup

Refactor ipncheck

---

extras/curltester.php

The first piece of output is 
```
Error Connection uses TLS 1.2
```
This is confusing.  The error is not that the connection uses TLS 1.2.
Changed to 
```
Checking server against howsmytls.com
Error (Rerun with "?d=1" for details)
Connection uses TLS 1.2
```

Improve curltester output

---

ajax.php

Ref https://github.com/zencart/zencart/pull/6462/files/d12720d8ba0cc343012b00232c3d33df929b39f5#r1617831844

Possible realpath returns false

---

admin/includes/languages/english/lang.orders.php
admin/includes/languages/lang.english.php
admin/invoice.php
admin/packingslip.php

Invoice and packing slip warning

---

includes/modules/pages/index/main_template_vars.php

Add category description to notifier

---

includes/classes/shopping_cart.php

QUANTITY_DECIMALS: Look for qty that *doesn't* include '.'

---

includes/classes/order.php
includes/classes/shopping_cart.php

shopping_cart/order: Simplification of QUANTITY_DECIMALS calculations

---

admin/coupon_admin.php

Some were already done but most not.
Gives fatal errors if using strict mode.

coupon admin: cast mktime parameters to int

---

includes/modules/order_total/ot_coupon.php

coupon-redemption - fix strict errors when no order is present yet

---

includes/modules/pages/document_general_info/header_php.php
includes/modules/pages/document_product_info/header_php.php
includes/modules/pages/product_free_shipping_info/header_php.php
includes/modules/pages/product_info/header_php.php
includes/modules/pages/product_music_info/header_php.php

Fix broken prod-not-found

---

admin/includes/application_bottom.php

... and simplify the output of the first output.

Admin: Add debug output of additional language files loaded

---

admin/product.php

Fixes new product creation

---

includes/modules/pages/search_result/header_php.php
includes/templates/template_default/sideboxes/tpl_search.php
includes/templates/template_default/sideboxes/tpl_search_header.php

Restore keywords to search box

---

zc_plugins/POSM/v6.0.0/admin/products_options_stock_view_all.php

Correct invalid HTML yielding wonky display on POSM view-all

---

includes/modules/order_total/ot_group_pricing.php

Add notifier to ot_group_pricing

---

zc_plugins/POSM/v6.0.0/manifest.php

Correct typo in POSM manifest

---

admin/languages.php
zc_plugins/POSM/v6.0.0/admin/includes/classes/observers/class.products_options_stock_admin_observer.php

Fixes issue #6588
Update POSM table products_options_stock_names when language is added/deleted.

POSM table products_options_stock_names not updated

---

admin/salemaker.php

Fixes issue #6568 
Added missing button to form, to toggle sales on or off.

Enable/Disable salemaker by clicking red/green box

---

includes/classes/Product.php

Return 'base' info only if product doesn't yet have language components

---

includes/templates/responsive_classic/common/html_header.php
includes/templates/template_default/common/html_header.php
includes/templates/template_default/common/html_header_css_loader.php
includes/templates/template_default/common/html_header_js_loader.php

Part of [this](https://github.com/zencart/zencart/discussions/6428) discussion.

Child template prep: Split out CSS/JS loading from html_header.php

---

admin/languages.php

When adding a new language, field sort_order in table order_status is not copied/updated for the new language.

Table Order status' field sort_order missing when adding new language

---

includes/classes/PluginSupport/ScriptedInstallHelpers.php

Integrating @lat9 function to core

Add getConfigGroupId() to ScriptedInstallHelpers.php

---

admin/coupon_admin.php

```
--> PHP Warning: Undefined array key "coupon_free_ship" in /home/client/public_html/admin/coupon_admin.php on line 377.
```
(Line number from 1.5.8a)

Undefined array key "coupon_free_ship" in coupon_admin.php

---

admin/includes/classes/stats_sales_report_graph.php

Fixes truncated dates on Sales Report with Graphs report

---

includes/classes/db/mysql/query_factory.php

Previously only INSERT or UPDATE were allowed, with no way to IGNORE.

Add db->perform INSERT IGNORE

---

includes/classes/template_func.php

Remove `template_func::file_exists`, it's unused.

---

zc_plugins/POSM/v6.0.0/admin/includes/classes/observers/class.products_options_stock_admin_observer.php

Posm, Admin, product listing: correct inserted icon alignment

---

includes/functions/functions_prices.php

Adjust attribute pricing only if priced by attributes

---

.gitignore
not_for_release/testFramework/FeatureAdmin/PluginTests/BasicPluginInstallTest.php
not_for_release/testFramework/Support/Traits/GeneralConcerns.php
not_for_release/testFramework/Support/plugins/zenTestPlugin/v1.0.0/Installer/ScriptedInstaller.php
not_for_release/testFramework/Support/plugins/zenTestPlugin/v1.0.0/admin/includes/languages/english/extra_definitions/lang.zen_test_plugin_name.php
not_for_release/testFramework/Support/plugins/zenTestPlugin/v1.0.0/admin/zen_test_plugin.php
not_for_release/testFramework/Support/plugins/zenTestPlugin/v1.0.0/extra_datafiles/filenames.php
not_for_release/testFramework/Support/plugins/zenTestPlugin/v1.0.0/manifest.php

uses a dummy plugin that is defined within the test framework to test some plugin operations

Plugin testing

---

includes/init_includes/init_sanitize.php

Sanitization: Don't force $_GET vars to be strings

---

includes/classes/FileSystem.php
includes/classes/ResourceLoaders/ArraysLanguageLoader.php
includes/classes/ResourceLoaders/BaseLanguageLoader.php
includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php
includes/classes/ResourceLoaders/CatalogFilesLanguageLoader.php
includes/classes/ResourceLoaders/FilesLanguageLoader.php
includes/classes/ResourceLoaders/LanguageLoader.php
includes/classes/ResourceLoaders/LanguageLoaderFactory.php
includes/classes/ResourceLoaders/SideboxFinder.php

- Also some minor PSR-12 reformatting

Add type-hints to various ResourceLoaders

---

includes/templates/template_default/templates/tpl_account_history_info_default.php

Fix typo in earlier commit

---

admin/modules.php
includes/classes/ResourceLoaders/ArraysLanguageLoader.php
includes/classes/ResourceLoaders/LanguageLoader.php
includes/classes/ResourceLoaders/ModuleFinder.php
includes/classes/order_total.php
includes/classes/payment.php
includes/classes/shipping.php

Many, many commits so that the progress can be seen.

Enable order-total/payment/shipping modules to be encapsulated

---

includes/functions/featured.php

Fixes click enable/disable of featured cats.

---

includes/extra_datafiles/dist-site_specific_overrides.php
includes/init_includes/init_common_elements.php
includes/init_includes/init_non_db_settings.php
includes/languages/english/lang.order_status.php
includes/modules/pages/order_status/header_php.php
includes/modules/sideboxes/information.php
includes/templates/template_default/templates/tpl_order_status_default.php

Update `order_status` page to use OPC-like version

---

includes/classes/Category.php

My bad: didn't test for prefixes.
Fixes #6691

Use constant for table name

---

admin/option_name.php

Fixes #6671 
Also
- Reformats to PSR-12
- Sanitizes input, ensuring it's set and an array
- Refactors repetitive code

Correct/reformat/refactor `Catalog :: Option Name Sorter`

---

includes/templates/template_default/templates/tpl_modules_shipping_estimator.php

Shipping estimator display errors

---

admin/reviews.php

fixes fatal errors in strict mode

admin, reviews: cast times parameters to int for str_repeat

---

admin/orders.php

Increase robustness of mismatch check by adding postcode as a compared field.

Add delivery vs billing postcode check

---

admin/options_values_manager.php

Options Values Manager: Reformat/Refactor and correct search capability

---

includes/classes/ResourceLoaders/ArraysLanguageLoader.php
includes/classes/ResourceLoaders/FilesLanguageLoader.php

Correct over-zealous use of `protected` for lang-loading

---

admin/languages.php
includes/functions/functions_lookups.php

Revert "Translate copied order-status names when installing new language"

---

admin/category_product_listing.php
includes/functions/functions_products.php

the return type for the method is already `int`.  there is no need to further cast it.

remove cast and correct @return parm

---

includes/classes/ResourceLoaders/AdminFilesLanguageLoader.php
includes/classes/ResourceLoaders/CatalogFilesLanguageLoader.php

Remove those language-file loads both admin and catalog.

'Legacy' language files aren't supported for `zc_plugins`

---

includes/modules/shipping/table.php

As reported in [this](https://www.zen-cart.com/showthread.php?230325-2-01-log-file-question&p=1403269) Zen Cart forum posting.

Correct 'table' shipping module PHP Warnings when rates are based on a percentage

---

admin/includes/css/stylesheet.css

Introduced in [this](https://github.com/zencart/zencart/pull/6707) PR, a victim of copy/paste.

Admin stylesheet, correcting BS4/BS5 padding selectors

---

admin/customers.php
admin/includes/javascript/customers.php
admin/includes/languages/english/lang.customers.php

Various corrections to the admin's Customer-edit

---

admin/includes/classes/class.admin.zcObserverLogWriterDatabase.php
zc_install/sql/updates/mysql_upgrade_zencart_210.sql

They're uninteresting and can seriously affect the size of that table.

Don't log 'keepalive.php' accesses in the `admin_activity_log`

---

admin/plugin_manager.php

("Plugin key" is more of a dev thing, and end-user is probably more interested in the version number.)

Rearrange columns in Plugin Manager

---

admin/includes/functions/admin_access.php

... enabling a site to disallow an admin's login for site-specific reasons.

Add admin-login notification

---

zc_install/includes/application_top.php

Ref #6361 review
- Fixes unbalanced parentheses
Also adds detection of SSL port-forwarding on port 443, in sync with catalog/admin detections

Fix error in #6361

---

includes/init_includes/init_observers.php

At Zen Cart's auto-loader load-point `#175` we look for observer files whose filename begins with `auto.` and then `include()` the file, and then `instantiate` the class into a global object of the name of the class.
Note the `auto.` prefix on the filename, and the `zcObserver` prefix inside the class as the class name. 
| File name | Class name | Global object var |
|----|----|----|
| auto.ProductMusicObserver.php | zcObserverProductMusicObserver | $zcObserverProductMusicObserver  | 
| auto.MapMinAdvPriceAdmin.php | zcObserverMapMinAdvPriceAdmin | $zcObserverMapMinAdvPriceAdmin | 
| auto.downloads_via_aws.php | zcObserverDownloadsViaAws | $zcObserverDownloadsViaAws | 
| auto.non_captcha_observer.php | zcObserverNonCaptchaObserver | $zcObserverNonCaptchaObserver |
The mismatch of filename …

Allow PSR4 naming for auto-instantiated Observer class filenames

---

zc_plugins/System Inspection/1.5.0/admin/system_inspection.php

equate header section to Display Logs

System Inspection: add missing doctype

---

includes/templates/template_default/templates/tpl_account_history_info_default.php

... think "Ty Package Tracker".
Includes some minor alignment changes so that I could 'see' what I was dealing with!

Add notifications for OSH insert in account_history_info

---

includes/templates/responsive_classic/common/tpl_footer.php
includes/templates/template_default/common/tpl_footer.php

... that's where "Flexible Footer Menu" wants to output its stuff.
Includes some 'freshening' on those `tpl_footer.php` modules, too.

Add footer notifier after `navsup`

---

includes/functions/html_output.php

zen_href_link: Change user-error log to user-notice

---

admin/includes/languages/english/lang.product.php
admin/includes/modules/collect_info.php
admin/includes/modules/update_product.php

Add MPN as editable field

---

admin/includes/modules/update_product.php

(used for a lurking plugin for product kits)

admin, update product: add notifier for a product update

---

includes/functions/functions_addresses.php
includes/modules/create_account.php

Allow null country param to zones pulldown function

---

admin/category_product_listing.php
admin/includes/classes/observers/auto.search_box.php

Include products_mpn in admin search

---

includes/main_cart_actions.php

Enable zc_plugins to provide extra-cart-actions

---

admin/includes/modules/copy_product_confirm.php

... as identified in [this](https://www.zen-cart.com/showthread.php?230389-Creating-Duplicate-Copies-products_ordered) Zen Cart forum thread.

Reset products_ordered to 0 when duplicating a product

---

includes/modules/pages/ask_a_question/header_php.php

identical to https://github.com/zencart/zencart/pull/6835

Ask a Question email: add missing telephone to html email, and remove brackets around email

---

admin/invoice.php
admin/packingslip.php

Invoice/packingslip: Protect against missing order status values

---

includes/functions/functions_categories.php

Fixes #6843
Note: Actual correction on line 807; remaining changes are reformatting/refactoring.

`zen_get_categories_image`, ensure return is a string

---

admin/includes/modules/preview_info.php

Changing the category image and the product image in preview_info.php
Uses the same class as the edit from #6866.

Changing admin image display to size via CSS instead of HTML attribute for products in preview

---

includes/modules/pages/checkout_payment/header_php.php

Treat null gv balance as zero

---

includes/classes/ViewBuilders/PluginManagerController.php

Suppress clean-up option in plugin manager for uninstalled plugins

---

includes/templates/responsive_classic/css/stylesheet.css

RC stylesheet, restore `fieldset fieldset legend` styling

---

includes/templates/responsive_classic/css/stylesheet.css

RC CSS: remove surplus commas, remove duplicate property, add semicolons for consistency

---

includes/functions/functions_exchange_rates.php

fix admin-only constant

---

admin/banner_manager.php

Handle banner uploads differently

---

includes/modules/payment/paypalwpp.php

Correcting `paypalwpp` various warnings

---

includes/functions/functions_search.php

fixes no integer entered when searching & restricted to ids; fixes #6938

---

includes/templates/responsive_classic/common/html_header.php

responsive_classic: remove closing slashes on css

---

includes/modules/payment/paypal/paypalwpp_admin_notification.php

paypalwpp admin notification: increase field size to allow display of content

---

admin/includes/functions/general.php

Normalize id attribute with zen_cfg_select_option

---

includes/templates/template_default/jscript/jscript_sidebox_select_form.php

...however I don't see how this code comes into play to test it!

jscript_sidebox_select_form.php: escape forward slashes for validator

---

includes/classes/PluginManager.php

zc_plugins: Update description details when installing an update.

---

includes/classes/vendors/Mobile-Detect/MobileDetect.json
includes/classes/vendors/Mobile-Detect/README.md
includes/classes/vendors/Mobile-Detect/src/MobileDetect.php

MobileDetect 4.8.09

---

zc_plugins/POSM/v6.1.0/catalog/includes/templates/default/jscript/posm_dependencies_jscript.php

PHP 8.4 patch for POSM 6

---

includes/init_includes/init_canonical.php

Canonical URL search parameters

---

includes/classes/Customer.php

Show true order status, not last public OSH status

---

includes/modules/pages/checkout_success/header_php.php
includes/templates/template_default/templates/tpl_checkout_success_default.php

checkout_success: Correct action used to record product notifications

---

admin/category_product_listing.php
admin/includes/modules/collect_info.php
admin/includes/modules/preview_info.php
admin/includes/modules/update_product.php
includes/functions/functions_strings.php

Fixes #6902
Replaces and closes #6903

Preserve search field content between product edits

---

zc_install/includes/template/templates/admin_setup_default.php

zc_install - rework email confirmation validation

---

includes/languages/english/lang.password_forgotten.php

Use STORE_NAME constant directly

---

zc_install/sql/updates/mysql_upgrade_zencart_210.sql

Fixes #6913 
Fixes #7006 
Originally found in: #6841

Some MySQL update queries in mysql_upgrade_zencart_210.sql failing

---

admin/orders.php

allow encapsulated payment modules on admin orders page fixes #6993

---

includes/templates/responsive_classic/modalboxes/tpl_image_additional.php
includes/templates/template_default/modalboxes/tpl_image_additional.php

Before fix:
```
<div id="modalContent1 . '" class="imgmodal-content">
```
(Note missing close double quote and errant `.'"`)
After fix: 
```
<div id="modalContent1" class="imgmodal-content">
```

Fix additional images template issue

---

includes/classes/PluginSupport/ScriptedInstallHelpers.php

It read as if it was deleting keys for admin pages instead of adding a new value.

Changed log entry for adding configuration key

---

admin/includes/init_includes/init_general_funcs.php
includes/functions/functions_communications.php
includes/functions/functions_exchange_rates.php
includes/init_includes/init_general_funcs.php

This will allow making external calls from a shared function without having to build out all the usual setup.

Add zenDoCurlRequest() function

---

includes/languages/english/lang.account_history_info.php
includes/languages/lang.english.php

Move common-use constant to 'base' language file

---

includes/classes/order_total.php

add third option for return of preconfirmation check

---

admin/orders.php

building on 87a228c and #7004 and #6993, this refactor allows an encapsulated payment module to make use of the ZC common payment admin functions.  
it further reduces code duplication, while maintaining the same functionality.
the only functional change is that voids and refunds are ONLY recorded in the zen admin activity log if said function is executed by the module.  i see no reason to record that activity if the payment module does not contain the method.
that said, i do not feel strongly about when to record things in the admin activity log.

Refactor & deduplicate payment module instantiation in /admin/orders.php

---

admin/category_product_listing.php

include cPath parameters in javascript links

---

includes/modules/payment/moneyorder.php

allows for moneyorders to only be used for wholesale customers.  or for whatever reason a store owner wants...

add notifier to Money order and reformat

---

includes/functions/functions_addresses.php

Correct 'statecomma' handling in zen_address_format

---

admin/includes/classes/message_stack.php

Admin caution messages icon

---

admin/includes/dist-configure.php
includes/dist-configure.php

Update DB_CHARSET in dist-configure.php to use 'utf8mb4'

---

includes/functions/functions_email.php

Convert &nbsp; to single-space in text emails

---

includes/functions/functions_search.php

sql in build keyword search; fixes #7084

---

admin/featured_categories.php

Remove stray quote when removing featured category

---

includes/templates/template_default/sideboxes/tpl_categories.php

Fixes #7089
Pulls in all changes currently in the `responsive_classic` version of the file
- PSR-4 indentation
- Using exactly-equal
- Adds featured categories' link if enabled

"Sync" `template_default` Categories' sidebox w/ responsive classic

---

includes/templates/responsive_classic/sideboxes/tpl_categories.php

`responsive_classic`, categories sidebox: Remove double check of flags

---

includes/modules/sideboxes/featured_categories.php

Don't display empty "Featured Categories" sidebox

---

includes/languages/english/lang.featured_categories.php
includes/templates/template_default/templates/tpl_featured_categories_default.php

`featured_categories` page, message if none

---

admin/coupon_admin.php

Admin, include all fields in coupon email sent

---

includes/classes/FileSystem.php
includes/classes/ResourceLoaders/PageLoader.php
includes/templates/template_default/common/html_header_js_loader.php
index.php

Enabling zc_plugins to add page-specific files

---

admin/category_product_listing.php

Move category: Check for unwanted browser back-button click

---

includes/functions/functions_products.php
includes/modules/attributes.php
includes/modules/pages/document_general_info/main_template_vars.php
includes/modules/pages/document_product_info/main_template_vars.php
includes/modules/pages/product_free_shipping_info/main_template_vars.php
includes/modules/pages/product_info/main_template_vars.php
includes/modules/pages/product_music_info/main_template_vars.php

Remove use of deprecated Product class' fields property

---

includes/functions/functions_attributes.php

An alternate solution to #7135.
Correcting the issue at the source, essentially ensuring that any attribute-related function request validates that the 'options_id' associated with a `products_attributes` record exists in the `products_options` table.
Using `INNER JOIN` instead of `LEFT JOIN` to assure the above.

Correcting storefront logs when an option is missing from the db

---

includes/classes/Customer.php
includes/classes/class.zcPassword.php
includes/modules/pages/account_password/header_php.php
includes/modules/pages/login/header_php.php
includes/modules/pages/password_forgotten/header_php.php
includes/modules/pages/password_reset/header_php.php

The class now 'owns'
- The `customer_password_reset_tokens` table handling
- Retrieval and update of `customers::customers_password`

Consolidate customer-password recording into `Customer` class

---

includes/classes/Product.php
includes/functions/functions_products.php

Fixes #7012
Replaces and closes #7018

Protect against missing `products_description` record

---

admin/includes/modules/dashboard_widgets/SalesReportDashboardWidget.php

Replaces a hard coded decimal place in ZC dashboard widget by the default currency decimal place.
Complementary to PR #7162 .

Hard_coded_currency_decimal_place_in_dashboard_widget

---

admin/includes/modules/collect_info.php
admin/includes/modules/document_general/collect_info.php
admin/includes/modules/document_product/collect_info.php
admin/includes/modules/product_free_shipping/collect_info.php
admin/includes/modules/product_music/collect_info.php

Added the "object-fit-contain" class to the category icon display in collect_info.php

Updating category image to be proportionally fit

---

includes/languages/english/classic/lang.header.php
includes/languages/english/responsive_classic/lang.index.php

this is only a refactor.
both of these language files are template overrides.
as such, only new or changed elements are needed.

remove unneeded overrides

---

includes/init_includes/init_observers.php
includes/modules/extra_functions.php

Partially pulled from PR #7032

Simplify admin/catalog context determination

---

admin/modules.php
includes/functions/functions_general_shared.php

As a separate function, it can be called separately, such as in plugin updates.

Move module-cache update to its own function.

---

includes/classes/PluginManager.php

According to discussion in PR #7208 .

PLugins language file name changed to 'lang.menu.php'

---

includes/modules/pages/customers_authorization/header_php.php

`customers_authorization` set flags only if not set

---

admin/configuration.php

... since it's already got changes since zc210 release
- Use short-array syntax
- Use PHP short-echo tags
- Align PHP code indentations
- Use `===` where appropriate
- Remove extraneous parentheses in conditionals

Refactor/reformat admin/configuration.php

---

includes/modules/payment/moneyorder.php

For better tracking, makes sense to add in "who" made this record, even if it's just the system.

Moneyorder-Adding "user" of record

---

admin/attributes_controller.php

I'll squash when approved.
Aside there is a great deal of uneeded type casting in sql queries...I assume this should stay as belt and braces security?

Attributes Controller: minor things

---

includes/classes/InitSystem.php

Fix typo in variable name

---

admin/modules.php
includes/classes/ViewBuilders/PluginManagerController.php

Possible solution to close #6847

Notifiers for install/uninstall

---

zc_plugins/POSM/v6.1.1/catalog/includes/classes/observers/class.products_options_stock_observer.php

POSM: Enable observer to update stock messages

---

includes/classes/MeasurementUnits.php

Fixes https://github.com/zencart/zencart/issues/7259

Fix TypeError error

---

includes/functions/functions_products.php

functions_products: casting to match hints (strict mode)

---

admin/coupon_admin.php

(already touched in 220)
short array syntax
remove some parameter default values
use null coalesce ??
use str_ends_with
use ternary operator
no code changes

admin: coupon_admin

---

admin/includes/modules/dashboard_widgets/BaseStatisticsDashboardWidget.php

Widget base: mktime parameters cast strings to int

---

admin/salemaker.php

Admin: salemaker balance button and form tags

---

includes/functions/functions_customer_groups.php

Basic function to return the ID number of a given group when searched. Will return -1 if not found as 0 is assigned to all customers in a DB by default.

Adding a helper function to get an ID from a name

---

admin/includes/functions/html_output.php

Fix param type in zen_draw_date_selector

---

includes/init_includes/init_observers.php

Sort observers using natural and case-insenstive sort.

---

zc_plugins/POSM/v6.1.1/admin/products_options_stock.php
zc_plugins/POSM/v6.1.1/admin/products_options_stock_view_all.php

I'm not sure where the `cache`, `headers` and `error` elements came from, but they're unwanted and the error section alerts an undefined message.

POSM: Remove unneeded/unwanted params from admin AJAX calls

---

includes/classes/order.php

strict $new_qty

---

zc_plugins/SystemInspection/1.6.0/admin/includes/extra_configures/system_inspection_base.php

Does this have the right name in it?

System Inspection: Update outdated shipping modules

---

includes/functions/functions_osh_update.php

Conditionally use `nl2br` in osh-update email messages

---

zc_plugins/POSM/v6.1.1/admin/products_options_stock.php

POSM: Correct missing array key log when option is missing

---

admin/attributes_controller.php

Attrib controller: Remove redundant line, reformat and refactor

---

zc_plugins/POSM/v6.1.1/admin/includes/javascript/product_posm.php
zc_plugins/POSM/v6.1.1/admin/includes/languages/english/extra_definitions/lang.products_options_stock_menu_names.php

POSM: Replace product-entry Quantity box

---

laravel/app/Models/PluginControl.php

Add casts for PluginControl
