includes/functions/functions_categories.php
fixes:https://github.com/zencart/zencart/issues/3896
`$sql .= "AND pa.options_id = " . (int)$filter_by_option_name;`
1064 You have an error in your SQL syntax; .....
=> Add missing space before AND, in zen_draw_products_pull_down_attributes

includes/modules/downloads.php
The current threshold of 11000 is too small to show MB - you wind up with 0.0MB files. 
The comparison could be against `1024*1024` instead of `1024*1024/10` - but it certainly shouldn't be the current `11000`.
=> Use KB for smaller files

admin/includes/css/stylesheet.css, admin/includes/functions/html_output.php
I noticed that in zc 1.5.8 on the admin side there is no longer an asterisk shown on required fields.
These changes add back the asterisk on fields that are set as required through the input or select function.
The asterisk is placed in an input addon span. This ensures the alignment on the right is always the same as fields that are not required
=> Add an asterisk to fields

includes/init_includes/init_sanitize.php, includes/languages/english.php
Example: browse to index.php?main_page=unknown 
[10-Aug-2020 11:28:24 UTC] Request URI: /gh_demo_158/index.php?main_page=unknown, IP address: ::1
#1  require() called at [/Users/scott/Sites/gh_demo_158/includes/templates/responsive_classic/common/tpl_main_page.php:177]
#2  require(/Users/scott/Sites/gh_demo_158/includes/templates/responsive_classic/common/tpl_main_page.php) called at [/Users/scott/Sites/gh_demo_158/index.php:94]
--> PHP Warning: require(includes/templates/template_default/templates/tpl_unknown_default.php): failed to open stream: No such file or directory in /Users/scott/Sites/gh_demo_158/includes/templates/responsive_classic/common/tpl_main_page.php on line 177.
[10-Aug-2020 11:28:24 UTC] PHP Fatal error:  require(): Failed opening required …
=> Browsing to unknown page causes fatal error

admin/users.php
The required attribute is hard-coded in the parameters. IMO it is better to use the required switch in the input-field function. When using the function, the asterisk will be put behind the field.
=> change hard-coded required attribute to use function parameter

includes/modules/pages/advanced_search/header_php.php, includes/templates/template_default/templates/tpl_advanced_search_default.php
Some stores don't use manufacturers.  Don't create a dropdown list in advanced search for manufacturers if this is true.
=> Don't create a manufacturer select list in advanced search if store doesn't use them

admin/category_product_listing.php, admin/customers.php, admin/downloads_manager.php, admin/featured.php, admin/orders.php, admin/reviews.php, admin/specials.php, includes/functions/functions_search.php, includes/modules/pages/advanced_search_result/header_php.php
pursuant to a conversation on the above referenced PR, i thought about refactoring the building of where clauses for sql statements on keyword searches.  my thoughts are to have a function, where you pass an array of field names, and a string of keywords.  the function would then build the where part of the sql statement.
in the conversation on PR #3804, there are a bunch of scripts where this might be beneficial.
this PR shows proof of concept and i'm certainly open to input.  
it is built off code from:
https://github.com/zencart/zencart/blob/4717032046d64e92ff5a71552b019636ef3fc8f5/includes/modules/pages/advanced_search_result/header_php.php#L317-L359
and that could certainly be part of the refactoring as well.
=> refactor product search

includes/modules/payment/paypal/paypalwpp_admin_notification.php
[11-Sep-2020 17:10:02 Europe/London] Request URI: /admin/orders.php?oID=613520&action=edit, IP address: removed
#1  require(/home/store/public_html/includes/modules/payment/paypal/paypalwpp_admin_notification.php) called at [/home/store/public_html/includes/modules/payment/paypaldp.php:987]
#2  paypaldp->admin_notification() called at [/home/store/public_html/admin/orders.php:863]
--> PHP Warning: Use of undefined constant MODULE_PAYMENT_PAYFLOW_TRANSACTION_MODE - assumed 'MODULE_PAYMENT_PAYFLOW_TRANSACTION_MODE' (this will throw an Error in a future version of PHP) in /home/store/public_html/includes/modules/payment/paypal/paypalwpp_admin_notification.php on line 419.
As reported in https://www.zen-cart.com/showthread.php?227199-Use-of-undefined-constant-MODULE_PAYMENT_PAYFLOW_TRANSACTION …
=> Stop MODULE_PAYMENT_PAYFLOW_TRANSACTION_MODE notice

admin/attributes_controller.php, admin/banner_manager.php, admin/orders.php, admin/salemaker.php, admin/sqlpatch.php, includes/modules/pages/account_history_info/jscript_main.php, includes/modules/pages/advanced_search/jscript_main.php, includes/modules/pages/checkout_confirmation/jscript_main.php, includes/modules/pages/checkout_payment/jscript_main.php, includes/modules/pages/document_general_info/jscript_main.php, includes/modules/pages/document_product_info/jscript_main.php, includes/modules/pages/login/jscript_main.php, includes/modules/pages/product_free_shipping_info/jscript_main.php, includes/modules/pages/product_info/jscript_main.php, includes/modules/pages/product_music_info/jscript_main.php, includes/modules/pages/product_reviews/jscript_main.php, includes/modules/pages/product_reviews_info/jscript_main.php, includes/modules/pages/product_reviews_write/jscript_main.php, includes/modules/pages/shopping_cart/jscript_main.php, includes/modules/payment/paypaldp.php
Add `noreferrer` attribute to javascript popup dialogs.
While the built-in popups generally don't interact with offsite resources, being explicit about the noreferrer property prevents potential misuse.
=> Add noreferrer to js popups

admin/includes/init_includes/init_sessions.php, includes/init_includes/init_sessions.php
Sets the default `samesite` handling to `lax`. 
NOTE: This only works on sites using SSL. If you're not using SSL then this is pointless (and you won't be able to do secure payments).
If you need to override the default of `lax` mode (as some payment redirections will require), create a file named `/includes/extra_configures/samesite_cookie.php` containing the following:
```php
<?php
// -----
// Samesite cookie needs to be none when doing offsite payment gateway redirects
//
define('COOKIE_SAMESITE', 'none');
```
This same change should work on Zen Cart v1.5.5 and 1.5.6.
=> Add samesite cookie parameter support for v157

email/email_common.css
- background color for comments changed to tan
- comment block and products block given same padding as blocks below.
Old styling: 
New styling:
=> Update padding in HTML email CSS

includes/classes/InitSystem.php
````
[Datetime TimeZone Obscured] Request URI: /index.php?main_page=product_info&products_id=1, IP address: obscured
#1  Zencart\InitSystem\InitSystem->getLoadersFromFilelist() called at [/includes/classes/InitSystem.php:171]
#2  Zencart\InitSystem\InitSystem->loadAutoLoadersFromSystem() called at [/includes/classes/InitSystem.php:182]
#3  Zencart\InitSystem\InitSystem->loadPluginAutoLoaders() called at [/includes/classes/InitSystem.php:34]
#4  Zencart\InitSystem\InitSystem->loadAutoLoaders() called at [/includes/application_top.php:215]
#5  require(/includes/application_top.php) called at [/index.php:25]
--> PHP Notice: Undefined variable: autoLoadConfig in /includes/classes/InitSystem.php on line 221.
````
=> Eliminate notice on each catalog page load.

includes/classes/shopping_cart.php
Inspired from: https://www.zen-cart.com/showthread.php?227158-Parameter-must-be-an-array-or-an-object-that-implements-Countable-in-shopping-cart
=> Ensure that posted products_id is an array on update

includes/functions/functions_email.php
The line break means the message looks like this: 
```
--> PHP Notice: Email Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting<br /> in /home/username/zencart/includes/functions/functions_email.php on line 377.
```
No need for the line break in the middle.
=> Remove <br> tag from email error message

admin/includes/header.php
extra parameter belonged to the external zen_href_link function.
=> version detection had incorrect parameters assigned.

includes/functions/functions_email.php
In the file includes/modules/pages/contact_us/header_php.php
if you call
zen_mail($send_to_name, $send_to_email, EMAIL_SUBJECT, $text_message, $name, $email_address, $html_msg, 'contact_us_special');
the template used should be email/email_template_contact_us_special.html (assuming that exists), not
email/email_template_contact_us.html just because zen_mail was called from the contact_us page.
The $module parameter in the call, not the $current_page_base, should be the top priority.
=> Changed search order for email templates to use $module (not current_page_base)

admin/includes/modules/search_box.php
There are multiple pages in the admin that use a search box. The code for these boxes have to be maintained separately on each page, which is a pain when you want to change something.
This update puts the search box in a separate file (```admin\includes\modules\search_box.php```). This file contains mainly html code to display the box.  To display on a page do something like this:
```php
<div class="col-sm-offset-8 col-sm-4">```
<?php include DIR_WS_MODULES . 'search_box.php'; ?>
</div>
```
=> Put admin search box in seperate file

includes/functions/functions_prices.php
A population tool or other mod could accidentally forget to set the products.products_quantity_order_units field.  Prevent a divide by 0 error if that happens.
=> Prevent divide by 0 error on misconfigured products

admin/sqlpatch.php
For the FROM "rule" had considered: `$line = 'FROM ' . $table_prefix . ltrim(substr($line, 5));`
but that only works for one replacement not multiple like the
str_replace/str_ireplace would do. I don't know exactly why multiple
would need to be replaced, but kept with the same concept.
=> Allow SQL patch FROM processing to not require capitalization.

includes/classes/shopping_cart.php, includes/languages/english.php
pursuant to conversation on #3937; i have added a message for attempting to add an invalid product to the cart, and also addressed uncalled for redirects.  i think we should respect the created links and remove the action.  
in the referenced issue, creating a link to add 1 to the cart and go directly to the product page for that item fails; as the `products_id` gets added to the parameter exclude list.  apparently there is an attempt to make this not happen for reviews, however, i believe the `$parameters` array will already contain the `products_id`, so in my testing the if statement does nothing.
the addition of a notifier in the `zen_get_products_allow_add_to_cart` function is great, and was the exact idea that i had.  i think the function should check for an inactive product as it is …
=> disallow add to shopping cart for actionBuyNow and fix redirect

admin/sqlpatch.php
Relates to: https://www.zen-cart.com/showthread.php?227174-Spurious-error-message-Query-incomplete-missing-closing-semicolon&p=1372630#post1372630
The addition of the message was proposed for entry in PR #3288.
=> Still provide error message if final query doesn't have a semi-colon.

includes/modules/payment/paypalwpp.php
Credit to @lat9 for this fix, as reported in 
https://www.zen-cart.com/showthread.php?227112-PayPal-Express-Checkout-issue
Recommended for backport. 
Symptom: 
The admin will see "duplicate orders" of which only the last one was actually charged. 
A PHP notice is created which will look like this: 
--> PHP Fatal error: 1265:Data truncated for column 'settle_amount' at row 1 :: INSERT INTO paypal (order_id, txn_type, module_name, module_mode, reason_code, payment_type, payment_status, pending_reason, invoice, first_name, last_name, payer_business_name, address_name, address_street, address_city, address_state, address_zip, address_country, address_status, payer_email, payer_id, payer_status, payment_date, business, receiver_email, receiver_id, txn_id, parent_txn_id, num_cart_items, …
=> Strip currency code before inserting PayPal record

admin/options_values_manager.php
Ensures that regardless the parameter assignments that the end of the
url is appropriate (e.g. doesn't end with '&').
This also removes the use of page=1 to eliminate duplication of
address meaning (no page parameter and page=1 identifying the same thing)
=> Change option-name-values screen pagination URLs and remove page=1.

includes/templates/responsive_classic/css/responsive_mobile.css
Responsive Classic template on a mobile device (iPhone 7).  
Before image: 
After image: 
Looks ok on tablet; issue is only on phone.
=> Need padding between qty box and update icon on shopping cart page

includes/classes/split_page_results.php, includes/init_includes/init_canonical.php, includes/init_includes/init_sanitize.php
Prevents display/inclusion of `page=1` in the generated web address(es).
This is to remove the added page parameter into the page address as a
result of this being eventually fed to the canonical link.
This change also addresses the parameter and its appearance in the
canonical link if manually added to the web address.  This does a full
removal from the canonical address when page=1 or if the parameter
is non-numeric.
Fixes #4008
=> Prevent page parameter when link goes to page=1

includes/templates/responsive_classic/css/responsive_mobile.css
=> Prevent button truncation on checkout confirmation

admin/mail.php, includes/functions/audience.php
a) get_audiences_list second parameter should be 'true' or 'false', not 'customers_email_address'.  In this case, 'false' makes sense because you're emailing one customer and you don't want to wait for the counts to be created. 
b) in get_audiences_list, second parameter needs exact compare to 'true' or true.  Using == means you always enter the loop, because 'customers_email_address' (or 'false') will == true. 
c) The check for display_counts should be done in one place and reused in determining whether to add the count to the string; current code appends "(0)" when this display_counts is false, which is misleading.
=> Corrections in "audiences" processing

includes/functions/salemaker.php
Current code always disables any sale with a start or stop date of 0001-01-01.
=> [158] Fix salemaker disable logic

admin/orders.php
Since we're moving towards standardizing on this anyway, doing it now.
It may be beneficial to some admin plugins given the overrides it supports.
(If we had a reason for holding off on this in v157 I don't recall what it was.)
=> Update admin orders page to use shared admin_html_head

admin/includes/init_includes/init_sessions.php, includes/init_includes/init_sessions.php
... since the associated `php.ini` setting wasn't introduced until PHP 7.0, so the `ini_set` operation yields an empty value for the samesite attribute.
=> [157] Use alternate method to set samesite cookie attribute on PHP < 7.0

includes/modules/pages/ask_a_question/header_php.php
$pid is already cast to the integer of $_GET['pid'], simplifies the code
to use that cast value throughout the header file.
=> Remove unnecessary casting and variable use.

admin/featured.php
A piece of code was duplicated, and results in a fatal error on the page
=> Featured page: Remove extra code resulting in fatal error

admin/ezpages.php
The comma results in an fatal error
=> Remove extra comma form query in EZ Page

admin/products_to_categories.php, includes/functions/functions_categories.php
1) Comparison: global $products_filter is integer, slq result was string: the source product appeared in the target list.
2) Copy links always returned "Nothing to do".  (int)$row['categories_id'] was always 1 as the array returned from the new function is a simple array of ids.
=> Products to Categories, global tool copy links to another product, not working

admin/products_to_categories.php
Only first product was listed.
=> Products to Categories: fix linked product removal message: missing concatenation

admin/products_to_categories.php
Now I've remembered how to use Github 😒 ...
All the products were marked as selected.
a) $products_filter was not being passed when a different product was selected/form was submitted.
b) The drop down was not using that passed value either.
=> products to categories: $products_filter not being passed with form/not displaying selected product correctly

admin/specials.php
i need to look closer some times....
apologies...
this fixes the id correction from #4080.  that bug identified another bug that was addressed by the initialization of the specials_array outside of all loops.  considering the pulldown is not within the blocks where the specials array gets created, this makes sense to me.
=> specials. #4080

includes/functions/functions_prices.php
The round operation can fail and return 0 in some cases, making the value field zero.  Removing it prevents this from occurring.
**WITH round:** 
mysql> select options_values_price, round(concat(price_prefix, options_values_price), 5) as value from zen_products_attributes where products_id = '661' and attributes_display_only != '1' and attributes_price_base_included='1' order by options_id, value;
+----------------------+---------+
| options_values_price | value   |
+----------------------+---------+
|             110.0000 | 0.00000 |
|              90.0000 | 0.00000 |
|              50.0000 | 0.00000 |
|              70.0000 | 0.00000 |
+----------------------+---------+
4 rows in set (0.00 sec)
**WITHOUT round:** 
mysql> select options_values_price, concat(price_prefix, …
=> Do not round concatenated value used in sorting

admin/salemaker.php
i am not sure what is preferred; `!empty()` or `isset()` as both are used on this variable prior to the `is_object` check.  i choose to use the former.
=> fix PHP notice when no salemakers exist

admin/customers.php
ZC158 and current,
If the fields company, address second line ("suburb"), and state are disabled in admin configuration customers, Edit customer and save produces the notices
PHP Notice: Undefined index: entry_suburb in ..\zencart-158\admin\customers.php on line 97.
PHP Notice: Undefined index: entry_company in ..\zencart-158\admin\customers.php on line 101.
PHP Notice: Undefined index: entry_state in ..\zencart-158\admin\customers.php on line 102.
PHP Notice: Undefined variable: entry_zone_id in ..\zencart-158\admin\customers.php on line 185.
I've also set the Company column to hide on the listing when disabled.
=> Admin, Customers, Edit Customer: Fixes for php notices and hide Company column

includes/modules/pages/contact_us/header_php.php
we have already `strip_tags` on the posted `enquiry` var; and now passed it to a notifier.  
if one had modified the template to allow additional information to be posted (ie an order number) and wants to include that in the email; modifying the `$enquiry` var seems to be the place to do it.
in fact, i see value in adding an order number field (as i do for my clients) to the contact us page.  in this way, the email can have the order number field AND we can in turn populate the order comments table for a record of that communication.
if not, this change makes sense to me.
=> Allow notifier to add info to email inquiry

includes/modules/order_total/ot_coupon.php
- i do not think this is overly aggressive
- i think this is much easier to understand 
- it preserves all of the explanatory comments
- from a functional standpoint, i see no difference.
- it removes 39 lines of code and comments.
=> Combine switch statements in ot_coupon

admin/includes/functions/general.php
Missing single quote.  Backport of #4110 to 1.5.7.
=> [157] Missing single quote

includes/functions/functions_email.php
includes/classes/vendors/PHPMailer/src/PHPMailer.php line 1364 notes that send() can throw an exception, but we don't catch it in Zen Cart.  This means a fatal error, which could cause the checkout confirmation page to appear to hang (and cause multiple re-submits).
=> Catch exception when send() fails

includes/classes/shipping.php
just because a shipping module is ENABLED does not mean the module will return a quote. 
adding a tax element to an empty quote creates more problems down the line.
=> fix empty quote of enabled shipping module

includes/modules/shipping_estimator.php
looking at this code, i see the arrow anti-pattern; and it gets a bit confusing.  with more time, i would consider a refactor.
however, just looking at the code, one can see how `$selected_quote` might not get set, which has happened to me with my existing datasets.
setting the shipping to the same values as if there was an error in the selected quote seems like the best option for now, and corrects the warnings that i am seeing.
=> fix selected quote not getting set

includes/modules/order_total/ot_shipping.php
=> Prevent empty shipping module tax_class property being used for comparison

includes/classes/shopping_cart.php
when a customer is logged into their account and they have items in their cart, if that item goes inactive prior to them checking out, PHP notices for undefined index and Trying to access array offset on value of type null get generated.
breaking out of the products loop (similar to lines 1282-1283) addresses these notices.
=> break out of product loop if item removed from cart

includes/functions/functions_products.php
A common customization of this function is to check other fields.  Let's make it easier to do this by pulling the whole row in.
=> Pull all fields in query for allow_add_to_cart

admin/includes/functions/extra_functions/load_php_polyfills.php, includes/functions/extra_functions/php_polyfills.php
This provides (many, but not all) core PHP functions introduced between 5.6 and 8.0 for the purpose of backward-compatibility.
=> Polyfill PHP functions for mismatched PHP versions

includes/modules/pages/index/header_php.php
If SHOW_CATEGORIES_ALWAYS is enabled and CATEGORIES_START_MAIN is set to `0` for the home page cpath, the refactor in #3819 & #3841 was failing because the first query's checks give a false positive due to the nature of `0` not being found as a valid category record in the db.
Ref: https://www.zen-cart.com/showthread.php?227579-157b-No-categories-on-storefront-main-page
=> Restore "Always Show Categories on Main Page" feature from v156

admin/whos_online.php
If tracking a particular session, when the session disappears or is removed
it remains to be tracked; however, no longer exists. Further, if the session
being tracked is incorrectly entered, it will appear ass if the session
does not have a cart even if there is one.
This becomes a visible problem if there are two or more sessions active,
one of them is being tracked and the page is set to refresh periodically.
When that session expires and eventually only one session exists, at that
point, it is not possible to click on a session to force tracking it.
This clears the tracking data if it doesn't exist.
=> Remove inspected entry from whos_online URI if session no longer exists

admin/includes/classes/WhosOnline.php
Reduces the need to provide/attempt all other sessions and doesn't limit
to the first session that is returned. When a session is provided then
as each session is evaluated then when reviewing the cart information
only that session's cart data will be included.
=> Whos-online: Inspect all sessions if no specific session has been provided.

includes/functions/functions_prices.php
When using PHP 7.4+ and attempting to perform mathematical operations against an empty string (`''`), a warning message is generated about a non-numeric value being encountered as a result of the returned value from the price function `zen_get_discount_calc`.  Although the thread where this was recently reported identifies problems with the output from that function, there are mathematical operations performed within the function that could also cause similar messages because the empty quote may be multiplied by a number which is expected to also generate a warning.
This appears to resolve the issue identified at this specific post: https://www.zen-cart.com/showthread.php?227580-A-non-numeric-value-encountered-in-shopping_cart-php&p=1376008#post1376008
=> Correct non-numeric value.

includes/classes/shopping_cart.php
Address notice at line 1789, ensuring that $attributes is set to an array of some type, either empty or including attribute data. Formerly this looked for the "presence" of the attribute; however, both in current PHP environments and when strict PHP is enabled a notice was expected to be generated when entering this code cycle.
Corrects potential notice associated with product being evaluated if it is not within the `$_POST`ed content (for whatever unusual reason that may exist).
Corrects notice when evaluating decrease but the quantity increases or remains the same or in reverse if evaluating for increase and the quantity decreases or remains the same.
Fixes #4180
=> shopping cart notices on product update

includes/modules/order_total/ot_coupon.php, not_for_release/testFramework/unittests/testsDiscountCoupon/DiscountCouponsTest.php
This refactoring segments several big long blocks of code into smaller functions.
The end result is that it now allows for some external processes to use the module's coupon validation rules.
For example, it would be fairly easy to capture a `?coupon=FOO` from the URL and ask ot_coupon whether it is valid, and if it's valid then apply it to the Session (eg, cart) automatically.
Handy for emailings or in-site clickable links.
**Backward compatible with v1.5.7** save for a small change in the data passed to the `NOTIFY_OT_COUPON_CALCS_FINISHED` notifier that was added in 1.5.7.
=> Refactor ot_coupon to expose validation methods

admin/stats_products_lowstock.php, admin/stats_products_purchased.php, admin/stats_products_viewed.php
these old style links stopped working a couple of versions ago for product types whose `type_handler` was not `product`.  purchase some music on your testdata and see.
=> correct links on admin/stats_products_* pages

includes/templates/responsive_classic/templates/tpl_account_default.php, includes/templates/template_default/templates/tpl_account_default.php
The 'Total' column displaying the customer's previous orders is currently being displayed as a 'raw' number instead of using a currency format..
=> [158] account: Format order-totals using currency in which order was placed

admin/category_product_listing.php
Additional notifications added for the admin's Category/Product listing, enabling an observer to
- Handle additional form-actions
- Insert columns into the _products_ listing, both before and after the Quantity column
=> [157] Additional category_product_listing.php notifiers

admin/includes/modules/copy_product_confirm.php
`zen_get_product_details` has 2 fields from `TABLE_PRODUCT_TYPES` that need to be skipped in order that the copy of a product succeeds.
=> fix copy product failing

admin/category_product_listing.php
there is a refactor of search terms here.  it just seems clearer to me.
i would think that we can add the page parm into the same var, but....
**more importantly** on new lines, 920, 921; the inclusion of the `$search_parameter` is necessary.  else, depending on the size of your products table and various other configs, you can end up with `$pInfo` not getting properly populated due to the split page results populating the limit on the raw sql, with results in a search set that does not have the product identified by the `$_GET['pID']` as part of said search results.  (screenshot below.)
i have encountered this bug numerous times over the years.
personally, i think we should carry over search terms after completing a copy, move, delete, etc.  but i did not want to get too aggressive.  but …
=> fix move and copy after searching

admin/modules.php
Reproducible by accessing the modules page (e.g. shipping) from some other
page in the admin, editing the default selected module and saving that
module without navigating to anything else.  During this process, the
uri parameter of module will not be set and later cause a notice on line 65.
Had previously submitted a fix for line 65; however, recently was able
to recreate the issue directly and specifically.
=> Prevents notice during module setting.

admin/orders.php
The admin version of `zen_redirect` has only one parameter which is the
destination address. The generation of that address through `zen_href_link`
accepts an indicator of whether to use `SSL` or `NONSSL`. That value is
expected to be in the third position of calling the `zen_href_link`
function. The modified line originally has `NONSSL` as the second parameter
to the `zen_redirect` function. When modified as provided, this would
correctly become the third parameter.
=> Parameter for zen_redirect of zen_href_link incorrect.

includes/modules/pages/address_book_process/header_php.php
When the state (free text field) is not set (when dropdown in use), on form submission, $state is set in header to FALSE.
Later this is operated on by trim which errors in strict mode as it is a boolean instead of a string.
It seems safe to change the FALSE to ''.
=> account, edit address. when state not set, $state is false in header, triggers strict error with trim

includes/modules/pages/address_book_process/jscript_addr_pulldowns.php
If dropdown with list is shown: it is required (hidden state text field is not required).
If dropdown with "Select" (and no list) +  state text field is shown: text field is required (not drop-down).
=> account, address edit. sets required on state fields as...required

includes/modules/pages/address_book_process/jscript_addr_pulldowns.php
For account edit address.
On change of country, js was only checking if the previous option was not "".
`  if (SelectedZone != "") theForm.elements["zone_id"].value = SelectedZone;`
and then used that value irrespective if it existed in the options list object or not.
So when there is no match, nothing is "selected" and so the drop-down field is blank instead of showing "Please Select..."
My solution iterates through the object until it finds a match, maybe there is a better way...
=> change of country does not leave zone dropdown option "Please Select..." as selected.

admin/configuration.php
Should amplify that this was considered from a link address where the gID parameter was set, but it was set to a value that is not present in the database.
=> Mitigate notices for a non-existent gID

admin/includes/languages/lang.english.php, admin/modules.php, includes/languages/english/modules/payment/paypal.php, includes/modules/order_total/ot_coupon.php, includes/modules/payment/paypal.php
I did a couple of examples (coupons, PayPal Standard) in this PR to show how the result would look.  I can do the others once this PR is merged. 
Here is a screenshot of the dialog produced for the help in PayPal Standard:
=> Allow ship/pay/ot modules to offer their own help

includes/modules/shipping/table.php, zc_install/sql/updates/mysql_upgrade_zencart_158.sql
In the original description, "ordered" is misspelled "orderd." 
Took the opportunity to restructure the description so that it is in the same order as the options shown (weight, price, item).
=> Fix typo in description for MODULE_SHIPPING_TABLE_MODE

includes/functions/functions_search.php
the previous change on line 163 (eliminating the early return) introduced a PHP notice if no valid keywords are submitted to the function.  the coalesce function on line 205 addresses that issue.
in my previous testing for my category and product pulldowns PR, i also discovered a situation that text being cast as integers would result in `0` which gave results that were not as accurate as i like.  i pushed that change in that PR, but probably should have created its own PR.  given that i wanted to address the (minor) PHP notice i added that fix here.
=> fixes php notice and improves search results on fields ending in _id

admin/category_product_listing.php, admin/includes/languages/english/lang.category_product_listing.php
Initiated by the unequal row count between category and product results, I've attempted to simplify this mixmatch between the category and product information.
a) Added images and a title to the category listing to bring it closer to the product listing. Show/hide the images I intend to add to another PR. 
b) Added a preview icon to the cats and changed the icon to the popup icon for all: as it is not a **pre-**view but a real view of the catalog, and I didn't think the current icon reflected the function.
Put that icon/link with the name instead of in its own table cell/column, removing colspan.
This makes it much easier to understand the layout.
simplify table row layout (add category image, merge preview icon with name), correct unequal rowcount for search results, change review icon …
=> category-product listing: correct unequal columns for search results

admin/includes/functions/general.php
Doing so will cause a PHP log on systems where php_uname() "has been disabled for security reasons."
=> Don't call php_uname if exec disabled

includes/functions/functions_general.php
Adding a notification to the `zen_get_buy_now_button` function, enabling a watching observer to make modifications to the to-be-returned button ... think Back-in-Stock Notifications.
Suggest back-port to the zc157 series.
=> zen_get_buy_now_button, adding notification

includes/classes/order.php
as 1 example: with the addition of `emp_admin_login` into the base ZC, i see instances where stores that are entering orders via this tool would not want the extra emails in their inbox.  adding a boolean to the existing notifier could accomplish this task.
=> add boolean to send-extra-order-email notifier

admin/products_to_categories.php
Fixes https://github.com/zencart/zencart/issues/4249
This is the same as used in attribute controller.
Note that the products_id returned from the function zen_get_linked_products_for_category is the lowest numerical id, and is used as the preselected product in the list.
The overly complicated (and bug-causing) query that this replaces, **was** returning the first products_model (my preference, of course).
A similiar query is also in products_price_manager, but returning the lowest product name.
So, three places, three "defaults". 
I would suggest replacing the products_price_manager with the same function call, so at least there is consistency.
Then conclude the discussion about how to allow the user to have their choice of sorting option, prior to modifying this function and other …
=> products to categories: simplify query...result is lowest products_id

admin/orders.php
Instigated by a html warning as two anchors shared the "status" id.
I've separated and rationalised the naming for the status filter and status update forms and posts to clarify their function.
=> admin orders: separate and clarify status update and status filter forms

admin/includes/languages/english/lang.layout_controller.php, admin/layout_controller.php, includes/functions/functions_templates.php
Layout Boxes Controller enhancements
- choose from available templates instead of only editing the live template
- reset by copying settings from another template or from original ZC defaults
- you can now reset `template_default`'s settings as a convenient way to preserve preferences
- "single-column" settings removed, in favor of left/right
Note: template selection choices are based on templates whose directory exists catalog-side, regardless of whether registered in database or enabled in Admin template selection screen.
=> Layout Boxes Controller enhancements

includes/modules/order_total/ot_coupon.php
preface: coupons are hard and confusing.
this PR has 2 corrections. 1 is a question of style; the other corrects incorrect logic.
the style correction removes an error message buyers would see when removing a coupon.  it is very easily demonstrable on a vanilla v158 install.  create a coupon; add items to your cart applicable to said coupon; use the coupon; now use the remove code to remove it.  one gets 2 messages, one of which is the `TEXT_INVALID_REDEEM_CODE`, which seems completely wrong to me.
now, if one has no coupons as part of the cart, and types in the remove code, no message comes up.  i thought about this scenario, and thought about coding for it; easily enough done, but is it of any value?  rare situation...  but following the directions on the screen and getting an error …
=> correct misleading message, and correct minimum order amount requirements

admin/invoice.php, admin/orders.php
People using external tax calculation software like Taxcloud will find it confusing to see the an inaccurate tax column for products.  We can make this easily switchable in the orders and invoice admin modules.
=> Provide variable to disable product tax column display

includes/functions/functions_taxes.php
If function is used to look up tax rates based on a description, even
TEXT_UNKNOWN_TAX_RATE is not present and therefore leads to the problem
described at this ZC forum thread:
https://www.zen-cart.com/showthread.php?228051-tax_rate-undefined-index
Chose the specific use of setting the tax rate to 0.0 so that one could
"easily" consider other rates to apply if necessary or some other
variation. Another alternative to this could have been to upfront
evaluate `$description` and if it equaled TEXT_UNKNOWN_TAX_RATE to then
continue the loop which would skip the tax assignment.
=> Remove php notice when searching for non-existent description

admin/coupon_admin.php
addresses the following 2 errors:
```
PHP Fatal error: 1052:Column 'coupon_id' in where clause is ambiguous :: SELECT coupon_code, coupon_start_date, coupon_expire_date, coupon_calc_base, coupon_is_valid_for_sales, coupon_product_count
FROM coupons c
LEFT JOIN coupons_description cd ON cd.coupon_id = c.coupon_id
AND language_id = 1
WHERE coupon_id = 37
```
```
PHP Notice: Undefined index: message_html in /var/www/admin/coupon_admin.php
```
=> sql error: column ambiguous

admin/categories.php
If a category image was defined but missing/not found, this info was being hidden.
Moved clause to prevent php error from getimagesize.
=> ZC158, admin, categories: fix image meta info

admin/specials.php
Problem: `$specials_price` is converted to `float` resulting in a percentage-based special price becoming an absolute price
=> Bugfix: ZC158, admin, specials, remove cast to float

includes/languages/english/modules/shipping/zones.php, includes/modules/shipping/zones.php
We don't need a second weight abbreviation.  Use the main one.
=> Remove duplicate definition of shipping weight units string in zones module 

includes/modules/payment/paypal/paypal_curl.php
Paypal NVP NOTE has a max length of 255 characters
Payflow COMMENT2 has a max length of 128 characters
=> Truncate Paypal/Payflow note length to max acceptable values

admin/includes/modules/copy_product_confirm.php
Easier to read, easier to modify, consistent with earlier updates which also have been switched to use this method.
=> Make copy product use zen_db_perform

admin/modules.php
This is a bit nitpicky, and I'll understand if this is rejected. Just makes it so that an installation (using default language files with `\n` newlines) send the HTML version of the notification message with actual `<br>` for line breaks in it. (Most email programs don't immediately interpret `\n` newlines as `<br>`. At times they'll just leave it as one block.)
=> Render line-breaks in Admin-settings-notifications HTML messages

admin/invoice.php
Fix in case there's another 157 branch release.  
From: https://www.zen-cart.com/showthread.php?227861-printed-order-comments-are-squished-instead-of-spanning-page-width&p=1379049#post1379049
=> Widen comments block in invoice

includes/functions/functions_prices.php
I was finding erratic results with the "Starting At" price when changing attribute prices...at some point the displayed price would not be the cheapest.
I found this to be the culprit:
https://github.com/zencart/zencart/blob/190bda0360fe1b3ad64c00fbcbd2da9404012884/includes/functions/functions_prices.php#L428-L436
The code subsequent to the query iterates through the results only once per option_id and so it is expected that the first instance of option_id in the query result will be the cheapest option. The sql concat structure produces the "value" field on which the results per options_id are ordered.
However, "value" is a string with maybe a + or - in it and so a set of attributes is sorted as this 
+11
+6
-1
no prefix 1
so +11 will be taken and displayed as the cheapest option.
I …
=> Modify query for "Starting From" price

includes/modules/order_total/ot_coupon.php
when Calculated From = "Based on Full Order Total of All Products"
Without this fix you'll get an error message saying a total of <$X> is required to use this coupon, as though the Calculated From setting were "Based on Total of Allowed Products according to Coupon Restriction Rules".
=> Fix coupon min. required calculation wrong 

includes/classes/PluginSupport/BasePluginInstaller.php
I think that this change is required as well as the typo that has already been changed by Dr Byte
e.g.
/includes/classes/PluginSupport/Installer.php:        if (!file_exists($pluginDir . '/Installer/' . $patchFile)) {
=> Change 'installer' to 'Installer'

includes/modules/pages/login/header_php.php
3 commits provided, First truly fixes the issue, but understand that alternate solutions may be considered desirable and are provided.
1 -     Prevent debug log when hiding cart combine
Addresses the issue described at:
https://www.zen-cart.com/showthread.php?228272-Help-with-Error-Log-(PHP-Notice-Undefined-variable-zc_check_basket_before)
This takes the shortest/simplest action to correct the issue by use of logic
instead of additional code.  Any other change simply adds more code to file
but may be desired to ensure updaters take at least one action which would
prevent this issue in a common otherwise unmodified store.
This is applicable to V1.5.7 and previous version as well, but likely
is not made known unless using strict PHP operation as it does not appear
to have been revealed …
=> V158 pages login combine cart

includes/classes/cache.php
This fixes this PHP Warning that happen when the file never existed:
```
PHP Warning: unlink(/var/www/html/cache/zc_7eb4ed1f36d90140477d9474b61e0e26.sql): No such file or directory in /var/www/html/includes/classes/cache.php on line 92
```
In order to be able to use the `existing sql_cache_exists()` method I update it to be null by default, if no cache time is passed to it.
=> Fix expire sql cache only if file/db entry exist

includes/functions/database.php
The message suggests to replace `zen_db_output` with
`zen_output_string_protected`.
Issue is that the admin processing of `zen_output_string_protected` is
different than the catalog side and only the catalog side provides the
equivalent "output" as `zen_db_output` did.
Basically zen_db_output double encoded even on the admin side. Usage of
double encoding may have been incorrect in some uses. That should be
corrected in a different way than the deprecation of the function.
Unfortunately, `zen_output_string_protected` is in a way also mis-represented
as it does *not* double encode on the admin side where double encoding
would be *"more"* protected, although also may directly cause an issue
because characters such as an ampersand would have the ampersand double-encoded.
Double encoded would …
=> Modify the deprecation message for admin use of zen_db_output

admin/options_values_manager.php
Fix for:
if a duplicate name is inserted, triggers php warning Undefined variable $check_dups
=> Option Values Manager fixes for php warning Undefined variable $check_dups

admin/configuration.php, admin/includes/languages/lang.english.php
To sort more configuration menus by name, modify `CONFIGURATION_MENU_ENTRIES_TO_SORT_BY_NAME` in 
`admin/includes/languages/lang.english.php` (1.5.8). 
To sort more top level menus by name, modify `MENU_CATEGORIES_TO_SORT_BY_NAME` in `admin/includes/languages/english.php` (1.5.7) or `admin/includes/languages/lang.english.php` (1.5.8).
=> Sort Configuration > My Store alphabetically

admin/stats_sales_report_graphs.php
The current graph tries to superimpose avg sales on top of the current view.  This works ok for weekly or daily but fails on monthly because the required scale of monthly means avg sale will disappear from view.  Separating out these charts works better.  Here is monthly with the current software - notice how avg sale is invisible. 
and here it is broken out by this PR:
=> Improve Sales Report Graphs

includes/templates/template_default/templates/tpl_checkout_payment_default.php
use of the ternary operator `?:` does NOT address an isset situation.
use of the null coalescing operator addresses this problem.
from the php page on the operators:
The expression (expr1) ?? (expr2) evaluates to expr2 if expr1 is null, and expr1 otherwise.
In particular, this operator does not emit a notice or warning if the left-hand side value does not exist, just like isset().
=> correct misuse of ternary operator

includes/modules/pages/redirect/header_php.php
```
--> PHP Warning: Undefined array key "action" in .
.../includes/modules/pages/redirect/header_php.php on line 15.
```
I've had a couple of times for urls missing the action, eg:
> ... index.php?main_page=redirect&products_id=1575
> ,.. index.php?main_page=redirect&manufacturers_id=5
=> ZC158, php warning when action not set: assign value to action when not set

admin/includes/header.php, includes/filenames.php
- In if statement:
- Remove unused define ```FILENAME_DEFINE_LANGUAGE```
- Remove ```FILENAME_PRODUCTS_OPTION_NAME``` Seems not really needed in my opinion
- Replace ```and``` with ```&&```
- Replace ```sizeof``` with ```count```
- Short arrays
=> Remove unused Define, and some code modernising, in admin header.php

admin/orders.php
the sort still needs to be there as `$db->Execute` returns the results in a reverse order which is different than running the query in a mysql session.  
this results in faster response with same results.
=> improve query performance #4500

includes/modules/payment/paypal/paypal_curl.php, includes/modules/payment/paypaldp.php
- paypaldp.php
- `selection`: Correcting PHP notices, missing $ccnum and $maestronum.
- `pre_confirmation_check`: 
- issue_month, issue_year, issuenumber might not be present
- requestXML, rawXML are not included in the response
- Use simple comparison instead of strcasecmp
- `before_process`: Capture 3Ds variables in log (better remote debugging)
- `zcLog`: $_GET['token'] might not be set
- `get3DSecureLookupResponse`: 
- $_SESSION['cart']->get_content_type is a function, not a variable
- 'SPAHiddenFields' not always (or ever?) included in the response
- paypal_curl.php
- Adding 'PAYMENTINFO_0_' to the list of prefixes removed for payflow-uk
Note: Also capturing zc157 changes not already incorporated
=> 158: paypaldp/paypal_curl, correcting PHP notices, partial payflow-uk

includes/functions/functions_osh_update.php
We already provide most of the other parameters to zen_mail() as parameters to zen_update_orders_history() - let's do this one too.
=> Allow attachments in zen_mail call in zen_update_orders_history

admin/banner_manager.php, admin/category_product_listing.php, admin/customer_groups.php, admin/customers.php, admin/ezpages.php, admin/featured.php, admin/geo_zones.php, admin/group_pricing.php, admin/manufacturers.php, admin/orders.php, admin/reviews.php, admin/specials.php
Through observation this counter needs to begin at a value of 0 so that
when a quantity spans more than one page, that the last item on the first
page can be selected allowing the page to reload with it selected and
editable. There may be other arrangements, but this fixes the issue with
the code continuing to exist here.
In some cases, added back the recently removed code to support this operation.
Fixed #4489
=> v158 Begin numbering so that all items on first page area always selectable.

admin/invoice.php, admin/packingslip.php
Replacement for #4447
invoice.php changes
1.     Restore hardcoded defaults.
2.     Additional notifier NOTIFY_ADMIN_INVOICE_DEFAULTS to allow changing of default settings.
3.     Additional notifier NOTIFY_ADMIN_INVOICE_HEADING_B4_TAX, NOTIFY_ADMIN_INVOIVE_HEADERS_AFTER_TAX to allow product field headings to be added before and after tax information on the invoice
4.     Additional notifier NOTIFY_ADMIN_INVOICE_SORT_DISPLAY and minor code change to allow invoice to be sorted into different sequence.
5.     Additional notifiers NOTIFY_ADMIN_INVOICE_DATA_B4_TAX, NOTIFY_ADMIN_INVOICE_DATA_AFTER_TAX to allow product field to be added before and after tax information on the invoice
packingslip.php changes
1.     Additional notifier NOTIFY_ADMIN_PACKINGSLIP_DEFAULTS to allow changing of …
=> add notifiers to invoice and packing slip

admin/options_values_manager.php
When there is no filter set of an option name:
php version <8 : all the option values are listed
php version >8 : no option values are listed
due to string to number comparison change:
https://www.php.net/manual/en/migration80.incompatible.php
In this file the filter is set to an integer or 0 integer, and all comparisons apart from this one in the query are already strict.
=> ZC158 options values manager fix for comparison fail from php8

admin/categories.php, includes/functions/functions_categories.php
Incorporates the idea of reducing number of lines of code and code duplication by use of a single function instead of the same code rewritten multiple times differing only in the image that is assigned. This is similar to the newly added `zen_set_category_status` function.
The second commit in this PR implements the use of the new function `zen_set_category_image` that is in `catalog/includes/functions/functions_categories.php`.
=> V158 add and incorporate function zen set category image

admin/includes/modules/move_product.php
Move product was not working from a search result listing.
The Move Product infobox form action has a cPath parameter. On form submission this cPath is used to generate the current_category_id **for that product** which in turn is used in the move sql prior to changing the entry in the products_to_categories table.
So, this cPath must be one in which the product is located (whether master or linked), to generate a valid current_category_id.
1) If you navigate to a product and use the Move function, the cPath on the form action is a valid one for that product and so the Move works.
2) If you search, and use the Move function from one of the products in the list, the cPath used on the form action is the one related to the **last product in the results list**.
Here you see the Matrox is in …
=> ZC158 Admin, Move Product from a search result: use cPath value from current_category_id of selected product

admin/includes/auto_loaders/config.product_category_pulldowns.php, includes/classes/categoryPulldown.php, includes/classes/productPulldown.php, includes/classes/pulldown.php, includes/functions/functions_categories.php
in looking at the 2 category and 2 product functions, i decided to refactor them into a small class file.  i'm not hugely tied to any of it, but it makes much more sense to me.
persuant to our conversation in #4083, we talked a bit about separating the db functions from the decorating.  i'm not sure if by decorating you were referring to the html parameters; or the names in the pulldown.  the names in the pulldown are harder to separate without doing unnecessary db hits.
in any event, this can easily be tested with the following code:
```
<?php
require 'includes/application_top.php';
require 'includes/classes/prod_cat_pulldown.php';
echo zen_draw_products_pull_down_categories('test');
echo __FILE__ . ':' . __LINE__ . '<br>';
$pull_down = new prod_cat_pulldown('category');
echo …
```
=> Refactor prod cat pulldowns into class file.

includes/classes/db/mysql/query_factory.php
Without this fix, you get a PHP log in 1.5.7 when editing a product that looks like this: 
[18-Sep-2021 06:57:43 America/New_York] Request URI: /store/admin/index.php?cmd=product&cPath=105_110&product_type=1&pID=3826&action=new_product, IP address: ::1
#1  zen_set_field_length() called at [/Users/scott/Sites/store/admin/includes/modules/product/collect_info.php:452]
#2  require(/Users/scott/Sites/store/admin/includes/modules/product/collect_info.php) called at [/Users/scott/Sites/store/admin/product.php:102]
#3  require(/Users/scott/Sites/store/admin/product.php) called at [/Users/scott/Sites/store/admin/index.php:11]
--> PHP Warning: A non-numeric value encountered in /Users/scott/Sites/store/admin/includes/functions/general.php on line 2230.
=> Add TINYTEXT to the list of types that don't provide a length

admin/orders.php
Without this fix, order navigation looks like this: 
With this fix, it looks better:
=> Wider order number required for sites with 6+ digit order numbers

admin/includes/functions/general.php, admin/server_info.php
I have seen a number of cases where Admin > Version shows 
MySQL Slow Query Log Status: On
when the true value is Off.
This change fixes that issue.
=> Correctly reflect state of slow_query_log global

includes/functions/functions_general.php
It's confusing to have Sold Out use the same styling as a button with an action.  This change reverts to using the old style image. 
Before:
After:
=> Sold out should not be presented as a button

admin/mail.php
Fixes #4494 
This bug also exists in Zen Cart 1.5.7. 
Now admin/mail.php will show the counts of each audience if the admin setting Admin > Configuration > Email > Audience-Select Count Display is set to true.
=> Fix incorrect call to get_audiences_list()

includes/functions/functions_prices.php
Without a trailing space added, products with both a min and units setting are shown as
Min: 5Units: 5
=> Add trailing space after min

zc_install/includes/languages/en_us/main.php, zc_install/includes/systemChecks.yml
Fixes #4535
Add check to see if php-zip is installed
Add error message TEXT_ERROR_PHPZIP_SUPPORT to main.php
Add now critical error to check zip module installed to systemChecks.yml
Tested against php 8.0
=> Fixes #4535 Demo images not present - ZipArchive not found on install of 1.5.8 zen cart

admin/featured.php, admin/includes/functions/html_output.php, admin/specials.php
i decided to use a common function for building the search form.  i'm hopeful of potentially using it in additional places.  it still provides this functionality to the specials and featured pages on the admin side:
in addition, both scripts were missing a closing div tag which i added.
=> add a common search form; fix missing closing tag

includes/templates/template_default/templates/tpl_modules_checkout_address_book.php
If you select a different shipping address from your billing address, the billing address should show up as the selected one when you try to change the payment address. 
See also https://github.com/lat9/ZCA-Bootstrap-Template/pull/106
=> Current address should match payment, not shipping

zc_install/sql/updates/mysql_upgrade_zencart_158.sql
Tell a Friend has been deprecated for a long time but these settings are still lying around.
=> Remove config settings related to Tell a Friend

admin/developers_tool_kit.php, admin/includes/languages/english/developers_tool_kit.php
With the addition of Plugins to the admin side of the store, searching
for information within the plugins remains advantageous. However, with the
addition of plugin versions, all plugin software is searched when looking
at the admin and not just the latest or active version nor is there a way
to exclude searching the plugins on a per search basis.
This adds a checkbox to add the zc_plugins directory into the applicable
search which currently is all files, all admin and just the plugins
searches plugins directory. An alternative solution that was temporarily
locally implemented was to add options into the dropdown to describe
performing the search without plugins; however, the list becomes that much
longer and more code to be added.
The choice of add plugins was made to demonstrate that if …
=> Include Plugins in Search?

includes/languages/lang.english.php
It was loosely comparing to an integer instead of a string.
=> fix: Storefront language comparison

admin/stats_products_viewed.php
@swguy this removes spiffycal from this script.  personally i am a fan of having built in functions do all of the validations, so i pulled a lot of that stuff out.  i'm not seeing complaints on datepicker (on other admin scripts) and its error checking so i think we are good there; but some additional testing and another set of eyes is always good.
on another note, in my testing the split page class does not provide accurate results.  which messes up the pager in this script.
in my testing this bug was independent of my branch and should be easily reproduced on the v158 branch.  at least it is for me.
=> remove spiffyCal from stats_products_viewed #4363

admin/customers.php
1.5.8 fixes the position of these fields by moving out out of the conditional for ACCOUNT_COMPANY.  However, it just puts them directly below the close of this block, which means they are outside of a row.  
This change moves them into the row labelled "Personal" below email address.
=> Properly position extra customer fields created by NOTIFY_ADMIN_CUSTOMERS_CUSTOMER_EDIT

admin/customers.php
It was checking for is_array which was always true.
=> admin, customers, notifier: check for array content

admin/developers_tool_kit.php
Make modifications as suggested in the following post: 
https://github.com/zencart/zencart/pull/4486/files/88be03db7b6cc4ee80d1610711e520b2215e6b58#r782133429
Associated  with pr #4486.
Changing isset followed by a non-falsey test to !empty
Also changing assignments where to use a value of it is set otherwise use some default value to using the format of: `$value = $othervalue ?? $default;`
This is supported by the minimum php version for Zen Cart 1.5.8 and above not expecting to use nor support php version less than 7.
=> Replace isset as able

admin/category_product_listing.php
Fixes #4480.
Use `MAX_DISPLAY_RESULTS_CATEGORIES` for pagination only if not searching; otherwise use `MAX_DISPLAY_SEARCH_RESULTS`.
=> Pagination should be different for search

admin/includes/languages/english/lang.options_values_manager.php
the filter is based on selecting the Name not the Value.
Also, I was looking at this text and think it is wrong/pointless/can be removed. 
Also I believe Default Order should be Sort Order.
=> admin, option values manager, correct text

includes/languages/english/lang.product_reviews_write.php, includes/languages/lang.english.php
This constant is used on the initial review page and the post-submission page, but is only declared for the initial review page.
So, after submitting a review:
> PHP Fatal error: Uncaught Error: Undefined constant "TEXT_APPROVAL_REQUIRED" in ...zencart\includes\templates\responsive_classic\templates\tpl_product_reviews_default.php:87
This PR moves this constant to the main language file.
=> move  TEXT_APPROVAL_REQUIRED to main language file

admin/includes/functions/admin_access.php, includes/functions/functions_general_shared.php, includes/functions/functions_osh_update.php, not_for_release/testFramework/unittests/testsNotifiers/AdminLoggingTest.php
If zen_update_orders_history() is called on the storefront due to an action by an admin logged in using Place Order, the admin id should be recorded in the order status history table.
=> Record admin id if Place Order was used when an OSH record is being added 

admin/includes/init_includes/init_errors.php, admin/includes/languages/lang.english.php
1) The constant was wrapped with zen_output_string_protected: I couldn't see why.
2) The additional info is useful after importing a real db for local use and forgetting to change to suit the local server transport method.
=> Admin, developer email diversion message: add transport info

includes/templates/template_default/templates/tpl_account_history_info_default.php
Set first false even if initial order comment is blank.
=> Guard against first comment being blank

includes/modules/pages/login/header_php.php
admins who are configured for automatic login should not have to logoff their previous session.  or the system should do it for them.  one less step for admins.  this accomplishes that task.
=> allow admins to auto login without the need to logoff previous session

includes/classes/shopping_cart.php
=> Restore public scope on shopping_cart::get_cart_id

includes/modules/pages/password_forgotten/header_php.php
store owners should be able to make the determination as to whether the session message tells the customer if their email address was in the database or not.
=> ability to change session message on password forget

includes/autoload_func.php, includes/classes/InitSystem.php
=> format debug output from DEBUG_AUTOLOAD = true

admin/attributes_controller.php, includes/functions/functions_products.php
On page load, the check for product_filter == '', fails due to php8 changes:
https://stackoverflow.com/questions/66025397/empty-string-comparison-to-zero-gives-different-result-in-php-8-than-in-previous
When there is nothing selected, the rest of the page is incorrectly shown, based on a product id of 0.
Initially in the page, $products_filter and $_GET['products_filter] are equalised to an integer or 0, but then later in the page, returns from zen_get_linked_products_for_category are strings.
So I've made all returned values and comparisons integer-based.
I think this is more evidence why my (previously criticised) stance of making all comparisons strict and adding strict_mode to files I review/overhaul, is the correct development approach and not just blindly pandering to IDE …
=> attribute controller: fixes for php8 strict comparison failure

admin/includes/functions/html_output.php
in further exploring the keyword search, i have found the following changes to make it more universal in its usage.  especially for those developers who might want to use any of the pulldown classes.
i think the parameter input list could be better, ie i think `$includeForm` should be first; but i did not want to change the 3 existing files that currently use this function.
=> improve search form for use in pulldowns

admin/includes/languages/english/lang.orders.php, admin/orders.php
With the definition of tax nexus shifting in the US, it may be useful for some shops to see at a glance which state an order is going to.
Feature is switchable for those who may not want it.
=> Show Delivery Zone Information for orders

includes/templates/responsive_classic/templates/tpl_modules_mobile_menu.php
... as identified in [this](https://www.zen-cart.com/showthread.php?228741-One-page-payment-and-default-responsive_classic-template-issue) Zen-Cart support-thread posting.  Otherwise, the "Logoff" and "Account" links are shown instead of "Login" when a customer is in the middle of a guest-checkout.
=> responsive_classic mobile menu needs !zen_in_guest_checkout

admin/includes/languages/english/lang.sqlpatch.php, admin/sqlpatch.php
**Before**
I found the "details" button did not popup/it showed a new page, and only repeated most of the text on the main page.
So I merged the texts into one warning for the main page, and removed the popup.
**After**
<strike>
And, deep breath....I changed the name from "Install SQL Patches" to "SQL Query Executor" as per the page title as that seems more accurate and does not imply that installing patches is a common thing to do.
</strike>
=> Admin, sql tool: texts, remove popup

includes/classes/order.php
Previously
> ID# 2        Matrox G400 32MB              Qty Left: 0
"Qty Left:" was hard-coded text.
Changed to:
> MG400-32MB		 "Matrox G400 32MB" (#2)		 In Stock:  0
Model displays only if used.
=> low stock email: remove hard-coded text and rejig format

admin/includes/init_includes/init_admin_auth.php
add an observer to catch any action by non-superuser
if non-superuser is NOT allowed to delete a category, a product or an order, this notifier can easily be used to prevent such actions
=> Add notifier to init_admin_auth.php, enabling additional non-superuser actions to be denied

includes/auto_loaders/config.core.php, includes/extra_datafiles/dist-site_specific_overrides.php, includes/init_includes/init_common_elements.php, includes/modules/sideboxes/information.php
Creates an initialization file that sets some "soft" configuration settings, overridable via variables present in a site-specific extra_datafiles module.
Starting with a flag that controls whether/not to display the "Brands" page's link in the information sidebox.
=> Fixes #4156

includes/modules/shipping/freeoptions.php
Fixes #4766.
- Moves the final "enabled" check into the `update_status` method, so a quote's only requested when (er) there's something to quote.
- Overall refactor of the code to (a) simplify, (b) improve performance and (c) use PHP strict comparisions.
=> V158 freeoptions updates

includes/functions/functions_general_shared.php
=> v158: Correcting `zen_rand` PHP 8.1 Deprecation log

admin/customers.php, includes/functions/functions_addresses.php
in researching `zen_get_country_zones` for adding of `zone_code` to the return array, it seems that we can reduce the db hits on the customers script by making use of the return values from said function.
=> add zone_code and refactor admin.customers

includes/templates/template_default/templates/tpl_modules_shipping_estimator.php
as referenced by the form action
`<?php echo zen_draw_form('estimator', zen_href_link($show_in . '#view', '', $request_type), 'post'); ?>`
=> shipping estimator template, change deprecated name to id

includes/modules/pages/address_book_process/header_php.php
Regarding extra-fields used in the address book table (such as in my case a telephone number per address),  
there are notifiers for adding extra-field validation and extra-field insertion, but not for retrieval.
The original sql pulls **all** the columns from the table anyway, by name. Changing this to SELECT * does the same but includes the extra-field(s).
=> retrieve all fields from address_book

includes/classes/Customer.php, includes/templates/responsive_classic/templates/tpl_account_default.php, includes/templates/template_default/templates/tpl_account_default.php
Fixes #4813.
- Moving the formatting into the `Customers.php` class to address the changes required for both #4196 and #4813.
- Created a separate array element returned by the class' `getOrderHistory` method to also return the 'raw' value of each order's total.
- Removing the template-specific formatting introduced in #4813.
=> v158: Correcting account-history unformatted totals

admin/invoice.php, admin/packingslip.php
As discussed in #4688, document how to override switches for displaying various things in `invoice.php` and `packingslip.php`, as was done in `orders.php`.
=> Document overriding of show_ settings

includes/functions/functions_email.php
[26-May-2022 22:25:27 UTC] Request URI: /gh_demo_158/admin/index.php?cmd=modules&set=ordertotal&action=install, IP address: ::1
#1 /Users/scott/sites/gh_demo_158/includes/functions/functions_email.php(582): file_exists()
#2 /Users/scott/sites/gh_demo_158/includes/functions/functions_email.php(109): zen_build_html_email_from_template()
#3 /Users/scott/sites/gh_demo_158/admin/modules.php(108): zen_mail()
#4 /Users/scott/sites/gh_demo_158/admin/index.php(11): require('/Users/scott/si...')
--> PHP Deprecated: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in /Users/scott/sites/gh_demo_158/includes/functions/functions_email.php on line 582.
=> Fix null param deprecation in PHP 8.1 when testing for email templates

admin/sqlpatch.php
[27-May-2022 10:42:25 UTC] Request URI: /gh_demo_158/admin/index.php?cmd=sqlpatch&action=uploadquery, IP address: ::1
#0 /Users/scott/sites/gh_demo_158/admin/sqlpatch.php(117): zen_debug_error_handler()
#1 /Users/scott/sites/gh_demo_158/admin/sqlpatch.php(771): executeSql()
#2 /Users/scott/sites/gh_demo_158/admin/index.php(11): require('/Users/scott/si...')
--> PHP Warning: Undefined array key 4 in /Users/scott/sites/gh_demo_158/admin/sqlpatch.php on line 117.
=> Fix sqlpatch undefined array key notice in PHP 8.0

admin/category_product_listing.php, admin/includes/css/stylesheet.css
Right now when viewing Admin > Catalog > Categories/Products, you cannot tell at a glance if a product has quantity discounts. If a product may be added to the cart, the icon is green.
This change makes the icon dark green if quantity discounts are present.
=> Change color for icon when Quantity Discounts enabled

includes/classes/order.php
PHP Notice:  Malformed value for session-based shipping module; customer will need to re-select: false in includes/classes/order.php on line 327
=> Fix for (some of) PHP Notice for malformed shipping 

includes/modules/pages/checkout_payment/jscript_main.php, includes/templates/responsive_classic/css/stylesheet_colors.css, includes/templates/template_default/css/stylesheet_css_buttons.css
Javascript to disable the continue button on the checkout payment page.
CSS changes to make button grey when disabled.
=> Disable continue if T&C not present

includes/modules/pages/about_us/header_php.php
=> v158: Adding start/end page notifiers for `about_us` page.

admin/customer_groups.php, admin/includes/languages/english/lang.customer_groups.php
a) Info button overlaid with right arrow icon looks wonky. 
Remove info button.  Displays right arrow when row is not the currently selected one. 
b) Remove help text at the top of page.  We have a separate help repository that is linked on the right.
=> Fix issues on customer groups page

admin/includes/languages/english/lang.options_name_manager.php, admin/options_name_manager.php, includes/modules/attributes.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_158.sql
This field is referenced in code, but, as Cindy noted in a forum post 
not actually in the database.  This PR adds it to the database and handles it on the admin and storefront sides.
I added the comment "This is the color comment" to the Color attribute.  
Here it is in position 0
and here it is in position 1
=> Add comment_position field to products_options

admin/customers.php
IP registration header is **before** table header observer but IP registration data was **after** table column data.
This PR corrects this.
Also corrected th alignment.
.
=> admin, customers: bugfix, relocate IP data prior to observer

includes/classes/order.php
`$payment_class` gets set on line 1218.  there is no guarantee this var is set on line 1229; hence the need for an additional conditional.
=> check for empty payment class

includes/functions/functions_gvcoupons.php
as discussed here https://github.com/zencart/zencart/issues/4317
=> function zen_create_coupon_code: remove type hint from parameter SECURITY_CODE_LENGTH

includes/classes/db/mysql/query_factory.php
Newer MySQL versions have deprecated display width. 
Fixes #4875.
=> Handles MySQL 8.0.17+

admin/coupon_admin.php
This bug shows up if more than a page of coupons is shown when you go to
Admin > Discounts > Coupon Admin.
search for a coupon code from the second page (or greater).
you will get a URL like
http://localhost:8888/gh_demo_158/admin/index.php?cmd=coupon_admin&cid=48&status=Y
but the sidebar does not contain the coupon data:
This change fixes it so the data is available for editing or accessing other screens.
=> Fix multi-page coupon search

admin/includes/classes/configurationValidation.php
With the recently merged addition of `configurationValidation::sanitizeEmailNullOK`, I'm met with a couple of issues:
1. A Fatal PHP error:
```
[19-Jun-2022 06:40:04 America/New_York] PHP Fatal error:  Uncaught Error: Using $this when not in object context in C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\classes\configurationValidation.php:23
Stack trace:
#0 [internal function]: configurationValidation::sanitizeEmailNullOK('0')
#1 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\includes\functions\configuration_checks.php(53): filter_var('0', 1024, Array)
#2 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\configuration.php(22): zen_validate_configuration_entry('0', '{"error":"TEXT_...')
#3 C:\xampp\htdocs\zc158\hoisT-PYL-teAch\index.php(11): require('C:\\xampp\\htdocs...')
#4 {main}
thrown in …
```
=> v158: Correcting PHP Fatal error for configurationValidation

includes/functions/html_output.php
In the case that an image is defined, but not found, ensure an image is assigned. Apart from a missing image looking bad, it can mess up the template layout too.
Maybe this section needs a review as this adds another check for !file_exists, but I don't see another simple way.
Discussed here:
https://github.com/zencart/zencart/issues/4112
=> check for a missing image

includes/functions/html_output.php
sites with handled images do not use the SIZE suffixes: will always fail.
Check for image source should be post handle_image.
=> fix: move missing image check after handle_image

admin/admin_activity.php
The WHERE clause for the admin user filter was **replacing** the WHERE of the log data filter instead of being **concatenated** to it.
=> admin activity: bugfix for use of both filters

includes/classes/order_total.php
Fixes this log, seen during `index.php?main_page=checkout_process`: 
```
--> PHP Warning: sizeof(): Parameter must be an array or an object that implements Countable in /var/www/html/myaccount/mystore.com/shop/includes/classes/order_total.php on line 66.
```
=> Check output before referencing

includes/languages/english/html_includes/responsive_classic/define_main_page.php
It's a minor infraction to use "use this link" for the three template-viewing options in the includes/languages/english/html_includes/responsive_classic/define_main_page.php.
These three link fixes get us closer to removing the 14 link alerts on the default home page.
=> Add name= to Ambiguous Links in Define_Main_Page

admin/customers.php
If customers file has `declare(strict_types=1);` set, (which I usually add to get a heads-up), opening the customer address book (when there is more than one), triggers this error.
`PHP Fatal error:  Uncaught TypeError: zen_get_customers_address_primary(): Argument #1 ($customer_id) must be of type int, string given, called in D:\GitHub\zencart\admin\customers.php on line 660 and defined in ...zencart\includes\functions\functions_customers.php:44`
So parameter needs to be cast. I also made the comparison strict (to annoy someone).
=> admin, customers, addresses: parameter passed to zen_get_customers_address_primary must be integer

admin/downloads_manager.php
Typo in class - stray semicolon.   
Before: 
After:
=> Fix filename LEDs

admin/products_price_manager.php
#4615 
also addresses additional actions being displayed when no product is selected under php8.x.
=> provide php74, 80 and 81 compatibility to price manager

includes/modules/payment/paypal/paypalwpp_admin_notification.php
passing  null to stripslashes causes a debug similar to this https://github.com/zencart/zencart/pull/4907
=> paypawpp_admin notification check for null

admin/customers.php
Data is right aligned so header should be as well. 
Before: 
After:
=> Fix alignment of GV Balance header on customers

admin/includes/modules/product/collect_info.php
Fix for problem 
> PHP Fatal error: Uncaught TypeError: strtr(): Argument https://github.com/zencart/zencart/pull/1 ($string) must be of type string, array given
as reported here: 
https://github.com/zencart/zencart/issues/4946
=> admin, collect_info: handle $pInfo->products_name as array or string

includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php
Results in an attempt to load `includes/languages//lang.english.php`, performance wasteful.
=> v158: CatalogArraysLanguageLoader, extraneous directory-separator used

admin/downloads_manager.php, admin/includes/extra_datafiles/dist-site_specific_admin_overrides.php, admin/includes/languages/english/lang.downloads_manager.php
When enabled, a new column is added showing the file modification time.
=> Optionally show file mtime in downloads manager

includes/functions/database.php
=> v158: Correct `zen_db_perform` handling of `null` values.

admin/includes/functions/general.php, admin/orders.php
This function should not have been deprecated; it's much faster than calling getStatusHistory.
References to the return value need to be simplified for readability.
=> Fix zen_get_orders_comments and calls to it

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_158.sql
Increase length to varchar(96) to be consistent with other zen cart
email address fields.
fixes #5004
=> emailed_to length in coupon_email_track table

includes/classes/ResourceLoaders/LanguageLoader.php, includes/modules/require_languages.php
... to correct missing constant errors for AJAX-loaded language constants.
Fixes #4983.
=> v158: Move page-specific language-loading to `require_languages.php`

includes/modules/pages/shopping_cart/jscript_addr_pulldowns.php, includes/modules/shipping_estimator.php
when SE was inline: double loading of jscript
when SE was button: unnecesary loading of jscipt on shopping cart
=> shipping estimator: prevent double loading of jscript

admin/coupon_restrict.php, admin/includes/extra_configures/flags.php, admin/includes/languages/english/lang.coupon_restrict.php, admin/includes/languages/lang.english.php, includes/extra_configures/flags.php, includes/languages/lang.english.php
Establishes a mechanism for setting non-language constants that were in language files in prior releases. 
Fixes #4649
Fixes #3126
Fixes #4633 
This PR is not intended to address all constants everywhere, it's just the first step.  Additional constants can be moved in future PRs.
=> Begin migration of non-language constants

admin/categories.php
This will empty out a category description if tags were improperly entered. 
This issue will only show up if CKEditor is not used when editing the category page.  CKEditor will correct improper tags.
=> Remove check for empty tags

zc_install/ajaxValidateAdminCredentials.php
Partial correction for #4449
Noting that (as with zc157) a password mismatch will be indicated on an upgrade from zc155/zc156 (or unsuffixed zc157) if the upgrading admin's password contains one or more 'htmlspecialchars': `&<>"`.
=> v158: Removing FILTER_SANITIZE_STRING use during zc_install

includes/classes/observers/auto.non_captcha_observer.php, includes/modules/pages/contact_us/header_php.php
Fixes #4987
Changes were required to both the `contact_us` page's header and the SPAM observer class.  The page-header has also been updated to 'not collect' customer information for the page's display when guest-checkout is active, using exactly-equal-to where relevant and removing a redundant `elseif` clause.
=> v158: Correcting spam detection on `contact_us` page

includes/templates/template_default/templates/tpl_gv_send_default.php
Change to use `$error = $error ?? false;` instead of `$error ??= false`.
=> v158: `??=` not introduced until PHP 7.4

includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php, includes/templates/template_default/templates/tpl_modules_products_all_listing.php
as seen when viewing All Products
> [03-Aug-2022 14:28:53 UTC] PHP Parse error:  Unclosed '{' on line 84 does not match ')' in zencart\includes\templates\responsive_classic\templates\tpl_modules_products_all_listing.php on line 85
> [03-Aug-2022 14:28:53 UTC] Request URI: /zencart/index.php?main_page=products_all, IP address: 127.0.0.1
> --> PHP Parse error: Unclosed '{' on line 84 does not match ')' in zencart\includes\templates\responsive_classic\templates\tpl_modules_products_all_listing.php on line 85.
=> z158 fix: All Products listings extra/missing brackets

includes/modules/payment/paypalwpp.php
fixes occasional debug when country1 or country2 not set as described here
https://github.com/zencart/zencart/issues/4656
=> paypalwpp: add test for empty for country1/country2 in log

admin/customer_groups.php, admin/featured.php, admin/group_pricing.php, admin/includes/modules/document_general/collect_info_metatags.php, admin/includes/modules/document_product/collect_info_metatags.php, admin/includes/modules/product/collect_info_metatags.php, admin/includes/modules/product_free_shipping/collect_info_metatags.php, admin/salemaker_popup.php
Toward html5 compliance. All these files have a space missing before a
tag attribute.
fixes "No space between attributes." on validation
I have started to break down #5085 to make it easier to understand, if you don't want me to do this please let me know.
=> missing space in html tag

includes/functions/functions_taxes.php
as discussed [in this thread](https://github.com/lat9/edit_orders/issues/215), this function does not account for a cart which is all virtual and the `$_SESSION['sendto']` gets set to `false`.
if `STORE_PRODUCT_TAX_BASIS` is set to Store, and the cart is all virtual, this method returns:
after this change, the method returns:
(your results may vary based on your test data...)
=> no sendto for taxes if cart is all virtual

admin/denied.php, admin/popup_image.php
Change doc type to HTML and remove Netscape coding from java script as
causing resize to be too small when using Firefox.
fixes #5128 5128
=> HTML5 and Firefox resize

admin/banner_statistics.php, admin/coupon_admin_export.php, admin/developers_tool_kit.php, admin/downloads_manager.php, admin/includes/attributes_preview.php, admin/includes/javascript/calendarcode.js, admin/includes/javascript/spiffyCal/spiffyCal_v2_1.js, admin/invoice.php, admin/media_manager.php, admin/newsletters.php, admin/option_values.php, admin/packingslip.php, admin/product_types.php, admin/salemaker.php, admin/stats_products_purchased.php, admin/stats_sales_report_graphs.php, admin/store_manager.php, admin/tax_classes.php, admin/whos_online.php
Fixes HTML5 Validation error 'The align attribute on the ... element is obsolete. Use CSS instead.' in the admin section of zencart.
fixes #5119
=> HTML5 Compliance Remove Obsolete Align Attribute

admin/includes/classes/box.php, admin/includes/classes/table_block.php
Define parameters for table_block and its sub classes
$table_row_parameters, $table_data_parameters are only used in the class and subclass so I have set to protected.
$heading, $contents are only used in this class so I have set them to private.
no changes required.
Do you agree with my logic? While I come from a process background, I have read up on OO and will happily take input if I have not got it right.
Part of #5103
=> PHP 8.2 Define Parameters table_block

admin/includes/classes/AdminRequestSanitizer.php
$arrayName set to private. Used to hold current rule being sanitized.
Part of #5103
=> PHP8.2 Define Parameters AdminRequestSanitizer

includes/classes/PluginManager.php
- $pluginControl
- $pluginControlVersion
Part of #5103
=> PHP8.2 Define Parameters PluginManager

admin/coupon_restrict.php
fix #5141
Always display the table heading rows to remove the HTML5 validation errors.
- Table column 3 established by element td has no cells beginning in it.
- Table columns in range 5…6 established by element td have no cells beginning in them.
I have done this for both tables to be consistent, even though it was only necessary for the second table.
Before
After
**Note:** the movement of the two lower buttons means that they are now more consistently placed on the screen when restrictions are present. If you want the screen to be totally consistent, would have to add bootstrap column widths.
=> Coupon_restrict HTML5 Validation

includes/modules/pages/discount_coupon/header_php.php
The field coupon_description (unlike `$_POST['lookup_discount_coupon']`) is not user input and should not be displayed using `zen_output_string_protected`.  It is entered by the store admin and may contain HTML.
=> Coupon description should correctly display HTML

admin/server_info.php
fix #5133
I have:
- removed border=0 from \<IMG> tag
- changed the doctype to html
- cleaned up the output from phpinfo
- changed \<font>\</font> to \<span>\</span>
- replaced name= with id= in \<a> tags
- removed border=0 from \<img> tags
- added a colspan for one occurrence of table row missing \<td>element
- Added htmlspecialchars to the output of system variables
I tested against php 7.4, 8.0, 8.1, 8.2
I had to define a lot of variables in the classes for 8.2. I just set them to public, and it worked fine. (not included in this release)
=> admin server info HTML5 complient

includes/classes/ResourceLoaders/ArraysLanguageLoader.php, includes/classes/ResourceLoaders/BaseLanguageLoader.php, includes/classes/ResourceLoaders/FilesLanguageLoader.php, includes/classes/ResourceLoaders/LanguageLoader.php
All private not used outside class
- $languageFilesLoaded
- $arrayLoader
- $fileLoader
no changes
Protected used in sub classes
- $fallback
- $fileSystem
- $languageDefines
- $pluginList
- $templateDir
Public used in subclass but not using $this
- $currentPage
protected used in sub classes
- $mainLoader
no changes
no changes
protected used in sub classes
- mainLoader
no change
no changes
=> PHP8.2 Define Parameters LanguageLoader

includes/classes/db/mysql/query_factory.php
Changed to Private
- $link
- $count_queries
- $total_query_time
Changed to public
- $dieOnErrors
- $error_number
- $error_text
Set to private
- $pConnect   
**N.B. $pConnect  could be completely removed as it is not used anywhere**
Part of #5103
=> PHP8.2 Define Parameters queryFactory

includes/classes/InitSystem.php
- $installedPlugins
- $debug
- $debugList
- $actionList
Changed from protected to private as not used outside of class
- $context;
- $loaderPrefix;
- $fileSystem;
- $pluginManager;
Part of #5103
=> PHP8.2 Define Parameters InitSystem

includes/classes/sniffer.php
- $browser,
- $database,
- $php,
- $server;
None of these appear to be set or used anywhere in the system
Part of #5103
=> PHP8.2 Define Parameters sniffer

admin/includes/classes/class.admin.zcObserverLogEventListener.php, admin/includes/classes/class.admin.zcObserverLogWriterDatabase.php, admin/includes/classes/class.admin.zcObserverLogWriterTextfile.php
- $notifier
I have bundeled these three together as basically same change.
Part of #5103
=> PHP8.2 Define Parameters zcObserverLog

admin/includes/classes/object_info.php
Define Parameters
Define all the parameters used by the class
Note this fixes 8.2 PHP Deprecated: Creation of dynamic property
**This does not fix the issue with customisation.** They will still be reported as a warning.
Could add #[AllowDynamicProperties] to disable the warning message.
=> PHP8.2 Define Parameters object_info

includes/classes/message_stack.php
$messages defined as private, not used outside of class, output method available to retrieve and add method to set.
=> PHP8.2 Define Parameters storefront messageStack

includes/classes/categoryPulldown.php, includes/classes/productPulldown.php, includes/classes/pulldown.php
$pulldown; is not used anywhere, so removed
Changed to protected as not used outside subclasses
- $attributes_join
- $show_id
- $set_selected
- $parameters
- $condition
- $exclude = []
- $count
Set as protected as used in sub classes not previously defined
- $keywords
- $keyword_search_fields
- $sort
- $sql
- $results
- $values = []
Set a private not used outside of class not previously defined
- $show_parent
- $show_full_path
No changes necessary
Set as private as not used outside of class not previously defined
- $categories_join
- $output_string
- $show_model
- $show_price
part of #5103
=> PHP8.2 Define Parameters pulldown

admin/includes/classes/stats_sales_report_graph.php
All set to public as used outside class $filter_link, $filter_sql = '', $status_available = [], $status_available_size = 0.
I did not set $filter_link as only defined in the class.
=>  PHP8.2 Define Parameters statsSalesReportGraph

admin/includes/classes/AdminNotifications.php
$projectNotificationServer set to private and not used outside of class
Also added check to see if set and return empty array if not set.
**Alternative**, if desired, remove both checks and fail if PROJECT_NOTIFICATIONSERVER_URL is not defined. 
Currently defined in include/version.php as "https://ping.zen-cart.com/api/notifications" and
in zc_install/includes/version.php as "https://versionserver.zen-cart.com/api/notifications".
=> PHP8.2 Define Parameters AdminNotifiers

includes/classes/zcDate.php
$dateObject set to protected. 
All other parameters are protected. This will allow for other classes to extend zcDate if needed.
=> PHP8.2 Define Parameters zcDate

includes/classes/split_page_results.php
Set to public as useful and used outside of class
- $current_page_number
- $number_of_pages
- $number_of_rows
- $sql_query
Set to private as only really useful inside class
- $number_of_rows_per_page
- $page_name;
- $countQuery
part of #5103
=> PHP8.2 Define Parameters splitPageResultsStorefront

includes/modules/checkout_new_address.php
Also added checks to $_SESSION['billto'] and $_SESSION['sendto'] as a precaution.
fix #5206
=> Check session payment set checkout_new address

includes/modules/main_product_image.php
If the filename in the database has no extension, strrpos returns false and this is not handled. If in strict mode, page dies.
This cropped up while testing a csv import of multiple products, and some idiot initially forgot to add the extension to the imported filenames.
=> fix for handling filename with no extension

includes/classes/shipping.php, includes/modules/shipping/flat.php, includes/modules/shipping/freeoptions.php, includes/modules/shipping/freeshipper.php, includes/modules/shipping/item.php, includes/modules/shipping/perweightunit.php, includes/modules/shipping/storepickup.php, includes/modules/shipping/table.php, includes/modules/shipping/zones.php
Set to public as notifiers may modify values
- $modules
- $enabled
- $abort_legacy_calculations
Set to protected not required outside class
- $_check;
Set to public used outside class
- $code;
- $description;
- $enabled;
- $icon;
- $quotes;
- $sort_order;
- $tax_basis;
- $tax_class;
- $title;
Set to public
- $debug = [];
Did not have $tax_basis have still included definition
Set protected as not required outside module
- $locations = [];
- $methodsList = [];
Set to protected only required by class
- $num_zones;
=> PHP8.2 Define Parameters shipping

includes/classes/order_total.php, includes/modules/order_total/ot_cod_fee.php, includes/modules/order_total/ot_coupon.php, includes/modules/order_total/ot_group_pricing.php, includes/modules/order_total/ot_gv.php, includes/modules/order_total/ot_loworderfee.php, includes/modules/order_total/ot_shipping.php, includes/modules/order_total/ot_subtotal.php, includes/modules/order_total/ot_tax.php, includes/modules/order_total/ot_total.php
Set to public used/required outside module
- $modules;
Set to protected as not required outside module
- $_check;
Set to public used/required outside module
- $code;
- $description;
- $sort_order;
- $title;
- $output = [];
Set to public used/required outside module
- $enabled;
$check changed to $_check for consistency.
Set to protected as not required outside module
- $coupon_code;
- $deduction;
- $validation_errors = [];
Set to public used/required outside module
- $calculate_tax;
- $credit_class;
- $header;
- $include_shipping;
- $include_tax;
- $tax_class;
- $user_prompt;
Set to protected as not required outside module
- $deduction;
Set to public used/required outside module
- $calculate_tax;
- $credit_class;
- $include_shipping;
- $include_tax;
- $tax_class;
$check changed to $_check …
=> PHP8.2 Define Parameters order totals

admin/group_pricing.php
fix #5144
Modify insert button to only output the gID if $gInfo is set.
Modify the new form to only output the gId if $_GET['gID'] is set.
Have done it this way so if you hit cancel in the form you are returned to the group you were editing. Not the first group of the page you are on.
=> Check $gInfo and gID set on insert

includes/classes/ajax/zcAjaxPayment.php, includes/languages/lang.english.php, includes/modules/pages/checkout_confirmation/header_php.php, includes/modules/pages/checkout_payment/jscript_main.php, includes/templates/responsive_classic/css/stylesheet_colors.css, includes/templates/template_default/css/stylesheet_css_buttons.css, includes/templates/template_default/templates/tpl_checkout_payment_default.php
Reworked terms and conditions to make a required field and sticky.
Changed error message to be relevent to new working.
Removed javascript and css changes from PR #4833 
Fixes #2344
I have reworked this to use required. There is still some javascript to issue the custom error message and reset the message on input. 
I have tested it on 1.5.8 and php 8.0.
I have tested with coupons and gift vouchers.
You now have to agree to the terms and conditions prior to clicking the continue button for any action. If the action requires you to return to the checkout_payment page, the status of T&C is remembered. If you leave the page and return later, the T&C status is remembered for the session.
Don't know what the implications are for OPC or Checkout as guest.
=> Refactor T&C

includes/functions/database.php
Ensure passed argument to `zen_db_input` is not empty. 
Fixes #5167
=> Head off a ton of PHP 8.1 deprecations

includes/classes/PluginSupport/Installer.php, includes/classes/PluginSupport/InstallerFactory.php
- $errorContainer;
- $patchInstaller;
- $scriptedInstallerFactory;
Removed as not used
- $errors
- $dbConn
- $errorContainer
- $pluginInstaller
part of #5103
=> PHP8.2 Define Parameters Installer

includes/functions/functions_dates.php
Checking for "win" anywhere in the string returns true for "Darwin" (MacOS). 
This is the only check in the core that doesn't look only at the first three characters.
=> Fix PHP_OS check to look at first 3 chars only

admin/countries.php, admin/coupon_admin.php, admin/coupon_admin_export.php, admin/gv_mail.php, admin/includes/javascript/calendarcode.js, admin/media_manager.php, admin/salemaker.php, admin/stats_sales_report_graphs.php
Replace width with css in \<table> and \<td> elements
Fix html5 validation error
Error The width attribute on the \<> element is obsolete. Use CSS instead.
fix #5220
=> HTML5 Width

admin/includes/modules/update_product.php
```
[18-Sep-2022 14:03:18 UTC] Request URI: /gh_demo_158/admin/index.php?cmd=product&cPath=18&action=insert_product, IP address: ::1
#0 /Users/scott/sites/gh_demo_158/admin/includes/modules/update_product.php(29): zen_debug_error_handler()
#1 /Users/scott/sites/gh_demo_158/admin/product.php(33): require('/Users/scott/si...')
#2 /Users/scott/sites/gh_demo_158/admin/index.php(11): require('/Users/scott/si...')
--> PHP Warning: Undefined variable $products_id in /Users/scott/sites/gh_demo_158/admin/includes/modules/update_product.php on line 29.
```
=> Prevent log on product creation

admin/includes/languages/english/lang.plugin_manager.php, includes/classes/PluginSupport/SqlPatchInstaller.php
- Define parameters
- Correct tableParamsOffset
- Remove break from function parse, so all errors are reported, not just first.
- Remove hard coding of error message in function processLine
- Add error for invalid syntax in function processLine
- Add check for missing FROM in processLineSelect
- Recode Join to find and process all joins in processLineSelect
- Add missing function processLineIndex to process create and drop index
- Add missing function processLineRenameTable to process rename table index
- Make sql error a friendly error, so an error is displayed if there is a failure installing install.sql
fix #5228 
Note more could be done to improve this. Currently, if you double-space anything, it will fail. Not an easy fix. Will add to documentation.
=> Refactor SqlPatchInstaller

admin/sqlpatch.php
Currently message says
Note: %u statements ignored via file upload. See database table "upgrade_exceptions" for additional details.
(i.e. count is omitted)
=> Fix ignored statements message in Install SQL Patches 

includes/classes/order.php
- Left Order_IDOrder_ID as protected.
- All other parameters set to public as may be altered by notifiers.
- Remove $products_ordered_email and $products_ordered_attributes_html as not used in class.
- Remove $subtotal as only set to zero not used in class
=> PHP8.2 Define Parameters order

admin/includes/modules/product/collect_info.php
After a product edit, then preview, then back, the $pInfo->products_id field is not set.  This means that notifiers get called without this value, and fail. 
This should be done for other product types too but I wanted to get this one in first.
=> Add products_id to pInfo object

admin/includes/classes/Paginator.php
I don't think this is used any more. LaravalPaginator used instead.
All set to protected
=> PHP8.2 Define Parameters Paginator

includes/modules/payment/authorizenet.php, includes/modules/payment/authorizenet_aim.php
**Note: I have done these base on the code as I don't have Authorize set up to test.**
- var change to public
- $code
- $title 
- $description 
- $enabled 
- $auth_code 
- $transaction_id 
- $order_status 
- $sort_order
- var changed to protected 
- $version 
- $gateway_mode 
- $reportable_submit_data 
- $authorize
- var changed to private
- $_logDir
- new set to public 
- $form_action_url 
- $submit_extras
- new set to protected
- $cc_card_number
- $cc_card_type 
- $cc_expiry_month 
- $cc_expiry_year
- new set to private
- $_check
- var change to public
- $code
- $title 
- $description 
- $transaction_id 
- $collectsCardDataOnsite
- var changed to protected 
- $authorize 
- $commErrNo 
- $commError 
- $reportable_submit_data
- var changed to private
- $_logDir
- new set to public
- …
=> PHP8.2 Define Parameters php82PaymentMethod Authorize

includes/classes/shopping_cart.php
Set to public
- $contents
- $cartID
- $total
- $weight
NB.
- $weight could be set to protected if order class changed to use show_weight() method
- $total could be set to protected if includes\modules\pages\login\header_php.php and includes\modules\payment\paypal\tpl_ec_button.php changed to use show_total() method
- $content_type
- $download_count
- $free_shipping_item
- $free_shipping_price
- $free_shipping_weight
- $total_before_discounts
=> PHP8.2 Define Parameters shoppingCart

includes/functions/functions_taxes.php
In line with other parts of this set of tax functions. Set the tax_address to the store values if customer is not logged in. This is used by ot_loworderfee.
As raised in #5060 
fix #5296
=> Check Logged in when setting tax locations

admin/includes/modules/product/collect_info.php, zc_install/sql/updates/mysql_upgrade_zencart_158.sql
In 1.3.8, the lengths of the _company fields were increased but there was no conversion done for people who had older databases.  All customers who have been using Zen Cart since 1.3.7 or prior have this issue.
=> Fix company field definitions

includes/modules/payment/paypal/paypal_curl.php
Set to public
-  $_endpoints
-  $_logDir
-  $_logLevel
-  $_mode
-  $_trxtype
-  $lastParamList
-  $_curlOptions
-  $_partner
-  $_pwd
-  $_server
-  $_signature
-  $_user
-  $_vendor
-  $_version
-  $lastHeaders
-  $values
Defined as protected
-  $outputDestination;
**NB.** This class has a function setParam($name, $value) which is not used that will cause undefined warnings if it is use for any parameters not in list above
=> PHP8.2 Define Parameters papyal_curl

zc_install/includes/classes/LanguageManager.php, zc_install/includes/classes/class.systemChecker.php, zc_install/includes/classes/class.zcConfigureFileWriter.php, zc_install/includes/classes/class.zcDatabaseInstaller.php
- $adminDirectoryList = [];
- $errorList = [];
- $extraRunLevels = [];
- $localErrors;
- $selectedAdminDir;
- $serverConfig;
- $systemChecks;
- $inputs = [];
- $replaceVars;
- $ignoreLine;
- $jsonProgressLoggingCount = 0; 
- $basicParseStrings = [];
- $collateSuffix;
- $completeLine;
- $db;
- $dbCharset;
- $dbHost;
- $dbName;
- $dbPassword;
- $dbPrefix;
- $dbType;
- $dbUser;
- $dieOnErrors;
- $errors = [];
- $extendedOptions;
- $fileName;
- $func;
- $jsonProgressLoggingTotal;
- $keepTogetherCount;
- $keepTogetherLines;
- $line;
- $lineSplit = [];
- $newLine;
- $upgradeExceptions; # LanguageManager
- $langPath;
- $$languagesInstalled = [];
part of #5103
=> PHP8.2 Define Parameters install

includes/modules/payment/paypaldp.php
- $cc_type_javascript
- $code
- $collectsCardDataOnsite
- $description
- $enabled
- $enableDirectPayment
- $fmfErrors
- $order_status
- $sort_order
- $title
- $_logLevel
- $_logDir
- $buttonSource
- $cards
- $cc_type_check
- $enableDebugging
- $fmfResponse
- $order_pending_status
- $zone
-  $avs
-  $cvv2
-  $transactiontype
- $auth_code
- $form_action_url
- $ot_merge
- $transaction_id
- $_check
- $amt
- $cc_card_number
- $cc_card_type
- $cc_checkcode
- $cc_expiry_month
- $cc_expiry_year
- $codeTitle
- $codeVersion
- $correlationid
- $emailAlerts
- $feeamt
- $numitems
- $payment_status
- $payment_time
- $payment_type
- $pendingreason
- $reasoncode
- $responsedata
- $taxamt
$this→response['...']; to $this→responsedata['...'];
- $xml_parser
- $elementName
- $elementValue
part of #5103 …
=> PHP8.2 Define Parameters paypaldp

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_158.sql
Kudos to @mc12345678 for identifying that the zc_install version files were missed in the update.  The pre-release checklist has been updated.
=> Fix headers for two patched files

zc_install/includes/systemChecks.yml
This is not a bug in the 158 build, it's just an update for documentation.
=> zc_install was still comparing against 158-dev

admin/configuration.php, admin/coupon_admin.php
Change name to id to remove HTML5 validation warning 'The name attribute is obsolete. Consider putting an id attribute on the nearest container instead.'
=> HTML5 name to id for admin

includes/modules/pages/login/header_php.php, includes/modules/payment/paypal/paypal_currency_check.php, includes/modules/payment/paypal/tpl_ec_button.php, includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php
This would be better written as a function. Having said that, where do I put it so that it can be called by all these routines.
I have checked to see is 'USD' is a valid currency and if not then fetched the conversion value using the functions_exchange_rates. If that fails to find a rate it will create a warning file with $rate not found similar to now. It will still process the transaction as it does now.
I am expecting feedback to please review.
Will fix #4749
=> Fix PayPal require USD

includes/functions/functions_products.php
As identified in [this](https://www.zen-cart.com/showthread.php?229078-Product-Description-Does-not-Show-up-in-All-Products-and-other-Pages) Zen Cart forum posting, the description returned by the subject function is always an empty string.  That's because the fall-back (when no language is supplied on the call) was setting a variable named `$language` instead of `$language_id`, so the $language_id used for the query was always 0.
=> v158: Correcting `zen_get_products_description`

admin/manufacturers.php
Logs: 
```
[25-Oct-2022 15:32:55 UTC] Request URI: /client/admin/index.php?cmd=manufacturers, IP address: ::1
#0 /Users/scott/sites/client/admin/manufacturers.php(331): zen_debug_error_handler()
#1 /Users/scott/sites/client/admin/index.php(11): require('/Users/scott/si...')
--> PHP Warning: Undefined variable $mInfo in /Users/scott/sites/client/admin/manufacturers.php on line 331.
[25-Oct-2022 15:32:55 UTC] Request URI: /client/admin/index.php?cmd=manufacturers, IP address: ::1
#0 /Users/scott/sites/client/admin/manufacturers.php(331): zen_debug_error_handler()
#1 /Users/scott/sites/client/admin/index.php(11): require('/Users/scott/si...')
--> PHP Warning: Attempt to read property "manufacturers_id" on null in /Users/scott/sites/client/admin/manufacturers.php on line 331.
```
=> Fix log when manufs list empty

includes/modules/product_listing.php
There are a large number of variables that are calculated repeatedly to the same value in the loop that started on line 207. Moving the loop stare and the initialised variables to line 273 removes the repeated calculation of these variables.
I have not changed the indentation, so it is easier to see the change.
And move the $listing_description processing to stay in the loop.
=> Improve Efficency  in products_listing

admin/category_product_listing.php
Makes no difference to core functionality, but when the query is expanded by an observer to include other tables, multiple results may be returned.
=> admin: category-product listing, add DISTINCT to search query

zc_install/includes/classes/class.zcDatabaseInstaller.php
Fixes #5343. 
Databases with prefixes have not yet gotten the fixes from the 157 upgrade file that perform these operations:
ALTER TABLE customers_basket DROP final_price;
ALTER TABLE ezpages DROP languages_id;
ALTER TABLE ezpages DROP pages_title;
ALTER TABLE ezpages DROP pages_html_text;
=> Handle ALTER TABLE DROP/ADD commands on db with prefix

includes/modules/shipping/table.php
--> PHP Warning: Undefined variable $show_box_weight in /home/thatsoftwareguy4/public_html/SITE/includes/modules/shipping/table.php on line 186.
=> Correct log for table-based shipping when the mode is not by weight

includes/functions/functions_strings.php
Have added tests for null value in a few places to avoid depreciation errors in php8.2. An alternative is to place (string) before the parameter. e.g.
`strlen((string)$string)`
This also removes the depreciation warning. If you think this is a better approach, let me know and I'll redo.
As requested #5373
=> Add test for null

admin/option_values.php
Dropdown showed all defined names, then on edit dealt with those with no values. 
Seemed a pointless process.
Changed to remove Option Names from the dropdown that have no values/nothing to sort.
Subsequently I will PR the rejigged edit part.
=> Option Values Sorter: filter Option Names that have no values

includes/extra_configures/enable_error_logging.php
Rationale: newer stricter PHP versions are going to produce a lot more language file logs, and fixing them can be tricky in multilanguage carts if you're not sure which language was being used when the log was created.
=> Add language id to log for multilanguage sites

includes/templates/template_default/templates/tpl_zc_install_suggested_default.php
As mentioned in https://www.zen-cart.com/showthread.php?229055-Installer-shows-blank-page
=> The define HTML_PARAMS may not be set if Welcome page is loaded

admin/ezpages.php, admin/includes/languages/english/lang.ezpages.php
Right now you have to click on an ezpage with the red LED to see the error message and understand what's wrong.  This change adds a legend just like the orders page has.
=> Add legend to ezpages

includes/classes/ResourceLoaders/CatalogFilesLanguageLoader.php, includes/extra_datafiles/dist-site_specific_overrides.php
This worked before PHP 8 because additional duplicate defines were simply dropped.  Now they create log files, so we have to provide a mechanism to disallow (at least for legacy language files) if it will be harmful. 
I don't think the same change is required for includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php because there, the first setting wins and there's no PHP warning.
=> Optionally Bypass loading substring-matching language files

includes/modules/payment/authorizenet_aim.php
```
[21-Nov-2022 03:44:18 UTC] Request URI: /index.php?main_page=checkout_confirmation, IP address: 174.... 
#0 /home/client/public_html/site/_livesite/includes/modules/payment/authorizenet_aim.php(263): zen_debug_error_handler()
#1 /home/client/public_html/site/_livesite/includes/classes/payment.php(248): authorizenet_aim->pre_confirmation_check()
#2 /home/client/public_html/site/_livesite/includes/modules/pages/checkout_confirmation/header_php.php(89): payment->pre_confirmation_check()
#3 /home/client/public_html/site/_livesite/index.php(35): require('/home/client...')
--> PHP Warning: Undefined array key "authorizenet_aim_cc_number" in /home/client/public_html/site/_livesite/includes/modules/payment/authorizenet_aim.php on line 263.
```
And three more for …
=> authorizenet_aim: Ensure variables are set prior to use

includes/functions/functions_email.php
The `<br />` needs to be there; was removed in PR #5383
=> Restore `<br />` replacement for `functions_email.php`

admin/includes/functions/admin_access.php
Plugins that extend the menuing system may not be defined if they are being removed or haven't yet been added.
```
[24-Nov-2022 14:30:58 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "BOX_HEADING_M1_EXPORT_ALL" in /Users/scott/sites/client/admin/includes/functions/admin_access.php:838
```
=> Admin: Don't load admin menu names if the associate constant isn't defined

includes/classes/ajax/zcAjaxPayment.php
Fix for issue reported on the forum: 
https://www.zen-cart.com/showthread.php?229150-Credit-Card-checkout-not-processing
=> Fix ajax payments (e.g. paypaldpp.php, authorizenet_aim.php) missing language constants

admin/category_product_listing.php
... when the $_GET['page'] parameter is not present.
Fixes #5408
=> v158: Correcting admin product listing page count

admin/salemaker.php
Setup: use the demo data, go to Admin > Catalog > Salemaker and turn off all sales except the first one ($5.00 off). 
Edit this sale.  You'll see the message 
Warning: 1 sale(s) already include this category
which is created because it's not filtering out the sale you are editing.
=> Misleading warning message in Salemaker

admin/category_product_listing.php
To allow an observer to handle additional actions.
NOTIFY_ADMIN_PROD_LISTING_DEFAULT_ACTION: as it stands it cleared any added action, as pointed out here https://github.com/zencart/zencart/issues/5280
so not of much use.
NOTIFY_ADMIN_PROD_LISTING_DEFAULT_INFOBOX: new to allow an infobox to be associated with the new action.
Done specifically to enable this mod:
https://github.com/zencart/zencart/issues/5267
=> category_product_listing: modify and add notifier for additional actions

admin/orders.php
Current logic to inspect is bad; leads to logs like 
```
--> PHP Warning: Undefined array key "restock" in /site/store/admin/orders.php on line 319.
```
when not checked.
=> Restock flag

includes/functions/functions_general_shared.php
These function signatures were changed in 1.5.8 in #4083; let's add back the old signatures so that plugins won't break.  We can add a deprecated log in the future.
Fixes issue described in https://www.zen-cart.com/showthread.php?229167-Functions-removed-from-1-5-8-discussion
=> Add old signatures for backwards compatibility

admin/featured.php, admin/specials.php
Repro steps: 
- Using demo dataset, go to Admin > Catalog > Specials 
- click "Add Special by Product ID" and enter id 15. 
- Observe that add screen shows a search field.  It should not.
=> Don't show search box during special add by ID

includes/functions/functions_attributes.php
fixes: https://github.com/zencart/zencart/issues/5446
=> function zen_copy_products_attributes: correct bug for skipping pre-existing attribute

zc_install/includes/functions/general.php
a float parameter was being fed to mt_srand. As of PHP 8.1, this conversion had been deprecated but zc_install was not evaluated for having the same issue as found elsewhere in the code.
Fixes #5476
=> mt_srand requires integer parameter

admin/attributes_controller.php
After copying (for example graphics card to mouse), the category is maintained for the graphics card but the product shown is the mouse:
This PR corrects that.
=> Attributes Controller, Copy Attributes to Another Product: match current_category_id to product

admin/salemaker.php, includes/functions/functions_prices.php
Lots of logs are created when working on a sale with no categories selected. 
--> PHP Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /Users/scott/sites/gh_demo_158/includes/functions/functions_prices.php on line 1064.
--> PHP Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /Users/scott/sites/gh_demo_158/includes/functions/functions_prices.php on line 1542.
--> PHP Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /Users/scott/sites/gh_demo_158/admin/salemaker.php on line 353.
--> PHP Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /Users/scott/sites/gh_demo_158/admin/salemaker.php on line 353.
=> Fixes for logs created when sale has no categories

admin/salemaker.php, includes/functions/functions_prices.php
Creating a new sale, creating a sale with no categories selected. 
```
[26-Nov-2022 13:51:00 UTC] Request URI: /gh_demo_158/admin/index.php?cmd=salemaker&page=1&action=new, IP address: ::1, Language id 1
#1 /Users/scott/sites/gh_demo_158/admin/salemaker.php(286): htmlspecialchars()
#2 /Users/scott/sites/gh_demo_158/admin/index.php(11): require('/Users/scott/si...')
--> PHP Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/scott/sites/gh_demo_158/admin/salemaker.php on line 286.
[26-Nov-2022 13:51:00 UTC] Request URI: /gh_demo_158/admin/index.php?cmd=salemaker&page=1&action=new, IP address: ::1, Language id 1
#1 …
```
=> Fix salemaker issues

admin/includes/css/options_values_manager.css, admin/option_name.php, admin/options_values_manager.php
- Move \<form> element to with in \<td> or \<th> and adjust \<table> elements to remove HTML5 errors.
- Add additional formatting to options_values_manager to retain current look and feel.
- Correct `colspan` for revised form position.
- Remove additional `class` attribute from option_name
fix #5337
=> Correct HTML5 form Element Position

includes/classes/db/mysql/query_factory.php
Allows access to the mysqli object of the database class. This permits the following mysqli_xxx functions to be usable:
mysqli_affected_rows
mysqli_autocommit
mysqli_begin_transaction
mysqli_change_user
mysqli_character_set_name
mysqli_close
mysqli_commit
mysqli_dump_debug_info
mysqli_errno
mysqli_error_list
mysqli_error
mysqli_execute_query
mysqli_field_count
mysqli_get_charset
mysqli_get_connection_stats
mysqli_get_host_info
mysqli_get_proto_info
mysqli_get_server_info
mysqli_get_server_version
mysqli_get_warnings
mysqli_info
mysqli_insert_id
mysqli_kill
mysqli_more_results
mysqli_multi_query
mysqli_next_result
mysqli_options
mysqli_ping
mysqli_prepare
mysqli_query
mysqli_real_connect
mysqli_real_escape_string
mysqli_real_query
mysqli_reap_async_query
mysqli_refresh …
=> Restore access to the mysqli object

admin/attributes_controller.php
fixes: https://github.com/zencart/zencart/issues/5450
Note that for the redirect, leaving product_filter empty lets the page set it onload. 
For the moment I've no more bugs/fixes pending for this file.
=> Attribute Controller->Copy Attributes to a Category, fixes

admin/includes/extra_datafiles/dist-site_specific_admin_overrides.php, admin/packingslip.php
Allow the packing Slip and the invoice to have different options for displaying images.
This allows images to be displayed on the invoice but not the packing slip ang vice versa.
=> Split Invoice And Packing Image Decision

includes/modules/shipping/zones.php
The three removed lines are redundant; the setting is done further down in each `case` block.
=> Remove redundant assignments

includes/extra_configures/enable_error_logging.php, includes/functions/functions_traffic.php
These happened because a cron job was using `php <path>` to run a script, so things that would normally be set in browser invocation were not set. 
```
[20-Nov-2022 08:08:07 America/Chicago] PHP Warning:  Undefined array key "REQUEST_URI" in /home/client/public_html/siteurl/_livesite/includes/extra_configures/enable_error_logging.php on line 84
```
```
--> PHP Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/client/public_html/siteurl/_livesite/includes/functions/functions_traffic.php on line 36.
```
=> Fix logs created by cron running PHP job

admin/customers.php
`address_book.entry_company` can be null, and we need to check for it or we'll get this log:
```
#1 /Users/scott/sites/gh_demo_158/admin/customers.php(723): htmlspecialchars()
#2 /Users/scott/sites/gh_demo_158/admin/index.php(11): require('/Users/scott/si...')
--> PHP Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/scott/sites/gh_demo_158/admin/customers.php on line 723.
```
=> Check for null company value

includes/functions/functions_products.php
Prevents activating disabled product that have a historical `products_date_available` that is equal to `'0001-01-01'`. Initial testing of this (nearly two years ago) had indicated that the same result is obtained if the actual date/time is `'0001-01-01 00:00:00'`.
Fixes #5502
=> Retain disabled product status after upgrade

includes/modules/payment/paypaldp.php
Fixes https://www.zen-cart.com/showthread.php?229094-New-install-1-5-8-Paypal-Pro-PHP-Fatal-error-1062
Log produced was
```
[30-Oct-2022 02:38:15 UTC] Request URI: /MyAdmin/index.php?cmd=modules&set=payment&action=install, IP address: **.***.***.***
#1 /home/gtbullet/public_html/includes/classes/db/mysql/query_factory.php(667): trigger_error()
#2 /home/gtbullet/public_html/includes/classes/db/mysql/query_factory.php(634): queryFactory->show_error()
#3 /home/gtbullet/public_html/includes/classes/db/mysql/query_factory.php(275): queryFactory->set_error()
#4 /home/gtbullet/public_html/includes/modules/payment/paypaldp.php(1218): queryFactory->Execute()
#5 /home/gtbullet/public_html/MyAdmin/modules.php(109): paypaldp->install()
#6 …
```
=> Fix paypaldp fatal error on initial installation

admin/includes/css/products_to_categories.css
Go to the multiple categories link manager page on product 2 in the demo data set:
/admin/index.php?cmd=products_to_categories&products_filter=2&current_category_id=4
As a floating button, the update category links button can occlude other parts of the page.
It's better to just put it under the table it operates on.
=> Place update category links button under cat table

includes/modules/meta_tags.php
For example, by META_TAG_TITLE_PAGENAME in a custom page called 'pagename'.
This works for me with my example `tpl_custom_page.php` example described in Issue #5449 .  Warnings are no longer emitted, and my customised meta tags are used.  It is a little clumsy to test each constant line by line, but I thought this would be less intrusive than introducing more formal branches of logic or control variables such as the existing `$meta_tags_over_ride`.  The logic in that module is already pretty twisty.
=> Don't try to redefine META_TAG_* if previously defined, fixes #5449.

includes/modules/pages/ask_a_question/header_php.php
If a site has disabled the `ask_a_question` link (via Catalog :: Product Types :: Layout Settings for a product type), the page still renders.
It's likely that the site's disabled the link because they don't want to deal with additional emails coming from that page, but a knowledgeable person could still navigate to that product-specific page via their browser's address bar.
This update simply redirects back to the product's `_info` page if the feature is disabled for its product-type.  There's also a change to the redirect if a product is not found, since the `_info` pages expect to see a `products_id` parameter, not a `pid` one.
=> "Disable" ask-a-question if disabled for product's type

zc_plugins/DisplayLogs/v3.0.2/Installer/ScriptedInstaller.php, zc_plugins/DisplayLogs/v3.0.2/admin/display_logs.php, zc_plugins/DisplayLogs/v3.0.2/admin/includes/auto_loaders/config.display_logs.php, zc_plugins/DisplayLogs/v3.0.2/admin/includes/css/display_logs.css, zc_plugins/DisplayLogs/v3.0.2/admin/includes/extra_datafiles/display_log_filenames.php, zc_plugins/DisplayLogs/v3.0.2/admin/includes/init_includes/init_display_logs.php, zc_plugins/DisplayLogs/v3.0.2/admin/includes/languages/english/extra_definitions/lang.display_logs_name.php, zc_plugins/DisplayLogs/v3.0.2/admin/includes/languages/english/lang.display_logs.php, zc_plugins/DisplayLogs/v3.0.2/manifest.php
There are times when there are just a few files to keep, but many others to be removed. Selecting a few to then inverse the selection and then choose to delete all selected improves efficiency.
Added a button to inverse the selection(s). Also updated the script within the main file to not be encapsulated around HTML comment blocks.
Updated as version 3.0.2. Tested the upgrade process which successfully completed.
Fixes #5515
=> Add inverse selection feature for DisplayLogs plugin

includes/classes/productPulldown.php, includes/functions/functions_categories.php
fixes the bug as documented in [this forum post.](https://www.zen-cart.com/showthread.php?229219-Am-curious-how-to-alphabetize-this)
the  only question now is if we want to add to the description of this config value that it is also used for product pulldowns:
https://github.com/zencart/zencart/blob/d4398a6ccc9e1c8f30007a0720d9e6024c123109/zc_install/sql/install/mysql_zencart.sql#L2881
=> fixes product sorts on pulldown

admin/category_product_listing.php
use case:
working with a client who has 5726 categories short of 4 gazillion, i have found the ability to input a category_id number into the search field very beneficial.
=> add cat_id to product category search

includes/functions/functions_search.php
use case:
scott wilson wants to limit searches on a particular page to only `products_id`.  adding this notifier will allow him to do that.  it will also allow for adding of additional fields as well.
i see plenty of times when this will come in handy.
=> add notifier to build_keyword function

includes/functions/functions_search.php
use case:
```
$where = zen_build_keyword_where_clause(['products_id',], 'anythingThatIsNotInteger', true);
```
in this situation, `$where` evaluates to `WHERE ( ()  )`.
this PR addresses that situation.
=> fix build search

admin/includes/modules/search_box.php
given that the search box is drawing a form using the http request of get; providing the ability to add other items in the form group is crucial to being able to make use of them.
use case and example:
category products listings now searches the description; by utilizing a checkbox (added using this notifier), one can add a checkbox for search in description.  if the box is unchecked, one can then use the `NOTIFY_BUILD_KEYWORD_SEARCH` notifier to remove the `products_description` and `category_description` from the `$fields` array in the `zen_build_keyword_where_clause` method.
it has always been my intention to allow that flexibility when using the `zen_build_keyword_where_clause` method.  with all/most of the search boxes, now sharing a common bit of code (thank you @Zen4All!); users …
=> add notifier to search box

admin/product_types.php
also check for empty:  if empty passed to zen_info_image it incorrectly says image missing (i.e. not found) instead of not defined.
=> admin,Product Types: fix incorrect parameters to zen_info_image

admin/orders.php
the removed line is already called on line 109:
https://github.com/zencart/zencart/blob/3de0e040e4cb07e8a7150950c4377f7b4c825a69/admin/orders.php#L108-L109
=> refactor, order is already established

includes/modules/pages/products_all/header_php.php
Prevents log: 
[09-Feb-2023 11:44:41 America/Los_Angeles] Request URI: /client/index.php?main_page=products_all, IP address: ::1
#0 /Users/scott/sites/client/includes/modules/westminster_new/product_listing.php(416): zen_debug_error_handler()
#1 /Users/scott/sites/client/includes/templates/westminster_new/templates/tpl_modules_product_listing.php(14): include('/Users/scott/si...')
#2 /Users/scott/sites/client/includes/templates/westminster_new/templates/tpl_products_all_default.php(18): require('/Users/scott/si...')
#3 /Users/scott/sites/client/includes/templates/westminster_new/common/tpl_main_page.php(253): require('/Users/scott/si...')
#4 /Users/scott/sites/client/index.php(94): require('/Users/scott/si...')
--> PHP Warning: Undefined array key "manufacturers_id" in …
=> Add manufacturers_id to query

includes/classes/observers/auto.downloads_via_url.php
Seeing logs similar to
```
[15-Feb-2023 14:53:06 America/New_York] Request URI: /zc158/index.php?main_page=download&order=40&id=3, IP address: 127.0.0.1, Language id 1
#1  zcObserverDownloadsViaUrl->updateNotifyCheckDownloadHandler() called at [C:\xampp\htdocs\zc158\includes\classes\traits\NotifierManager.php:87]
#2  base->notify() called at [C:\xampp\htdocs\zc158\includes\modules\pages\download\header_php.php:89]
#3  require(C:\xampp\htdocs\zc158\includes\modules\pages\download\header_php.php) called at [C:\xampp\htdocs\zc158\index.php:35]
--> PHP Notice: Trying to access array offset on value of type bool in C:\xampp\htdocs\zc158\includes\classes\observers\auto.downloads_via_url.php on line 93.
[15-Feb-2023 14:53:06 America/New_York] Request URI: …
```
=> Correct PHP Warnings during download

admin/includes/functions/html_output.php
The issue here was that, for 'get' type forms, the hidden field added by `zen_draw_form` neglected to remove the `.php` from the submitted `$action`, which identified the associated 'cmd=' variable's value.
Fixes #5607
=> `zen_draw_form`, correct hidden 'cmd' variable contents

admin/includes/functions/html_output.php
cols can only be a positive integer.
Aside, this dumps the % that may be passed, but subsequently I'll review the admin instances to remove those parameters.
Should be followed up by the same on the storefront to equate the functions for a future merge.
=> admin function textarea: check for cols parameter

includes/modules/pages/search_result/header_php.php
i am not sure why this conditional is in here.  line 133 even states it (although it should be above line 132).
this code seems to mimic the code at the top of the file.  but it does not allow for the overriding by the notifier.
i'm not sure why we need these redundant checks, i was tempted to remove them; rather than that i just allowed the override done with the notifier on line 34, to override these checks as well.  code at the top:
https://github.com/zencart/zencart/blob/29399901200641ca2c94415877e9eea1ac8a2bef/includes/modules/pages/search_result/header_php.php#L33-L41
=> allow override on search inputs

includes/languages/english/lang.popup_coupon_help.php
Otherwise the coupon-help displays `Coupon Name :` instead of `Coupon Name:`; ditto for "Coupon Description"
=> Remove unwanted spaces from popup_coupon_help language file

includes/modules/order_total/ot_coupon.php
Fixes #5619.
The root-cause of the issue was the `validateCouponMaximumUses` method's checking of the _number of records_ returned as opposed to the _count of uses_ returned.  The issue surfaces whenever a coupon's maximum uses is configured as a value other than empty (i.e. unlimited).
The number of records returned is *always* 1 (since the query's a `COUNT`), so the coupon check would always fail if the coupon's max-usage was configured as `1` and would _always pass_ for a max-usage > 1.
=> Correct `ot_coupon` determination of max-uses-per-coupon

includes/modules/pages/brands/header_php.php, includes/modules/sideboxes/brands.php
Fixes #5629 
On the "Brands" sidebox and listing-page, don't display manufacturers that have no active products if the site's configuration (`PRODUCTS_MANUFACTURERS_STATUS`) so indicates.
=> Brands page and sidebox restrictions

includes/languages/english/modules/payment/lang.square.php
Modified to stop the already defined messages appearing if you have installed Square webPay. It defines a number of variables as constants that are already defined in this language file.
As I assume that square will be removed completely from Zen Cart at some point. So I thought it better to modify this file rather than have code in a new webPay module.
=> Stop duplication of defines if Square Webpay is installed.

includes/modules/downloads.php
More modern MySQL versions choke if a field is referenced twice in the select list.
=> Remove second use of opd.download_maxdays

includes/modules/payment/authorizenet_aim.php
```
[14-Mar-2023 18:39:39 America/Chicago] Request URI: /admin/index.php?cmd=orders&page=1&oID=17072&action=doVoid, IP address: 1.1.1.1
#1 /home/client/public_html/includes/modules/payment/authorizenet_aim.php(760): trim()
#2 /home/client/public_html/includes/modules/payment/authorizenet_aim.php(944): authorizenet_aim->_debugActions()
#3 /home/client/public_html/admin/orders.php(385): authorizenet_aim->_doVoid()
#4 /home/client/public_html/admin/index.php(11): require('/home/client/...')
--> PHP Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/client/public_html/includes/modules/payment/authorizenet_aim.php on line 760.
```
=> Fix log from authorize_aim in admin

includes/classes/ajax/zcAjaxPayment.php
Fixes issue documented in https://www.zen-cart.com/showthread.php?229178-Authorize-net-AIM-problems-1-5-8
Last one is fatal and kills checkout. 
```
[14-Mar-2023 16:12:47 America/Chicago] Request URI: /ajax.php?act=ajaxPayment&method=prepareConfirmation, IP address: 1.1.1.1
#0 /home/client/public_html/includes/classes/ajax/zcAjaxPayment.php(129): zen_debug_error_handler()
#1 /home/client/public_html/ajax.php(85): zcAjaxPayment->prepareConfirmation()
--> PHP Warning: Undefined array key "cc_id" in /home/client/public_html/includes/classes/ajax/zcAjaxPayment.php on line 129.
[14-Mar-2023 16:12:47 America/Chicago] Request URI: /ajax.php?act=ajaxPayment&method=prepareConfirmation, IP address: 1.1.1.1
#0 /home/client/public_html/includes/classes/ajax/zcAjaxPayment.php(166): …
```
=> Fix authorize aim issue in 1.5.8/PHP 8.1

includes/classes/shopping_cart.php
Prevents log when POST data missing entirely. 
```
--> PHP Warning: Undefined array key "products_id" in /home/client/public_html/includes/classes/shopping_cart.php on line 2112.
```
=> check empty vs using count

includes/extra_configures/robots_pages_to_skip.php
- ask a question should be in the list (since contact us is)
- order_status needs a comma after it.
=> Fixes for ROBOTS_PAGES_TO_SKIP

includes/modules/pages/ask_a_question/header_php.php
Adds a notifier to allow being asked a product question as an observer permits.
Defaults to redirect as set in the header file, allowing override. At least one situation where this functionality is desired is in turning off display of ask a question for product type, but including link in email to ask a product question.
Without this change, then code edit required instead of addition of an auto loading observer.
=> Add a notifier for `SHOW_` . `$info_page` . `_ASK_A_QUESTION`

includes/modules/payment/authorizenet_aim.php
Seen a few times in a 1.5.7 cart; issue still exists in 1.5.8.   Happens if Enable Database Storage = true. 
```
[14-Mar-2023 17:11:10 America/Los_Angeles] Request URI: /shop/index.php?main_page=checkout_process, IP address: ********
#1  trigger_error() called at [/var/www/html/client/shop/includes/classes/db/mysql/query_factory.php:170]
#2  queryFactory->show_error() called at [/var/www/html/client/shop/includes/classes/db/mysql/query_factory.php:142]
#3  queryFactory->set_error() called at [/var/www/html/client/shop/includes/classes/db/mysql/query_factory.php:269]
#4  queryFactory->Execute() called at [/var/www/html/client/shop/includes/modules/payment/authorizenet_aim.php:752]
#5  authorizenet_aim->_debugActions() called at [/var/www/html/client/shop/includes/modules/payment/authorizene …
```
=> Protect against empty data during save for authorizenet_aim

admin/invoice.php, admin/packingslip.php
```
[29-Mar-2023 12:19:18 UTC] Request URI: /gh_demo_158/admin/index.php?cmd=invoice&oID=2, IP address: ::1, Language id 1
#0 /Users/scott/sites/gh_demo_158/admin/invoice.php(118): zen_debug_error_handler()
#1 /Users/scott/sites/gh_demo_158/admin/index.php(11): require('/Users/scott/si...')
--> PHP Warning: Trying to access array offset on value of type bool in /Users/scott/sites/gh_demo_158/admin/invoice.php on line 118.
```
other similar logs in packingslip.
=> Packingslip & invoice log when storepickup is used

includes/modules/payment/authorizenet_aim.php
This is a PHP8.1+ issue that happens because of increased checking. 
Handle errors like
```
--> PHP Warning: Undefined array key 3 in /home/client/public_html/site_home/_livesite/includes/modules/payment/authorizenet_aim.php on line 440.
```
```
--> PHP Warning: Undefined array key 4 in /home/client/public_html/site_home/_livesite/includes/modules/payment/authorizenet_aim.php on line 441.
```
etc
=> Handle undefined array keys in authorizenet_aim

includes/functions/functions_email.php, not_for_release/testFramework/Support/zcUnitTestCase.php
Building on PR #5671,
- Use `zen_define_default` where applicable.
- Use `===` and `!==` where applicable
- Remove error suppression; it's removed in PHP 8.2.
- Use `strpos` instead of `preg_match` for better performance
- Replace double-quotes with single-quotes where no in-string replacements are made.
- Replace `size` with `count`
- Use lowercase for false, true and null
=> functions.email, restructuring

includes/modules/order_total/ot_coupon.php
there are numerous reasons why one would NOT want to show the coupon box on checkout.
inserting this notifier allows store owners to do so.
=> add notifier to ot-coupon

includes/modules/pages/login/header_php.php
i have tracked down the following error:
```
PHP Fatal error: unknown address_book_id (225223) for customer_id (5684) in /var/www/myBloodyDomain/includes/classes/OnePageCheckout.php on line 1063.
```
to some session vars not getting unset when an admin places multiple orders in a row.
there might be other session vars that need to get unset; and destroying the session entirely is not really an option.
=> unset session vars when doing an hmac admin login

includes/functions/functions_products.php
```
[27-Apr-2023 12:46:50 America/New_York] PHP Fatal error:  Uncaught Error: Undefined constant "MODULE_ORDER_TOTAL_GV_STATUS" in /homepages/19/userid/htdocs/estore/includes/functions/functions_products.php:777
Stack trace:
#0 /homepages/19/userid/htdocs/estore/includes/functions/functions_general.php(201): zen_get_products_allow_add_to_cart()
#1 /homepages/19/userid/htdocs/estore/includes/modules/bootstrap/product_listing.php(349): zen_get_buy_now_button()
#2 /homepages/19/userid/htdocs/estore/includes/templates/bootstrap/templates/tpl_modules_product_listing.php(12): require('/homepages/19/d...')
#3 /homepages/19/userid/htdocs/estore/includes/templates/bootstrap/templates/tpl_index_product_list.php(105): require('/homepages/19/d...')
#4 …
```
=> Fix fatal error if GVs not used

includes/modules/payment/paypaldp.php
[01-May-2023 02:41:58 UTC] Request URI: /index.php?main_page=checkout_process, IP address: 68.110.228.9, Language id 1
#1 /home/client/public_html/site/shop/includes/modules/payment/paypaldp.php(2215): strcasecmp()
#2 /home/client/public_html/site/shop/includes/modules/payment/paypaldp.php(1032): paypaldp->determine3DSecureProtection()
#3 /home/client/public_html/site/shop/includes/classes/payment.php(297): paypaldp->after_process()
#4 /home/client/public_html/site/shop/includes/modules/pages/checkout_process/header_php.php(16): payment->after_process()
#5 /home/client/public_html/site/shop/index.php(35): require('/home/teamrick2...')
--> PHP Deprecated: strcasecmp(): Passing null to parameter #1 ($string1) of type string is deprecated in …
=> Fix deprecation

includes/functions/salemaker.php
Partial fix for #5415 
Required for some newer versions of MySQL which will enable a sale whose start date and end dates are set and is in range, but then disable the same sale.
=> put dates in quotes

admin/coupon_admin.php, admin/includes/init_includes/init_category_path.php, admin/includes/init_includes/init_sanitize.php, admin/includes/modules/dashboard_widgets/OrderStatusDashboardWidget.php
This seems to obsolete code, that has been there since the beginning of Zen Cart.
=> Remove 'selected_box' references

zc_install/sql/install/mysql_zencart.sql
Fix #5745
Missing Drop table instruction in SQL file '../zc_intall/sql/install/mysql_zencart.sql':
DROP TABLE IF EXISTS customer_groups; on line 673 and
DROP TABLE IF EXISTS customers_to_groups; on line 689.
=> Missing Drop table

admin/includes/classes/WhosOnline.php
Decoding session data with `base64_decode` appears to no longer return all data that was initially encoded. As a result, the search of the decoded session data could likely fail finding one or more product in the list. This takes advantage of the added class method `inspectSessionCart` that temporarily becomes the session to collect the data and return the session information back.
Passing an empty value for the `session_id` because the code already requires the `session_data` to be non-`empty` and the method is written to operate so long as either is non-`empty`.
Added a variable (`$inactive`) to support a single calculation instead of the same evaluation multiple times.
Simplified logic as either there is a return because there are no rows in the cart or the return is because of the …
=> Restore cart identification in whos online

admin/whos_online.php
As described in Issue #5633 the on page links used the old admin/whos_online.php syntax.  In my case this broke javascript widgets in our common header on that page because the generated <html> element wasn't set up correctly.
=> Fix on-page links to use cmd= URL syntax - Fixed #5633

includes/modules/payment/paypaldp.php
As mentioned in the forum:
https://www.zen-cart.com/showthread.php?229318-Advise-needed-to-change-the-format-of-INVNUM-to-fight-duplicated-orders&p=1393626
This PR is a walk around solution to reduce/fight the duplicated orders/submissions. It will reduce the resolution for INVNUM value from 1s to 60s. Paypal will auto denied the duplicated transactions with the same INVNUM number.
=> Paypaldp.php INVNUM format change to fight duplicated orders

includes/modules/product_listing.php, includes/modules/responsive_classic/product_listing.php
It's an accessibility violation to not specify the TH in a table.
"Data tables include header and data cells arranged in a grid.
Each data cell <td> should be assigned to at least one column or row header cell <th>. When this is done, a screen reader can announce each data cell in context."
=> Fix accessibility for all product listing pages with tables

includes/languages/english/lang.account_history_info.php, includes/templates/template_default/templates/tpl_account_history_info_default.php
fixes: https://github.com/zencart/zencart/issues/5553
=> replace hard-coded warning missing shipping info

extras/curltester.php
SellOnline has moved, and the REST URL being used was the test one.
=> update Canada Post URLs for curltester

ajax.php
Call the `includes/application_bottom.php` file applicable to the side of the store used to open the ajax load.
Do away with nested if/elseif logic where return is used for true evaluation.
Eliminate single line if statements and add parentheses to support expanded logic grouping.
Eliminate the parentheses around the filename for calls of `require`.
Fixes #5800.
=> v158 ajax closure and refactor

admin/categories.php
If file not found, show full (incorrect) image file path and redirect to edit category for correction.
Fixes: https://github.com/zencart/zencart/issues/3628
=> admin, add category image manually, handle file not found

admin/category_product_listing.php, includes/functions/functions_search.php
Regarding #5715, the search parsing code tries to split around whitespace, and then recognise grouped logical terms, e.g. `foo (wibble and bar)` but fails when there is missing whitespace e.g. `foo(wibble and bar)`.
I've taken a very simple approach of using regex replace to separate words from parentheses before the parsing begins, so the search string is turned from `foo(wibble and bar)` into `foo (wibble and bar)` and the splitting and query building proceeds as normal.
Also return early (after notifier is called in case of required modification) when search string is empty to fix #5666.
=> Fix admin prod/cat search with missing whitespace or empty string - Fixes #5715, #5666

includes/classes/order.php
Before:
```
<div class="order-detail-area"><table class="product-details" border="0" width="100%" cellspacing="0" cellpadding="2"><tr>
<td class="product-details" align="right" valign="top" width="30">1&nbsp;x</td>
<td class="product-details" valign="top">One Time Charge (ONETIME) 
<nobr><small><em><br />
Color Red</em></small></nobr></td>
<td class="product-details-num" valign="top" align="right">&euro;34.79</td></tr>
<tr><td class="product-details">	*onetime charges = </td>
<td>&euro;3.87</td></tr>
<tr>
<td class="product-details" align="right" valign="top" width="30">1&nbsp;x</td>
<td class="product-details" valign="top">Microsoft Internet Keyboard PS/2 (MSINTKB) </td>
<td class="product-details-num" valign="top" align="right">&euro;54.10</td></tr>
</table></div>
```
After
```
<div …
```
=> order email: correct format onetime charge

includes/modules/pages/login/header_php.php
see #5698 
pretty sure this one is the missing element.
=> unset customer_default_address when doing an hmac admin login

admin/category_product_listing.php, includes/classes/sniffer.php
Guards against using 'back' button to revisit page with previous values that are no longer valid, e.g. after move_product to another category.
=> Check that provided cID, pID exist, redirect if not - fixes #5743

admin/includes/modules/search_box.php
The container, outside of search_box.php for example customers.php, is col-md-4 which means it will be 4/12 width in medium breakpoint, and full page width in smaller breakpoints.  The columns here were also set to col-md-4, so they were 4/12 each in a space that was already quite narrow. In small breakpoints they jumped to 100% width which is also not optimal.
The approach here is:
- extra small and small, 50% width so the checkboxes lay out side by side.
- other breakpoints - 100% width so the checkboxes stack on top of each other in the narrow screen space they have been allotted by their parent.
Screenshots:
Small screen - before, the checkboxes are on top of each other:
Small screen - after, the checkboxes are side by side, saving some vertical screen space:
Wide screen - before, the …
=> Fix layout of search_box elements.

admin/includes/functions/html_output.php
Fixes #5518
Instead of returning the images folder as the URL within an image tag, it returns blank.
=> Return blank if image is not specified

zc_install/ajaxLoadUpdatesSql.php, zc_install/includes/languages/en_us/main.php
The zc_install process will now process all files in /zc_install/plugins/updates alphabetical order, after the core version upgrade SQL is run.
Fixes #2848 
Closes #5830
=> zc_install upgrade now processes plugin update SQLs

includes/extra_configures/enable_error_logging.php
If a log is requested to be generated before `$_SESSION` has been set or specifically if `$_SESSION['languages_id']` is not set, then the absence of that data causes an issue/error such as the below:
[Date Time Timezone] PHP Warning:  Undefined global variable $_SESSION in /catalog-path/includes/extra_configures/enable_error_logging.php on line 84
[Date Time Timezone] PHP Warning:  Trying to access array offset on value of type null in /catalog-path/includes/extra_configures/enable_error_logging.php on line 84
This commit allows that to not exist and adds more information onto the reporting to indicate that it didn't exist at the time of log generation.
=> Allow intended error logging before `$_SESSION` set

includes/modules/pages/login/header_php.php
see #5854 and #5698.
i have verified another [scenario](https://github.com/lat9/one_page_checkout/issues/378#issuecomment-1635070031) where the `cart_address_id` causes this problem:
```
PHP Fatal error: unknown address_book_id (448) for customer_id (1478) in /myWebRoot/includes/classes/OnePageCheckout.php on line 1064.
```
=> unset cart_address_id when doing an hmac admin login

includes/modules/checkout_new_address.php, includes/modules/create_account.php
Fixes #5707
When submitting create account form, message 'Please select a state from the States pull down menu.' appears although state field (input text) has been properly filled. Only when 'Configuration>Customers Details>State field - Display as pulldown when possible?' is set to false and has zones defined.
=> States pull down menu error when creating account

admin/includes/functions/html_output.php
Fixes #5520
Updated admin function zen_draw_separator() in html_output.php to fix some HTML error in invoice and packing slip.
=> admin, invoice: html error

admin/includes/classes/AdminRequestSanitizer.php
v158b Refactor Admin Sanitizer and add String Only sanitization
In association with fixing #5849, applied the same type of correction
to other unique filters that only managed array type sanitization.
With incorporation of a change, took an opportunity to refactor the
code using some of the principles that have been applied by others in the
community.
early escape
remove empty lines
use elseif instead of else if
=> V158 sanitizer regex url

includes/modules/order_total/ot_group_pricing.php
The `include_tax` property is set to the value of the configuration setting, a 'true' or 'false' string, so its value is always interpreted as _truthy_.
Add a strict comparison to determine whether/not the taxes are to be included.  As the module currently sits, tax is _always_ included in the deduction when the "Calculate Tax" setting is "None".
=> ot_group_discount: Correct tax calculations when "Calculate Tax" when "None"

admin/developers_tool_kit.php, admin/includes/css/developers_tool_kit.css
Part of #5807
Changes
1) Added variables `$output` & `$outCount` to display output from zen_diaplay_files to allow output after `<body>` tag separated count from matches.
1) Moved `pixel_black.gif` to  `zen_diaplay_files` function and added to `$output`
1) Moved matches to display below menu bar.
1) Replaced `<table> border, cellspacing, cellpadding` tags with css 
1) Added missing` id` tags to fields and made unique, changing label where necessary 
1) Added `htmlspecialchars `to configuration value so you can see value if it contains html
=> Make DevelopersToolKit HTML5 compliant

admin/includes/modules/product/preview_info.php
...otherwise embedded image references in the description do not display/point to the admin images folder.
Use-case for embedded images: screenshots of software etc., in a relevant language to the description.
=> admin, product preview, display of description, embedded images: substitute relative image paths for shopfront

admin/includes/classes/class.admin.zcObserverLogEventListener.php, ajax.php, includes/classes/observers/auto.downloads_via_aws.php, includes/functions/functions_dates.php, includes/functions/functions_strings.php, not_for_release/testFramework/Unit/testsNotifiers/AdminLoggingTest.php
Fixes #5387
Notes:
- Issuing an `E_USER_DEPRECATED` log for any usage of `utf8_encode_recurse`, just in case some plugin is using that function.
- The removal of the `testEnsureDataIsUtf8` method from the test framework's AdminLoggingTest.php will most likely result in a unit-test failure.  I don't know where that test is invoked!
=> Remove usage of the deprecated `utf8_encode`

admin/category_product_listing.php
Mentioned here: https://www.zen-cart.com/showthread.php?229613-category_product_listing-issue&p=1396101#post1396101
When in the subcategory immediately below the TOP, the sorting options redirect to the TOP category due to this:
```
if (isset($_GET['cID'])) {
$_GET['cID'] = (int)$_GET['cID'];
}
```
$_GET['cID'] is set, but an empty string, but there is no category 0 so it redirects to the top, maintaining the previous sort order.
So a change to 
```
if (!empty($_GET['cID'])) {
$_GET['cID'] = (int)$_GET['cID'];
```
seems a fix: both category and product sort as selected.
=> admin: correct category sort below top category

admin/customers.php
Reformatting of `admin/customers.php` for readability and maintainability
- Use short-array syntax
- Maintain PHP conditional indentation separate from HTML tag indentation
- Makes it less error-prone when adding new conditionals and/or tags
- Keep short PHP statements on a single line for readability
=> Reformatting admin/customers.php for readability/maintainability

admin/customers.php
Refactoring `admin/customers.php`:
- Use `===` where warranted.  Note that the customers_id element returned by the `Customer` class is an integer!
- Use the null coalesce (`??`) operator where warranted.
- Use short-array syntax on those missed in the reformatting.
- Remove list_addresses_done action; simply redirect to the listing from the list_addresses action.
- Cast posted values that _should be_ integers to integers.
- Use "LIMIT 1" on updates for performance on sites with a large number of customers.
- Preserve search keywords on list_addresses, status, edit, delete and pwreset actions.
- Cast fax_number and suburb to string for htmlspecialchars (they can be null when editing and were triggering PHP Deprecated logs).
- Use ctype_digit instead of is_numeric for status action …
=> Refactoring admin/customers.php

includes/extra_datafiles/dist-site_specific_overrides.php, includes/functions/functions_categories.php
Currently, the category count counts the number of products in each sub category individually. This means that if you have a product in more than one sub category of the parent category, it is counted once for each category that it is in. If, like me, you have products that you put into many sub categories to allow searching by a feature of the product, the category count can get highly inflated. 
This mod counts the distinct products_id(s) in a category and all its sub categories.
=> Add ability to count distinct products for category counts

zc_install/sql/install/mysql_utf8.sql, zc_install/sql/updates/mysql_upgrade_zencart_158.sql
United Nations as of 2 June 2022 recognizes the name change and it should therefore be adopted here.
Keeping in line with the way that countries are now handled in Zen Cart, a new install will have Türkiye at country 215, while an upgrade will update the country name if it's countries_iso_code_3 is present. This is in line with the explanation/direction provided in issue #3664.
If the country has been deleted, then reinsertion would need to be by some other path.
=> Observe the name change for Türkiye

includes/init_includes/init_add_crumbs.php
- Using null-coalesce where appropriate
- Use `count` instead of `sizeof`
- Using multiple variables on `isset` where appropriate
- Use foreach instead of while/$db->MoveNext on multiple-record query.
- Gather a single query where either a single or no record is expected to be returned
- Use `===` instead of `==`
- Simplify the 'get-terms-to-filter' section
- Ensure that `$cPath` is set for the product-name portion
- Use $result->EOF instead of $result->RecordCount()
Next up, adding a notification so that **_Ceon URI Mappings_** can discontinue its use of an unwanted override of this file!
=> Refactoring init_add_crumbs.php

includes/init_includes/init_add_crumbs.php
As previously mentioned, this can be used by the "Ceon URI Mapping" plugin so that it doesn't have to overwrite the file to include its custom parameters.
=> Add link-parameter notification for init_add_crumbs.php

includes/modules/order_total/ot_coupon.php
fixes #5925 and moves notifier to correct place.  notifier was added AFTER v158a release.  intention was to allow a observer to prevent coupon box from appearing during checkout.
i am not opposed to changing the notifier name if so desired.
=> early return for ot_coupon and add notifier

includes/modules/pages/checkout_process/header_php.php
- Start all lines in column 1
- `unset` all session variables in one command
- Remove parentheses from `require` statements
- Use exactly-equal-to for the action comparison
=> checkout_process: Minor reformatting and refactoring

admin/media_manager.php, admin/music_genre.php, admin/record_artists.php, admin/record_company.php
Fixes #5923
Admin > Extras > Media Types was fixed in #5924, this PR fixes the remaining sub-menus
`media_manager.php` may need a closer check as it's possible that I may have lost my way, slightly.
=> Fix for missing buttons in empty product-type Extras sub-pages

includes/functions/functions_dates.php, includes/modules/payment/paypal/paypal_functions.php, includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php
While currenly only used directly by PayPal modules, these functions could be used elsewhere. And making them part of functions_dates makes them accessible to all paypal modules equally.
Fixes #5931
Updates #5929
Ref #5927
=> Move paypal date-functions to core

includes/functions/functions_general_shared.php
if we are now making this method available on the storefront, we should not assume that there will always be a `$_SESSION['admin_id']` set.
i have opted for an empty return but i'm not opposed to something else.
i think the check should definitely be done in this method as opposed to the call to the method.
=> early return if adminID not set

includes/modules/shipping_estimator.php
Strict reporting, php8.3.0beta2, vanilla shop, set shipping estimator to display on cart page, add product, go to cart:
[25-Aug-2023 09:09:03 UTC] Request URI: /zencart/index.php?main_page=shopping_cart, IP address: 127.0.0.1, Language id 1
#0 D:\Github\zencart\includes\modules\shipping_estimator.php(139): zen_debug_error_handler()
#1 D:\Github\zencart\includes\templates\responsive_classic\templates\tpl_shopping_cart_default.php(204): require('D:\\Github\\zenca...')
#2 D:\Github\zencart\includes\templates\responsive_classic\common\tpl_main_page.php(178): require('D:\\Github\\zenca...')
#3 D:\Github\zencart\index.php(94): require('D:\\Github\\zenca...')
--> PHP Warning: Undefined array key "zone_country_id" in D:\Github\zencart\includes\modules\shipping_estimator.php on line 139.
when …
=> module shipping_estimator: cast result (as $_POST['zone_country_id'] may not be set)

includes/modules/pages/product_reviews/header_php.php
Avoid this log:
--> PHP Warning: Undefined array key "products_id" in /home/client/public_html/includes/modules/pages/product_reviews/header_php.php on line 25.
Occurs when someone modifies the URL 
index.php?main_page=product_reviews&products_id=85
to remove products_id parameter (presumably in hopes of seeing all reviews).
=> Handle loading product_reviews page where products_id not specified

admin/includes/application_bootstrap.php, includes/application_top.php, includes/extra_configures/enable_error_logging.php, includes/extra_configures/set_time_zone.php, includes/functions/functions_error_handling.php
This leaves the extra_configures/enable_error_logging.php file as merely a simple configuration file.
Also fixes #5944
=> Extract error-handling code into core functions file

admin/featured.php, admin/includes/init_includes/init_special_funcs.php, admin/salemaker.php, admin/specials.php
Semi-replicating the once-per-day/session handing on the storefront for the specials/featured/salemaker auto-enable/expire checks.  Otherwise, the expirations (which normally happen only once/day) are checked on *every* admin page-load.
Discovered this issue on a zc158 site whose admin was taking 1-2 seconds to load each-and-every admin page.  The site had minimal (i.e. < 20) of these automatic updates to perform, but adding this change, the other pages in the admin averaged less than 250ms to load.
=> Auto-expire specials/featured/sales once per admin session/day

admin/customers.php
admin -> customer was done prior to the 3rd input parm for the method which dictates how the search clause should start.
=> small refactor of admin customer search

includes/templates/responsive_classic/templates/tpl_shopping_cart_default.php, includes/templates/template_default/templates/tpl_shopping_cart_default.php
so on an Update, the cart table is the main part of the viewport, instead of the top of the page, and having to scroll down.
(A similar thing is done for the shipping estimator)
I found that linking to the actual table id left the top of the table obscured by the header in bootstrap.
=> Cart Update: link to top of cart table

includes/templates/template_default/templates/tpl_about_us_default.php
The majority of the define pages already have a back button, especially those of a similar ilk  - privacy, conditions,pages 2,3,4, shipping.
=> Adding a back button to the About Us page

admin/orders.php
On a site that has 120K+ orders, adding the 'limit 1' when a specific order is being viewed is a significant performance improvement.
For the orders' button row, change the middle section to have a large-viewport column-width of 4 (so the column-counts are 4/4/4).  Otherwise, site-specific button additions will overflow.
=> Admin/orders: Limit when single order, correct layout

includes/functions/functions_products.php
Since that value can be `null`, returning a string prevents PHP deprecated issues like
```
--> PHP Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in C:\xampp\htdocs\zc200\admin\includes\modules\collect_info.php on line 419.
```
=> Return string-type from zen_get_products_url

admin/customers.php
There's no such posted variable as `current`, use the `current_status` variable which _is_ present.  Otherwise, a PHP warning is issued.
=> admin/customers.php, 'current_status', not 'current'

includes/modules/sideboxes/manufacturers.php
Fixes the bug
Manufactures Sidebox dosn't check for products/active status even when set in admin.
Setting ADMIN-->CONFIGURATION-->MAXIUMVALUES-->Manufacturers List - Verify Product Exist to true (1)
should filter the manufactures side box to exlude manufactures with no active products
it dosnt work
issues #5961
=> Manufactures Sidebox not correctly checking for products/active status

admin/featured.php, admin/specials.php, includes/functions/functions_categories.php
persuant to [this conversation on the forum](https://www.zen-cart.com/showthread.php?229738-Admin-Specials-and-Featured-Sort-order&p=1397342#post1397342), the sorting of product pulldowns was not working.  this code addresses that problem.
in addition, it removes the var `$prev_next_order` from a couple of scripts.  it is not used as the pulldown function grabs the config value and sorts the pulldown accordingly within the zen_draw_pulldown_products function (line 367: `zen_products_sort_order(false)`).
i also would like to note that DESC sorting is currently not supported in the pulldowns (there is no DESC sort in the config value for `PRODUCT_INFO_PREVIOUS_NEXT_SORT`).  supporting a DESC sort would require a rethinking/refactoring of the `setSort` function within the pulldown class.
=> Correct sorting on admin's Specials and Featured tools

includes/functions/functions_products.php
- Also includes some minor reformatting
- array() to []
- Use ->EOF instead of ->RecordCount() where appropriate
- Use `===` where appropriate
- Refacturing
- Use zen_get_product_details when possible (reduces unique database queries)
- Functions that take a language input, default that input to null so that the above function deals with a language not specified
- `zen_remove_product`, customers_basket entry for attributed products not removed, since that table's product_id field is tinytext and can be set to a uprid.
=> functions_products, refactoring and product removal correction

includes/classes/shopping_cart.php
Reformatting
- Use null coalescing (??) operator where indicated
- Use short array syntax
- No one-line multiple assignments
Refactoring
- Since the `contents` property is keyed on a 'uprid', change the `$products_id` key to be `$uprid` on foreach traversals of that array.  That makes it more obvious when viewing the code as to what the `contents` array is keyed on.
- Limit MySQL updates to a single row for unique operations.
- Use `===` where warranted.
- Use `zen_define_default` where warranted.
- Use `strpos` instead of `preg_match` when checking for gift-certificates in the cart.
- Remove redundant code.
- Use `zen_get_product_details` where warranted to get maximum cached queries.  Results in a roughly 50% reduction in time taken to add/remove/update a …
=> Shopping cart performance enhancements

zc_install/includes/classes/class.systemChecker.php, zc_install/includes/languages/en_us/main.php, zc_install/includes/systemChecks.yml
Add a check into the install to ensure that the database is at least the minimum version of Mysql of MariaDB. The check only fails if it is able to perform a version check and the version is less than that specified in systemChecks.yml.
fixes  #6002
=> Add mysql version check

admin/includes/modules/dashboard_widgets/TrafficDashboardWidget.php
... for PHP 8.2 and later.  Seeing logs like
```
[15-Oct-2023 08:38:27 America/New_York] PHP Fatal error:  Uncaught TypeError: mktime(): Argument #4 ($month) must be of type ?int, string given in C:\xampp\htdocs\zc200\admin200\includes\modules\dashboard_widgets\TrafficDashboardWidget.php:23
Stack trace:
#0 C:\xampp\htdocs\zc200\admin200\includes\modules\dashboard_widgets\TrafficDashboardWidget.php(23): mktime(0, 0, 0, 'my', 'tt', '`php')
#1 C:\xampp\htdocs\zc200\admin200\index_dashboard.php(65): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\zc200\admin200\home.php(25): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc200\admin200\index.php(11): require('C:\\xampp\\htdocs...')
#4 {main}
thrown in C:\xampp\htdocs\zc200\admin200\includes\modules\dashboard_widgets\TrafficDashboardWidg …
```
=> TrafficDashboardWidget: mktime parameters must be ints

includes/modules/checkout_process.php
If a payment module, e.g. `authorizenet_aim`, sets a different status during its `before_process` method, that status is not initially recorded into the order &mdash; which can cause customer confusion.
For instance, if an a.net/aim transaction is being held for review, a specific a.net/aim order-status can be set.  Currently, the order's initial status (viewable by the customer) indicates that the order is awaiting processing, but a subsequent (hidden) status-update by the a.net/aim payment module sets the order's status to its "Under Review" setting.
This update corrects that issue.
=> Capture payment module final status in order

admin/includes/init_includes/init_templates.php
I've got a client, for instance, that wants the invoice/packingslip `title` attribute to reflect the associated order so that a "Save to PDF" print will automatically have a suggested unique filename.
=> Enable override of admin pages' HTML 'title' attribute

includes/classes/payment.php
Seeing logs similar to the following due to variable-name 'misspelling':
```
[25-Oct-2023 11:38:20 America/Chicago] Request URI: /index.php?main_page=checkout_process, IP address: x.x.x.x, Language id 1
#0 /home/mystore/public_html/includes/classes/payment.php(134): zen_debug_error_handler()
#1 /home/mystore/public_html/includes/modules/checkout_process.php(84): payment->checkCreditCovered()
#2 /home/mystore/public_html/includes/modules/pages/checkout_process/header_php.php(13): require('/home/mystore/...')
#3 /home/mystore/public_html/index.php(35): require('/home/mystore/...')
--> PHP Deprecated: Creation of dynamic property payment::$selected_method is deprecated in /home/mystore/public_html/includes/classes/payment.php on line 134.
```
=> Payment class, correct PHP deprecation by using the correct variable

admin/includes/init_includes/init_category_path.php, admin/includes/languages/lang.english.php
If an invalid `cPath` is provided to the category_product_listing (e.g. cPath=999999), the listing page displays an empty category to which other categories or products can be added.
If, in this case, a category is added that newly-added category's `parent_id` reflects that invalid (non-existent) category; if a product is added, the product's `master_categories_id` reflects that invalid category.
This PR corrects that issue.
=> Protect admin against invalid cPath

admin/featured.php, admin/specials.php
As identified in [this](https://www.zen-cart.com/showthread.php?229760-Featured-Special-Products-Active-From-date-cant-be-today&p=1397550#post1397550) Zen Cart forum bug-report.
=> Featured/Specials, save dates when 'today'

includes/functions/functions_general.php
Avoids unnecessary crawling of results pages by not following links that only change the sort order of results, not the actual content.
=> Make sort headings rel=nofollow, for SEO, fixes #6040

admin/customers.php, includes/functions/functions_customers.php
Fixes #6046
- The admin customer tool wasn't including the 'timestamp' in the generated hmac.
- For whatever reason, browsers update a posted 'timestamp' hidden field when there's also an `id=` parameter (go figure).
- The check in `zen_validate_hmac_login` needs to check its generated HMAC against that passed from the admin and ensure that the 'timestamp' value was posted.
- Includes a couple of refactorings, using multi-variable `isset` checks instead of looping.
=> Correcting auto-login on "Place Order"

includes/modules/pages/popup_image/header_php.php, includes/modules/pages/popup_image_additional/header_php.php
If the `popup_image` or `popup_image_additional` pages' $_GET variables are 'externally' manipulated, either removing or providing an invalid value to one, various PHP Warnings and Deprecated errors are logged.
This PR corrects those situations.
=> popup images', correcting PHP warnings and deprecations

includes/templates/template_default/templates/tpl_account_history_info_default.php
Fixes #6050 
Note new Notifiers:
NOTIFY_ACCOUNT_HISTORY_INFO_EXTRA_COLUMN_HEADING
Passed:  $order, $extra_headings
NOTIFY_ACCOUNT_HISTORY_INFO_EXTRA_COLUMN_DATA
Passed:  [ 'order' => $order, 'orders_product' => $op ], $extra_data
=> New notifiers for adding custom columns to product table - fixes 6050

admin/includes/application_bootstrap.php, includes/application_top.php, zc_install/includes/application_top.php
Required since PHP 8.3.0 RC5 and expected in all 8.3+ versions. Also required in PHP 8.1.25 and 8.2.12 (but hopefully not in 8.1.26+ and 8.2.13+)
If not configured at the server/system level, then it defaults to `'C'` (un'C'onfigured), which is invalid when IntlDateFormatter is called, which now throws an exception in such cases.
Fixes #6010
=> Set a default locale in case the server's default is invalid or unconfigured

admin/includes/init_includes/init_sessions.php, includes/functions/functions_traffic.php, includes/init_includes/init_sessions.php
Since the gathered IP might come back as a comma-separated list, the `zen_get_ip_address` function was finding an invalid IP when a proxy is in use.
This PR corrects that issue.
=> Correct IP-address gathering when using proxies

includes/templates/template_default/templates/tpl_account_history_info_default.php
Fixed #6058 ... accidentally put the declaration of `$extra_headings` inside an `if` block intended to test for `checkout_success` page.
I had not actually noticed the implication of this conditional when adding the `$extra_headings` code.  It would be worth noting in any documentation for the new notifiers `NOTIFY_ACCOUNT_HISTORY_INFO_EXTRA_COLUMN_HEADING` and `NOTIFY_ACCOUNT_HISTORY_INFO_EXTRA_COLUMN_DATA` that the page is called in the two contexts: 1/ new order summary in checkout_success and 2/ customer visiting order history page.  Quite possibly, any extra data added on the order history page is irrelevant on the order summary page, so any observer using these would do well to react to `$current_page`, for example by not adding any extra headings in that case.
=> Move initialisation of $extra_headings out of conditional.

includes/functions/functions_taxes.php
=> tax address entries reversed

includes/auto_loaders/config.core.php, includes/classes/Exceptions/SearchException.php, includes/classes/class.search.php, includes/init_includes/init_sanitize.php, includes/languages/lang.english.php, includes/modules/pages/search/header_php.php, includes/modules/pages/search_result/header_php.php, includes/templates/template_default/templates/tpl_search_result_default.php
Took the bulk of search_result/header.php which built the SQL and put it in a helper class Zencart\Search\Search.
Inputs to the search refactored into SearchOptions so they can be called programatically without needing a GET request to trigger it. Parsing of $_GET retained in the search/header.php and search_result/header.php.
New message_stack: 'search_result' for displaying a message at the top of
the search results page (for example 'try also doing xyz').
New notifier: NOTIFY_SEARCH_NO_RESULTS_MESSAGE, given $results, $message
For reacting to the search results e.g. add to message stack (to appear
on the 'search' form).
=> Refactor search SQL operations into helper class, catalog side.

admin/customers.php, admin/orders.php, includes/classes/Customer.php
Fixes #6054 - feel free to critique.
The more elements are turned into FontAwesome icons, the more the graphic icons such as `icon_edit.gif` and `icon_info.gif` on the orders page stand out.  I'd be happy to take a stab at converting them if there is general support from the core team to do so.
=> Improve links between orders and customers screens.

includes/classes/Customer.php
If a customer places an order in a currency other than a store's default, the orders-list from the `account` and `account_history` pages displays the associated currency symbol correctly
... but the amount isn't converted from the default currency to the order's currency, which it is after the correction in this PR:
=> Customer::getOrderHistory doesn't convert from default currency

admin/includes/functions/general.php
The function's currently passing invalid parameters to `zen_draw_password_field`,
```php
function zen_draw_password_field($name, $value = '', $required = false, $parameters = '',$autocomplete = false) {
```
... resulting in a wonky display with that password-input being required.
... with that password-input being required.
=> Correct `zen_cfg_password_input`

includes/templates/template_default/jscript/zen_addr_pulldowns.php
If a customer changes their country from the US to Canada (or any other country that has defined 'zones'), the first entry in the state dropdown is missing (e.g. for Canada, Alberta is missing).  That's because invalid HTML is rendered by the `/includes/templates/template_default/jscript/zen_addr_pulldowns.php`'s jQuery.
The invalid HTML is created because (for whatever reason), the `countryZones.split('<option')` returns an extra (empty) string as the first element of the array.  As identified in [this](https://stackoverflow.com/questions/12836062/string-split-returns-an-array-with-more-elements-than-expected-empty-elements) SO posting, adding `.filter(function(el) {return el.length != 0})` corrects the issue.
=> Missing first state/province from state dropdowns when country changed

admin/includes/functions/html_output.php
Seeing logs like
```
[09-Dec-2023 14:40:04 America/New_York] Request URI: /zc200w/admin200/index.php?cmd=orders&page=1&oID=19&action=edit, IP address: 127.0.0.1, Language id not set
#0 C:\xampp\htdocs\zc200w\admin200\includes\init_includes\init_general_funcs.php(39): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc200w\admin200\includes\init_includes\init_general_funcs.php(39): require()
#2 C:\xampp\htdocs\zc200w\includes\autoload_func.php(40): require_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc200w\admin200\includes\application_top.php(42): require('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\zc200w\admin200\orders.php(8): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\zc200w\admin200\index.php(11): require('C:\\xampp\\htdocs...')
--> PHP Deprecated: Using ${var} in strings is …
```
=> Correct PHP deprecations in `zen_icon`

admin/customers.php, includes/classes/Customer.php
This follows on from discussion on #6061 
After our discussion in your review comments, I agreed we could get rid of my new function `Customer::getRecentOrderRecords()`, and I re-wrote the original function `Customer::getOrderHistory()` so it can be used instead.  However I have hit a problem in its use of `splitPageResults` because that function does some basic string searching in the SQL for things like 'from' and splits the query so it can count rows, which fails when a subselect is used (anything with a 'from' or 'group by' clause, it seems).  The result is malformed SQL, probably an issue you've been long aware of with `splitPageResults`.
(Note, the only place I see `account_history` being linked to, and thus using this splitPageResults path, is from a "(show all orders)" link on the …
=> Use Customer::getOrderHistory for recent order info.

includes/functions/functions_email.php
Otherwise, a call like the following
```
zen_mail('Send to Name', 'joe@example.com', 'Test Message Subject', $email_message_text, STORE_NAME, STORE_OWNER_EMAIL_ADDRESS);
```
... when sent to an email that's configured for HTML results in the HTML email's body containing `$EMAIL_MESSAGE_HTML`.
=> zen_mail: Copy text message to HTML, if not present

crowdin.yml
Used for syncing English core language files from GitHub to Crowdin.
Note! Files in html_includes are added as txt files in Crowdin to make them translatable, since they isn't real language files with defines. On export they will be automatically renamed back to php.
_*I recommend moving flag icons out of language packs, and rather incorporate them in the core by default like other systems do._
=> Adding Crowdin config file

admin/includes/languages/english/lang.orders.php, admin/orders.php
Fixes #6080.
Display the value if-and-only-if the value is not 1, implying that the order was placed in the store's default currency.
=> Display currency-value on admin orders' details

includes/modules/payment/paypaldp.php, includes/modules/payment/paypalwpp.php
Fixes #6129.
- Note, contains some reformatting so that I could 'see' what was going on.
- Moves admin title/description changes after the payment module has been determined to be enabled.
=> Correct paypaldp/paypalwpp 'retirement' update

admin/coupon_admin.php, admin/gv_mail.php, admin/includes/auto_loaders/config.core.php, includes/auto_loaders/config.core.php, includes/classes/Coupon.php, includes/classes/CouponValidation.php, includes/classes/sniffer.php, includes/functions/functions_gvcoupons.php, includes/modules/create_account.php, includes/modules/order_total/ot_coupon.php, includes/modules/pages/gv_send/header_php.php, not_for_release/testFramework/Support/StubCouponValidation.php, not_for_release/testFramework/Unit/testsDiscountCoupon/DiscountCouponsTest.php
Pursuant to the comment by @proseLA in #5974 this extracts numerous blocks of background logic out of the top of `coupon_admin`, into `static` methods on 2 new classes: `Coupon` and `CouponValidation`.
I anticipate that perhaps the `CouponValidation` class could be the new home for many of the validation methods currently in `ot_coupon`. Indeed, it is `ot_coupon` that uses the methods that are now in that class.
In `functions_gvcoupons.php` are only a couple functions related to GV's, and a few backward-compatibility stubs for the functions that were moved into the new classes.
=> Extract common db activities out of Coupon_Admin

includes/functions/functions_taxes.php
Fixes #6131
If the selected country/zone results in an empty set, return '0' for either the country or zone_id.
=> Correct zen_get_tax_locations

admin/configuration.php
A small typo in the in the form class for the configuration page
=> Fix typo in configuration.php

includes/modules/payment/paypaldp.php
As discussed in [this](https://www.zen-cart.com/showthread.php?229894-PHP-Fatal-error-Undefined-constant-MODULE_PAYMENT_PAYPALDP_MERCHANT_COUNTRY&p=1398612#post1398612) Zen Cart forum posting.
- Create a local variable that is `null` if the constant's not (yet) defined; otherwise, contains the configured value.
- Correct the comparison to use 'USA' (was 'US', which is not one of the configured values).
=> `paypaldp`: Correct error on upgrade (new config constant) and comparison

includes/init_includes/init_sessions.php
Fixes #5940 
Note, 3 commits (the first two contain reformatting and refactoring; the third is the actual correction).
=> Correct PHP warning when SSL_SESSION_ID doesn't exist

includes/modules/order_total/ot_coupon.php
=> Correct tax-removal in `ot_coupon` for excluded products

includes/templates/responsive_classic/templates/tpl_ajax_checkout_confirmation_default.php, includes/templates/template_default/templates/tpl_ajax_checkout_confirmation_default.php
As reported in [this](https://www.zen-cart.com/showthread.php?229896-PHP-Notice-ob_flush()-Failed-to-flush-buffer-zcAjaxPayment-php&p=1398629#post1398629) Zen Cart forum bug report.
=> Correct tpl_ajax_checkout_confirmation_default.php Warnings

includes/modules/order_total/ot_loworderfee.php
It (currently) checks to see if `MODULE_ORDER_TOTAL_LOWORDERFEE_LOW_ORDER_FEE` is 'true' before adding its fee to the order.  That value's a fee, not a true/false switch!
This order-total is either installed or not (no true/false status setting), so just remove that invalid check (after some reformatting and refactoring since I was "in there" anyway) to correct the issue.
=> `ot_loworder_fee` hasn't worked for a couple of releases

includes/functions/functions_addresses.php
=> `zen_get_country_name`, return empty string if invalid country-id supplied

includes/modules/pages/checkout_shipping/header_php.php
When a shipping module returns no quotes, sometimes the ['methods'] sub-array is not present.
=> Fix "undefined array element 'methods'"

includes/classes/shopping_cart.php
These are used by some shipping modules which offer dimensional quoting capability. Including these here means those shipping modules don't need to overwrite the shopping_cart class file.
=> Add product "dimension" field stubs to shopping_cart.

includes/templates/template_default/templates/tpl_checkout_shipping_default.php
Optional flow can be changed in template or in site-specific-overrides.
Fixes #5988
=> Show contact-us button instead of continue, when no shipping available

admin/includes/extra_datafiles/dist-site_specific_admin_overrides.php, admin/includes/languages/english/lang.orders.php, admin/orders.php
While the `orders::order_weight` handling was added in zc156, it's not displayed anywhere in the admin and could be a useful troubleshooting element.  Like when a product's weight hasn't been set in its definition.
=> Admin order's details, display overall weight

admin/orders.php
Current customer search is by email address.  This fails if the customer has changed their email address, but will work if the customer id associated with the order is non-zero and is used in a search.
=> Orders page - make customer lookup check by cID before email

admin/includes/init_includes/init_special_funcs.php, includes/classes/shopping_cart.php, includes/functions/functions_general_shared.php, includes/functions/functions_products.php
=> Updates for strict-types

admin/category_product_listing.php
Fixes #5897 - Admin: Categories & Products Display Order intrinsically linked
This retains the single config setting, but splits into 2 session variables, so that the last-used cat sort is used on all cats, and last-used prod sort on all prods, in a given session.
=> Use 2 session vars for admin cat/prod sort

includes/modules/order_total/ot_coupon.php
Fixes `Uncaught TypeError: CouponValidation::is_product_valid(): Argument #1 ($product_id) must be of type int, string given`
=> Strict product id on coupon validation

admin/includes/admin_html_head.php, admin/includes/header.php, admin/includes/languages/lang.english.php, admin/includes/menu.css, admin/includes/menu.js, admin/includes/stylesheet.css
Fixes #6214.
For each admin-session, the first time a page is loaded that doesn't use admin_html_head.php to perform the base CSS load, a message is displayed
... and a PHP Deprecated log is created.
```
[10-Feb-2024 14:32:17 UTC] Request URI: /zc200w/admin200/index.php?cmd=header_test, IP address: 127.0.0.1, Language id 1
#1 C:\xampp\htdocs\zc200w\admin200\includes\header.php(71): trigger_error()
#2 C:\xampp\htdocs\zc200w\admin200\header_test.php(58): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\zc200w\admin200\index.php(11): require('C:\\xampp\\htdocs...')
--> PHP Deprecated: This page requires updates for the next Zen Cart version. Please let your site developer or plugin author know! in …
```
=> Compatibility for pages without admin_html_head

includes/classes/productPulldown.php
in the event one wants to extend the product pulldown class, some vars need a `protected` visibility.
=> allow for extending product pulldown

admin/customers.php
(Before this, "ID" and the numeric id were together.)
=> Add a space between "ID" and customer id so cust id can be copied more easily

admin/orders.php
For example, a single product-weight of 25 with a quantity of 10 (an overall weight of 250) was having the trailing (and significant) '0'  trimmed.
=> Correct admin orders' products' total weight display

admin/coupon_admin.php, admin/includes/javascript/coupon_admin.js, admin/includes/languages/english/lang.coupon_admin.php, includes/classes/CouponValidation.php
See conversation on Issue #6193 (which is closed, not sure how these PR's are supposed to work in this case).
Two improvements to the coupon-admin UI for the recently added `coupons.referrer` field:
- Search now includes `referrers` field.  Not perfect as it's just a substring search on the raw field, so if the field has `a.com,b.com` in it, you can search for "com,b" and it'll match, but this seems good enough for now.
- Edit UI now has a series of input boxes with +/- icons, and the update/preview handler pulls these values, validates that no other coupon has a specific referrer (displays error message and prevents save).
The actual values are still stored as a CSV list, so the catalog side does not need changing.
I wrote the +/- handling from scratch, adding new file …
=> Add coupons.referrer edit UI and validation.

admin/includes/header.php, admin/includes/languages/lang.english.php, includes/classes/zcDate.php
`%Z` shows `ZZZZ` equivalent, which shows the timezone offset
Fixes #6229 
Refs: 
https://www.php.net/manual/en/function.strftime.php
https://www.php.net/manual/en/datetime.formats.php
https://unicode-org.github.io/icu/userguide/format_parse/datetime/#date-field-symbol-table
=> IntlDateFormatter - show timezone offset

includes/modules/category_row.php, includes/modules/product_listing.php, includes/modules/responsive_classic/product_listing.php, includes/templates/responsive_classic/css/responsive_default.css, includes/templates/responsive_classic/css/stylesheet.css
Pre-settable variables include:
- `$grid_category_classes_matrix`
- `$grid_category_cards_classes`
- `$grid_category_card_params`
- `$grid_category_wrap_classes`
- `$category_row_layout_style`
and
- `$grid_product_classes_matrix`
- `$grid_product_cards_classes`
- `$grid_product_card_params`
- `$grid_product_wrap_classes`
- `$product_listing_layout_style`
Inspired from https://github.com/lat9/ZCA-Bootstrap-Template/issues/305
Also adds lazy-loading of product images, and closes #6246
=> Extend the 'fluid' layout mode from products to categories too

includes/modules/new_products.php
Restores functionality accidentally removed in v1.5.8
Fixes #6223
=> Use new-product-specific image-size

admin/includes/functions/html_output.php
Needed for future updates to CKEditor
eg: `textarea` with `name=pages_html_text[1]` now also gets `id="pages_html_text-1-"`
(The `[` and `]` characters are replaced with `-` to prevent clashing with other CSS syntax.)
=> Auto-add unique-ish id attribute to admin textarea fields

includes/classes/Customer.php
In the restructuring of customer information to the `Customer` class, plugin additions to the `address_book` table have been lost.
Gather *all* fields from the `address_book` table in the `getFormattedAddressBookList` method to resurrect those fields.  See this VAT4EU issue for some of the fall-out: https://github.com/lat9/vat4eu/issues/23.
That way, all those fields will be present in each `addresses` array's `address` element for that (and other) plugins to us.
=> Gather *all* fields from the address-book table

includes/classes/zcDate.php
Ref: https://github.com/zencart/zencart/pull/6239#issuecomment-1962285093
Ref: #6229 
@piloujp 
If someone wants to override the calendar used with `$zcDate->output()`, they can pass the desired calendar-related locale.
=> zcDate->output() - allow calendar override

includes/modules/payment/paypalwpp.php
[27-Feb-2024 11:34:19 America/Indiana/Indianapolis] Request URI: /admin/index.php?cmd=orders&cID=10039&page=1&oID=35853&action=doRefund, IP address: ****, Language id 1
#0 /home/client/public_html/includes/modules/payment/paypalwpp.php(3170): zen_debug_error_handler()
#1 /home/client/public_html/includes/modules/payment/paypalwpp.php(961): paypalwpp->_errorHandler()
#2 /home/client/public_html/admin/orders.php(345): paypalwpp->_doRefund()
#3 /home/client/public_html/admin/index.php(11): require('/home/client/p...')
--> PHP Warning: Undefined array key "RESULT" in /home/client/public_html/includes/modules/payment/paypalwpp.php on line 3170.
=> Fix PayPal logs (paypalwpp)

includes/functions/functions_addresses.php
... in `zen_address_format`, to pass on to any observer.  In a similar vein as PR #6266.
=> Keep additional address parameters

admin/includes/classes/split_page_results.php
Before: 
`WHERE SUBSTRING(foo) = 'Z'ORDER BY bar`
After:
`WHERE SUBSTRING(foo) = 'Z' ORDER BY bar`
=> Fix missing space in generated query

includes/classes/MeasurementUnits.php, includes/psr4Autoload.php
Moving it from `\Zencart\Zencart\MeasurementUnits` to just `MeasurementUnits` seems to make it more intuitive.
This has not been officially released yet, so this is probably the best time to do it.
=> Remove double namespace from MeasurementUnits class

includes/classes/MeasurementUnits.php
Intent was to be able to drop the last `null` from this:
`MeasurementUnits::convertWeight(10, 'lbs', 'oz', null)`
like:
`MeasurementUnits::convertWeight(10, 'lbs', 'oz')`
=> Allow optional parameter to be null

ipn_main_handler.php
It was retired in PHP 7.0
And is proposed to throw deprecations starting in PHP 8.4
=> Remove E_STRICT

includes/classes/SessionHandler.php, includes/functions/sessions.php, includes/psr4Autoload.php
Currently in PHP 8.4.0-dev the call to `session_set_save_handler()` only accepts 2 parameters, not the multiple procedural-style parameters that have historically been used. Throws deprecation notifications.
`PHP Deprecated: Calling session_set_save_handler() with more than 2 arguments is deprecated`
This PR reworks the code to implement the [SessionHandlerInterface](https://www.php.net/manual/en/class.sessionhandlerinterface.php) which was introduced in PHP 5.4.0
=> Move session handling to OOP format for PHP 8.4 compatibility

includes/classes/Settings.php, includes/classes/TemplateSettings.php, includes/functions/functions_general_shared.php, includes/init_includes/init_templates.php, includes/psr4Autoload.php, includes/templates/responsive_classic/template_settings.php, includes/templates/template_default/template_settings.php
(This essentially makes the `tpl()` function unnecessary, so it is deleted here.)
The global var `$tplSetting` added here (can choose a different name before merge) is a (class) object that (initially) loads all its properties from the global `$tpl_settings[]` array found in `template_settings.php`. 
(Other "soft settings" global vars in that file are unrelated, and can happily be there without conflict.)
Example:
(These are hypothetical, illustrative only; I'm not suggesting that these actual settings would commonly be used.) `template_settings.php` contains:
```
$tpl_settings['SET_COLUMN_LEFT_LAYOUT'] = '2';
$tpl_settings['SET_COLUMN_RIGHT_LAYOUT'] = [
'value' => '2',
'type' => 'int',
];
$tpl_settings['BS4_AJAX_SEARCH_ENABLE'] = [
'value' => 'true',
'type' => 'string',
]; …
```
=> Add $tplSetting object for accessing Template Settings

includes/templates/template_default/sideboxes/tpl_manufacturer_info.php
As reported in 
https://www.zen-cart.com/showthread.php?229987-Manufactuerer-s-Sidebox-Images-Are-Huge
=> Manufacturer images are not scaled in sidebox.

admin/sqlpatch.php, zc_install/includes/classes/class.zcDatabaseInstaller.php
Some `v200` SQL "upgrade" queries rely on INNER JOIN syntax, instead of just LEFT JOIN which is already supported.
=> Add INNER JOIN parser support

includes/functions/functions_dates.php
Fixes #6293
Removing code in zen_date_short function for an old bug that does not exist anymore and actually provoking a new bug in certain condition. See issue #6293.
=> Removed old bug correction for year 1969

admin/includes/modules/copy_product.php
Per @torvista comment at https://github.com/zencart/zencart/pull/6262#issuecomment-1985295632
References #6257
Updates #6262
UI now does this: (depends on whether linked categories, discounts, attributes, specials exist)
=> copy-to: also hide category/discount/edit options

zc_install/sql/updates/mysql_upgrade_zencart_200.sql
SQL keywords like `FROM` and `INNER JOIN` and `LEFT JOIN` should start on a new line in order for zc_install and sqlpatch to recognize them and correctly insert the tablename prefixes.
Related to #5912
=> Reformat upgrade SQL for tablename prefix support

includes/modules/order_total/ot_gv.php
If an order has only Gift Certificates/Vouchers, don't offer Gift Vouchers as a possible payment for the order.
Processing currently displays on the `checkout_payment` page, but quietly disallows the GV payment if the order contains only GV products.
=> Don't offer GV payment if order only has GV's

includes/languages/lang.english.php, includes/templates/template_default/templates/tpl_modules_shipping_estimator.php
If all shipping methods have zones set and the selected address (or entered data) is outside the zones, the estimator simply shows a blank below available methods.
This change adds the warning message from the checkout page.
=> message in estimator when no shipping available

includes/functions/functions_email.php
Seeing more and more of these: 
```
[13-Mar-2024 21:40:32 UTC] PHP Notice:  Email Error: SMTP Error: data not accepted.SMTP server error: DATA END command failed Detail: Mail contain spam content BCCCF140117^M
SMTP code: 550 Additional SMTP info: 5.7.1
in /home/account/domains/client.com/public_html/includes/functions/functions_email.php on line 426
```
There's no value to dropping a log; this is just idiots pasting in junk to the contact_us page. 
I suspect the message above was written by a non-native speaker of English and will eventually be corrected to say "Mail contain**s** spam content" so I'm just grepping for the last two words.
=> Email failures: Don't log if message rejected for spam

admin/customers.php
this problem looks to be in v158 as well.  
in v157, we had the following:
https://github.com/zencart/zencart/blob/40c161c8f5c0d58ac9e39d2dec479780d522e47e/admin/customers.php#L1236-L1237
currently we have:
https://github.com/zencart/zencart/blob/0430d9573f21170459aadbb4585f6122a3f98d90/admin/customers.php#L1627-L1630
now, above this, there is this notifier:
https://github.com/zencart/zencart/blob/0430d9573f21170459aadbb4585f6122a3f98d90/admin/customers.php#L1580-L1585
now the var `$new_fields` is only used in the `$customers_query_raw` which is now ONLY used to get the customers_id and then use the Customer object.  so those new fields are now lost.  and certainly not available for use in the `NOTIFY_ADMIN_CUSTOMERS_LISTING_ELEMENT` notifier.
now, i suppose one could very easily get …
=> change parameter of notifier in admin customers

includes/templates/responsive_classic/template_info.php
Force the "Layout Boxes Controller" to show the settings for "Single Column" mode for the `responsive_classic` template.
=> Display "Single Column Settings" for responsive classic

includes/auto_loaders/config.core.php
That way `$current_page_base` is set and the active template is established.
Sorry for the churn.
=> Move split-page-results init to CP 115

includes/modules/order_total/ot_loworderfee.php
Seeing logs like
```
[24-Mar-2024 15:48:37 America/New_York] Request URI: /zc200w/index.php?main_page=checkout_payment, IP address: 127.0.0.1, Language id 1
#0 C:\xampp\htdocs\zc200w\includes\modules\order_total\ot_loworderfee.php(48): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc200w\includes\classes\order_total.php(56): ot_loworderfee->__construct()
#2 C:\xampp\htdocs\zc200w\includes\modules\pages\checkout_payment\header_php.php(99): order_total->__construct()
#3 C:\xampp\htdocs\zc200w\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Deprecated: Creation of dynamic property ot_loworderfee::$enabled is deprecated in C:\xampp\htdocs\zc200w\includes\modules\order_total\ot_loworderfee.php on line 48.
```
=> Correct ot_loworderfee PHP Deprecated log

admin/includes/functions/admin_access.php, admin/includes/init_includes/init_general_funcs.php, admin/includes/init_includes/init_pci_settings.php, admin/login.php
Move PCI-related configuration settings to a single file.
This lets a storeowner configure the values in a central place when standards change.
=> Centralize PCI configuration settings

includes/functions/functions_prices.php
As reported in [this](https://www.zen-cart.com/showthread.php?230034-Products-Price-Manager-discounts-aren-t-working-on-multiple-attributes-even-though-th) Zen Cart forum-thread.
Issue introduced via PR #3784; restoring storefront-specific processing for the `zen_get_products_discount_price_qty` function.
=> Correct PPM discounts with multiple attributes

includes/functions/functions_products.php
SHOW_NEW_PRODUCTS_LIMIT is an int, not a string #6399
Fixes #6398.
Removal of old `zen_get_products_new_timelimit` to be done as a follow on PR.
=> Correct new products query in 2.0.0

includes/modules/payment/paypaldp.php
--> PHP Warning: Undefined variable $order_amount in /home/client/public_html/store/includes/modules/payment/paypaldp.php on line 375.
=> PayPal check - wrong variable used

includes/functions/functions_email.php
Forgotten password doesn't pass in an array because no HTML email is sent.  So this log happens:
```
--> PHP Warning: Undefined array key "EMAIL_TO_ADDRESS" in /home/client/public_html/store/includes/functions/functions_email.php on line 626.
```
This PR fixes.
=> Fix for forgotten password email

includes/modules/payment/paypalwpp.php
Null field will cause a debug log.
=> Required for downloadable products

admin/category_product_listing.php
the use of `zen_get_all_get_parameters` allows for more flexibility; especially for those of us that do additional filtering of products and use additional `$_GET` parameters.
existing functionality would not change.
=> allow further get parameters when resetting product status

includes/init_includes/init_templates.php
- Includes some reformatting
- Line 71/74; no need to `null-coalesce`, $tpl_settings has been set.
- Previous lines 105-109 unneeded; $tplSetting previously set at line 71/74.
- New line 110; no need to `null-coalesce`, $tpl_settings has been set.
=> Remove redundant code from `init_templates.php`

not_for_release/testFramework/FeatureStore/GVCoupons/GiftVoucherRedeemTest.php, not_for_release/testFramework/FeatureStore/LowOrderFees/LowOrderFeeTest.php, not_for_release/testFramework/Support/Traits/GeneralConcerns.php
When the test fails, it's easier to debug by looking through a shorter segment than through the entire page's HTML.
=> Test optimization: shorten strings for assertion

includes/modules/sideboxes/information.php
Many plugins, like [Printable Price List]( https://www.zen-cart.com/downloads.php?do=file&id=173) have only one template override to add an additional link to the information sidebox.
This PR adds a notification to enable that addition.
=> No means to insert additional "Information" sidebox links

includes/classes/Customer.php
Fixes #6444 
Simple bug mixing up internal data array names with database field names.  Tested OK by stepping through in VS Code.
=> Fix attempted INSERT IGNORE on every customer login.

includes/classes/Customer.php, includes/functions/functions_customers.php, includes/functions/functions_strings.php, includes/functions/php_polyfills.php
Prevent depreciation warning in PHP8.4
=> Add explicit null allowed for function type definitions.

admin/orders.php
If 2 IPs are listed, both are turned into clickable whois links.
Fixes #6333
=> Split order IP whois links

ajax.php
Currently, only files present in `/includes/classes/ajax` are loaded to handle AJAX requests.
=> Enable zc_plugins to provide AJAX content

includes/classes/ResourceLoaders/PageLoader.php
In trying to get the Bootstrap template to accept a _specific_ file from a zc_plugin's directory, I found that using
```php
$user_styles = $template->get_template_dir('site_specific_styles.php', DIR_WS_TEMPLATE, $current_page_base, 'css') . '/site_specific_styles.php';
if (file_exists($user_styles)) {
require $user_styles; 
}
```
didn't find the plugin's file `/catalog/templates/default/css/site_specific_styles.php` even though the file was present.  It turns out that `FileSystem->fileExistsInDirectory` uses a _greedy_ regex pattern when making its determination:
```php
$filePattern = '/' . str_replace("/", "\/", $filePattern) . '$/';
```
... thus matching `/includes/templates/bootstrap/css/dist-site_specific_styles.php`.
Changing the Bootstrap code to use
```php
$user_styles = …
```
=> PageLoader should use FileSystem for file exists

includes/classes/PluginSupport/ScriptedInstallHelpers.php, includes/classes/PluginSupport/ScriptedInstaller.php, includes/classes/PluginSupport/ScriptedInstallerFactory.php, zc_plugins/DisplayLogs/v3.0.2/Installer/ScriptedInstaller.php
Built as a trait for now. Could incorporate directly into the parent class.
Any `ScriptedInstaller.php` class that an encapsulated plugin runs has access to these helpers:
```
public function getConfigurationKeyDetails(string $key_name, bool $only_check_existence = false): array|bool
public function addConfigurationKey(string $key_name, array $properties): int
public function updateConfigurationKey(string $key_name, array $properties): int
public function deleteConfigurationKeys(array $key_names): int
public function addConfigurationGroup(string $group_title, array $properties): int
public function updateConfigurationGroup(int $group_id, array $properties): int
public function deleteConfigurationGroup(int $group_id): int
public function getConfigurationGroupDetails(int|string $group, bool …
```
=> Provide additional script helpers for encapsulated plugin mgmt

includes/functions/functions_email.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_210.sql
Fixes #6449 
*PLEASE REVIEW* the database upgrade script, I've had a half hearted stab at it.  I still don't know how this install/upgrade process works and I'm surprised to see the latest file has version `210` in it.  My changes here probably need rewriting and including in the install script too.
I've tested this change on my local zencart, running the `ALTER TABLE` manually.  It inserts NULL errorinfo if no errorinfo was provided (empty string), otherwise the errorinfo stirng.
Also rewrote the email_archive insert to use `$db->perform` just because I feel it looks neater.  Happy to stand corrected.
=> Include errorinfo in email_archive.

includes/classes/traits/NotifierManager.php, includes/classes/traits/ObserverManager.php
Adds the following methods to Notifier and Observer base traits:
`registerDeprecatedEvent($old, $new)`
`registerObserverAlias($old, $new)`
=> Allow Notifier deprecations to be registered

admin/products_price_manager.php, admin/specials.php, includes/classes/CouponValidation.php, includes/classes/shopping_cart.php, includes/functions/functions_prices.php, includes/functions/functions_products.php, includes/modules/order_total/ot_gv.php
Products model is a nullable field.
--> PHP Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /Users/scott/sites/client/includes/functions/functions_prices.php on line 32.
=> Make allowance for null products model

includes/classes/Product.php, includes/classes/shopping_cart.php, includes/functions/functions_products.php, includes/modules/also_purchased_products.php, includes/modules/featured_products.php, includes/modules/new_products.php, includes/modules/pages/document_general_info/header_php.php, includes/modules/pages/document_general_info/main_template_vars.php, includes/modules/pages/document_product_info/header_php.php, includes/modules/pages/document_product_info/main_template_vars.php, includes/modules/pages/product_free_shipping_info/header_php.php, includes/modules/pages/product_free_shipping_info/main_template_vars.php, includes/modules/pages/product_info/header_php.php, includes/modules/pages/product_info/main_template_vars.php, includes/modules/pages/product_music_info/header_php.php, includes/modules/pages/product_music_info/main_template_vars.php, includes/modules/product_listing.php, includes/modules/responsive_classic/product_listing.php, includes/modules/sideboxes/best_sellers.php, includes/modules/specials_index.php, includes/modules/upcoming_products.php, includes/psr4Autoload.php, includes/templates/responsive_classic/sideboxes/tpl_reviews_random.php, includes/templates/template_default/sideboxes/tpl_featured.php, includes/templates/template_default/sideboxes/tpl_reviews_random.php, includes/templates/template_default/sideboxes/tpl_specials.php, includes/templates/template_default/sideboxes/tpl_whats_new.php
Centralizes all basic product-related querying and overriding. (Not including attributes or pricing.)
Closes #6367
The easiest override/notifier hook is now `NOTIFY_GET_PRODUCT_OBJECT_DETAILS`
=> Product class

includes/classes/InitSystem.php
Currently, the `initSystem` fails to load those files
```
[153] => ##################################################################
[154] => Action Point - 78
[155] => Auto Type Method - processAutoTypeClass
[156] => processing class - C:/xampp/htdocs/zc200w/zc_plugins/POSM/v5.0.0/catalog/C:/xampp/htdocs/zc200w/includes/classes/observers/class.products_options_stock_observer.php
[157] => loading class - C:/xampp/htdocs/zc200w/zc_plugins/POSM/v5.0.0/catalog/C:/xampp/htdocs/zc200w/includes/classes/observers/class.products_options_stock_observer.php - FAILED
```
=> Correct storefront auto-load of zc_plugin classes

includes/classes/Product.php
Seeing logs like the following, using the Bootstrap template and demo products
```
[25-May-2024 13:18:41 America/New_York] PHP Fatal error: Uncaught TypeError: zen_get_products_manufacturers_name(): Return value must be of type string, array returned in C:\xampp\htdocs\zc200w\includes\functions\functions_products.php:520
Stack trace:
#0 C:\xampp\htdocs\zc200w\includes\classes\ajax\zcAjaxBootstrapSearch.php(63): zen_get_products_manufacturers_name('43')
#1 C:\xampp\htdocs\zc200w\ajax.php(72): zcAjaxBootstrapSearch->searchProducts()
#2 {main}
thrown in C:\xampp\htdocs\zc200w\includes\functions\functions_products.php on line 520
[25-May-2024 13:18:41 America/New_York] Request URI: /zc200w/ajax.php?act=ajaxBootstrapSearch&method=searchProducts, IP address: 127.0.0.1
--> PHP Fatal error: …
```
=> Non-language `get` fails when element is `NULL`

extras/ipncheck.php
From PHP 8,1 and later, certain changes to the $GLOBALS array throws fatal errors. In general, modifying individual array elements is allowed, but making mass changes are not allowed.
Current code throws a fatal error which shows as an HTTP 500.
=> Fix PHP 8.1 syntax in ipncheck.php utility

includes/templates/template_default/templates/tpl_gv_faq_default.php
- redemption code was displaying the FAQ number by default ... should be blank
- "back" button was blocking layout of redemption field
=> Fix GV_FAQ page

includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php
While a `zc_plugin`'s page-specific language files _can_ be overridden by a template-override language file, a plugin's `extra_definitions` language files cannot be.
This PR corrects that condition, ensuring that any template-overrides (er) override.
=> Enable zc_plugin `extra_definitions` to be overridden by templates

includes/templates/template_default/templates/tpl_zc_install_suggested_default.php, includes/templates/template_default/templates/tpl_zc_phpupgrade_default.php
In PHP8, we get a warning about this constant because the base language file isn't pulled in. 
Let's just remove the constant.
```
[31-May-2024 11:53:23 UTC] PHP Warning:  Use of undefined constant HTML_PARAMS - assumed 'HTML_PARAMS' (this will throw an Error in a future version of PHP) in /home/client/public_html/store/includes/templates/template_default/templates/tpl_zc_phpupgrade_default.php on line 19
```
=> `install_suggested` and `phpupgrade`, correct missing constant warning/error

includes/functions/functions_general_shared.php
Intended for use with configuration switches whose values are truthy/falsey but stored as strings. eg: "True", 'true', 'On', 'OFF', 'Yes', 'no'
Instead of converting `==` to `===` when refactoring comparisons with configuration switches that are really boolean-ish, use `zen_is_boolean(CONSTANT)` and treat the response as boolean.
eg:
`SHOW_PRODUCTS_SOLD_OUT_IMAGE == '1'` could be replaced with 
`zen_is_boolean(SHOW_PRODUCTS_SOLD_OUT_IMAGE) === true` (even leave off the `=== true` part)
`strtolower(IMAGE_USE_CSS_BUTTONS) === 'yes'` 
could be replaced with `zen_is_boolean(IMAGE_USE_CSS_BUTTONS) === true` (again, can leave out the `=== true` suffix)
=> Add zen_to_boolean() function

includes/classes/Product.php
Fixes #6516 by treating master_categories_id as "not" a category to which the product is linked
=> Product class - linked products count

admin/includes/modules/copy_product_confirm.php, includes/classes/db/mysql/query_factory.php
The `$db->metaColumns(tablename)` function returns a list of db fields, and with this PR now also returns field types and other schema data that could be used for casting to native types, determining whether NULL could be expected, and more.
Fixes errors occurring in #6504 by using this meta data to determine which fields can actually be cloned when duplicating a product, thus ignoring all "fields" derived from other product data prepared by the `Product` class.
=> Enhance queryFactoryMeta class to track more data

includes/init_includes/init_sessions.php
```
--> PHP Warning: Undefined array key "HTTP_USER_AGENT" in /home/client/catalog/includes/init_includes/init_sessions.php on line 150.
```
=> Fixes undefined array key log when sessions config uses Check User agent

includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php
A corollary to https://github.com/zencart/zencart/pull/6493.
The default 3rd parameter for `pluginLoadArraysFromDirectory` is "admin'.
=> CatalogArraysLanguageLoader: Use correct 3rd parameter

admin/attributes_controller.php, admin/category_product_listing.php, admin/includes/auto_loaders/config.core.php, admin/includes/modules/copy_product_confirm.php, admin/media_manager.php, admin/product.php, admin/products_price_manager.php, admin/stats_products_lowstock.php, admin/stats_products_purchased.php, includes/classes/products.php, includes/functions/functions_files.php, includes/functions/functions_lookups.php, includes/functions/functions_products.php
Partly fixes #6504 
The `products` class (global var `$zc_products`) contains several helper functions that are basically subsumed by the `Product` class and/or some helper functions already used across the code base.
This moves toward deprecating that class. Nothing changes inside it, so won't cause a breaking change until we actually delete the class in a future version.
=> Admin: retire $zc_products class

admin/includes/auto_loaders/config.core.php, includes/auto_loaders/config.core.php, includes/auto_loaders/paypal_ipn.core.php, includes/classes/shopping_cart.php, includes/psr4Autoload.php
... thus enabling ~~that class~~ those classes to be overridden if needed.
=> Use `$psr4Autoload` instead of `config.core.php` to handle the base class' loading

admin/downloads_manager.php
As it is now, closing the col-sm-6 and re-opening it between the misconfigured and missing listings forces them to be separated and confuse the store owner. https://www.zen-cart.com/showthread.php?230203-Downloadable-Product-is-misconfigured.
before
after
=> Realign Icons for Downloads Manager

includes/modules/pages/unsubscribe/header_php.php
Occurs when spammers supply an `action=unsubscribe` but no `addr=` variable on the page-link, resulting in logs like
```
--> PHP Warning: Undefined array key "addr" in /home/mysite/public_html/includes/modules/pages/unsubscribe/header_php.php on line 29.
```
=> Php warning unsubscribe

admin/includes/classes/WhosOnline.php, admin/whos_online.php, includes/classes/shopping_cart.php
```
[24-May-2024 19:39:30 Europe/London] Request URI: /catalog/admin/index.php?cmd=whos_online&q=time_last_click-desc, IP address: 86.129.104.124, Language id 1
#1  WhosOnline->inspectSessionCart() called at [/home/client/catalog/admin/includes/classes/WhosOnline.php:249]
#2  WhosOnline->getStatusCode() called at [/home/client/catalog/admin/includes/classes/WhosOnline.php:157]
#3  WhosOnline->retrieve() called at [/home/client/catalog/admin/whos_online.php:52]
#4  require(/home/client/catalog/admin/whos_online.php) called at [/home/e-smith/files/ibays/sw-zen/html/catalog/admin/index.php:16]
--> PHP Warning: Undefined array key "currency" in /home/client/catalog/admin/includes/classes/WhosOnline.php on line 358.
- duplicated 
[24-May-2024 19:39:30 Europe/London] Request URI: …
```
=> Fixes whos_online logs

admin/languages.php
In Admin pages, when using 2 languages and deleting the one (not default) that you are actually using through languages page, you get stuck in that language.
The language drop down menu is not there anymore and although in languages page there is only the default language English, you can't change back to it...
With this modification, language will change back to default using GET parameter when deleting the language that is actually in use.
=> Language in admin stuck to deleted language

admin/attributes_controller.php, includes/functions/functions_prices.php
Fixes #6564
There was, for whatever reason, an already present parameter on `zen_get_attributes_price_final` to indicate whether/not to include the product's base price, it was just never used.
Additional parameters needed for the admin's Attributes' Controller display, since that _does_ include the product's base pricing.
Noting that the issue's been around since at least zc158a.
=> Corrects attribute pricing display

admin/orders.php
If a plugin writes to the order_status_history table and uses a status of 0 (or any non-existent status), this will produce a log. 
```
--> PHP Warning: Undefined array key 0 in /home/client/public_html/store/admin/orders.php on line 1057.
```
=> Protects against non-existent order statuses

includes/classes/PluginManager.php, includes/classes/ViewBuilders/PluginManagerDataSource.php
Currently, `zc_plugin` files are loaded in the order in which they were installed, leading to an unpredictable load order.
This PR loads them, instead, by sorting the installed plugins' `unique_key`.
=> Load `zc_plugin` directories in a predictable order

admin/includes/ckeditor.php, admin/includes/css/stylesheet.css, editors/ckeditor5/config.js
Ref #6209
This uses CKEditor 5 "Classic Mode", which turns a textarea field into an in-browser editor field.
Minor differences from CKE4:
- right-click "context menu" is no longer a custom menu: it's just the browser's own context-menu.
- button-bar no longer offers cut/copy/paste: but normal keyboard shortcuts and right-click menu can be used.
- spell-check not offered without purchasing a commercial license
Tested on versions v210, v200, v158, v157, v156 to confirm that the CKE5 editor loads correctly using the code changes in this PR.
To backport to an older version, simply copy the files from this PR.
`/admin/includes/ckeditor.php` (whole file)
`/editors/ckeditor5/config.js` (whole file and directory)
and manually patch the stylesheet:
`/admin/includes/css/stylesheet.css` (just the …
=> CKEditor 5

includes/classes/InitSystem.php
Starting with zc157 (!) via [this](https://github.com/zencart/zencart/commit/a838c137bd5f686028cc9ab7807ac9009eb11ca4) commit, the "core" auto-loader is no longer loaded first (i.e. `config.core.php` or `paypal_ipn.core.php`).
Essentially, all files in the `auto_loaders` directory are now loaded alphabetically, with no special casing for the "core" file.  To see the potential for problems:
1. Create a file `includes/auto_loaders/config.aaaa.php` containing:
```php
<?php
$autoLoadConfig[0][] = [
'autoType'=>'init_script',
'loadFile'=> 'init_aaaa.php'
];
```
2. Create a file `includes/init_includes/init_aaaa.php` containing:
```php
<?php
if (PROJECT_VERSION_MAJOR === '2') {
//- do something
}
```
Load the associated storefront to be met with a whitescreen and a log similar to
``` …
```
=> Ensure that `{$loaderPrefix}.core.php` is the first auto-loaded file

admin/includes/classes/stats_sales_report_graph.php
Monthly needs to go back a year.  Tested with a large database. 
Fixes #6567.
=> Fixes next and previous links for monthly.

includes/functions/functions_categories.php
For text-substitution, boilerplate, short codes...
Currently this function is only used in the admin, but there is scope for it to replace storefront discrete queries (I have).
=> add notifier for category description

includes/application_top.php
If a 'bad actor' has specified any of the built-in `$_GET` variables as arrays, various logs can be generated.  This PR refactors `/includes/application_top.php` and then ensures that none of the built-in variables are submitted as arrays.  If so, an HTTP 406 header is issued and the page load fails.
=> Storefront sanitization of various `$_GET` variables

admin/configuration.php
Typos with language file name (lang. missing)  in comments in configuration.php.
=> Typos with language file name in configuration.php

admin/includes/functions/html_output.php
Don't generate autocomplete tag if already present in `$parameters` (or if override is set).
Fixing it this way allows other templates to benefit from the fix, instead of having to update every one of them.
Fixes #6637
=> Avoid generating duplicate autocomplete tag

includes/classes/query_cache.php
When running a query which fails (for example due to a schema issue) but which still lands in cache as a boolean `false` instead of a proper mysqli_result, a fatal error is thrown: `PHP Fatal error:  Uncaught TypeError: mysqli_data_seek(): Argument #1 ($result) must be of type mysqli_result, false given in query_cache.php:42`
The cache retrieval can be avoided by adding an additional type check in the `inCache()` check method.
This scenario is unusual because the query cache is in-memory ("memoized") and refreshed on each page-visit. To trigger the problem, one would need to re-run the same query again in the same visit. Usually this doesn't happen because a fatal error normally halts execution. But if that fatal error is bypassed (eg: with $dieOnFailure = false), then this cache bug is …
=> Fix error on query cache miss

admin/orders.php
That way, the cursor stays on the clickable link instead of pushing to the top-of page so you have to scroll down again.
=> Use Bootstrap 'collapse' for order payment detail notifications

admin/customers.php, admin/includes/modules/search_box.php
It was lost in the zc157->zc158 transition.  Used to be only on Categories/Product, but now since the search-box is used multiple places, it'll be widespread.
=> Restore auto-focus to admin search

includes/classes/pulldown.php
All callers use lower case 'd' (`generatePulldownHtml`).
=> `pulldown` class: Align name with usage

includes/functions/functions_general.php
Now that AAQ is built-in, I think the contact us link shown instead of the buy now button should indicate the product, as the ask a question page does.
=> Buy now button for showcase

includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php
In a multi-language site, if a non-english per-page language file (e.g. `lang.contact_us.php`) doesn't include one of the 'base' required constants ... a whitescreen results.
This PR provides a fallback mechanism to pull in any missing constants from the english version of the file.
=> Correct multi-language fallback for per-page language files

includes/modules/payment/paypaldp.php
--> PHP Warning: Undefined array key "L_LONGMESSAGE0" in /home/client/public_html/store/includes/modules/payment/paypaldp.php on line 2019.
--> PHP Warning: Undefined array key "L_ERRORCODE0" in /home/client/public_html/store/includes/modules/payment/paypaldp.php on line 2023.
--> PHP Warning: Undefined array key "L_ERRORCODE0" in /home/client/public_html/store/includes/modules/payment/paypaldp.php on line 2019.
etc.
=> `paypaldp.php`: Fixes for PHP8 warnings

admin/includes/css/layout_controller.css, admin/includes/css/stylesheet.css, admin/options_values_manager.php
Include some basic Bootstrap 4/5 CSS Utility classes in the admin's base `stylesheet.css` as an aid in transitioning admin tools to a more recent version of Bootstrap.  The currently-used classes are also removed from other admin .css and .php files.
The classes are in alphabetical order towards the end of that file.
Note: Also removed duplication of `.clearBoth` definition.
=> Admin: Additional BS4/BS5 CSS classes in stylesheet.css

includes/classes/ResourceLoaders/AdminArraysLanguageLoader.php
Currently, the admin language-loading falls back to 'english' _only for_ the base language files.  This has (I think) been a problem since the language-arrays were introduced for multi-language sites.
This will 'protect' upgrading sites when new language-constants are defined in the ZC 'core' (e.g. `lang.ezpages.php` and `lang.layout_controller.php`) or when english-only encapsulated plugins are installed.
=> Admin language-loads, fallback to english

includes/classes/order.php, includes/modules/order_total/ot_coupon.php
i can get by without the change to the order class; but it just seems adding that value to the order object saves a whole bunch of database hits.
=> allow changes to ot_coupon; fixes #6710

admin/languages.php, includes/functions/functions_lookups.php
Expects admin `lang.languages.php` or a file in `extra_definitions` to contain order status defines for each pre-existing english status name. 
Any statuses for which a matching define is not found, will just use the English value, as before, and can be manually translated via the Admin UI as before.
French example for pending, processing, delivered, update:
```
'INSTALL_ORDER_STATUS_PENDING' => 'En attente',
'INSTALL_ORDER_STATUS_PROCESSING' => 'En cours',
'INSTALL_ORDER_STATUS_DELIVERED' => 'Livré',
'INSTALL_ORDER_STATUS_UPDATE' => 'Mise à jour',
```
Addendum to #6584
=> Translate copied order-status names when installing new language

includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php
I've no clue where I had that idea from!
=> Catalog language loader: Don't strip `lang.` prefix from known file

includes/modules/categories_tabs.php, includes/templates/template_default/templates/tpl_modules_categories_tabs.php
Inspired by #6719
The template optionally allows referring back to already-queried categories_id if an override template wants to do more with that information (such as show subcategories/products).
=> Simplify style-overrides for category-tabs template

includes/classes/ResourceLoaders/AdminArraysLanguageLoader.php, includes/classes/ResourceLoaders/ArraysLanguageLoader.php, includes/classes/ResourceLoaders/BaseLanguageLoader.php, includes/classes/ResourceLoaders/CatalogArraysLanguageLoader.php
Essentially, aligning with the docs: https://docs.zen-cart.com/dev/languages/language_constant_logic/
=> Language loading, catalog per-page and template-override updates/corrections

admin/includes/modules/update_product.php
while i have not been able to reproduce, i have come across this error:
```
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /worsthost/worstadminrename/includes/modules/update_product.php:21
```
so if these `$_POST` vars are not set, we are passing a string.  which causes a FATAL error.
this can easily be reproduced by executing this 1 line script:
```php
// good
$test2 = implode(' ', $test ?? []);
//bad
$test2 = implode(' ', $test ?? '');
```
=> implode 2nd argument requires array; string errors out

admin/modules.php, includes/classes/ResourceLoaders/ArraysLanguageLoader.php, includes/classes/ResourceLoaders/FilesLanguageLoader.php, includes/classes/ResourceLoaders/LanguageLoader.php, includes/classes/order_total.php, includes/classes/payment.php, includes/classes/shipping.php
- Provide 'fallback' (i.e. 'english') language processing for module-type language files
- Legacy (i.e. non-`lang.` prefixed) language files load _only_ for the current session language, following previous Zen Cart versions' handling.
=> Module language fallback; legacy only for session language

includes/classes/order.php
Add a notification to enable an observer to override customer/delivery/billing addresses for an order created from the 'cart' in preparation to be recorded in the database.
The addition of this notification will allow the next-generation of "Edit Orders" to make use of the base order-class processing in the gathering of the information for the to-be-updated order.
Also includes some minor reformatting, breaking out the `country` elements into one-line for each array key.
=> Add an order-class notification for address overrides

includes/classes/ResourceLoaders/ArraysLanguageLoader.php, includes/classes/ResourceLoaders/LanguageLoader.php, zc_plugins/POSM/v6.0.0/admin/includes/classes/observers/class.products_options_stock_admin_observer.php
There are a couple of plugins, POSM included, that use a common language definition between the admin and storefront.
This PR provides that helper-function that loads the requested `lang.` array file from the storefront/catalog side, using the language-fallback strategy incorporated in all other catalog language files' loading.
=> Admin plugin 'helper' to load a specific catalog language `array` file

includes/classes/Product.php
Needed for the Edit Orders update, in case a product in an order no longer exists on the site.
The `$data_override` variable, if updated, _must_ be an array type or a PHP Warning/Error will occur.
=> Product-class: New notifier when requested product isn't found

includes/functions/functions_search.php
As originally identified in [this](https://www.zen-cart.com/showthread.php?230339-PHP-Warning-Undefined-array-key-0-in-functions_search-php) forum posting, a search for `"/linkiFrAme src="jAvasCript:alert(1);"/iframe]` results in a PHP Warning from the `zen_parse_search_string` function.
This PR corrects that warning.
=> Correct storefront search PHP Warning

admin/orders.php, includes/classes/order.php
... otherwise, the admin's base `orders.php` and/or EO needs to, essentially, repeat that query to also pull in the records hidden from the customer's view.
=> `order` class: Gather all order-status entries for admin use

admin/plugin_manager.php, includes/classes/ViewBuilders/DerivedItemsManager.php, includes/classes/ViewBuilders/PluginManagerController.php, includes/functions/functions_lookups.php
If a plugin contains language defines for
`ADMIN_PLUGIN_MANAGER_NAME_FOR_xyz`
or
`ADMIN_PLUGIN_MANAGER_DESCRIPTION_FOR_xyz`
... then they will be used when displaying details of **installed and enabled** plugins in the Plugin Manager, 
according to whatever language is actively selected in the Admin interface.
=> Update Plugin Manager translations support

admin/includes/init_includes/init_admin_auth.php, zc_install/sql/updates/mysql_upgrade_zencart_210.sql
A corollary to [this](https://github.com/zencart/zencart/pull/6765) PR.  Non-superuser admins were not only getting a page-access log for `keepalive.php` but also another log for page-access denied since `keepalive` isn't in the list of permitted pages.
This also backs out the zc_install update that removes page-access logs for `keepalive.php`, otherwise the follow-on `denied.php` record becomes an orphan:
=> Don't consider `keepalive` as an invalid page-access

admin/modules.php
Update to admin/modules.php to use the zen_lookup_admin_menu_language_override function for translation using constants placed in admin's lang.modules.php.
Complements PR #6584
=> Update to admin/modules.php to use admin lookup function for translation

includes/templates/responsive_classic/common/tpl_main_page.php, includes/templates/template_default/common/tpl_main_page.php
This added CSS class would allow plugins to pre-target formatting for specific templates.
eg: 
```diff
-<body id="productInfo">
+<body id="productInfo" class="tpl_responsive_classic">
```
There are pros and cons to this. 
Pros include convenience. 
Cons, as far as plugins go, include accidentally excluding "all" templates from necessary formatting by neglecting including generic styles.
=> Add `tpl_`+template_name to `body` class list

includes/classes/ResourceLoaders/PageLoader.php, includes/classes/traits/InteractsWithPlugins.php
This will allow Observers in Encapsulated Plugins to query details about the plugin version/directory in which it is located. Helps with:
- knowing what version is in effect
- knowing what context we're in (admin/catalog/Installer)
- loading a catalog stylesheet via a plugin, first from plugin directory, and then from active template directory (as an override), without having to publish files to the core catalog directory.
To use:
```diff
<?php
+use Zencart\Traits\InteractsWithPlugins;
use Zencart\Traits\NotifierManager;
use Zencart\Traits\ObserverManager;
class MyEncapsulatedPluginObserverClass
{
+    use InteractsWithPlugins;
use NotifierManager;
use ObserverManager;
```
and then that observer class will have access to:
```php
protected bool $isAZcPlugin;
protected string …
```
=> Add `InteractsWithPlugins` trait for Observers in Encapsulated Plugins

includes/modules/hreflang.php, includes/templates/responsive_classic/common/html_header.php, includes/templates/template_default/common/html_header.php
- relocated hreflang-generation logic to separate module file
- added notifier to allow bypass (ie: to intercept and output different format)
- added x-default "fallback" link, which simply points to the no-language-specified version of the page (ie: default language)
Retains bi-directional linking.
Retains former behavior of only outputting hreflang links if more than 1 language is installed.
Retains prior language-choosing via $_GET parameter provided in URL:
> (eg: If a visitor is directed to a page with `language=` in the URL, that page will display using that language, if still installed (and will also set the language in the session, for subsequent clicks to stay in that language). 
**Further**, if visitor "first" hits the x-default or canonical (eg: without a GET param or a session …
=> Extract `hreflang` logic to separate module, adding notifier

includes/classes/PluginSupport/InstallerFactory.php
@zcwilt
It would seem that it checks here for `$versionDir/installer/Installer.php` and then tries to load `$versionDir/Installer.php` Plus the use of `new Installer()` missing the `\` as in `new \Installer()` potentially clashes with the main `Installer` class, which has none of the methods on it that are expected by the code using this Factory to generate an "installer" object for.
So, I'm not convinced that this PR is even a proper "fix", but it does point out where there are mismatches that need attention.
What was the "Installer/Installer.php" fallback intended to be used for?  Is there a use-case for other than `BasePluginInstaller`, which `ScriptedPluginInstaller` uses?
=> Encap plugin installer logic error?

includes/modules/pages/ask_a_question/header_php.php
Seeing more of these.  Happens when people go directly to the URL 
`index.php?main_page=ask_a_question&action=send&pid=NNN`
This prevents the log; the check done later will bounce them back to the AAQ page.
=> Check for null entity

admin/category_product_listing.php
As discussed in [this](https://github.com/lat9/options_stock_support/issues/60) POSM support issue.
Extended from what's posted there to enable buttons to be added to a category listing as well as a product one.
=> Add 'action button' notification for category/product listings

includes/modules/sideboxes/best_sellers.php, includes/templates/template_default/sideboxes/tpl_best_sellers.php
... as identified in [this](https://www.zen-cart.com/showthread.php?223910-ZCA-Bootstrap-4-Template-Support-Thread&p=1403427#post1403427) forum-post and introduced in [this](https://github.com/zencart/zencart/pull/5599) PR.
Templates are _obviously_ expecting that the array returned has an index that starts with 1.
=> Correct best-sellers' sidebox index

admin/attributes_controller.php
this script needs a bunch of work.  wish i had more time to clean up all of the duplicate code here as well as reformat.
in any event, some notifiers for adding additional fields to the products_attributes table are all that this is doing.
i tried following the formatting of the collect_input script; but i will be the first to admin i am not the css bootstrap guy.
=> add notifiers to attributes controller

admin/orders.php
When clicking on the link to expand the section:
All examples I find use the (0).
=> admin, orders: prevent console error on expanding extra payment info

includes/functions/functions_categories.php
if the request is made to only include active categories, it seems appropriate to NOT include categories where the count of items in the category is 0.
=> remove 0 count categories from `zen_get_categories()` when requesting active categories

admin/includes/modules/delete_product.php
To potential warn/prevent deletion for specific products (used for a lurking plugin for product kits).
=> Admin, Delete product: notifier for InfoBox data

admin/category_product_listing.php, admin/includes/functions/html_output.php
This change allows the image to be resized dynamically via CSS instead of hardcoded via HTML <img> attributes.
For example: the pictures in the category listing would be stretched to fit both the height and width of the image settings as designated in the admin backend. This change moves the setting of the image's height and width to CSS where appropriate (ie. where the image's height or width are set in the function call).
=> Changing admin image display to size via CSS instead of HTML attribute

includes/templates/responsive_classic/sideboxes/tpl_categories.php
Missing alias for table products in responsive classic side box file tpl_categories.php.
This causes an error 500 on catalog when SHOW_NEW_PRODUCTS_LIMIT is set to anything else than 0 (default) in `Configuration::Maximum values:New Product Listing - Limited to ...`
`PHP Fatal error: MySQL error 1054: Field 'p.products_date_added' unknown in where clause :: SELECT products_id FROM products WHERE products_status = 1  AND p.products_date_added >= 20241001 limit 1 ==> (as called by) ...\includes\templates\responsive_classic\sideboxes\tpl_categories.php on line 77 ...`
I checked all other 6 files that uses function `zen_get_new_date_range` where the error was actually originating, and they all use 'p' as alias for table products.
Adding it to tpl_categories.php on line 77 resolved the …
=> Missing alias for table products in tpl_categories.php

admin/profiles.php
Multiple CSS classes are now applied to checkbox elements, so we can't check for `element.className == val`; instead, must use `element.classList.contains(val)`
=> Fix checkAll() button on profile-edit page

admin/includes/init_includes/init_sessions.php, includes/functions/sessions.php, includes/init_includes/init_sanitize.php, includes/modules/payment/paypal/paypal_curl.php
The PHP core team is considering deprecating `uniqid()` in favor of better alternates in future PHP versions. 
Given that we only use it for one purpose, changing it here is straightforward.
=> Replace uniqid() with better entropy

admin/includes/classes/class.admin.zcObserverLogEventListener.php, admin/includes/classes/class.admin.zcObserverLogWriterTextfile.php, includes/functions/functions_general_shared.php, zc_install/includes/functions/general.php
PHP 8.4 will deprecate the use of null as default if the type is not also declared as nullable (using `?`)
=> Fix nullable type signature declarations

includes/functions/functions_categories.php
Cast `$categories_id` to string in `zen_get_categories_products_list()`, for the sake of `strict_mode`
Fixes #6814
=> Cast to string

includes/classes/Coupon.php, includes/functions/functions_general_shared.php, includes/modules/payment/authorizenet.php, zc_install/includes/functions/general.php
`rand()` was retired in PHP 7.2, being made an alias of `mt_rand()`, which has since been superceded by `random_int()` when specifying a range. mt_rand() is still valid for the ways in which we use it.
=> Retire obsolete rand() in favor of newer methods

includes/classes/Coupon.php
Removes redundant code
Addresses edge-case fatal error crashes if wildly invalid parameters are set
=> Refine coupon-generator function

includes/classes/PluginSupport/PluginErrorContainer.php, includes/classes/cache.php, includes/classes/class.zcPassword.php, includes/classes/traits/ObserverManager.php, includes/functions/functions_products.php, includes/functions/password_funcs.php, includes/modules/pages/order_status/header_php.php, zc_install/includes/functions/password_funcs.php, zc_plugins/DisplayLogs/v3.0.2/admin/display_logs.php, zc_plugins/POSM/v6.0.0/admin/includes/classes/PosmSalesReport.php, zc_plugins/POSM/v6.0.0/catalog/includes/functions/products_options_stock_functions.php
`md5()` -> `hash('md5')`
We're not currently using `sha1()` directly: we're already using `hash('sha1')`.
The bulk of our use of `md5()` is just to prepare a token, or to identify one element from another with some uniqueness. So this is not really a change that affects cryptography per se. It merely steps away from using the (potentially-being-retired) `md5()` function.
This change is backward-compatible to PHP 7.0, and sets future compatibility when the PHP team finally agrees to retire the md5/sha1 functions in favor of `hash()`, probably to be re-proposed in PHP 9.0
=> Change hashing functions to use modern methods

admin/category_product_listing.php, admin/includes/modules/copy_product_confirm.php, admin/includes/modules/delete_product_confirm.php, admin/includes/modules/move_product_confirm.php
Allows these modules to be called directly from other modules/plugins, particularly in a batch/loop, without triggering the redirects.
- move zen_redirect() to category_product_listing.php
- reduce nested indents by using early-return in copy_product_confirm.php (no other changes, although indentation touches the whole file)
Replaces and closes #6811
=> Relocate zen_redirect() calls in admin product copy/move/delete modules

includes/classes/order.php
Needed for EditOrder's reconstruction of the order; the attribute related information is already present in the captured order.
=> Enable cart->order conversion to bypass attributes

includes/modules/pages/ask_a_question/header_php.php
On one of the site's that I'm managing, I'm seeing warning logs for those missing variables.
=> AAQ: Account for missing posted variables

admin/includes/javascript/flot/jquery.flot.js
In reality, the JS Flot library is already restricted behind several other layers of protection, and has very limited scope of use.
Nevertheless, these patches make it more secure, even though most of our implementation doesn't use the affected areas of code.
=> Patch flot graph library

zc_plugins/POSM/v6.0.0/catalog/includes/templates/default/jscript/jquery.posm_dependencies.js
Fixes [https://github.com/zencart/zencart/security/code-scanning/9](https://github.com/zencart/zencart/security/code-scanning/9)
To fix the problem, we need to ensure that any user-controlled data is properly escaped before being inserted into the DOM as HTML. This can be achieved by using a function that escapes special HTML characters, thereby preventing the execution of any injected scripts.
The best way to fix this issue without changing existing functionality is to create a utility function that escapes HTML characters and use it to sanitize the `optionName` before concatenating it into the HTML string.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 9: DOM text reinterpreted as HTML

admin/category_product_listing.php, admin/includes/css/stylesheet.css
In my other edit (#6793), I made this change to allow the images displayed to keep their proportions. I failed to realize I had only changed the category icon in that edit. This change now makes the same change for the images of the product listing rows.
(Duplicate of #6863, since other edits were added. This PR is the correct one to use since it only contains just the one edit.)
=> Changing admin image display to size via CSS instead of HTML attribute for products

admin/banner_manager.php
If no banners were available in the DB, the switch/if statement would still try to pull info from an empty or unset variable `$bInfo`.
This change stops that effort by seeing if `$bInfo` is set.
=> admin/banner_manager:  Stop trying to select a non-existent banner

admin/includes/functions/functions_mfa.php
Since a person can have multiple services installed on their domain which may use MFA, this edit changes the description of the MFA Handle to better represent what it entails.
In this case, it is the store's name (retrieved from the DB Constant `STORE_NAME`) and the name of the software (ZenCart). For example: if the store's name is "Blockbuster Video", when you scan the MFA QR Code, it will show as "Blockbuster Video - ZenCart" in the MFA tool. This change does NOT affect any already issued MFA tokens as it is only changing the Issuer field and does not touch anything of the issued Secret.
=> Change description of MFA to add "Zen Cart" suffix, for disambiguation

admin/configuration.php
This may be possible in other ways, but the creates a hook when a setting in the Configuration Table has been changed by the admin area. It won't pick up if the change is performed by script, SQL import, or other external means).
Some ideas might be if the measuring weight or store's measurement standard has been allowed for all items in the store to be changed quickly. Or if the location itself has changed as well.
=> Creates a Notifier Hook on Config Change

includes/classes/upload.php
uploaded files are renamed to unix-style names - all lowercase, spaces replaces with dashes, double dots removed. avoids issues with JPG vs jpg files, using user-uploaded images with spaces in srcset tags and similar issues
=> rename file uploads to unix format

admin/invoice.php, includes/classes/traits/NotifierManager.php
Fixes #6896
Ref #4518
NOTE: Documentation is needed in release notes, as existing plugins or custom modifications may be impacted. (Fix is a simple search-replace in one's code-base)
=> Fix misspelling in notifier hook name

includes/classes/shipping.php, includes/templates/template_default/templates/tpl_checkout_shipping_default.php
If a shipping module returns an empty array for its quotes, a PHP warning is issued:
```
[03-Jan-2025 23:17:03 America/Chicago] Request URI: /index.php?main_page=checkout_shipping, IP address: xx.xx.xx.xx, Language id 1
#0 /includes/templates/template_default/templates/tpl_checkout_shipping_default.php(66): zen_debug_error_handler()
#1 /includes/templates/responsive_classic/common/tpl_main_page.php(181): require('/home/mysite/...')
#2 /index.php(94): require('/home/mysite/...')
--> PHP Warning: Undefined array key "module" in /includes/templates/template_default/templates/tpl_checkout_shipping_default.php on line 66.
```
This can be triggered by configuring the `zones.php` shipping module with a single zone to offer a fixed-price to any non-US-destined order:
=> Correct PHP warning for empty shipping quote returned

includes/classes/order.php
While the `order` table field `is_wholesale` was created in zc200, the `order.php` class neither records that value when an order is placed nor gathers it into a queried order.
This PR corrects that oversight.
=> Record/gather order's wholesale status

admin/sqlpatch.php
The string length of 'INNER JOIN ' should be 11 not 10
=> 'INNER JOIN ' not working in sql patch

admin/sqlpatch.php, includes/classes/http_client.php, includes/classes/upload.php
In commit 3f13e22bd98fadff3516d3c44428c59367523bc3 
which was focused on migrating from zen_not_null() to empty(), 
the copy and replace had a small issue in a handful of places: 
`!zen_not_null()`
was changed to 
`!!empty()`.
This PR simplifies those changes to just `empty()` (since !!empty is the same as empty).
Credit to @lat9 for finding this issue.
=> Fix !!empty() to empty()

includes/modules/pages/search_result/header_php.php
=> Display `search_result` page correctly if no matches found

admin/includes/header.php, admin/includes/header_navigation.php
this PR does 2 things:
- removes duplicate code so that items do not have to match every time we want to change the upper menu items.
- adds the ability to override those links via a notifier.
admins want quick links to get where they want to go.  this PR will allow people to customize those links to their choosing as opposed to the maintainers choosing.
=> add override ability for upper menu items

admin/includes/functions/html_output.php, includes/classes/db/mysql/query_factory.php, includes/functions/functions_error_handling.php
Fixes #6876
Adds `exit()`/`die()` to treat as fatal.
And, in order to retain former `logging` as `error` (not "warning"), the word `'FATAL'` is added as a prefix to the error string, when combined with E_USER_WARNING.
=> Retire use of E_USER_ERROR for PHP 8.4 compatibility

admin/users.php
```
[25-Jan-2025 12:04:40 UTC] Request URI: /gh_demo_200/admin/index.php?cmd=users, IP address: ::1, Language id 1
#0 /Users/scott/Sites/gh_demo_200/admin/users.php(111): zen_debug_error_handler()
#1 /Users/scott/Sites/gh_demo_200/admin/index.php(16): require('/Users/scott/Si...')
--> PHP Warning: Undefined array key "profile" in /Users/scott/Sites/gh_demo_200/admin/users.php on line 111.
```
Reproduction: 
- login to admin 
- Admins > Admin Users > Edit (on currently logged in account)
- change the username, then save
Profile is not passed in when current user is being edited.
=> Prevent log while editing current admin user

includes/functions/functions_email.php
i was on the fence about validating the dev email override; but i feel it is not a bad idea, with minimal processing time.
i'm a fan of logging that error; but not including the notifier `NOTIFY_EMAIL_ADDRESS_VALIDATION_FAILURE`. if you are a developer, learn to read logs, and enter a valid email address.
in addition, if there are multiple email addresses in the `$to_address`, you will now get 1 email for each of those addresses in the format requested by said customer.  which i think is a better testing methodology for ensuring that all of those emails are getting created and getting sent.  which i think mimics the behavior of all of you fancy developers with your own custom email server doing your own fancy overrides there as opposed to within ZC.
Fixes #6905
=> developer email override; fixes #6905

admin/manufacturers.php
This change uses the same "object-fit-contain" class that was added in another PR (#6866).
In short makes the admin-area manufacturer image display as `object-fit: contain` as it would just show smushed or stretched to fit in an disproportional manner.
=> Change to display manufacturer image in backend proportionally

includes/classes/categories_ul_generator.php
One can now override any of the configurable properties of the class without extending it. 
And one can now specify a $max_levels value when calling `->buildTree()` to limit the levels to 1 or some other value, instead of getting the entire nested list. 
Also caches the db query for 5 minutes, to improve performance when site is getting higher traffic volume.
=> Refactor categories_ul_generator class to allow specifying max_level

includes/functions/functions_osh_update.php
Notifier hook: `ZEN_UPDATE_ORDERS_HISTORY_BEFORE_SENDING_CUSTOMER_EMAIL` 
allows customizing order status update email content messaging
Requested by https://github.com/daphilli224 
Closes #6872
=> Add notifier to osh update

admin/includes/functions/html_output.php
Partial fix for issue #6983 
3- Light green status icon missing/not mapped in Font Awesome class.
=> Corrected Light Green Round Icon Mapping with Font Awesome

includes/modules/payment/paypaldp.php
Add same check as `paypalwpp.php.`
Original log:
```
[07-Feb-2025 08:24:44 America/Los_Angeles] Request URI: /cart/index.php?main_page=checkout_process, IP address: xx.xx.xx.xx, Language id 1
#0 /home/client/public_html/cart/includes/modules/payment/paypaldp.php(1645): zen_debug_error_handler()
#1 /home/client/public_html/cart/includes/modules/payment/paypaldp.php(744): paypaldp->getLineItemDetails()
#2 /home/client/public_html/cart/includes/classes/payment.php(350): paypaldp->before_process()
#3 /home/client/public_html/cart/includes/modules/checkout_process.php(98): payment->before_process()
#4 /home/client/public_html/cart/includes/modules/pages/checkout_process/header_php.php(13): require('/home/client/...')
#5 /home/client/public_html/cart/index.php(35): require('/home/client/...') …
```
=> Fix PayPal log

includes/classes/order.php
casting an array to an int will not give you the id of the country.
`$this->customer['country']` and `$this->billing['country']` are arrays.  the `['id']` element is what is needed for the method.
this bug is very clearly seem in the commit 65cff41ab3 as the delivery array got it correct.
=> fix zone_id in order class

admin/includes/languages/english/lang.configuration.php, includes/classes/class.zcPassword.php, includes/database_tables.php, includes/filenames.php, includes/languages/english/lang.password_forgotten.php, includes/languages/english/lang.password_reset.php, includes/modules/pages/password_forgotten/header_php.php, includes/modules/pages/password_reset/header_php.php, includes/modules/pages/password_reset/jscript_form_check.php, includes/templates/template_default/templates/tpl_password_reset_default.php, zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_220.sql
OLD: When a customer requests a password reset, the old behavior was to generate a new password for them, reset it to that password, and email that password to the customer. These emails often got lost in spam traps, and if the email never arrived then the customer could never login again even if they remembered their old password because their old password had been replaced.
NEW: This updated logic now generates a temporary reset token and emails that token in the form of a URL to click to take them to the password_reset page where they can choose their own new password. Once the token is validated and the user selects a (suitable-length) password, their account is updated to use that new password, and the token is deleted.
Tokens also auto-expire after an admin-configurable timeframe, …
=> Send password-reset URL instead of new password

editors/ckeditor5/config.js
Instead of leaving license code blank, specify 'GPL'. 
This has the side-benefit of being able to simply edit it to set a commercial key when one is purchased.
(Also, setting 'GPL' is *required* in future CKE versions ... although those cannot be loaded over CDN since version 44.x, but that's another matter.)
=> CKEditor-set GPL license as default, instead of blank

admin/includes/init_includes/init_errors.php
As identified in [this](https://www.zen-cart.com/showthread.php?230626-blank-pages-when-upgrading-to-2-10-zencart-unusual-time-stamp-error-logs) Zen Cart forum posting, if the "New Signup Discount Coupon" was previously set and then removed, the site's admin will subsequently fail to load when running on a now-current version (i.e. 8.3+) of PHP.
=> Correct admin fail-to-load if coupon missing

includes/classes/Customer.php
Some older sites have customized versions of the "Dual Pricing" plugin (on which the zc200+ Wholesale pricing was based).  This notification enables those sites to make use of the now-core pricing calculations with minor customization overrides (i.e. the addition of an observer).
=> Add notification to override Customer's wholesale information

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_220.sql
Fixes #6988
Using `varchar(191)` consistently, since the fields in the `products_options` and `products_options_values` tables are keys.
=> Expand option/option-value names to 191 characters

admin/category_product_listing.php, admin/includes/modules/collect_info.php, admin/includes/modules/document_general/collect_info.php, admin/includes/modules/document_general/preview_info.php, admin/includes/modules/document_product/collect_info.php, admin/includes/modules/preview_info.php, admin/includes/modules/product_free_shipping/collect_info.php, admin/includes/modules/product_music/collect_info.php, admin/includes/modules/update_product.php
Admin product listing: include products which are missing a description record
Fixes #6828
- requires the search to include missing-lang products, in order to "find" such products
- requires all the fallback-lookups used when editing/previewing/updating to allow for missing data, in order to prevent filled-in-data from being blanked-out due to failed joins
- requires checking whether the "update" record exists, and fallback to "insert" mode if not found, instead of trying to update the missing record
=> Admin product listing: include products which are missing a description record

admin/banner_manager.php
```
[05-Mar-2025 11:52:02 UTC] Request URI: /client/admin/index.php?cmd=banner_manager&page=1&bID=6, IP address: ::1, Language id 1
#0 /Users/scott/Sites/client/admin/banner_manager.php(554): zen_debug_error_handler()
#1 /Users/scott/Sites/client/admin/index.php(16): require('/Users/scott/Si...')
--> PHP Warning: Undefined array key 1 in /Users/scott/Sites/client/admin/banner_manager.php on line 554.
```
=> Fix errors in banner manager when Group names don't conform to pattern

includes/functions/database.php
Fixes #7013
Note: Changed input name to (er) `$input` (was `$string`).
=> `zen_db_prepare_input`: Add `int` type to input and output

includes/modules/checkout_new_address.php
For the new shipping address and new billing address screens, the gender is not preselected.  We must anticipate someone not selecting a gender when the form is submitted. 
Sample log created: 
```
[06-Mar-2025 18:32:25 UTC] Request URI: /store/index.php?main_page=checkout_shipping_address, IP address: xxx.xxx.xx.xxx, Language id 1
#0 /home/client/public_html/store/includes/modules/checkout_new_address.php(32): store_debug_error_handler()
#1 /home/client/public_html/store/includes/modules/pages/checkout_shipping_address/header_php.php(46): require('/home/client/publi...')
#2 /home/client/public_html/store/index.php(35): require('/home/client/publi...')
--> PHP Warning: Undefined array key "gender" in /home/client/public_html/store/includes/modules/checkout_new_address.php on line 32.
```
=> Handle gender radio button not selected

includes/modules/shipping/freeoptions.php
See [this](https://www.zen-cart.com/showthread.php?230639-Free-Shipping-Issue&p=1406530) Zen Cart forum posting for the initial report of the problem.
Essentially, the checks in the `checkForFreeOptions` method are too strict, resulting in the shipping module being enabled even though the configuration indicates that it should not be.
With this configuration, for example, on an order with a weight of 7 the "Free Shipping Options" is still enabled due to MODULE_SHIPPING_FREEOPTONS_TOTAL_MIN being set to '0.00':
=> `freeoptions` shipping can be invalidly enabled

zc_plugins/POSM/v6.1.0/admin/includes/classes/observers/class.products_options_stock_admin_observer.php
Seeing logs similar to the following prior to the included change:
```
[14-Mar-2025 16:01:01 America/New_York] Request URI: /zc210/admin210/ajax.php?act=ajaxEditOrdersAdmin&method=newProductChosen, IP address: 127.0.0.1, Language id 1
#0 C:\xampp\htdocs\zc210\zc_plugins\POSM\v6.1.0\admin\includes\classes\observers\class.products_options_stock_admin_observer.php(1084): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc210\zc_plugins\POSM\v6.1.0\admin\includes\classes\observers\class.products_options_stock_admin_observer.php(1062): products_options_stock_observer->getProductsStockMessage()
#2 C:\xampp\htdocs\zc210\zc_plugins\POSM\v6.1.0\admin\includes\classes\observers\class.products_options_stock_admin_observer.php(664): products_options_stock_observer->getProductNameWithMessage()
#3 …
```
=> POSM/EO-5: Correct PHP warnings when added product isn't POSM-managed

admin/includes/auto_loaders/products_cron.core.php, admin/products_cron.php, includes/functions/functions_products.php
This cron specifically activates products as-of the current minute (actually to the "second") when the cron job runs, by passing `false` to new `$useMidnight` parameter.
`php /path/to/admin-dir/products_cron.php` with optional timezone being passed. Call with `-help` for details.
If one wanted to bypass using the cron job but set activations to happen "at the current minute", passing `false` to the new `$useMidnight` parameter where this function is called in `/includes/init_includes/init_special_funcs.php` would accomplish the same.
These changes are relatively straightforward because the `products_date_available` field is a `datetime` field already, supporting not just a date but also time. So, as long as that field is set to the desired minute (or second) for an activation time, the …
=> Add cron for activating enabled products

admin/includes/javascript_loader.php, admin/includes/keepalive_module.php, includes/templates/classic/css/stylesheet_image_modals.php, includes/templates/responsive_classic/common/html_header.php, includes/templates/responsive_classic/css/stylesheet_image_modals.php, includes/templates/responsive_classic/jscript/jscript_responsive_framework.php, includes/templates/template_default/common/html_header.php, includes/templates/template_default/css/stylesheet_image_modals.php, includes/templates/template_default/jscript/jscript_framework.php, includes/templates/template_default/jscript/jscript_sidebox_select_form.php
As discussed
https://github.com/zencart/zencart/issues/6966
Admin
to
Storefront
to
There are loads of/too many page-specific scripts, better to do those when a file is updated.
=> add identification titles to base inline css/jscript files

includes/templates/responsive_classic/css/stylesheet.css
Fix attributes/product variations box layout on product pages on desktop devices from 1215PX and over.
Noticed that if you use product attributes / product variations, e.g: you have a product that is available for example in various different colours.
Depending on the length of the text for these attributes, on desktop devices of 1215PX and over you can end up with some of the variations on one single line, and the others taking up two lines, which looks quite messy.
A simple fix is to use display: grid for devices over 1215PX.
Have tested in the latest version V2.1.0, using PHP 8.4,
I've submitted a pull request which fixes this issue (link below):
https://github.com/zencart/zencart/commit/0e10310a0ffd42322914ae35ef566c397b5dffb4
Kind Regards,
Andy
=> CSS fix for product attributes box / product variations on desktop devices of 1215PX and over #7014

includes/modules/payment/paypaldp.php
As noted in [this](https://www.zen-cart.com/showthread.php?230670-A-few-of-PHP-Warnings&p=1406836#post1406836) Zen Cart posting:
lastly, I received this PHP warning when a customer uses a coupon code in the Discount Coupon area during checkout, to get the product for free
```
Request URI: /shop/index.php?main_page=checkout_process, IP address: 66.61.47.189, Language id 1
#0 /home/shop/includes/modules/payment/paypaldp.php(1645): zen_debug_error_handler()
#1/home/public_html/shop/includes/modules/payment/paypaldp.php(744): paypaldp->getLineItemDetails()
#2 /home/public_html/shop/includes/classes/payment.php(350): paypaldp->before_process()
#3 /home/public_html/shop/includes/modules/checkout_process.php(98): payment->before_process()
#4 …
```
=> paypaldp: Account for shipping modules with no tax_class

includes/templates/responsive_classic/templates/tpl_product_info_display_details.php, includes/templates/template_default/templates/tpl_product_info_display_details.php
Displayed on a product's 'detailed information' (e.g. `product_info`) page, the notification enables site (or plugin) additions to be added seamlessly.
=> Add notification for additional product details

includes/functions/whos_online.php
Strip out non-standard characters.
Injection is already protected against, but this avoids unsupported characters.
Fixes #7050
=> Additional UA santization

includes/functions/functions_categories.php
If a category (for whatever reason) has no record in the `categories_description` table, the category cannot be removed via the admin's **_Catalog :: Categories/Products_** tool.
When removing a category, the `category_product_listing.php` module retrieves the category's tree (i.e. it and its children) via the `zen_get_category_tree` function.  That function currently doesn't include the requested category in its return (when `$include_itself` is true) if the category has no such record.
Using the `zen_get_category_name` function instead of direct SQL query; that function returns an empty string if the category's name-record isn't found.
=> Can't delete category if it has no `categories_description` record

includes/functions/functions_urls.php
Enable an observer to override a page-redirect.  For instance, an AJAX add-to-cart handler wouldn't want the `shopping_cart` class to do its `$goto` redirect since the AJAX handler is dealing with that.
=> Add notification to override `zen_redirect`

includes/functions/functions_taxes.php, includes/languages/lang.english.php
this bit of code is not enough:
https://github.com/zencart/zencart/blob/02b6efdd442a0ba89d28511e90d62c42a5ac53c9/includes/functions/functions_taxes.php#L22-L27
most US clients show taxes separate from the line item and utilize what in ZC we call an `order_total` module.  without this PR, when a store is set up with wholesale customers being tax exempt, and taxes are not shown in the price, ie `(DISPLAY_PRICE_WITH_TAX !== 'true')`, the tax amount is not calculated as 0.
this PR addresses that issue.
=> fix tax exempt customers to not get tax

includes/modules/pages/document_general_info/main_template_vars.php, includes/modules/pages/document_product_info/main_template_vars.php, includes/modules/pages/product_free_shipping_info/main_template_vars.php, includes/modules/pages/product_music_info/main_template_vars.php
```
[25-Apr-2025 10:50:54 UTC] Request URI: /zen/index.php?main_page=document_general_info&cPath=63&products_id=5132, IP address: **.***.***.***, Language id 1
#0 /home/client/public_html/zen/includes/modules/products_quantity_discounts.php(92): zen_debug_error_handler()
#1 /home/client/public_html/zen/includes/modules/pages/document_general_info/main_template_vars.php(139): require('/home/client/publi...')
#2 /home/client/public_html/zen/includes/templates/responsive_classic/common/tpl_main_page.php(181): require('/home/client/publi...')
#3 /home/client/public_html/zen/index.php(94): require('/home/client/publi...')
--> PHP Warning: Undefined variable $products_discount_type_from in /home/client/public_html/zen/includes/modules/products_quantity_discounts.php on line 92.
```
This is …
=> Debug logs when a non- `product_info` type product is "not found"

includes/classes/observers/auto.non_captcha_observer.php
```
[30-Apr-2025 13:24:40 America/Los_Angeles] Request URI: /index.php?action=send&main_page=contact_us, IP address: 184.75.190.2, Language id 1
#0 /home/client/public_html/includes/classes/observers/auto.non_captcha_observer.php(99): zen_debug_error_handler()
#1 /home/client/public_html/includes/classes/observers/auto.non_captcha_observer.php(35): zcObserverNonCaptchaObserver->testURLSpam()
#2 /home/client/public_html/includes/classes/observers/auto.non_captcha_observer.php(45): zcObserverNonCaptchaObserver->update()
#3 /home/client/public_html/includes/classes/traits/NotifierManager.php(106): zcObserverNonCaptchaObserver->updateNotifyContactUsCaptchaCheck()
#4 /home/client/public_html/includes/modules/pages/contact_us/header_php.php(31): base->notify()
#5 …
```
=> Prevent array input where undesired

admin/invoice.php, admin/packingslip.php, includes/classes/order.php
If a site doesn't require a telephone number (i.e. Configuration :: Minimum Values :: Telephone Number is set to 0), empty telephone numbers are still displayed on an order's invoice or packingslip and are also included in the order's confirmation email.
This PR includes the telephone number in those 3 spots only if the value isn't "empty".
=> Invoice/packingslip/confirmation email: Don't include empty phone number

includes/index_filters/default_filter.php, includes/index_filters/music_genre_filter.php, includes/index_filters/record_company_filter.php
Seeing logs like the following, note that `(int)39` is a single-quote:
```
[29-Apr-2025 14:15:31 America/New_York] Request URI: /zc210/index.php?main_page=index&cPath=3_10&disp_order=8&filter_id=&alpha_filter_id=39, IP address: 127.0.0.1, Language id 1
#1 C:\xampp\htdocs\zc210\includes\classes\db\mysql\query_factory.php(734): trigger_error()
#2 C:\xampp\htdocs\zc210\includes\classes\db\mysql\query_factory.php(679): queryFactory->show_error()
#3 C:\xampp\htdocs\zc210\includes\classes\db\mysql\query_factory.php(307): queryFactory->set_error()
#4 C:\xampp\htdocs\zc210\includes\modules\pages\index\header_php.php(131): queryFactory->Execute()
#5 C:\xampp\htdocs\zc210\index.php(35): require('C:\\xampp\\htdocs...')
--> PHP Fatal error: FATAL …
```
=> Sanitize `alpha_filter_id`

includes/classes/navigation_history.php
=> `navigation_history`: Ensure properties are arrays prior to use

admin/developers_tool_kit.php
Fixes #7105 
When coming back from Look Up Constant definition page to Developer Tool page, there is no POST data `context_lines`. Taking this in account avoids warning log.
=> Developer tool missing POST data

includes/classes/Customer.php, includes/classes/order.php
this is only a refactor.
no logic has changed.
the `$customer` object is already established by the time we get to the `order->cart` method. 
3 less `$db->Execute` calls.  
plus more removal of code duplication.
i could potentially see the new methods being part of the `customer` object; and am open to that refactor as well.
=> use Customer object for order class

includes/modules/pages/popup_coupon_help/header_php.php
The `popup_coupon_help` page should only be displayed when a discount-coupon has been applied to an order.
This PR prevents unwanted accesses attempting to find coupon information.
=> Coupon help, only active when a coupon's been applied

includes/modules/pages/account_history_info/header_php.php
Prevents this log:
```
[20-Jun-2025 15:11:16 UTC] Request URI: /index.php?main_page=account_history_info&order_id=1234, IP address: ::1, Language id 1
#0 /Users/scott/Sites/gh_demo_200/includes/modules/pages/account_history_info/header_php.php(27): zen_debug_error_handler()
#1 /Users/scott/Sites/gh_demo_200/index.php(40): require('/Users/scott/Si...')
--> PHP Warning: Undefined array key "customer_id" in /Users/scott/Sites/gh_demo_200/includes/modules/pages/account_history_info/header_php.php on line 27.
[20-Jun-2025 15:11:17 UTC] Request URI: /index.php?main_page=account_history_info&order_id=1234, IP address: ::1, Language id 1
#0 /Users/scott/Sites/gh_demo_200/includes/templates/template_default/templates/tpl_account_history_info_default.php(13): zen_debug_error_handler()
#1 …
```
=> Check order object after creation

includes/classes/Customer.php
Remove any records in the `customer_password_reset_tokens` table when a customer is deleted.
=> Remove password-reset-tokens when customer deleted

includes/modules/attributes.php
Updates/fixes refactor in #7107 
... otherwise, various PHP warnings/deprecations are thrown because the shopping_cart class doesn't create the 'attributes_values' element of its `contents` array.
```
[25-Jun-2025 10:01:40 America/New_York] Request URI: /zc210/index.php?main_page=shopping_cart, IP address: 127.0.0.1, Language id 1
#0 C:\xampp\htdocs\zc210\includes\classes\shopping_cart.php(1064): zen_debug_error_handler()
#1 C:\xampp\htdocs\zc210\includes\classes\shopping_cart.php(1393): shoppingCart->attributes_price()
#2 C:\xampp\htdocs\zc210\includes\modules\pages\shopping_cart\header_php.php(22): shoppingCart->get_products()
#3 C:\xampp\htdocs\zc210\index.php(40): require('C:\\xampp\\htdocs...')
--> PHP Warning: Undefined array key "attributes_values" in …
```
=> Correct TEXT attributes form name

admin/includes/languages/lang.english.php
```
[28-Jun-2025 12:06:18 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "ERROR_PRODUCT_OPTION_SELECTION" in /Users/scott/Sites/gh_demo_200/includes/classes/shopping_cart.php:1098
Stack trace:
#0 /Users/scott/Sites/gh_demo_200/includes/classes/shopping_cart.php(1393): shoppingCart->attributes_price('1:edff669e5da95...')
#1 /Users/scott/Sites/gh_demo_200/admin/includes/classes/WhosOnline.php(361): shoppingCart->get_products()
#2 /Users/scott/Sites/gh_demo_200/admin/includes/classes/WhosOnline.php(249): WhosOnline->inspectSessionCart('', 'securityToken|s...')
#3 /Users/scott/Sites/gh_demo_200/admin/includes/classes/WhosOnline.php(157): WhosOnline->getStatusCode(Array)
#4 /Users/scott/Sites/gh_demo_200/admin/whos_online.php(52): WhosOnline->retrieve('', '423a3f87ea98313...', true, …
```
=> Prevent log during who's online

includes/modules/payment/paypaldp.php
From the PayPal NVP [docs](https://developer.paypal.com/api/nvp-soap/do-capture-nvp/), the `PNREF` and `AUTHCODE` fields are not (or no longer?) returned.
Seeing logs like
```
[30-Jun-2025 14:36:00 UTC] Request URI: /admin/index.php?cmd=orders&page=1&oID=110267&action=doCapture, IP address: x.x.x.x, Language id 1
#1  paypaldp->_doCapt() called at [/home/mysite/public_html/admin/orders.php:369]
#2  require(/home/mysite/public_html/admin/orders.php) called at [/home/mysite/public_html/admin/index.php:16]
--> PHP Warning: Undefined array key "PNREF" in /home/mysite/public_html/includes/modules/payment/paypaldp.php on line 1451.
[30-Jun-2025 14:36:00 UTC] Request URI: /admin/index.php?cmd=orders&page=1&oID=110267&action=doCapture, IP address: x.x.x.x, Language id 1
#1  paypaldp->_doCapt() …
```
=> paypaldp::_doCapt, logs due to missing response fields

includes/classes/Customer.php, includes/languages/lang.english.php
Enables display of orders with missing `orders_status` records for the order's `orders_status` and/or the current language.
=> Customers::getOrderHistory, when order's status is missing

includes/auto_loaders/config.core.php
With the change in PR #7134, logs are now being seen
```
[29-Jun-2025 22:48:23 America/Chicago] Request URI:  /index.php?main_page=product_music_info&cPath=17&products_id=178,  IP address: 157.100.87.87, Language id not set
#0 /includes/classes/Product.php(251): zen_debug_error_handler()
#1 /includes/classes/Product.php(33): Product->loadProductDetails()
#2 /includes/functions/functions_products.php(419): Product->__construct()
#3 /includes/init_includes/init_sanitize.php(236): zen_products_id_valid()
#4 /includes/autoload_func.php(40): require_once('/home/haremark/...')
#5 /includes/application_top.php(329): require('/home/haremark/...')
#6 /index.php(27): require('/home/haremark/...')
--> PHP Warning: Undefined array key "languages_code" in /includes/classes/Product.php on line 251. …
```
=> Initialize session language prior to `init_sanitize.php`

admin/reviews.php, includes/templates/responsive_classic/templates/tpl_product_reviews_info_default.php, includes/templates/template_default/templates/tpl_product_reviews_info_default.php
Fixes #7113 
Removes use of function zen_break_string in templates reviews' display that leads to random line breaks when multibyte characters are used in languages with no spaces between words.
=> Function zen_break_string use

admin/define_pages_editor.php
A bug was introduced in PR #7123 in file admin/define_page_editor.php line 72 where using mb_strlen() function gives wrong results as the variable is coming from POST data and is encoded differently from a standard PHP multibyte string.
Just replacing back `mb_strlen()` by `strlen()` function fixes the problem.
=> Unnecessary Multibyte function provoking bug

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_220.sql
Some currency services (ie, OpenExchangeRates) have support for four-digit currency codes—namely CryptoCurrencies like DOGE (DogeCoin), DASH, others.
Some currencies are longer, but those are mostly "Black Market Rates" not widely in circulation or use.
=> Modifying currencies table to support four letter codes

includes/modules/payment/paypal/paypalwpp_admin_notification.php
Ensure that the two PayPal NVP configuration constants are defined, to prevent a whitescreen on the admin's Customers :: Orders page.
=> PayPal Admin notification, correcting missing constant whitescreen

includes/classes/order.php
During the `order` class' `query` method (retrieving a previous order from the database), that method gathers **all** fields from the `orders` and `orders_products` tables, but there's no way for an observer watching 'NOTIFY_ORDER_AFTER_QUERY' or 'NOTIFY_ORDER_QUERY_ADD_PRODUCT' to make use of the information.
This PR adds the database fields to those notification.  An observer can determine whether that value's present by testing either notification's 3rd parameter for `null` and performing the database query for additional fields on its own.
=> Order query: Enable observer to reuse gathered product info

admin/includes/functions/general.php
`product=Product Page` can be parsed for key of `product` and display in checkboxes as `Product Page`
Before:
After:
=> zen_cfg_select_multioption - allow = separator for descriptive text

includes/modules/order_total/ot_group_pricing.php
Replaces return statement with break so notifier is reached if tax is zero and tax recalculate option is set to Standard (the default).
Fixes #7174
=> Fixes #7174 Notifier bypassed in ot_group_pricing

includes/classes/ResourceLoaders/SideboxFinder.php
When a plugin's sidebox path is requested **without** the full path (as it is in the admin's Layout Boxes Controller), that path is currently returned without a trailing slash (/), resulting in a wonky display on that admin tool.
This PR corrects that display issue:
=> Correct plugin sidebox path w/o full path

zc_install/sql/install/mysql_zencart.sql, zc_install/sql/updates/mysql_upgrade_zencart_220.sql
With only 10 characters for a plugin's version, a plugin can't provide a `v1.1.1-alpha1` version since that requires 13 characters.
=> Update plugin control version field to accommodate alpha/beta

includes/classes/ViewBuilders/PluginManagerController.php
Essentially, lining up the radio/checkbox inputs.
Without these changes:
With these changes:
=> Admin :: Plugin Manager: Refactor radio/checkbox input layout

includes/functions/functions_general_shared.php
The shipping-enabled check might be called in a plugin, in the admin, or in other places where the session cart hasn't been instantiated.
=> Optimize cart object check in zen_get_shipping_enabled()

includes/classes/Customer.php, includes/extra_datafiles/dist-site_specific_overrides.php, includes/modules/pages/login/header_php.php, includes/modules/pages/password_forgotten/header_php.php
Extend the `password_forgotten` throttling to the `login` page, using a common (and override-able) maximum number of failures value.
The session-based count increments each time either a `login` page error is detected or an unknown email_address is submitted to the `password_forgotten` page.  If that session-based count exceeds the maximum value above, both pages' form-processing respond with an HTTP 406 response code until the session times out.
The `password_forgotten` page is also updated to throttle the sending of the password-reset-link email.  If a password-reset email has been previously sent for an email address and the link's still valid, simply display the "check your email" message without resending that email.  This makes it more difficult for a site to reach its …
=> Customer login/password-forgotten throttling

admin/tax_rates.php, includes/functions/functions_taxes.php
This PR adds possibility to edit all languages versions of tax description whatever the language setting is in the same way as orders status. Actually, you have to change admin language to edit the desired language description.
English display BEFORE:
English edit BEFORE:
French edit BEFORE:
English display AFTER:
English edit AFTER:
=> Tax_description_editing

includes/classes/class.search.php
we already have the `default_filter` script.  during a search, that script gets hit; why i do not know.  perhaps something for another day.
that script has a notifier here:
https://github.com/zencart/zencart/blob/17d3fcf12da531374812b5723e12f8e2f0a50404/includes/index_filters/default_filter.php#L148-L149
while this search class already has a number of notifiers, adding this new notifier here, mimics the notifier in the aforementioned script; allowing for an observer to reuse the same code for both notifiers.
=> add notifier in search class similar to default filter

includes/classes/order.php, includes/modules/pages/shopping_cart/header_php.php
Fixes #7164
Potential issues: 
- in both cases a notifier will not fire, which previously was expected to fire; however, a PHP Fatal error due to EOF would have blocked the notifier as well
- in one case a counter doesn't get updated; not sure if that counter's value is essential in that it needs to match a count elsewhere, or if it's merely incrementing the array index.
=> Skip empty attribute queries.

includes/modules/pages/customers_authorization/header_php.php
Corrects PHP warnings on the `customers_authorization` page when the page is "hit" and a customer isn't logged in.
Also
- Correctly displays the page when the customer's current authorization status is '3' (Pending, can browse with prices but cannot purchase until authorized).
- Simplifies the header/footer/left/right enable/disable settings.
=> Correct PHP warnings on `customers_authorization` page

admin/attributes_controller.php
already touched in 2.2.0
use <?= and inconsistent closing;
null coalesce
fix: method call name case mismatch
add css semicolons
remove px from style 0px
remove redundant arguments size: ''
no code changes, yet.
=> Attributes controller tidy

admin/includes/functions/general.php, admin/orders.php, includes/classes/order.php
Found the function referenced once in admin\includes\functions\general.php. This is a breaking change, I guess. (But I know of only one other module that used it, fraudlabspro, and I converted that to an observer class.)
=> Moving `zen_remove_order` to `order.php` class

includes/classes/cache.php
... as reported [here](https://www.zen-cart.com/showthread.php/230855-quot-Undefined-array-key-quot-warning-in-includes-classes-cache-php) on the Zen Cart forums.
Also 'refreshes' the class' processing.
=> Correcting 'undefined array key' log thrown by the cache.php class

zc_plugins/POSM/v6.1.1/catalog/includes/classes/observers/class.products_options_stock_observer.php
Was missing the '/' between the directory name and the filename.
Fixes #7243
=> Correcting POSM CSS Override

zc_plugins/POSM/v6.1.1/catalog/includes/classes/observers/class.products_options_stock_observer.php
This functions returns int or float
https://github.com/zencart/zencart/blob/28e44ef618cc9e81e49f5661e7dfa4f41107962a/includes/functions/functions_products.php#L471-L489
but the observer may return a string.
Fix copied from here
https://github.com/zencart/zencart/blob/28e44ef618cc9e81e49f5661e7dfa4f41107962a/includes/classes/Product.php#L159
Or maybe the observer should watch this method?
=> POSM observer: do not return quantity as string

includes/functions/functions_customer_groups.php
Simply adding a function to display the Group Comment field from the DB. This can be handy if you want a "friendly" display of what groups a customer belongs to rather than a potentially cryptic `group_name` field.
=> Adding function to display the group comment

admin/includes/functions/html_output.php, admin/orders.php
Could be confusing having two "edit" references (one from innate ZenCart and the other from something like Edit Orders) next to each other. Changing the link to the order itself to read as "Details" using an already existing define.
=> Changing tooltip for edit order

includes/classes/traits/NotifierManager.php
Usage:
```php
define('NOTIFIER_TRACE_EVENTS', [comma-separated-list-of-events]);
```
Using the above definition, the `notifier_trace.log` file can be limited to the selected events.  Requires also that the `NOTIFIER_TRACE` definition is defined and 'enabled'.
=> Enable notifier-tracing to limit events monitored

includes/functions/whos_online.php
Discovered the following warning using 2.2.0:
``` shell
[23-Sep-2025 18:46:26 America/New_York] Request URI: /ajax/api/content_infraction/getIndexableContent, IP address: 5.79.66.133, Language id 1
#0 /includes/classes/navigation_history.php(38): zen_debug_error_handler()
#1 /includes/autoload_func.php(62): navigationHistory->add_current_page()
#2 /includes/application_top.php(329): require('...')
#3 /ajax.php(24): require('...')
--> PHP Warning: Undefined array key "act" in /includes/classes/navigation_history.php on line 38.
[23-Sep-2025 18:46:26 America/New_York] Request URI: /ajax/api/content_infraction/getIndexableContent, IP address: 5.79.66.133, Language id 1
#0 /includes/functions/whos_online.php(13): zen_debug_error_handler()
#1 /includes/init_includes/init_special_funcs.php(18): …
```
=> Avoiding possible warning about unset array key

admin/includes/templates/plugin_manager.php, admin/plugin_manager.php, includes/classes/PluginManager.php, includes/classes/PluginSupport/BasePluginInstaller.php, includes/classes/PluginSupport/PluginStatus.php, includes/classes/ViewBuilders/PluginManagerController.php, includes/classes/ViewBuilders/PluginManagerDataSource.php
A corollary to PR #7303, this PR adds a `PluginStatus` class where the various plugin-status constants are defined for common use.
It's a bit easier to 'understand'
```php
$this->setPluginVersionStatus($pluginKey, '', PluginStatus::NOT_INSTALLED);
```
than
```
$this->setPluginVersionStatus($pluginKey, '', 0);
```
=> PluginStatus class, provides common 'status' values

admin/includes/init_includes/init_sessions.php, includes/init_includes/init_sanitize.php, includes/templates/template_default/jscript/jscript_framework.php
Using HTTP code 418 as an indication that either the AJAX request was initiated without a securityToken or that the token doesn't match the current session value.
If the 418 is received, the storefront redirects to the `time_out` page while the admin redirects to the `denied` page.
=> Ensure that security tokens are passed on AJAX requests

zc_plugins/SystemInspection/1.6.0/admin/includes/extra_configures/system_inspection_base.php
- Adding `customers_auth_tokens`, added for [this](https://github.com/zencart/zencart/issues/7235) issue.
- Removing `paypal_webhooks`, mistakenly added via [this](https://github.com/zencart/zencart/commit/b36771915bb8680dc3501288e6568d26da6da8b0) commit.
=> System Inspection: Updating built-in tables

zc_plugins/DisplayLogs/v3.0.3/manifest.php
The `pluginId` provided in the Display Logs encapsulated manifest refers to an obsolete version of the plugin as the encapsulated version's been in-core since zc157.
=> Display Logs: `pluginId` refers to obsolete plugin

admin/includes/header_navigation.php
HTML validator indicates "Error: No space between attributes." (no space prior to `class=` attribute):
``
<li class="upperMenuItems"><a href="http://localhost:8083/zc210/admin210/"class="headerLink">Home</a></li>
``
=> Admin header-nav, correct invalid HTML
